### ISSUE TITLE
Dependency importing

### ISSUE THREAD

**Issue by Neoplayer** [reactjs/React.NET#1002]
When I try to import an extension
![image](https://user-images.githubusercontent.com/17293976/71557348-f0dfb180-2a55-11ea-81c7-5bbb3df725be.png)
 This error always occurs
![image](https://user-images.githubusercontent.com/17293976/71557324-c55cc700-2a55-11ea-91f8-19d703c28ff7.png)
![image](https://user-images.githubusercontent.com/17293976/71557362-0e148000-2a56-11ea-8b82-14c7ee65f561.png)

**Comment by dustinsoftware** [comment]
We need some better documentation here; ES modules are not supported without using webpack. 

Independent of this library, you could try using something like https://www.snowpack.dev/
