### ISSUE TITLE
React.NET not working on ASP.NET 5 and MVC 6

### ISSUE THREAD

**Issue by radenkozec** [reactjs/React.NET#101]
I have followed tutorial on http://reactjs.net/getting-started/aspnet5.html
to use React with ASP.NET 5.
I cannot make it work. (I have used Reactjs.NET on ASP.NET MVC 5 successfully)

I am just getting blank page. (no info in console) and don't have react tab in chrome develop tools.
Can you please upload a simple project (hello world) where you have managed to run it in ASP.NET 5 so I can try to implement it myself?

**Comment by Daniel15** [comment]
Do you see any errors in the Visual Studio output window?

There's a sample project in the React.Sample.Mvc6 project in the
repository. Clone the project, run dev-build.bat, then you can open the
solution in Visual Studio.

**Comment by radenkozec** [comment]
There is no errors in the Visual Studio output window.
I will try figure out what's wrong from your project.
Thanks for help.

I will post update soon.

**Comment by radenkozec** [comment]
I have succeeded to run your example by extracting project from solution and manually fixing issues.
It would be nice if you can reference React.js from Bower instead of fb for next versions. (some of us have problems with referencing fb because of company policies for social networks)

Also I am hoping that you will enable support for aspnetcore50 soon. Without .NET Core your implementation for ASP.NET 5 is not complete because we will be stuck with Windows and Full Framework.

**Comment by Daniel15** [comment]
Did you figure out what the issue with your project was?

> It would be nice if you can reference React.js from Bower instead of fb for next versions

This already works for client-side code, just include your own version of React rather than using it from the CDN.

> Also I am hoping that you will enable support for aspnetcore50 soon. Without .NET Core your implementation for ASP.NET 5 is not complete because we will be stuck with Windows and Full Framework.

This is blocked on the dependencies (ClearScript and JavaScriptEngineSwitcher) supporting ASP.NET 5 Core. .NET Core isn't functional on Linux or Mac OS X yet, and ASP.NET 5 still runs on those platforms via Mono even without Core.

**Comment by radenkozec** [comment]
Hm That is a great. I got the impression that ASP.NET projects will not work on Linux or MacOS without .NET Core. 
Thanks for clarification.

**Comment by Daniel15** [comment]
I recently built a hello world app with the Yeoman generator (to scaffold it) and Sublime Text. It worked! :) http://blogs.msdn.com/b/webdev/archive/2014/08/12/develop-asp-net-vnext-applications-on-a-mac.aspx

**Comment by radenkozec** [comment]
Great. 
I am glad you have already test it .
I haven't got time to test it on Mac yet.

**Comment by radenkozec** [comment]
I looked at explanation here: 
http://www.asp.net/vnext/overview/aspnet-vnext/aspnet-5-overview
It seams that Cross-Platform CLR is not yet released.
So KRE CLR is actually Full CLR which is not working on Linux?

**Comment by radenkozec** [comment]
Actually you are correct: http://blogs.msdn.com/b/cesardelatorre/archive/2014/11/18/what-is-net-core-5-and-asp-net-5-within-net-2015-preview.aspx
Here is stated: This is today (running ASP.NET 5 on top of Mono), but Microsoft is also going to release an official distribution of the .NET Core for Linux, as well as an official distribution of .NET Core for the Mac OS X, as well.
