### ISSUE TITLE
The Webpack example doesn't work when the server side webpack 'target' is set to 'node' (as it should)

### ISSUE THREAD

**Issue by Bram-Zijp** [reactjs/React.NET#1013]
**The problem**
Currently, the Webpack example seems to be based around a Webpack setting `target: 'web'`. As soon as you hardcore the `target` to `node`, it will state that `Components.ComponentName` is `undefined`. In general, you wan't your server side rendered bundle to have the window object to be 'undefined'. This is because many module's/developers call `typeof window !== 'undefined'` to verify it is running in a browser environment

**The solution**
- Adding `target: "node",` to the Server sided webpack config.
- Rendering Components inside of the .NET application like so `@Html.React("global.Components.ComponentName", new { })`
- Replacing `global.Components` with `window.Components` or `Components` in the output of  the `Html.ReactInitJavaScript()` method.

**To discover**
I'm unsure if there's another way to make the `Components` variable available with the Webpack target set to `node` without using the `global.` prefix to call them.

**Comment by dustinsoftware** [comment]
This is unfortunately a rough spot; setting node will cause webpack to assume certain APIs are available when they really aren’t, which breaks code splitting. Native “require” for instance does not work at all. 

Is there something more specific you are trying to accomplish? Have you tried target “webworker”?

**Comment by dustinsoftware** [comment]
Also setting target “web” shouldn’t cause the window object to suddenly be defined in the server context... do you have a poly fill somewhere that is assigning that globally somewhere?

**Comment by Bram-Zijp** [comment]
> This is unfortunately a rough spot; setting node will cause webpack to assume certain APIs are available when they really aren’t, which breaks code splitting. Native “require” for instance does not work at all.
> 
> Is there something more specific you are trying to accomplish? Have you tried target “webworker”?

The same goes for setting the target to 'web'. Some modules expose different entrypoints based on the the target. The browser libraries try and use the Browser API's. For example: 
```
// package.json
{
  "main": "./lib/non_browser",
  "browser": "./lib/browser",
}
```
