### ISSUE TITLE
Server-side rendering crashing due to 3rd-party packages assuming target is web-based

### ISSUE THREAD

**Issue by Auk14HP** [reactjs/React.NET#1017]
### Please verify these steps before filing an issue, and check them off as you go
- [x] The relevant native JavascriptEngineSwitcher library packages are installed (such as `JavaScriptEngineSwitcher.V8.Native.win-x64`)
- [x] The VC++ 2017 runtime is installed
- [x] The value of `SetUseReact` and `SetUseBabel` is correct in `ReactConfig.cs` or `Startup.cs`
- [x] I've looked at the sample projects in this repo to verify that my app is configured correctly

### I'm using these library versions:
- `ReactJS.NET`: `4.1.1`
- `JavaScriptEngineSwitcher`: `3.0.5`
- `react` and `react-dom`: (N/A if using bundled react, or version number) `16.8.4`
- `webpack`: (N/A if using bundled react) `4.29.5`
- `node`: (N/A if using bundled react) `12.13.0`

### Runtime environment:
- OS: (Mac, Windows, Linux flavor. Include 32-bit/64-bit and version) Windows 10 64-bit
- .NET Framework or .NET Core Version: .Net Framework `4.8`

### Steps to reproduce

-------

Our project has been using ReactJs.net's server-side rendering successfully up to this point.  Recently, however, a js package we use updated one of it's [dependencies](https://github.com/JedWatson/react-select).  With this new update the dependency [now serves up a different file based on the consumer's webpack `target`](https://github.com/JedWatson/react-select/blob/8fa6c0f01416b923d2c7a6f31ee687b6248fcd71/package.json#L140). 

Said-file assumes that `window` is defined.  Because our server js webpack has it's target set to `webworker` the aforementioned dependency serves up the file that references `window` and crashes our server-side render.

Should we have a different webpack `target`?  We tried setting it to `node` but that still resulted in a crash due to `require` not being defined.

**Comment by SpencerAlexander** [comment]
👍 Essentially `webworker` is neither a true `browser` environment (with a `window`). Nor a true `node` environment with `require()` api. Thus the `react-select` dependency bundle breaks whether we specify browser or node environment. Is there a way to run in a true `node` environment, with access to all commonJS modules?

**Comment by dustinsoftware** [comment]
Sounds like you are running into this: https://github.com/JedWatson/react-select/issues/3802

Consuming modules targeted specifically for Node is not supported by this library without rolling them up ahead of time with all their dependencies. 

These types of bugs/limitations are often missed by library maintainers, as component updates are tested in the browser and with Node SSR but often not with a server-side JS environment lacking a CommonJS-type module system.

I recommend first submitting a PR to the library that adds a `typeof window !== 'undefined'` check, along with using library fork that patches the underlying problem in case an update can't be published for a while.

You could also skip the component render during SSR by doing a dynamic import in `componentDidMount` or `useEffect` callback.

**Comment by Auk14HP** [comment]
> These types of bugs/limitations are often missed by library maintainers, as component updates are tested in the browser and with Node SSR but often not with a server-side JS environment lacking a CommonJS-type module system.

Is this really a bug/limitation they missed, though?  In this case they've declared this code only works in a browser where `window` is defined and, given the `webworker` target we're getting served up that file despite ReactJs.net not having access to `window`.

Seems working from a forked-copy or adding a work-around to our code will unblock us on this particular instance but just push the problem down the road until the next dependency has another browser-specific file they serve up.

**Comment by dustinsoftware** [comment]
I'm open to suggestions about how to implement this but emulating Node's APIs is not a simple undertaking and it's not on the roadmap unfortunately.

There might be a way to get webpack to point to the Node bundle and shim all of the globals that are present in real Node environment. As long as all the dependencies are rolled up into the JS bundle the server executes then it should work. Timer callbacks like `setTimeout, Promise.resolve, setImmediate` could be defined and be a no-op to hack around assumptions that libraries make.

**Comment by dustinsoftware** [comment]
I am in the process of making a PR for proper Node support that should solve for this use case, please see #1021 for updates.

**Comment by DaniilSokolyuk** [comment]
When #1021 is not ready yet and you not use [render function](https://github.com/reactjs/React.NET/tree/master/src/React.Core/RenderFunctions) or On-the-fly JSX to JavaScript compilation you can try my [NodeReact.NET](https://github.com/DaniilSokolyuk/NodeReact.NET), it uses NodeJS for SSR and API compatible with React.NET

**Comment by dustinsoftware** [comment]
Active development for Node support has paused for now; closing this issue since the question has been answered. Maybe someday we'll have first-class support for a Node engine, but that has a bunch of other complexities to be sorted out...

**Comment by Methuselah96** [comment]
@dustinsoftware Are we at a dead-end here? I believe `react-select` is [correctly assuming that `window` is defined for the `browser` aliases](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#browser).

**Comment by dustinsoftware** [comment]
Probably? I don’t know of a way around the issue due to the way this
library is currently built.

I recommend forking react-select and patching out the check for window.
