### ISSUE TITLE
Tutorial version problems

### ISSUE THREAD

**Issue by JohnnyBizzel** [reactjs/React.NET#1018]
Thanks for filing a bug! To save time, if you're having trouble using the library, please check off the items you have tried. If you are just asking a question, skip right to the bottom.

### Please verify these steps before filing an issue, and check them off as you go
No idea about this >>>
- [ ] The relevant native JavascriptEngineSwitcher library packages are installed (such as `JavaScriptEngineSwitcher.V8.Native.win-x64`)
- [ ] The VC++ 2017 runtime is installed
- [ ] The value of `SetUseReact` and `SetUseBabel` is correct in `ReactConfig.cs` or `Startup.cs`
- [ ] I've looked at the sample projects in this repo to verify that my app is configured correctly

### Runtime environment:
- OS: Windows 10
- .NET Framework or .NET Core Version: 2.1

-------

I receive a NU1107 Error when trying to install NuGet package REACT 5.1.2
I am unsure how to proceed.

**Comment by JohnnyBizzel** [comment]
Is there a tutorial for .NET core 2.1? This tutorial won't compile on my PC.

**Comment by dustinsoftware** [comment]
Sorry, we are a limited team and can only maintain a handful of tutorials.

That said this commit has the sample running on .NET Core 2.2, and the published packages should still work with it. 

https://github.com/reactjs/React.NET/commit/287a5196687009337c829eafc31ca8befbe92501#diff-eeb90c9286538956d86b059dff186ca9
