### ISSUE TITLE
Dictionary get serialized as camel case

### ISSUE THREAD

**Issue by knyzorg** [reactjs/React.NET#1019]
The way ReactJS.NET configures Newtonsoft to serialize dictionaries is causing the keys of dictionaries to appear as camel case instead of their original case.

Furthermore, it appears impossible to configure manually.

Is there a work-around this behaviour?

**Comment by dustinsoftware** [comment]
Yes, that can be configured via `SetJsonSerializerSettings`
https://github.com/reactjs/React.NET/blob/d6ff20050e53283f10d3d1dd017e3eaa1cc517eb/tutorial-code/Startup.cs#L69-L73

Does that help?

**Comment by knyzorg** [comment]
Yes it does. As a side-note, what do you think about moving to `System.Text.Json` ?

**Comment by Daniel15** [comment]
> what do you think about moving to System.Text.Json ?

I imagine quite a few users would be customizing the Json.NET settings at the moment, so I think this would have to be opt-in.

Also, does it work for older .NET Framework versions too, or is it just part of newer .NET Core versions?

**Comment by knyzorg** [comment]
Only since 3.0. Microsoft is forcing people to change their code relating to json configuring _anyways_, so its a good time for it.

If you could distribute separate versions for 2.x and 3.x until support for 2.x is dropped - I think it would be ideal. It's just a matter of preferring the stdlib over nuget libraries, doesn't matter that much.
