### ISSUE TITLE
Props are always null when passed into component (.NET Core 3.1)

### ISSUE THREAD

**Issue by upsilondynamics** [reactjs/React.NET#1022]
Thanks for filing a bug! To save time, if you're having trouble using the library, please check off the items you have tried. If you are just asking a question, skip right to the bottom.

### Please verify these steps before filing an issue, and check them off as you go
- [ X] The relevant native JavascriptEngineSwitcher library packages are installed (such as `JavaScriptEngineSwitcher.V8.Native.win-x64`)
- [ X] The VC++ 2017 runtime is installed
- [ X] The value of `SetUseReact` and `SetUseBabel` is correct in `ReactConfig.cs` or `Startup.cs`
- [X ] I've looked at the sample projects in this repo to verify that my app is configured correctly

### I'm using these library versions:
- `ReactJS.NET`: 5.1.2
- `JavaScriptEngineSwitcher`: ChakraCoreJsEngine (3.3.0)
- `react` and `react-dom`: (N/A if using bundled react, or version number)
- `webpack`: (N/A if using bundled react)
- `node`: (N/A if using bundled react)

### Runtime environment:
- OS: (Mac, Windows, Linux flavor. Include 32-bit/64-bit and version) Windows 10 Pro
- .NET Framework or .NET Core Version: .NET Core 3.1

### Steps to reproduce

@Html.React("Test", new { myVal = "123" })

The prop is always being passed in as null/blank.  This was working in .NET 4.7 until I upgraded, I need assistance.

https://stackoverflow.com/questions/60013968/react-net-net-core-3-1-not-passing-props-into-component

**Comment by dustinsoftware** [comment]
A few things to try:

Different JSON serialization defaults might be changing the casing from `PascalCase` to `camelCase` on you. `render() { return <span>{JSON.stringify(this.props)}</span> }` might help show what's getting passed in. If that's the case, it can be customized via [SetJsonSerializerSettings](https://github.com/reactjs/React.NET/blob/master/src/React.Core/ReactSiteConfiguration.cs#L152)

The webpack sample in this repo is a .NET Core 3.1 project, you could look at that to see what's different with the app you just updated.
