### ISSUE TITLE
Hello World is blank

### ISSUE THREAD

**Issue by spiegelj** [reactjs/React.NET#1035]
Thanks for filing a bug! To save time, if you're having trouble using the library, please check off the items you have tried. If you are just asking a question, skip right to the bottom.

### Please verify these steps before filing an issue, and check them off as you go
- [x ] The relevant native JavascriptEngineSwitcher library packages are installed (such as `JavaScriptEngineSwitcher.V8.Native.win-x64`)
- [X ] The VC++ 2017 runtime is installed  14.16.27033 (Visual C++ 2017 Redistributable (x64))
- [ ] The value of `SetUseReact` and `SetUseBabel` is correct in `ReactConfig.cs` or `Startup.cs` NO IDEA
- [ x] I've looked at the sample projects in this repo to verify that my app is configured correctly

### I'm using these library versions:
- `ReactJS.NET`:  React.AspNet v5.1.2
- `JavaScriptEngineSwitcher`:  javascriptengineswitcher.v8  v3.3.1
- `react` and `react-dom`: (N/A if using bundled react, or version number)
- `webpack`: (N/A if using bundled react)
- `node`: (N/A if using bundled react)

### Runtime environment:
- OS: (Mac, Windows, Linux flavor. Include 32-bit/64-bit and version)  Windows 7 64-bit
- .NET Framework or .NET Core Version: Core 3.1.1

### Steps to reproduce
1.  Follow the beginning [CommentBox tutorial](https://reactjs.net/tutorials/aspnetcore.html) through the "Your first component" step.  
2.  Run the code.
-------

Page is blank.  Page source:

```
<html>
<head>
    <title>Hello React</title>
</head>
<body>
    <div id="content"></div>
    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react/16.8.0/umd/react.development.js"></script>
    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.8.0/umd/react-dom.development.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/remarkable/1.7.1/remarkable.min.js"></script>
    <script src="/js/Tutorial.jsx"></script>
</body>
</html>
```

**Comment by dustinsoftware** [comment]
Does your output match the [tutorial source code](https://github.com/reactjs/React.NET/tree/master/tutorial-code) ?

**Comment by spiegelj** [comment]
Thank you, Dustin.  I no longer have access to the project.  I have since
recreated the tutorial in a different environment and it succeeded.  Either
I was missing something or the environment was.  The failing environment
was Windows 7 as the most glaring oddity, but this one may remain a mystery
at this point.

**Comment by dustinsoftware** [comment]
:) cheers
