### ISSUE TITLE
Tutorial.jsx file is not found "net::ERR_ABORTED 500"

### ISSUE THREAD

**Issue by AhammedNafeez** [reactjs/React.NET#1056]
Thanks for filing a bug! To save time, if you're having trouble using the library, please check off the items you have tried. If you are just asking a question, skip right to the bottom.

### Please verify these steps before filing an issue, and check them off as you go
- [ ] The relevant native JavascriptEngineSwitcher library packages are installed (such as `JavaScriptEngineSwitcher.V8.Native.win-x64`)
- [ ] The VC++ 2017 runtime is installed
- [ ] The value of `SetUseReact` and `SetUseBabel` is correct in `ReactConfig.cs` or `Startup.cs`
- [ ] I've looked at the sample projects in this repo to verify that my app is configured correctly

### I'm using these library versions:
- `ReactJS.NET`:
- `JavaScriptEngineSwitcher`:
- `react` and `react-dom`: (N/A if using bundled react, or version number)
- `webpack`: (N/A if using bundled react)
- `node`: (N/A if using bundled react)

### Runtime environment:
- OS: (Mac, Windows, Linux flavor. Include 32-bit/64-bit and version)
- .NET Framework or .NET Core Version:

### Steps to reproduce

-------

I am a beginner with .Net core and react.

I followed every single instruction from "https://reactjs.net/tutorials/aspnetcore.html" but still seems to be some error couldn't find the tutorial.jsx file "net::ERR_ABORTED 500"

When I move the "app.UseReact" code part below "app.UseStaticFiles();" then the browser throws an error says "Unexpected token '<' "

![index](https://user-images.githubusercontent.com/61694878/75683490-3d957200-5cbd-11ea-8adc-c2d56cb40e1c.PNG)
![jsx](https://user-images.githubusercontent.com/61694878/75683495-3ec69f00-5cbd-11ea-817e-9334ce716ff3.PNG)
![startup](https://user-images.githubusercontent.com/61694878/75683498-3f5f3580-5cbd-11ea-8003-b9451de78036.PNG)

**Comment by Jaked222** [comment]
I am getting this error as well with ASP.NET MVC 5. When putting a breakpoint in the global.asax to view more detailed error logs, I see that the type React.Web.BabelHandlerFactory is failing to resolve.

**Comment by dustinsoftware** [comment]
Are you able to repro the issue with the Mvc sample or template projects in
this repo?

**Comment by PratyushKumarDehury** [comment]
GET http://localhost:5173/src/main.jsx?t=1722964183685 net::ERR_ABORTED 500 (Internal Server Error) 

anybody please help me out to this issue?..that would be greatful!
