### ISSUE TITLE
Updating Babel's list of preset and plugin

### ISSUE THREAD

**Issue by Natura-Time** [reactjs/React.NET#1065]
Hello,

There isn't a lot of choice in the preset and plugin list available there in React.NET for Babel, only these if I'm correct : 
```
"presets": ["@babel/preset-react", "@babel/preset-env"],
"plugins": [
	"@babel/proposal-object-rest-spread",
	"@babel/plugin-syntax-dynamic-import",
	"@babel/proposal-class-properties"
]
```

I've got errors when I try to run my project with other plugins or presets...

So, is that possible to add more ? Like the "minify" preset for example ? Or some of these numerous plugins : https://babeljs.io/docs/en/plugins ?

I think here's the way to do it : https://github.com/babel/babel-standalone/issues/27

Thanks a lot in advance !

**Comment by dustinsoftware** [comment]
If you want to add more, that's what the webpack support is for :) the built in babel plugins aim to be "just enough" to get projects started that just want React compilation and SSR.
