### ISSUE TITLE
How do I warm up all engines?

### ISSUE THREAD

**Issue by scratch-net** [reactjs/React.NET#107]
Hi and thank you for such a great library.
We wanted to use it in our new project and perform some testing right now. We have a compiled .js file (using react and WebPack, of course) sized ~850 kb (minified) which on first load takes ~400 ms to run. After several page refreshes the response time reduces down to 10-12 ms which is, I suppose,  happening, because JSpool starts to use engines that were previously initialized.

So, how do I warm up all engines on the web app start to reduce the response time?

**Comment by Daniel15** [comment]
In 3ae436a376c0ffd6d5942378f1e1a06f1352834f I added a new `AddScriptWithoutTransform` method on the config object. Try that out, any scripts added with `AddScriptWithoutTransform` rather than `AddScript` will load as soon as the JavaScript engine is created.

**Comment by Daniel15** [comment]
Please feel free to reopen this if any other work need to be done on this.
