### ISSUE TITLE
EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by erdihu** [reactjs/React.NET#1097]
Thanks for filing a bug! To save time, if you're having trouble using the library, please check off the items you have tried. If you are just asking a question, skip right to the bottom.

### Please verify these steps before filing an issue, and check them off as you go
- [x] The relevant native JavascriptEngineSwitcher library packages are installed (such as `JavaScriptEngineSwitcher.V8.Native.win-x64`)
- [x] The VC++ ~~2017~~ **2019** runtime is installed
- [x] The value of `SetUseReact` and `SetUseBabel` is correct in `ReactConfig.cs` or `Startup.cs`
- [x] I've looked at the sample projects in this repo to verify that my app is configured correctly

### I'm using these library versions:
- `ReactJS.NET`: 5.2.4
- `JavaScriptEngineSwitcher`: 3.3.1
- `react` and `react-dom`: 16.12.0
- `webpack`: 4.42.1
- `clean-webpack-plugin`: 3.0.0
- `node`: 12.16.1

### Runtime environment:
- OS: Windows 10 64bit
- .NET Framework: 4.6.2

### Steps to reproduce
See below.

-------

Since upgrading to 5.2.4 from 4.1.1 I have been having random EBUSY: resource busy or locked error on bundle.server.js. I noticed that this is a pretty persistent problem when it happens, **if** it happens. The initial error has so far happened only while the webpack is in watch mode. Using LockHunter I can see that w3wp.exe is locking the js file. After releasing the lock manually and running the webpack again may or may not solve the problem; it often takes 2-3 retries (unlock file, run webpack) to make it dissappear (unless I delete the js file manually). 

I noticed that similar problems have been reported before. I have yet to test the effects of the suggested solution; adding .SetReuseJavaScriptEngines(false) to configuration.

I noticed that the JavascriptEngineSwitcher.v8 has a newer package (3.5.1) but via the changelogs I couldn't see anything that is related to this issue. Do you think it would help with the problem?

My config can be seen below:

```csharp
public class JsEngineSwitcherConfig
    {
        public static void Configure(IJsEngineSwitcher engineSwitcher)
        {
            engineSwitcher.EngineFactories.AddV8();
            engineSwitcher.DefaultEngineName = V8JsEngine.EngineName;
        }
    }
```
```csharp
[assembly: WebActivatorEx.PreApplicationStartMethod(typeof(ReactConfig), "Configure")]

namespace Project
{
    public static class ReactConfig
    {
        public static void Configure()
        {
            ReactSiteConfiguration.Configuration
                .SetLoadBabel(false)
                .AddScriptWithoutTransform("~/Static/bundle.server.js");
        }
    }
}
```

And here is the output I am getting from webpack:
```
> webpack --env.dev --progress


webpack is watching the files…

Live Reload listening on port 35729



* Webpack █████████████████████████ emitting (95%)


i ｢atl｣: Using typescript@3.8.3 from typescript
i ｢atl｣: Using tsconfig.json from D:/[redacted]/tsconfig.json (in a forked process)
i ｢atl｣: Checking started in a separate process...
95% emitting clean-webpack-pluginError: EBUSY: resource busy or locked, unlink 'D:\[redacted]\[redacted]\Static\bundle.server.js'
    at Object.unlinkSync (fs.js:1052:3)
    at Function.rimrafSync [as sync] (D:\[redacted]\node_modules\del\node_modules\rimraf\rimraf.js:314:17)
    at D:\[redacted]\node_modules\del\index.js:65:11
    at Array.map (<anonymous>)
    at module.exports.sync (D:\[redacted]\node_modules\del\index.js:57:40)
    at CleanWebpackPlugin.removeFiles (D:\[redacted]\node_modules\clean-webpack-plugin\src\clean-webpack-plugin.ts:304:29)
    at CleanWebpackPlugin.handleInitial (D:\[redacted]\node_modules\clean-webpack-plugin\src\clean-webpack-plugin.ts:239:14)
    at D:\[redacted]\node_modules\clean-webpack-plugin\src\clean-webpack-plugin.ts:189:26
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\[redacted]\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:14:1)
    at AsyncSeriesHook.lazyCompileHook (D:\[redacted]\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.emitAssets (D:\[redacted]\node_modules\webpack\lib\Compiler.js:491:19)
    at onCompiled (D:\[redacted]\node_modules\webpack\lib\Watching.js:51:19)
    at D:\[redacted]\node_modules\webpack\lib\Compiler.js:681:15
    at eval (eval at create (D:\[redacted]\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:18:1)
    at D:\[redacted]\node_modules\awesome-typescript-loader\src\instance.ts:523:16
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
i ｢atl｣: Time: 6742ms
```

**Comment by dustinsoftware** [comment]
Hmm unsure why this library would be locking the file. You could try switching to another JS engine like Chakra or NodeJS to see if it still happens...

**Comment by dustinsoftware** [comment]
Can't reproduce this; if I run into it or there is a solid repro case we'll see what we can do to make the engine release the file handle after it's done reading.

JSPool has its own file watcher implementation: https://github.com/Daniel15/JSPool/blob/286fadae1afe189ee1f3b7b96cabb70d579efd89/src/JSPool/FileWatcher.cs
