### ISSUE TITLE
Question about code splitting

### ISSUE THREAD

**Issue by optimatex** [reactjs/React.NET#1098]
Hi
I'm trying to implement code splitting through dynamic import since there is no similar solution like this one https://loadable-components.com/docs/server-side-rendering/ for React.NET SSR. Also, I was trying this code from the example https://github.com/reactjs/React.NET/blob/master/src/React.Template/reactnet-webpack/Content/components/lazy-load.jsx

But anyway I receive `JsRuntimeException: ReferenceError: 'window' is not defined`

Is there any way to implement code splitting with React.NET SSR ? Or, maybe there is some config that allows lazy-load.jsx example works without crash?

Thanks in advance

**Comment by dustinsoftware** [comment]
A few others have tried to get code splitting working, I haven’t yet found an approach that is fully compatible with how this library does SSR. 

See also #731

**Comment by WesselKroos** [comment]
I've found a solution that seems to work.
But it doesn't explain the `window is not defined` or the `document is not defined` errors to me.

You must not only add the runtime.js and main.js scripts to the configuration, but also the splitted chunks to the configuration via the
`ReactSiteConfiguration.Configuration.AddScriptWithoutTransform` 
method. 


I'm using thise code to load all the chunks in the asset-manifest.json:

```C#
using JavaScriptEngineSwitcher.Core;
using JavaScriptEngineSwitcher.V8;
using Newtonsoft.Json.Linq;
using React;
using System.IO;
using System.Linq;

[assembly: WebActivatorEx.PreApplicationStartMethod(typeof(TrueLime.Kentico.Mvc.Website.ReactConfig), "Configure")]

namespace your.project.name.space
{
public static class ReactConfig
{
	public static void Configure()
	{
		JsEngineSwitcher.Current.DefaultEngineName = V8JsEngine.EngineName;
		JsEngineSwitcher.Current.EngineFactories.AddV8();

		ReactSiteConfiguration.Configuration
			.SetLoadBabel(false)
			.SetLoadReact(false)
			.SetReactAppBuildPath(@"~\assets\js"); //asset-manifest.json directory

		var manifestPath = ReactSiteConfiguration.Configuration.ReactAppBuildPath.Replace(@"~\", System.AppDomain.CurrentDomain.BaseDirectory) + @"\asset-manifest.json";
		if(!File.Exists(manifestPath))
		{
			throw new System.Exception($"Cannot read the asset-manifest.json file. Absolute path: {manifestPath}");
		}

		var manifest = JObject.Parse(File.ReadAllText(manifestPath));
		var scripts = (manifest["files"] as JObject).Properties().Where(file => file.Name.EndsWith(".js")).Select(file => file.Value);
		foreach (var scriptPath in scripts)
		{
			ReactSiteConfiguration.Configuration.AddScriptWithoutTransform("~" + scriptPath);
		}
	}
}
}
```

**Comment by dustinsoftware** [comment]
At this point I'm going to close the code-splitting issues; it's likely this library will never support that use case for SSR. It's possible today for your components to use dynamic import after the main component has loaded (the webpack example does this).
