### ISSUE TITLE
ES6 class component declaration 

### ISSUE THREAD

**Issue by xabikos** [reactjs/React.NET#110]
According to documentation we can use the ES6 class syntax to declare components. I tried to do so but I am getting an error when the page is rendered server side.

My simple component looks like this
```
class App extends React.Component {
  render() {
    return <p>
        Hello World!
      </p>;
  }
}
```
But I am getting the error below:
```
Error while loading "~/Components/app.jsx": TypeError: Cannot read property 'prototype' of undefined
   at Script Document [6]:6:241 -> ];}}var ____SuperProtoOf____Class0=____Class0===null?null:____Class0.prototype
```

I have enabled the corresponding setting in react configuration (UseHarmony)

Is it possible to use this syntax today or am I missing something? I could create a small demo application to demonstrate this.

**Comment by Daniel15** [comment]
This is because ReactJS.NET isn't using the latest version of React. I'll
update it soon.

**Comment by xabikos** [comment]
Thanks for the quick response @Daniel15 I will keep an eye on it

**Comment by Daniel15** [comment]
The upgrade will be covered by #93. Closing this out.

**Comment by Daniel15** [comment]
Just tested after upgrading React to 0.13.1 and it works now. If you want to use it before I release a new version, you can get a ReactJS.NET build off the build server shortly, or just build it yourself. Instructions are on the site. Thanks for reporting!

**Comment by xabikos** [comment]
Thanks for the update @Daniel15

**Comment by xabikos** [comment]
Have you any idea when you will upgrade nuget package too?

**Comment by Daniel15** [comment]
New release will be some time in the next few days, I just need to do more
testing and see if there's any other bug fixes that I should do for this
release. In the meantime you can get packages off the development server,
or build it yourself and use the resulting NuGet packages. Instructions for
both are on the site.

**Comment by Daniel15** [comment]
I'm just pushing the updated NuGet packages now, they should be up in a few minutes.

**Comment by xabikos** [comment]
Thank you so much for the update. It's right on time. I want to incorporate the webpack with ES6 style syntax for our project.
