### ISSUE TITLE
How to use renderToNodeStream?

### ISSUE THREAD

**Issue by anuragbhd** [reactjs/React.NET#1105]
### I'm using these library versions:
- `ReactJS.NET`: 3.1.0
- `JavaScriptEngineSwitcher`: 2.4.9

-------

When we run a Lighthouse audit on our production website, one the the suggestions is to use `renderToNodeStream()` or `renderToStaticNodeStream()`:

<img width="687" alt="lighthouse-renderToNodeStream" src="https://user-images.githubusercontent.com/1288616/81260845-7c96c980-9058-11ea-93c5-4a31604aec21.png">

I checked the docs at https://reactjs.net/docs, and searched issues on GitHub but could not find any reference to how this Lighthouse suggestion may be implemented. Is this supported by ReactJS.NET?

**Comment by anuragbhd** [comment]
Gentle bump.

**Comment by dustinsoftware** [comment]
No it’s not supported at this time.

**Comment by anuragbhd** [comment]
Thanks for clarifying that, @dustinsoftware.
