### ISSUE TITLE
Issue when running React.NET in Azure web app

### ISSUE THREAD

**Issue by fremler** [reactjs/React.NET#1106]
I have a web app built on .Net framework 4.8 running in Azure, but I can't get React.NET to run properly. The file that is "missing" is [right in the directory](https://raw.githubusercontent.com/fremler/probable-memory/master/Anteckning%202020-05-07%20145534.png) were the error says it isn't.

I Googled for almost two days now, and my guess is that it's because of redistributable c++ 2015 is missing on the app "server". I've tried to include the DLLs for the package in my bin folder without luck.

I've also tried running withour server side rendering but I get the same error. Does anyone have React.NET running in an Azure app?

Below is a part of the stack trace.

`"EPiServer.Global : Unhandled exception in ASP.NET
React.Exceptions.ReactNotInitialisedException: ReactJS.NET has not been initialised correctly. Please ensure you have called services.AddReact() and app.UseReact() in your Startup.cs file. ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory ---> JavaScriptEngineSwitcher.Core.JsEngineLoadException: Failed to create instance of the V8JsEngine. Most likely it happened, because the 'v8-x64.dll' assembly or one of its dependencies was not found. See the original error message: “Cannot load V8 interface assembly. Load failure information for v8-x64.dll:
D:\local\Temporary ASP.NET Files\root\9a14b61e\9ccbdb01\assembly\dl3\2fe57c72\0033a03b_7012d601\x64\v8-x64.dll: The specified module could not be found
D:\home\site\wwwroot\x64\v8-x64.dll: The specified module could not be found
D:\home\site\wwwroot\bin\x64\v8-x64.dll: The specified module could not be found”. ---> System.TypeLoadException: Cannot load V8 interface assembly. Load failure information for v8-x64.dll:
D:\local\Temporary ASP.NET Files\root\9a14b61e\9ccbdb01\assembly\dl3\2fe57c72\0033a03b_7012d601\x64\v8-x64.dll: The specified module could not be found
D:\home\site\wwwroot\x64\v8-x64.dll: The specified module could not be found
D:\home\site\wwwroot\bin\x64\v8-x64.dll: The specified module could not be found
   at Microsoft.ClearScript.V8.V8Proxy.LoadNativeLibrary(String baseFileName)
   at Microsoft.ClearScript.V8.V8Proxy.LoadAssembly()
   at Microsoft.ClearScript.V8.V8Proxy.GetAssembly()
   at Microsoft.ClearScript.V8.V8Proxy.GetImplType(Type type)
   at Microsoft.ClearScript.V8.V8Proxy.CreateImpl[T](Object[] args)
   at Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags, Int32 debugPort)
   at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(V8Runtime runtime, String name, V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)
   at JavaScriptEngineSwitcher.V8.V8JsEngine..ctor(V8Settings settings)`

**Comment by dustinsoftware** [comment]
Please list the version of JavaScriptEngineSwitcher v8 you are using. Newer
versions do not need the runtime anymore afaik

**Comment by fremler** [comment]
Yes of course, sorry about that.

JavaScriptEngineSwitcher.Core 3.3.0
JavaScriptEngineSwitcher.V8 3.5.1
JavaScriptEngineSwitcher.V8.Native.win-x64 3.5.1
JavaScriptEngineSwitcher.V8.Native.win-x86 3.5.1
JSPool 4.0.0
React.Core 5.2.4
React.Web 5.2.4
React.Web.Mvc4 5.2.4

Those are the nuget packages that I have that I thought might be associated with React.NET. And I'm using webpack to bundle and transpile my js-files. I also import react via npm. Is there any other information I can provide?

**Comment by dustinsoftware** [comment]
Looks like the VC2019 runtime is required now for v8. I may have been
thinking of ChakraCore.....

https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v3.3.0

**Comment by Taritsyn** [comment]
@fremler All requirements for the JavaScript Engine Switcher's modules are specified in the descriptions of NuGet packages and [documentation](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki).

@dustinsoftware It seems that the latest version of Microsoft ClearScript.V8 library has broken the generation of detailed error messages.

```
JavaScriptEngineSwitcher.Core.JsEngineLoadException:
Failed to create instance of the V8JsEngine.
Most likely it happened, because the 'v8-x64.dll' assembly or one of its dependencies was not found.
See the original error message: “Cannot load V8 interface assembly.
Load failure information for v8-x64.dll: D:\local\Temporary ASP.NET Files\root\9a14b61e\9ccbdb01\assembly\dl3\2fe57c72\0033a03b_7012d601\x64\v8-x64.dll: The specified module could not be found D:\home\site\wwwroot\x64\v8-x64.dll: The specified module could not be found D:\home\site\wwwroot\bin\x64\v8-x64.dll: The specified module could not be found”.
```

Today I will try to fix this problem.

**Comment by fremler** [comment]
@Taritsyn Yeah I've probably read that as well at some point and I actually suspected that the missing Redistributable package was the issue. But I got confused with the error message.

@dustinsoftware I just tried running with the ChakraCore engine instead and that seems to be working fine so far! You really saved me a lot of time with your help, thank you so much!

**Comment by Taritsyn** [comment]
> I may have been thinking of ChakraCore.....

> I just tried running with the ChakraCore engine instead and that seems to be working fine so far!

@dustinsoftware @fremler In the last two versions of the JavaScriptEngineSwitcher.ChakraCore module due to application of the [Tomáš Deml's patch](https://github.com/microsoft/ChakraCore/issues/5973), it was fixed errors that occured in Linux. Therefore, now there are no restrictions on the use of this module.

**Comment by Taritsyn** [comment]
@fremler If you upgrade the JavaScriptEngineSwitcher.V8 package to [version 3.5.3](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v3.5.3), then error message will look like this:

```
JavaScriptEngineSwitcher.Core.JsEngineLoadException:
Failed to create instance of the V8JsEngine.
Most likely it happened, because the 'v8-zlib-x64.dll' assembly or one of its dependencies was not found.
Try to install the JavaScriptEngineSwitcher.V8.Native.win-x64 package via NuGet.
In addition, you still need to install the Microsoft Visual C++ Redistributable for Visual Studio 2019 (https://visualstudio.microsoft.com/downloads/#microsoft-visual-c-redistributable-for-visual-studio-2019).
```
