### ISSUE TITLE
[reactnet-webpack] Nested routes have ReactDOM undefined due to wrong manifest publicPath

### ISSUE THREAD

**Issue by mattywong** [reactjs/React.NET#1112]
Thanks for filing a bug! To save time, if you're having trouble using the library, please check off the items you have tried. If you are just asking a question, skip right to the bottom.

### Please verify these steps before filing an issue, and check them off as you go
- [x] The relevant native JavascriptEngineSwitcher library packages are installed (such as `JavaScriptEngineSwitcher.V8.Native.win-x64`)
- [x] The VC++ 2017 runtime is installed
- [x] The value of `SetUseReact` and `SetUseBabel` is correct in `ReactConfig.cs` or `Startup.cs`
- [x] I've looked at the sample projects in this repo to verify that my app is configured correctly

### I'm using these library versions:
- `ReactJS.NET`:
- `JavaScriptEngineSwitcher`:
- `react` and `react-dom`: (N/A if using bundled react, or version number)
- `webpack`: (N/A if using bundled react)
- `node`: (N/A if using bundled react)

### Runtime environment:
- OS: (Mac, Windows, Linux flavor. Include 32-bit/64-bit and version)
- .NET Framework or .NET Core Version:

### Steps to reproduce

Follow quick start guide with reactnet-webpack template. Go to /comments/page-2, check console, ReactDOM is undefined.

This is due to the webpack config missing the publicPath in ManifestPlugin, without it the path of the scripts are relative to the current route and not the actual wwwroot, e.g

@ /comments/page-2,

```
<script src="dist/bundle.js"></script> // /comments/dist/bundle.js
```
see:

https://github.com/reactjs/React.NET/blob/master/src/React.Template/reactnet-webpack/webpack.config.js

adding

```
new ManifestPlugin({
...,
publicPath: "/dist/", // suffix "/" is necessary otherwise a server error is thrown
...,
});
```

resolves this issue. Alternatively, also changing **output.publicPath** to "/dist/" should work too. See https://www.npmjs.com/package/webpack-manifest-plugin

```
output: {
    path: path.resolve(__dirname, "wwwroot/dist"),
    publicPath: "dist/", // before
    publicPath: "/dist/" // after
},
```

**Comment by dustinsoftware** [comment]
Nice catch, we can fix that....
