### ISSUE TITLE
How to achieve renderToNodeStream using React.NET ?

### ISSUE THREAD

**Issue by xtroncode** [reactjs/React.NET#1114]
Thanks for this awesome library.
We are using this library in production to server render our react application. We are observing that our time to first byte has increased on some large pages due to the time spent in rendering on the server. It is recommended to use `renderToNodeStream` to improve TTFB but I am not sure how it can be done using React.NET . Can someone point me in the right direction as to how to improve TTFB while using this library for SSR ?

**Comment by dustinsoftware** [comment]
Hey sorry for the delay on this, forgot to respond.

It probably won't be possible for a while; this library does not use Node streams at all (it uses an embedded JS engine like Chakra Core or V8).

Until renderToString is deprecated we probably won't move away from that as the SSR mechanism.
