### ISSUE TITLE
Documentation and Git repo does not match

### ISSUE THREAD

**Issue by IncrediblePony** [reactjs/React.NET#1120]
Hey - just wanted to let you know that in your tutorial you say that you use the `JavaScriptEngineSwitcher.V8` but in your `Startup.cs` in your own example on git you are using `JavaScriptEngineSwitcher.ChakraCore`

This information is not uniform :)

**Comment by Daniel15** [comment]
Either engine should be fine... @dustinsoftware Do you know if one engine should be preferred over the other?

**Comment by dustinsoftware** [comment]
V8 is windows only; chakra core is cross platform. V8 receives more active
support, Chakra Core is in maintenance mode now (but still works fine). The
docs should be updated to list them both as candidates. If we get the Node
engine to a place where it works well (it’s a bit rough around the edges
atm) then we would list that too.
