### ISSUE TITLE
Ability to provide own react.js version?

### ISSUE THREAD

**Issue by scratch-net** [reactjs/React.NET#113]
Hi there. 0.13 is out and 0.14 is approaching. Is it possible that we didn't have to wait for a next react.NET release and provide .js by ourselves?

**Comment by Daniel15** [comment]
I've added this in 27df77f84f2ea95994452b82f0d55c48493ba2df. Ensure you load a version of React in a script (eg. Webpack bundle) via `AddScriptWithoutTransform` and it should work fine. The only issue I can think of is if React's API changes between versions, as ReactJS.NET will still be calling the old methods internally (eg. `React.renderComponent` changing to `React.render` in 0.12).

**Comment by scratch-net** [comment]
Thanks a lot, no need to fork any more!
