### ISSUE TITLE
[Idea] Ability to specify own piece of js code when doing Html.React

### ISSUE THREAD

**Issue by Scratch-net** [reactjs/React.NET#114]
So, right now we rely on React.Net's internal composing of strings when we want to generate something on server side, but as you know the API may change dramatically in future versions.
Basically when using React serverside with webpack/etc we need 2 things
1) Load the big  webpacked JS ASAP (done in 1.5)
2) Run a piece of JS code that will return some html /clientside init

I suggest to add ability to compose js calls by ourselves in case main Html.React() will become outdated.

Moreover, it will make the library usable outside the ReactJS framework stack

**Comment by PeteDuncanson** [comment]
We've coded something like this in when we had to get ReactRouter working. I agree it would be a great idea to add in but the tricky bit comes from passing in .net vars you need to play with. For now we've got around that by creating a global object containing the bits we need that we poke into the engine before our script runs so it can safely reference the values it might need from the host. This object include the request url, form and query string values for now. That has made it super flexible.

**Comment by WirthAware** [comment]
I was looking for something similar. I'm using React and Redux. When we use server-side rendering i need to sync the redux initial state server-side and client-side. 

I had a look in the redux receipes for server-side rendering: https://github.com/rackt/redux/blob/master/docs/recipes/ServerRendering.md
That matches to this idea. 

My solution at the moment is more an anti pattern, but found no better way to do it. 
I'm using getInitialState function from React component to create the redux store with the initial state from Html.React. The redux state is now in sync server and client side. I'm not happy with it, but it works. 

I think that ability could help to build apps with React.NET.

**Comment by deevus** [comment]
@WirthAware I'm trying to solve the same problem, but I don't want to take your approach. I'm using Redux on a per page basis but I was trying to avoid creating specific components for every use.

**Comment by deevus** [comment]
For an event handler, perhaps it could be something like:

```
var props = new {
   onClick = new JsString("function (e) { e.preventDefault(); ... }")
};
```

React.NET would pass it as a function. Thoughts?

**Comment by WirthAware** [comment]
@deevus i'am a little bit lost. I was looking for a elegant solution to pass through the app state from the server redux to client redux and keep it in sync. 
How could onClick help me to do so? 
At the moment the easiest solution was just to use getInitialState from the root App component. 
I'am also using redux on a per page basis at the moment, each page is rendered server side.

**Comment by deevus** [comment]
@WirthAware Unless I'm mistaken, without some way to parse arbitrary Javascript to a child component I can't create a `<Provider>` with children that can change per page. It's not part of a one-page application so the state shape isn't static.
