### ISSUE TITLE
React is not working in IE11

### ISSUE THREAD

**Issue by gapsweety** [reactjs/React.NET#1149]
Hi I recently upgraded all the relevant packages to support our latest server 2019. And everything works fine with little tweaks on the existing code, but it doesnt seems to be working in IE11 at all. 
It seems to be Babel is not worked, it didn't convert the react code to plain javascript code.

All the react codes are displaying as it is

Framework: .Net MVC
.Net framework : 4.8
Please find the package config file.

package id="JavaScriptEngineSwitcher.ChakraCore" version="3.5.6" targetFramework="net48" />
package id="JavaScriptEngineSwitcher.Core" version="3.3.0" targetFramework="net48" />
package id="JavaScriptEngineSwitcher.Msie" version="3.4.3" targetFramework="net48" />
package id="JavaScriptEngineSwitcher.V8" version="3.5.5" targetFramework="net48" />
package id="JavaScriptEngineSwitcher.V8.Native.win-x64" version="3.5.5" targetFramework="net48" />
package id="JavaScriptEngineSwitcher.V8.Native.win-x86" version="3.5.5" targetFramework="net48" />
package id="JavaScriptEngineSwitcher.Vroom" version="3.3.0" targetFramework="net48" />

Can you let me know what I missed on this?

**Comment by dustinsoftware** [comment]
IE11 should still be working, not sure off hand why it is broken for you.

**Comment by gapsweety** [comment]
Any suggestion or clue might be helpful? since I haven't got the any relevant details from Google.

**Comment by dustinsoftware** [comment]
Take a look at the Mvc4 sample in this repo. It should build and work on
IE11. If it doesn’t, that is a bug we can look at fixing.

https://github.com/reactjs/React.NET/tree/main/src/React.Sample.Mvc4

**Comment by gapsweety** [comment]
Thanks for the sample. 

Finally I got to know the issue.

It works fine with Babel version 6, but not with 7.

So I am going to use the Babelversion 6 only to make it work in IE. I added the below configuration to make it work. Have to check anything else is breaking, but as of now it looks good with IE.

ReactSiteConfiguration.Configuration.SetBabelVersion(BabelVersions.Babel6);

**Comment by dustinsoftware** [comment]
Nice! Thanks for replying so others running into the same issue will find your solution :)
