### ISSUE TITLE
JSX parser unexpected token ">="

### ISSUE THREAD

**Issue by jpiccari** [reactjs/React.NET#116]
When a `=` is immediately preceded by a JSX "tag" it is interpreted as a single token rather than separate tokens. I'm seeing this issue on React.NET v1.4.0 while using `JsxBundle()` to bundle my JSX.

### Repro JSX code
```javascript
var Test = React.createClass({
	render: function() {
		return <i>=</i>;
	}
});
````
Working example (using in browser JSXTransformer.js) http://jsfiddle.net/a1k1mhge/

**Comment by Daniel15** [comment]
This looks like a bug with React 0.12, I can replicate the same issue on JSFiddle if I switch to using JSXTransformer 0.12: http://jsfiddle.net/a1k1mhge/1/. Please try upgrading to ReactJS.NET 1.5, as it upgrades React from 0.12 to 0.13 and should resolve this issue.

Thanks!
