### ISSUE TITLE
Improve error reporting for JsxBundle errors

### ISSUE THREAD

**Issue by mikecao** [reactjs/React.NET#117]
I am currently using the `System.Web.Optimization.React.JsxBundle` class to package all my `.jsx` files together. The entry in my `BundleConfig.cs` looks like this:

```C#
bundles.Add(
  new JsxBundle("~/bundle/jsx")
    .Include(
      "~/Scripts/*.jsx"
    )
);
```

However, whenever I get a syntax error, it doesn't specify the filename where the error occurred. The stack trace looks like this:

```
Error: Parse Error: Line 345: Unexpected token ) (at line 345 column 9)
   at ReactNET_transform (Script Document:50:9) -> throw new Error(ex.message + " (at line " + ex.lineNumber + " column " + ex.
Line: 50
Column:9

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: JavaScriptEngineSwitcher.Core.JsRuntimeException: Error: Parse Error: Line 345: Unexpected token ) (at line 345 column 9)
   at ReactNET_transform (Script Document:50:9) -> throw new Error(ex.message + " (at line " + ex.lineNumber + " column " + ex.
Line: 50
Column:9

Source Error: 
Line 12:     <div id="container"></div>
Line 13:     @Scripts.Render("~/bundle/js")
Line 14:     @Scripts.Render("~/bundle/jsx")
Line 15:     @RenderBody()
Line 16: </body>
```

I'm assuming the `at line 345 column 9` refers to a location of a concatenated file. It would really be helpful if the individual jsx file was mentioned somewhere, otherwise it's impossible to debug.

**Comment by Daniel15** [comment]
Good idea! I have a feeling the files have already been combined together by the time the JSX transformation runs, and Microsoft's bundling/minification framework doesn't output source maps, so we've already lost the original locations :(

I'll see if the transform can be ran earlier, before the combination takes place.

**Comment by keithn** [comment]
is there a work around for this? even knowing the text of the line of code that's a problem would be useful

**Comment by keithn** [comment]
this is what I ended up doing....

(using node)

**Comment by staznz** [comment]
I would also be very interested in this

**Comment by staznz** [comment]
That works brilliantly. Thanks @keithn

**Comment by Daniel15** [comment]
Hitting the JSX file directly (rather than the combined version) should give you the right line number, as long as you have the ReactJS.NET handler configured in Web.config. 

Unfortunately Microsoft's bundling/minification framework doesn't output source maps (so we've already lost the original locations by the time JSX is being processed), and they're discontinuing it with ASP.NET 5 in favour of using Gulp instead.

**Comment by Daniel15** [comment]
I'm going to close this out since Microsoft are no longer working on ASP.NET Web Optimization (`System.Web.Optimization`), and fixing this depends on changing Web Optimization to support it.

**Comment by keithn** [comment]
problem is knowing which file.

**Comment by cloudybrain** [comment]
I am having this problem even when setting - BundleTable.EnableOptimizations = false;

So there really is no optimizations happening.. maybe if this is turned off, we can capture the file, and if its turned on, make the debug just as encryptive as it is now?

**Comment by Daniel15** [comment]
@cloudybrain  - Setting `BundleTable.EnableOptimizations = false` should give you errors with correct file names and line numbers. This has been improved a bit in ReactJS.NET 2.0 and the error messages should be more useful now :)
