### ISSUE TITLE
Error on runtime

### ISSUE THREAD

**Issue by coyaniv** [reactjs/React.NET#119]
Hi,
I'm getting this error only in the azure env. 
React.Exceptions.ReactScriptLoadException: Error while loading "~/dist/scripts/hold.jsx": Expected identifier, string or number

What does it mean? How can I fixed this?

Thanks

**Comment by Daniel15** [comment]
Most likely you have a syntax error in your JavaScript, such as a trailing comma somewhere. It's possible that you're using the V8 engine when developing locally, but the MSIE engine when deploying to Azure. Try using the MSIE engine locally (simple way is to delete the ClearScript.V8 directory, as MSIE is only used as a fallback) and see if you encounter the same error.

Does the error have a line number?

**Comment by coyaniv** [comment]
The problem is coming from this code but I do not understand what is the problem...
 <div class="text-center">
	                    <small>By signing up, you agree to <a href="/terms" >Terms of Use</a> and <a href="/terms/privacy_policy">Privacy Policy</a>.</small>
	                    <br /><br />
	                    <small>Already got an account? <a onClick={this.handleClick} >Log In</a></small>
	                </div>

**Comment by Daniel15** [comment]
The code didn't come through properly, can you please post it via http://gist.github.com/ instead?

**Comment by coyaniv** [comment]
https://gist.github.com/coyaniv/d5a69e2097a700a81576

**Comment by coyaniv** [comment]
I'm not using  ClearScript.V8 locally (could not find this folder) but I'm still getting same error ...
The line number is point on "}"

**Comment by shadowii** [comment]
Hi Daniel,

I'm getting the same error after deploying to the server. I deleted the clearscript folder, but it continues to work fine locally. I've checked the js line that it's complaining about, but I see no error (it's built by webpack, too, I assume that would catch syntax errors?). 

The asp.net error:

```
[ReactScriptLoadException: Error while loading "~/Scripts/build/server.bundle.js": Expected identifier, string or number
Line: 934
Column:16]
   React.ReactEnvironment.EnsureUserScriptsLoaded() +646
   React.ReactEnvironment.CreateComponent(String componentName, T props, String containerId) +34
   React.Web.Mvc.HtmlHelperExtensions.React(HtmlHelper htmlHelper, String componentName, T props, String htmlTag, String containerId, Boolean clientOnly) +98
   ASP._Page_Views_Overview_Clients_cshtml.Execute() in e:\...\Clients.cshtml:403
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +280
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +126
   System.Web.WebPages.StartPage.ExecutePageHierarchy() +143
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +110
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +380
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +109
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +890
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +97
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +241
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +19
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +51
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +606
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +288
```

The relevant js line ("marker" is line 934, col 16):
```javascript
line: {
	              marker: {
	                  enabled: true,
	                  symbol: "triangle"
	              },
	              shadow: true
	          }
```

**Comment by shadowii** [comment]
I don't know if this will help or not, but I've noticed that the server took an unusual amount of time to load the page. Eventually I just deleted everything from the return object in GetDefaultProps, and it did load the page, but eventually it lead to an out of memory exception. I will follow up as I test more.

**Comment by shadowii** [comment]
@Daniel15 So you were right, it was an extra comma. Not quite at the line given, but near there. I ended up clearing all the properties and adding them in one by one. I'm surprised the JSX transpiler didn't pick it up, nor did VS once it was converted to JS. 

Well, TIL, just looked it up, trailing commas are valid in JS. http://stackoverflow.com/questions/7246618/trailing-commas-in-javascript

On another note, do you recommend V8 on the server? And how can one verify which engine is being used?

**Comment by Daniel15** [comment]
Hi! Sorry for the delay in replying!

> Well, TIL, just looked it up, trailing commas are valid in JS.

They're valid in most modern JS engines, but Internet Explorer doesn't like them. ReactJS.NET falls back to the MSIE engine if initialisation of V8 fails for whatever reason.

> Not quite at the line given, but near there

Yeah the line numbers are a bit off at the moment, I need to work on fixing that.

> On another note, do you recommend V8 on the server?

Yeah, it's much better than the MSIE engine :)

> And how can one verify which engine is being used?

That's a good question; it's pretty difficult to tell at the moment. One thing you can do is call `.SetAllowMsieEngine(false)` on your config, which will force it to only use the V8 engine (and throw an exception if it fails to initialise).

You should be able to get the current engine details by doing something like this:
```
var engineFactory = React.AssemblyRegistration.Container.Resolve<IJavaScriptEngineFactory>();
var engine = engineFactory.GetEngine();
var name = engine.Name;
var version = engine.Version;
engineFactory.ReturnEngineToPool(engine);
// Use the values of name and version.
```
I haven't tested this, but it should work.

**Comment by samppis** [comment]
I had this same problem and found a way around it by running V8 in Azure. Here's a blog post I wrote about it:  
http://www.samulihaverinen.com/web-development/dotnet/2016/01/19/how-to-run-clearscript-v8-javascript-engine-in-azure/

**Comment by Daniel15** [comment]
Thanks @samppis!  Since you have experience getting ReactJS.NET working in Azure, it would be great if you could add a documentation page about it :smile: The ReactJS site is in the `site` directory of this repo, in Markdown format.

I noticed you mentioned this in your post:

> Unfortunately for ASP.NET 5 people ReactJS.NET is using and older version (1.2.4) of JavaScriptEngineSwitcher.V8 package

I'll upgrade JavaScriptEngineSwitcher to the latest version soon :)

**Comment by samppis** [comment]
@Daniel15 Sure, I'll try to find some time for writing the documentation :smile: And thanks for upgrading the JavaScriptEngineSwitcher. Please let me know when it's done so that I can update that part on the blog post.

**Comment by samppis** [comment]
@Daniel15 I'm having trouble building the site (on windows). Running `jekyll build` gives the following error even though I've installed jekyll, jekyll-assets and bourbon:

    C:/tools/ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': 
    cannot load such file -- jekyll-assets/bourbon (LoadError)

What versions of those gems are you using? If you want you can shoot me with an email: samuli.haverinen@gmail.com

**Comment by Daniel15** [comment]
@samppis - Interesting, I'm not quite sure what's going on there. I haven't actually tried building the site on Windows - I'm using Mac OS (unfortunately - it's my work machine) in development and Linux in production. 

I'm not very familiar with Ruby and a lot of the Jekyll boilerplate was copied from the React site, but running `gem list` shows these versions installed on my machine:
```
bourbon (3.1.8)
jekyll (2.5.3, 2.2.0, 1.5.1, 1.3.0)
jekyll-assets (0.10.0, 0.7.7)
jekyll-coffeescript (1.0.1, 1.0.0)
jekyll-gist (1.2.1, 1.1.0)
jekyll-paginate (1.1.0, 1.0.0)
jekyll-redirect-from (0.8.0, 0.5.0)
jekyll-sass-converter (1.3.0, 1.2.0)
jekyll-watch (1.2.1, 1.1.0)
```

**Comment by samppis** [comment]
@Daniel15 Thanks. Unfortunately even after hours of trying I can't get the site to build. I'm not that familiar with ruby either but my guess is that it's a version conflict. When I run `gem install jekyll jekyll-assets bourbon` the following versions are installed:

```
jekyll (3.0.2)
jekyll-assets (2.1.2)
bourbon (4.2.6)
```

I tried to install the same versions that you have using [Development kit](https://github.com/oneclick/rubyinstaller/wiki/development-kit) but without luck. Running for example `gem install jekyll -v 2.5.3` gives the following error and I have no clue what might be causing it:

```
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    C:/tools/ruby22/bin/ruby.exe -r ./siteconf20160124-10120-z9bwh3.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating stemmer-x64-mingw32.def
      0 [main] sh 8356 fork_copy: linked dll data/bss pass 0 failed, 0x1E8000..0x1E8AD8, done 0, windows pid 10144, Win32 error 487
/bin/sh: fork: Resource temporarily unavailable
make: *** [stemmer-x64-mingw32.def] Error 128

make failed, exit code 2

Gem files will remain installed in C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/fast-stemmer-1.0.2 for inspection.
Results logged to C:/tools/ruby22/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/fast-stemmer-1.0.2/gem_make.out
```

**Comment by Daniel15** [comment]
@samppis Ah, that's annoying :( Feel free to just write up your content in Markdown format and submit a pull request without actually testing the Jekyll site (or just email the content to me if you prefer, email address is on my Github profile). I can pull your branch and ensure the page looks fine.  Thanks!

**Comment by samppis** [comment]
@Daniel15 Thanks for updating the JavaScriptEngine switcher. It seems to magically fix all issues and the V8 engine now runs out of the box in Azure! I still thought it might be a good idea to document the Azure support so I wrote a brief guide and submitted a pull request.

**Comment by Daniel15** [comment]
Great, thanks :+1: Closing this out since it sounds like there's no remaining issues.
