### ISSUE TITLE
Webpack template not supporting runtime compilation of React?

### ISSUE THREAD

**Issue by plrusek** [reactjs/React.NET#1204]
Like in the topic - it seems that for the brief time I used the vanilla template, making changes to .jsx files recompiled them on website refresh (what I'm used to coming from Razor runtime compilation). This does not happen on the webpack template - is that normal? Am I able to configure runtime compilation?

**Comment by baxxos** [comment]
@plrusek I'm sorry to revive this old thread but do you by any chance remember how did you resolve this? I'm currently struggling to make it work with Webpack.

**Comment by plrusek** [comment]
this was a problem back at my old job, but uh no, sorry, i'm pretty sure we went back to vanilla.
