### ISSUE TITLE
Webpack template does not work on Chrome or Brave browser

### ISSUE THREAD

**Issue by technicallyty** [reactjs/React.NET#1208]
Thanks for filing a bug! To save time, if you're having trouble using the library, please check off the items you have tried. If you are just asking a question, skip right to the bottom.

### Please verify these steps before filing an issue, and check them off as you go
- [x ] The relevant native JavascriptEngineSwitcher library packages are installed (such as `JavaScriptEngineSwitcher.V8.Native.win-x64`)
- [ x] The VC++ 2017 runtime is installed
- [ x] The value of `SetUseReact` and `SetUseBabel` is correct in `ReactConfig.cs` or `Startup.cs`
- [x ] I've looked at the sample projects in this repo to verify that my app is configured correctly

### I'm using these library versions:
- `ReactJS.NET`: reactnet-webpack template
- `JavaScriptEngineSwitcher`:  reactnet-webpack template
- `react` and `react-dom`: reactnet-webpack template
- `webpack`:  reactnet-webpack template
- `node`: (N/A if using bundled react)

### Runtime environment:
- OS: (Mac, Windows, Linux flavor. Include 32-bit/64-bit and version)
Windows 10
- .NET Framework or .NET Core Version:
.NET CORE 3.1
### Steps to reproduce
Follow the instructions for new projects on https://reactjs.net/bundling/webpack.html. 
Try running dotnet run and going to the corresponding localhost output by the console.
-------

(Describe your issue here)

I was attempting to look into solutions ReactJS.NET were providing by example. I was interested in the webpack sample, but the code does not seem to produce a working output. I've tried running dotnet run after following the instructions on https://reactjs.net/bundling/webpack.html. After some amount of time, I am shown by the console to go to a localhost route, but when visiting this page, the browser returns `This site can’t provide a secure connection .localhost sent an invalid response.`  This happens on both Brave and Chrome browser. This code runs on Firefox, however.

**Comment by dustinsoftware** [comment]
What error did you get? A screenshot would be helpful.

Yes the project is kept up to date...

**Comment by technicallyty** [comment]
For some reason, whenever i ran my code, hsts was blocking the localhost connection. I had to go to this flag:

`brave://net-internals/#hsts` for brave users, or `chrome://net-internals/#hsts` for chrome users, and do this:
![image](https://user-images.githubusercontent.com/48813565/94313014-d417d200-ff32-11ea-9d83-efbfa617743b.png)

I believe my program.cs or startup.cs was tampering with the browser.
