### ISSUE TITLE
Server-side `console.log`s before client-side

### ISSUE THREAD

**Issue by SoonDead** [reactjs/React.NET#122]
I love the current console shim. It is great to be able to output messages on the server.

What could be improved is the ordering of server and client-side messages. The server-side messages should show up on the console before client-side rendering happens.

Might be solvable with a simple reordering of `GetInitJavaScript()`, where the `consoleCalls` are appended before the components.

**Comment by Daniel15** [comment]
Yeah, you should simply be able to swap the order such that the console calls are first: https://github.com/reactjs/React.NET/blob/master/src/React.Core/ReactEnvironment.cs#L293-301

Feel free to send a pull request :)

**Comment by Daniel15** [comment]
This was merged in #133
