### ISSUE TITLE
Feed array to Html.React as object literal

### ISSUE THREAD

**Issue by SoonDead** [reactjs/React.NET#123]
I'm using server-side rendering.
I need to feed some data to the initial render of the component.

Usually on client-side I'm initializing the component's state with nulls and empty objects, and I only fetch the data through ajax on componentDidMount.

On the server-side this is a no-go. But I can fetch the same data there and feed it to the component as a property:

    var jsonListResult = new JavaScriptSerializer().Serialize(list);
    @Html.React("MyComponent", new
    {
        initialListItems = jsonListResult.ToString()
    })

Then in the component I can use it as:

    getInitialState: function () {
        return {
            listItems: JSON.parse(this.props.initialListItems),
        };
    }

There is an unnecessary JSON parse on both server and client side.

I would like to be somehow able to just use:

    @Html.React("MyComponent", new
    {
        initialListItems = list
    })

Where this would render the the parameter as an object literal. Can this be done somehow?

**Comment by PeteDuncanson** [comment]
Under the hood the @Html.React call will convert your Model (in this case your list) to JSON and inject it in as a string which when parsed by the JS engine on the server will appear as a object literal. As a result you should be able to just do this:

````
@Html.React("MyComponent", new
{
    initialListItems = list
})
````

And then you can load it in your component. You are using getInitialState, I'd be tempted to use getDefaultProps instead as you are passing in your values as props, depend on what you intend to do with that initial data I guess as its not clear from your question, either way they look very similar:

````
getInitialState: function () {
    return {
        listItems: this.props.initialListItems,
    };
}

// or

getDefaultProps: function () {
    return {
        listItems: this.props.initialListItems,
    };
}

````

**Comment by Daniel15** [comment]
As @PeteDuncanson mentioned, just put your data in the props directly, and ReactJS.NET will handle serialising it for you. This is exactly what the bundled sample code does: https://github.com/reactjs/React.NET/blob/master/src/React.Sample.Mvc4/Views/Home/Index.cshtml#L16-L17

**Comment by SoonDead** [comment]
Thank you.
