### ISSUE TITLE
Node Stream support for react v18?

### ISSUE THREAD

**Issue by LorenDorez** [reactjs/React.NET#1265]
With the upcoming React v18 i was wondering if much thought has been given about how to implement Node streams. As some of the new features for v18 React.Lazy and React.Suspense will be leveraging a new nodestream https://github.com/reactwg/react-18/discussions/22 

i dont have much experence on the node side of this. im not sure where to start with a basic implementation using `renderToNodeStream` any guidance would be appreciated.

I though about trying to do something with Web sockets and tie into the JS Engines that way but not sure that would work.

**Comment by dustinsoftware** [comment]
Yeah I’m not sure the embedded v8 engine would support this at all with the
current architecture. Might need to revisit some
kind of real Node interop later, I believe there was a PR from a while ago
that explored making that work.

For now only string based rendering is supported, at least until we sort
that path out.

**Comment by LorenDorez** [comment]
Well I see JES has a node engine that could be used but again not sure how you would be able to wireup the cross talk between JSE <> .Net <> Client. I was thinking you could use websockets or signalR to help with the .Net <> Client but not sure the JSE can handle the constant connection between it and .Net
