### ISSUE TITLE
Add an option to support renderToStaticMarkup method

### ISSUE THREAD

**Issue by xabikos** [reactjs/React.NET#127]
Reactjs provides the method [renderToStaticMarkup][static] which is very useful when we need to render a page server side but not edit it client side. This method doesn't add all the extra react specific data-attributes so the produced markup is lot cleaner.

[static]: https://facebook.github.io/react/docs/top-level-api.html#react.rendertostaticmarkup

**Comment by xabikos** [comment]
I am working on a pull request to resolve this

**Comment by Daniel15** [comment]
Merged the pull request, thank you! :)
