### ISSUE TITLE
Feed JSON to Html.React()

### ISSUE THREAD

**Issue by SoonDead** [reactjs/React.NET#132]
I have found myself in a scenario where I'm trying to pass a JavaScript object literal serialized as JSON to a property of the second parameter of `Html.React()`. Currently I'm doing this by Serializing the JSON into an anonym object, and using that.

This seems somewhat wasteful since it will get serialized internally anyway.

Is there a way to just pass that JSON object to be used?

If not, this might be easily achieved by definig a JSON type with a string property and prepare the library for that.

**Comment by Daniel15** [comment]
Where is the data coming from? Do you have a C# object containing your
data? You could pass that object as the second parameter  directly, rather
than wrapping it in an anonymous object.

**Comment by SoonDead** [comment]
The component loads it's data from a web service by an AJAX request.
This service is a black-box from our perspective, it returns JSON.

The problem is that I want to seed the component with initial data, so the first server side render has some actual value.

I'm trying to do this by fetching the result from the webservice server side, and feeding the result string as a parameter to my component:

    @Html.React("comp", new { initialJsonResult = result })

I could create a type just to deserialize the result into, so React.NET could later serialize it into an object literal.
Or I could do what I'm currently doing: calling `JSON.parse(this.props.initialJsonResult)` in `getInitialState()`.

Circumventing the web service and try to access the data in a non-json format would require us to tear out a lot of guts.

**Comment by Daniel15** [comment]
Try deserializing the data into a dynamic object (`dynamic result = JObject.Parse(rawResult)`) and pass the JObject in as a prop. I think JSON.NET should handle that.

**Comment by Daniel15** [comment]
Closing this out since this is a discussion rather than an issue, but please feel free to reply if you still need assistance. Thanks!
