### ISSUE TITLE
React MSBuild Transforming JSX to read only JavaScript files.

### ISSUE THREAD

**Issue by DamageInc54** [reactjs/React.NET#135]
I'm having an issue using React MSBuild with a project that uses TFS as Source Control. React MSBuild always tries to generate the JavaScript file even when no changes have been made to the JSX files. This is causing an error when building since it can't overwrite the JavaScript files if they are not checked out.

I was going to try and add a parameter to only do JSX files that are NOT read only but wanted to know if you thought it was worth it first. I realize it's not the most elegant solution, but it will work in my case. I don't want to change any default behavior, just add the setting.

**Comment by Daniel15** [comment]
You shouldn't be checking in the `*.generated.js` files (or in general, *any* generated files) to source control.

Having said that, the MSBuild transform could be adjusted to only write the file if it has been modified. The simplest solution would be to add a `WriteAsStringIfNotModified` method to `IFileSystem` that would first read the file and compare whether it's changed before writing it out, and then use that [here in JsxTransformer](https://github.com/reactjs/React.NET/blob/master/src/React.Core/JsxTransformer.cs#L384)

The generated JS files have a hash at the start of them, so it could just compare the hash of the old output vs the new output. This would be more efficient than comparing the whole file and is probably what I'll end up doing.

**Comment by DamageInc54** [comment]
Good point. I hadn't thought of just including the generated files in the project but excluding them from TFS. I guess that should work both locally and on the build server. Thanks much. And thanks for writing this great tool.

**Comment by Daniel15** [comment]
Let me know how that goes :)

That should work even better with the upcoming ASP.NET 5  as you no longer need to explicitly include files in the project like you do now (it just implicitly includes all files in the folder).

**Comment by DamageInc54** [comment]
Worked like a charm. Thanks for the idea.

I'm not closing this in case you want it to remain open until you make the changes you described above. My issue is resolved so close it at your discretion.

**Comment by Daniel15** [comment]
Closing this out since I haven't had any other requests for this.
