### ISSUE TITLE
How dependent on React is react.net?

### ISSUE THREAD

**Issue by ztsmith** [reactjs/React.NET#137]
I understand there are some react specific features like jsx compilation.
But if this is mostly just a wrapper over a Javascript engine, is there any reason why one wouldn't be able to use any isomorphic framework? Or execute any non dom dependent javascript?
Maybe there is a case to make a more generic library e.g. Isomorphic.NET?

**Comment by Daniel15** [comment]
If you just want to run JavaScript, you could use JSPool or
JavaScriptEngineSwitcher or ClearScript directly. There's some useful stuff
in ReactJS.NET that could probably be generalised (eg. the caching of
transformed JSX files could be changed to a generic "run this transformer
and cache the result") but the core functionality is provided by a JS
engine.

**Comment by Daniel15** [comment]
Closing this out since it's mainly a discussion, but feel free to comment if you have any other feedback :)
