### ISSUE TITLE
Unable to run reactjs in 64 bit mode 

### ISSUE THREAD

**Issue by espot** [reactjs/React.NET#139]
I have followed http://reactjs.net/getting-started/tutorial.html to ge tstarted with RectJS. 
The first step works fine running in IISExpress. However running the same example in "real" IIS does not work. I Get the following error:

```
 Server Error in '/' Application.

 Unable to resolve type: React.Web.IJsxHandler

 Description: An unhandled exception occurred during the execution of the current web request.   Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.Web.IJsxHandler

 Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

 Stack Trace: 


[TinyIoCResolutionException: Unable to resolve type: React.Web.IJsxHandler]
       React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration,     NamedParameterOverloads parameters, ResolveOptions options) +1165
   React.TinyIoC.TinyIoCContainer.Resolve() +163
   React.Web.JsxHandlerFactory.ProcessRequest(HttpContext context) +52
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +913
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +165
```

If I set  "Enable 32 bit applications" to true in the application pool, the solution starts to work.

Based on this I guess the problem is related to instansiating  the 64bit react dll (or v8 component)
I have tried installing the x64 runtime components but to no help.

**Comment by Daniel15** [comment]
Hmm, I guess this has something to do with the native library (V8) used by ClearScript.

Does that exception have an InnerException? Try attaching a debugger to the 'real' IIS and see. If it's a remote server, you can use the remote debug functionality in Visual Studio.

**Comment by espot** [comment]
In the debugger I get: " ReactJS.NET has not been initialised correctly." when running as a 64 bit process.

**Comment by Daniel15** [comment]
What's the InnerException? The very innermost InnerException should have more detail.

**Comment by espot** [comment]
InnerException : 
TinyIoC.TinyIoCResolutionException: {"Unable to resolve type: React.IReactEnvironment"}
Data: ListDictionaryInternal (count 0)
HelpLink: null
HResult: -2146233088
InnerException: null
Message: Unable to resolve type: React.IReactEnvironment
Source: React
StackTrace:    at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.Resolve[ResolveType]()
   at React.Web.Mvc.HtmlHelperExtensions.get_Environment()

**Comment by ryanhelms** [comment]
Any resolution to this? I have the same situation happening. The difference with me is that I am building from source and adding support for a ServiceStack AppHost. 

Thanks!

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
