### ISSUE TITLE
ClearScript/V8 dependency

### ISSUE THREAD

**Issue by toddlucas** [reactjs/React.NET#141]
Would it be possible to run React.NET without this? I really dislike the idea of adding 9MB of binaries, which is the size of my entire repo. NuGet allows us to avoid this typically. Plus, any updates will cause this size to expand.

I understand that it may not be possible to access the features you need through the JS engine switcher, which is probably why you link directly to MSIE and V8. Just curious if you see a workaround. Thanks!

**Comment by Daniel15** [comment]
V8 is optional, ReactJS.NET falls back to the MSIE JS engine if V8 is not available. You can just remove the reference to the ClearScript assemblies.

**Comment by toddlucas** [comment]
Oh I see. So I need to keep JavaScriptEngineSwitcher.V8, due to the dependency, but that component dynamically loads the ClearScript assemblies if it finds them (due to the need to run 32 bit or 64 bit). Thanks for the tip.
