### ISSUE TITLE
support tsx - typescript jsx files

### ISSUE THREAD

**Issue by prabirshrestha** [reactjs/React.NET#145]
Typescript supports JSX via `--jsx react` flag for `.tsx` extensions. It is currently merged in master branch but will be released in 1.6.

https://github.com/Microsoft/TypeScript/pull/3564

**Comment by Daniel15** [comment]
Hmm, I wonder how this would work. What language is the TypeScript compiler written in? Can I somehow embed it in ReactJS.NET?

**Comment by prabirshrestha** [comment]
It is written in typescript but you can use the compiled javascript files.

JSX will be supported in typescript 1.6 which is not released yet. The best way to try it out is to use the nightly builds as documented in the ts readme.

```bash
npm install -g typescript@next
```

More details at http://www.jbrantly.com/typescript-and-jsx/

**Comment by xaclincoln** [comment]
Is typescript supported now (2015/10/24), guys?

**Comment by protron** [comment]
I configured my Visual Studio project to use typescript + jsx (tsx files). VS compiles those tsx files into js on save, and I use those js files as input for reactjs.net. Works great and now VS 2013 understands the html tags inside the javacript (which don't work in jsx files, but they do in tsx files).

**Comment by Daniel15** [comment]
Closing this out since I think TypeScript is outside the scope of ReactJS.NET at the moment, and I won't get enough time to implement it. Personally I use Flow, and Flow types are already supported by Babel.

Unless someone wants to submit a pull request to add support! I'm always happy to accept pull requests :)

**Comment by ionescudev** [comment]
Flow ? I cant use flow in visual studio ( not visual code ).

**Comment by nmocruz** [comment]
sad, useless to me. moving to another option

**Comment by dustinsoftware** [comment]
This issue is really old but it’s always been possible to use webpack to build typescript files. With Babel 7 support it could probably support typescript types directly.
