### ISSUE TITLE
Does not work with MVC 6.0.0-beta4

### ISSUE THREAD

**Issue by varghesep** [reactjs/React.NET#148]
I have been following the instructions on this [http://reactjs.net/getting-started/aspnet5.html](ASP.NET MVC 6.0 Integration page) to integrate React.NET with a project created in the Visual Studio 2015 RC.

I used DNX 4.5.1 to build the project. This is the error I get:

**'IApplicationBuilder' does not contain a definition for 'UseRequestServices' and no extension method 'UseRequestServices' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)**

I commented out the line which compiled the project successfully. However, the sample app does not work. I don't see any rendering of the component on the html page. I looked at the project whether or not there is a **.JS** file created as a result of the build. I don't see one.

**Comment by xabikos** [comment]
The sample works fine with the beta4 version of asp.net 5. From the error you mentioned I guess that you tried to build and execute the sample with beta 5 and not beta 4. Try to execute the dmvm list on a command line and see which version of dnx is active. 

I am saying this as  a couple of days ago I made the changes to support the beta 5 version and will be released soon.

**Comment by Daniel15** [comment]
Sorry for the delay. I've pushed an update to ReactJS.NET that updates it to use Beta 6. It should now work fine on Visual Studio 2015 RTM + ASP.NET 5 Beta 6. Thanks!
