### ISSUE TITLE
Exception on Azure Env.

### ISSUE THREAD

**Issue by coyaniv** [reactjs/React.NET#149]
I'm getting this exception on Azure production env.
"JSPool.Exceptions.JsPoolExhaustedException: Could not acquire JavaScript engine within 00:00:05\r\n   at JSPool.JsPool.GetEngine(Nullable`1 timeout)\r\n   at React.JavaScriptEngineFactory.GetEngine()\r\n   at React.ReactEnvironment.\u003c.ctor\u003eb__13_1()\r\n   at System.Lazy`1.CreateValue()\r\n   at System.Lazy`1.LazyInitValue()\r\n   at System.Lazy`1.get_Value()\r\n   at React.ReactEnvironment.get_Engine()\r\n   at React.ReactEnvironment.EnsureUserScriptsLoaded()\r\n   at React.ReactEnvironment.CreateComponent[T](String componentName, T props, String containerId)\r\n   at React.Web.Mvc.HtmlHelperExtensions.React[T](HtmlHelper htmlHelper, String componentName, T props, String htmlTag, String containerId, Boolean clientOnly)\r\n   at ASP._Page_Views_Shared__Header_cshtml.Execute()\r\n   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()\r\n   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()\r\n   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)\r\n   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)\r\n   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)\r\n   at System.Web.Mvc.HtmlHelper.RenderPartialInternal(String partialViewName, ViewDataDictionary viewData, Object model, TextWriter writer, ViewEngineCollection viewEngineCollection)\r\n   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)\r\n   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model)\r\n   at ASP._Page_Views_Shared__WebsiteLayout_cshtml.Execute()\r\n   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()\r\n   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()\r\n   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)\r\n   at System.Web.WebPages.WebPageBase.\u003c\u003ec__DisplayClass3.\u003cRenderPageCore\u003eb__2(TextWriter writer)\r\n   at System.Web.WebPages.HelperResult.WriteTo(TextWriter writer)\r\n   at System.Web.WebPages.WebPageBase.Write(HelperResult result)\r\n   at System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body)\r\n   at System.Web.WebPages.WebPageBase.PopContext()\r\n   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)\r\n   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)\r\n   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)\r\n   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.\u003c\u003ec__DisplayClass21.\u003c\u003ec__DisplayClass2b.\u003cBeginInvokeAction\u003eb__1c()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.\u003c\u003ec__DisplayClass21.\u003cBeginInvokeAction\u003eb__1e(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Controller.\u003cBeginExecuteCore\u003eb__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Controller.\u003cBeginExecute\u003eb__15(IAsyncResult asyncResult, Controller controller)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.MvcHandler.\u003cBeginProcessRequest\u003eb__5(IAsyncResult asyncResult, ProcessRequestState innerState)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result)\r\n   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean\u0026 completedSynchronously)\r\n"
}

**Comment by Daniel15** [comment]
Try turning off polling (call `.SetReuseJavaScriptEngines(false)` in your config) and see if that resolves the issue.

**Comment by Daniel15** [comment]
I haven't heard back so I'm going to close this out, but let me know if you're still encountering issues. I know at least several people are successfully using ReactJS.NET on Azure, so this seems like a config issue. Turning off JS engine pooling may work around the issue :)
