### ISSUE TITLE
Could not install package 'React.AspNet 1.5.2

### ISSUE THREAD

**Issue by lzliu** [reactjs/React.NET#150]
In final vs2015 (not the RC version) MVC webapplication project using NETFramework,v4.6, when I install the React.AspNet package get the following errors::

Package 'React.AspNet 1.5.2' does not exist in project 'ReactJSWeb' Package 'React.AspNet 1.5.2' does not exist in folder 'E:\Projects\vs2015\ReactJSWeb\packages' Install-Package : Could not install package 'React.AspNet 1.5.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. At line:1 char:1 + Install-Package React.AspNet + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [Install-Package], Exception + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by Daniel15** [comment]
I think this maybe due to the fact that ReactJS.NET had a dependency on ASP.NET Beta 4, whereas you're using Beta 5. I just pushed ReactJS.NET 1.5.3 which switches the dependencies to Beta 5. Try upgrading to 1.5.3 and let me know if that works for you. Thanks!

**Comment by Daniel15** [comment]
Closing this out since I haven't heard back, but let me know if you're still encountering issues.

**Comment by lzliu** [comment]
Sorry for delayed reply, I was busy in my project. Thanks a lot for your great work and your help!
