### ISSUE TITLE
Simpler API

### ISSUE THREAD

**Issue by yoshicarroll** [reactjs/React.NET#154]
I would love to have an API that worked like this:

string html = ReactRenderToString("ComponentName", "{props:'as a string'}", "//Precompiled JS bundle");

Logically just a server side wrapper around React.renderToString. I would serialize the JSON, create the bundle that has transformed JSX, and worry about reading in the bundle and caching it.

Would adding something like this be of interest?

I realize this API would bypass most of React.NET's features, but for our use cases most of those features get in the way.

Thanks!

**Comment by Daniel15** [comment]
Hmm interesting idea. I'd probably need to split [ReactEnvironment.cs](https://github.com/reactjs/React.NET/blob/master/src/React.Core/ReactEnvironment.cs) into several smaller classes. I'd like to do that at some point anyway, as it's pretty big at the moment. 

Have you tried using `IReactEnvironment` directly? Perhaps you could just call `CreateComponent`.  You can get it through:
```csharp
var environment = React.AssemblyRegistration.Container.Resolve<IReactEnvironment>();
```
IReactEnvironment is scoped to the web request; one request = one IReactEnvironment

On the other hand, for your use case, perhaps just using a JavaScript engine (JavaScriptEngineSwitcher or ClearScript  V8) directly is the best approach? You could just do the `React.renderToString` call yourself in that case.

It really depends on how much abstraction you want :smile: What would your ideal library handle? How much should it do vs how much would you want to do yourself?

**Comment by yoshicarroll** [comment]
Using IReactEnvironment directly gave me 90% of what I wanted. Thanks. :)

Now if I wanted to reset the environment during my development workflow, is there an easy way to do that? I figure I could just re-evaluate my bundle (using Execute(bundleText) ) and that should probably work for what I need. We're using your Webpack pattern to create a separate bundle for server side components.

Using a JS engine directly might be where we end up, but you've already created the engine management infrastructure and I didn't want to redo that work now. It sounds like when you do split ReactEnvironment into smaller pieces we might end up with a small project that manages JS engines in a performant way and React.NET would sit on top of that. Is that what you were thinking?

Thanks again for your help.

**Comment by Daniel15** [comment]
> Now if I wanted to reset the environment during my development workflow, is there an easy way to do that?

It should already be automatically recycling the JS engines every time any of the loaded files change. You can also do `config.SetReuseJavaScriptEngines(false)`  in your config, which will create a new JS engine every time (slower, but you're guaranteed a fresh environment).

> we might end up with a small project that manages JS engines in a performant way and React.NET would sit on top of that

I already did that a while back, which resulted in [JSPool](https://github.com/Daniel15/JSPool) :)

**Comment by yoshicarroll** [comment]
Haha, JSPool looks great, it's exactly what I had in mind. =)

I just looked at the engine recycling again and it looks to do exactly what it should be doing. Look like some user error on that one.

Cheers!

**Comment by Daniel15** [comment]
Glad to help, let me know if you have any other questions :)

**Comment by mwethington** [comment]
Hi Daniel,

I am working with Yoshi. Why don't we split it up so that we can support both use cases?  The HtmlHelperExtensions Helper appears to use a response.write... Also, wouldn't React.renderToString potentially cause Garbage Collection issues for LOH when string is greater than 85,000 bytes? Normally we use Streams and avoid Strings.

https://blogs.msdn.microsoft.com/dotnet/2011/10/03/large-object-heap-improvements-in-net-4-5/

Thanks,

Bill

**Comment by Daniel15** [comment]
> .. Also, wouldn't React.renderToString potentially cause Garbage Collection issues for LOH when string is greater than 85,000 bytes

It's possible. This is something I didn't know about! Thanks for the link. I'm not sure of a way to server render React components without `renderToString` though, and I'm not sure of how we could get the result from the JavaScript without transferring the whole string. Perhaps it could be stored in a JS variable and returned one piece at a time, or something like that.
