### ISSUE TITLE
How can I close "console.warn" message

### ISSUE THREAD

**Issue by CityRay** [reactjs/React.NET#155]
Hi,
When I developed  through "Server-Side Rendering", it display a lot of warning. 
How can I close "console.warn" message in my production.
Thanks

**Comment by Daniel15** [comment]
Fix the warnings and they'll go away :stuck_out_tongue_winking_eye:  Normally warnings are things that should really be fixed.

**Comment by Daniel15** [comment]
Closing this out but feel free to respond if you still have questions :)
