### ISSUE TITLE
JsxBundle returns 404 and causes JavaScriptEngineSwitcher exception

### ISSUE THREAD

**Issue by ssippe** [reactjs/React.NET#156]
Hi,

I've wired up a jsxbundle like so...

bundles.Add(new JsxBundle("~/bundles/StandardExtraItem").Include(
                "~/Views/StandardExtraItem/extraItems.jsx"));

...and am including the bundle in my page like so...

@Scripts.Render("~/bundles/StandardExtraItem")    

...but on loading the page the request to the jsx file is returning 404 when ruinning IIS Express from Visual Studio.

In the Debug out put there is an exception...

Error initialising System.Func`1[JavaScriptEngineSwitcher.Core.IJsEngine]: System.NullReferenceException: Object reference not set to an instance of an object.
   at JavaScriptEngineSwitcher.V8.V8JsEngine..ctor(V8Configuration v8Config)
   at JavaScriptEngineSwitcher.V8.V8JsEngine..ctor()
   at React.AssemblyRegistration.<>c.<RegisterSupportedEngines>b__3_0()
   at React.JavaScriptEngineFactory.GetFactory(IEnumerable`1 availableFactories, Boolean allowMsie)
[JSPool 37] Starting thread
[JSPool 37] Received call
[JSPool 37] Call completed
[JSPool 37] Received call
[JSPool 37] Call completed
[JSPool 37] Received call
[JSPool 37] Call completed
[JSPool 37] Received call
[JSPool 37] Call completed

Note - this is in debug mode with optimisations off.

Any ideas how to avoid this exception?

**Comment by Daniel15** [comment]
> but on loading the page the request to the jsx file is returning 404 

What's the URL it's trying to hit? If optimisations are off then it'll be hitting the .jsx file directly, in which case you need to ensure you have the JSX handler correctly configured in Web.config.

**Comment by ssippe** [comment]
Yes it's the .jsx file. I tried adding .jsx as a application/JavaScript mime type in web.config but that didn't help.
Is there something else required to setup the handler?
On 20 Aug 2015 5:14 pm, Daniel Lo Nigro <notifications@github.com> wrote:
but on loading the page the request to the jsx file is returning 404 


What's the URL it's trying to hit? If optimisations are off then it'll be hitting the .jsx file directly, in which case you need to ensure you have the JSX handler correctly configured in Web.config.

**Comment by ssippe** [comment]
Followup...

Still getting a 404 when EnableOptimizations=false for direct links to .jsx files (without original JavaScriptEngineSwitcher exception)

To repoduce:
* Created a fresh asp.net mvc 5 application 
* Install from nuget  ReactJS.NET (MVC 4 and 4) and ReactoJS.NET - JSX for ASP.NET Web Optimisation Framework 
* modify bundle config to include bundles.Add(new JsxBundle("~/bundles/StandardExtraItem").Include("~/Views/Home/extraItems.jsx"));
* add the following to Views\Home\Index.cshtml @section scripts { @Scripts.Render("~/bundles/StandardExtraItem")    }
* create the file Views\Home\extraItems.jsx and put some jsx code in it. Set the "Build Action" on the file to Content
* Run in debug mode and note the 404 getting extraItems.jsx. 
* Modify Global.asax.cs to include the line BundleTable.EnableOptimizations = true; in Application_Start and run again and note the the bundled version of the jsx file is returned successfully.

Note that the nuget packages modify web.config to install a handler for .jsx file and not manual changes to web.config was made.

**Comment by Daniel15** [comment]
Interesting... What operating system and version of IIS are you using?

It's strange that it's throwing a 404 even though you have the correct section in the Web.config file. I'll try to replicate this issue myself later this week when I get some free time :)

**Comment by ssippe** [comment]
Windows 7 and iis express debugging from visual studio 2013.
On 24 Aug 2015 3:47 pm, Daniel Lo Nigro <notifications@github.com> wrote:Interesting... What operating system and version of IIS are you using?

It's strange that it's throwing a 404 even though you have the correct section in the Web.config file. I'll try to replicate this issue myself later this week when I get some free time :)
