### ISSUE TITLE
Question: how to integrate with react-bootstrap

### ISSUE THREAD

**Issue by johanforssell** [reactjs/React.NET#158]
How would I do server side rendering and asp.net bundling when integrating react-bootstrap? 
I can't get the React-bootstrap code to load properly.

**Comment by Daniel15** [comment]
What issues are you encountering? Is it throwing any errors?

**Comment by johanforssell** [comment]
Please close this issue, it's no longer relevant. 

- Johan Forssell




On Mon, Aug 31, 2015 at 4:22 PM -0700, "Daniel Lo Nigro" <notifications@github.com> wrote:












What issues are you encountering? Is it throwing any errors?
