### ISSUE TITLE
add script content in `ReactSiteConfiguration.Configuration`

### ISSUE THREAD

**Issue by ra0o0f** [reactjs/React.NET#159]
hi

can raw javascript be added to the configuration like adding script files

``` csharp
new ReactSiteConfiguration()
.AddScript("script.js")
// add raw javascript
.AddRawScript("var data = {};");
```

if there is no such method, i can submit a PR, let met know where should i do that

i found that script files are added in a `JSPool`

``` csharp
var allFiles = _config.Scripts
                .Concat(_config.ScriptsWithoutTransform)
                .Select(_fileSystem.MapPath);

            var poolConfig = new JsPoolConfig
            {
                EngineFactory = _factory,
                Initializer = InitialiseEngine,
                WatchPath = _fileSystem.MapPath("~/"),
                WatchFiles = allFiles
            };
```

but i think there is a way to add other resources like react itself

thanks for bring react to the .NET

**Comment by Daniel15** [comment]
What's your use case? Could you just create a JavaScript file containing your code, or do you want something that's dynamically generated?

**Comment by ra0o0f** [comment]
@Daniel15 

i started to use flux architecture and i realize i should manage state(mostly data from server) in `stores` not `components`.
at server side rendering i do this by passing data to `component` and from there to `store`.

is there a way to execute script before each server side rendering, so i can embed data by dynamic script for `store`?

i know now that i was asking the wrong question, config scripts are for client lifetime not before each server side rendering
```csharp
new ReactSiteConfiguration()
.AddScript("script.js")
```

**Comment by dustinsoftware** [comment]
Yes, this is possible now by implementing `IRenderFunctions`

See how we're implementing CSS-in-JS support as an example: https://github.com/reactjs/React.NET/blob/master/src/React.Core/RenderFunctions/StyledComponentsFunctions.cs
