### ISSUE TITLE
React.NET with self hosting and PerRequestSingletons

### ISSUE THREAD

**Issue by shaunol** [reactjs/React.NET#16]
Hi there, first of all thanks for the great library. It's useful to have familiar tooling when learning new things.

I'm running React.NET inside a Microsoft.Owin self hosted environment. I've picked out the parts I needed from existing sources and seemed to get an environment up and running reasonably painlessly, including using RazorEngine and server-side rendering.

My only issue is how can I inject the current request context into the IoC container correctly? In the React.Web example you've created a HttpContextLifetimeProvider which is speaking directly to the Asp.Net static HttpContext property. In Owin we have no such thing and instead must pass our context from inside the request pipeline.

Because the current strategy of creating PerRequest object instances relies on creating the instance creation Func on application startup, you never get an opportunity to create an instance of the LifeTimeProvider with a specific context. It seems quite engrained in the IoC implementation too not to be able to handle this.

Are there any plans to handle this and do you have any suggestions for what I can do in the meantime?

Cheers

Edit: Example of a potential Owin LifetimeProvider based on the original HttpContextLifeTimeProvider with context injected constructor: https://gist.github.com/shaunol/11238848

**Comment by Daniel15** [comment]
Fixed with #69
