### ISSUE TITLE
Errors doing fresh build for ASP.Net 5

### ISSUE THREAD

**Issue by sirsquidness** [reactjs/React.NET#160]
Heyo, 

Two issues while building ReactJS.Net for the first time, using commit 5196c1cfa4ca4ecaa66f8c1e090f0f97746a49a3 (latest on master)

First issue seems to be an incompatiblity with the latest version of git. Using `git version 2.5.0.windows.1`, build.cmd results in the following error:

```
C:\tools\React.NET>dev-build.bat
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 21/09/2015 15:41:15.
Project "C:\tools\React.NET\build.proj" on node 1 (default targets).
RestorePackages:
  tools\NuGet\nuget.exe restore src\React.VS2015.sln
  All packages listed in packages.config are already installed.
  All packages listed in packages.config are already installed.
C:\tools\React.NET\build.proj(50,3): error MSB6001: Invalid command line switch
 for "git.exe". Illegal characters in path.
Done Building Project "C:\tools\React.NET\build.proj" (default targets) -- FAIL
ED.


Build FAILED.

"C:\tools\React.NET\build.proj" (default target) (1) ->
(UpdateVersion target) ->
  C:\tools\React.NET\build.proj(50,3): error MSB6001: Invalid command line swit
ch for "git.exe". Illegal characters in path.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.35
Press any key to continue . . .
```

Once I changed my %PATH% to point to my installation of `git version 1.9.4.msysgit.0` instead, the build worked fine. 

The second issue is that `dnu restore` needs to be called from within the `/src` directory before attempting to build the React.VS2015 solution, otherwise the build fails with a few giant walls of red text because of missing dependencies - I suggest that this should be done from the build script.

**Comment by Daniel15** [comment]
Thanks for the bug report :) 

I recently fixed similar issues in one of my other projects, RouteJs (https://github.com/Daniel15/RouteJs/blob/master/build.proj#L66-L70). I need to do the same for ReactJS.NET too. Perhaps I should generalise this stuff into shared MSBuild scripts.

Not quite sure what's happening with that Git issue though. I'll need to see which version of Git my Windows box is using.

**Comment by Daniel15** [comment]
Fixed, confirmed via the AppVeyor build (which spins up a new environment for every build): https://ci.appveyor.com/project/Daniel15/react-net/build/3
