### ISSUE TITLE
Dependency on git.exe

### ISSUE THREAD

**Issue by samwa** [reactjs/React.NET#163]
I think dev-build.bat has a dependency on git.exe which I don't have installed
I get an error when running that batch file

"C:\Projects\React.NET-master\React.NET-master\b
uild.proj" (default target) (1) ->
(UpdateVersion target) ->
  C:\Projects\React.NET-master\React.NET-master\
build.proj(50,3): error MSB4018: The "GitVersion" task failed unexpectedly.\r
C:\Projects\React.NET-master\React.NET-master\bu
ild.proj(50,3): error MSB4018: System.Exception: Could not find git.exe.  Looke
d in PATH locations and various common folders inside Program Files.\r

I'm installing Git now, but though you might like to add this to your readme

**Comment by samwa** [comment]
Even with git installed and in my path, the build still errors because I don't have a local git repo to get the version number from. I ended up just removing the GitVersion msbuild task from the build.proj file

**Comment by Daniel15** [comment]
Yes, the build uses Git as the assembly version contains the Git commit hash of the code used to build the library. The build makes some assumptions about the environment, and that's one of them. I'll add it to the readme. Perhaps I should modify `build.proj` to skip that step if Git is not installed.

**Comment by Daniel15** [comment]
Added a note to the readme (https://github.com/reactjs/React.NET/commit/438c8970e28cdd1a17352a4a65841aacb74f3982).

**Comment by johnson4yrvirgingirl** [comment]
Yes I am ready how to meet
