### ISSUE TITLE
asp.net beta 8 support?

### ISSUE THREAD

**Issue by code4aman** [reactjs/React.NET#171]
Just updated to beta 8 and react [tutorial](http://reactjs.net/getting-started/aspnet5.html) sample won't start. Problem in:
```cs
app.UseReact(config =>
{
//actually, nothing but bunch of comments
}
```
And loader exception says:
```cs
{"Method not found: 'Microsoft.Framework.Caching.IExpirationTrigger Microsoft.AspNet.FileProviders.IFileProvider.Watch(System.String)'."}
```
Must be some beta 8 namespaces update, or something. I.e. I found `Microsoft.Framework -> Microsoft.Extensions` rename in aspnet repo

**Comment by Daniel15** [comment]
Yeah, beta 8 only came out earlier this week, and I haven't gotten around to upgrading to it yet. I'll try to do that tomorrow. :)

**Comment by code4aman** [comment]
Trying to build via `dev-build.bat`. How to specify which `dnx` to use?
Cause I have installed `beta7` and `beta8`, so my `dnu` uses `beta8` by default. Therefore can't generate `SharedAssemblyVersionInfo.cs` file

**Comment by Daniel15** [comment]
Try run `dnvm use beta7

**Comment by Daniel15** [comment]
Try run `dnvm use beta7` before running `dev-build.bat`

**Comment by Daniel15** [comment]
I submitted a diff to upgrade to beta 8, however I'm encountering build errors. I posted to https://github.com/aspnet/Home/issues/999 to get help from the ASP.NET team.

**Comment by Daniel15** [comment]
Found a fix and merged the changes to master :+1:
