### ISSUE TITLE
Is there a function I can call to input a JFX and output a min javascript?

### ISSUE THREAD

**Issue by PrimeObjects** [reactjs/React.NET#177]
For example 

string c = "var React = require('react');" + 
"var ReactDOM = require('react-dom');" + 
"ReactDOM.render(" + 
"&lt;h1&gt;Hello, world!&lt;/h1&gt;," + 
"document.getElementById('example')" + 
");";

string resultjs = AFUNCTION(c);

**Comment by Daniel15** [comment]
Do you mean you have some code containing some JSX in a C# string, and want to compile it? You can do something like this:

```
var environment = React.AssemblyRegistration.Container.Resolve<IReactEnvironment>();
string result = environment.Babel.Transform(input);
```

You could instead use the `TransformWithSourceMap` method to get a source map too.

**Comment by PrimeObjects** [comment]
Tried your script in a controller. I got the error below. I'm on .NET 5 beta7

System.InvalidOperationException
No service for type 'React.IReactEnvironment' has been registered.

**Comment by Daniel15** [comment]
> I also try to addService by using React.AspNet, it seems conflict with some other code and caused compile error.

What was the error? You need to have the ReactJS.NET services registered in Startup.cs in order to use it.

**Comment by PrimeObjects** [comment]
sorry for reply, it works!
