### ISSUE TITLE
Server-side rendering without ASP.NET MVC

### ISSUE THREAD

**Issue by HeavenMaster** [reactjs/React.NET#178]
Is it possible using React.NET?

**Comment by Daniel15** [comment]
Sure! See [HtmlHelperExtensions.cs](https://github.com/reactjs/React.NET/blob/master/src/React.AspNet/HtmlHelperExtensions.cs#L82) to see how it's hooked up in ASP.NET MVC. You could just call the same methods some other way. In 0dbd639efeb1387b1b82850667953e8fd7e441e7 I added an example showing how to render a React component from within a console application. There's a bit more code than I'd like, but it does work.

Basically, this is the code you need for server-side rendering:

```
var environment = React.AssemblyRegistration.Container.Resolve<IReactEnvironment>();
var component = environment.CreateComponent("HelloWorld", new { name = "Daniel" });
var html = component.RenderHtml();
```

You can then use `environment.GetInitJavaScript()` to get the JavaScript required to initialise all the instantiated components client-side. `IReactEnvironment` should be a per-request singleton (that is, every request creates a new one, but that same instance is shared throughout the entire request).

Hope that helps :)

**Comment by HeavenMaster** [comment]
Many thanx for the detailed answer, Daniel! 
I haven't tried yet, but it looks pretty helpful.
