### ISSUE TITLE
Array.find() in constructor/render is undefined

### ISSUE THREAD

**Issue by manuelfsixtour** [reactjs/React.NET#183]
Trying to call `Array.find()` in **constructor** or **render** methods of a React component throws an exception:

```
Error while rendering "MyComponent" to "react1": TypeError: undefined is not a function
   at render (Script Document [6]:31:30) ->       var value = [{id:1, value:'value'}].find(function (v) {
```

Code example:

```
class MyComponent extends React.Component{
  render(){
    var val = [{id : 1, value : 'VALUE'}].find(x => x.id === 1).value;
    return(
      <div>{val}</div>
    );
  }
}
```

Oh the other hand, trying to call the same function on another "non-React" method works well.

Thanks.

**Comment by TomasHubelbauer** [comment]
Is the array really hardcoded or is it something like `this.props.myArray` or `this.state.myArray` which could be not present at the first render, then asyncly loaded and present on the second render? Log the array to the console to make sure it is valid at the time of rendering.

**Comment by manuelfsixtour** [comment]
The array is not really hardcoded, but the example above does not work. 
So, it wouldn't work also with something like `this.props.myArray` or `this.state.myArray`.

**Comment by TomasHubelbauer** [comment]
Ok then if you log the array, the result of `find` and the result of `value`, at what point in this chain is `undefined` introduced?

**Comment by manuelfsixtour** [comment]
It is a rendering exception, I am not able to log anything.

I'm using the `Html.React` helper like this:
```
@Html.React("MyComponent", new { model = Model })
```

With the following (and only the following) code:

```
class MyComponent extends React.Component{
  render(){
    var val = [{id : 1, value : 'VALUE'}].find(x => x.id === 1).value;
    console.log(val); // -> never called
    return(
      <div>{val}</div>
    );
  }
}
```

I get this exception (without any console log):

![image](https://cloud.githubusercontent.com/assets/2269491/10934917/fc88e61a-82e2-11e5-98a5-c515163828c1.png)

**Comment by Daniel15** [comment]
Interesting, it sounds like `Array.prototype.find` is missing. I'm pretty sure V8 has native support for `find` though...

Try `console.log(Array.prototype.find ? 'Exists' : 'Does not exist')` and see what you get? If it's missing for some reason, you can polyfill it (stick the code at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfil somewhere)

**Comment by manuelfsixtour** [comment]
Thanks. It seems that it does exist and does not exist at the same time! :)

![image](https://cloud.githubusercontent.com/assets/2269491/11030816/c081b1f0-86d0-11e5-8c5c-20c16e5edad3.png)

I suppose that the **V8** dll in the solution is not fully compliant with the actual V8 engine.

**Comment by Daniel15** [comment]
Hmm, maybe the version of V8 used by ClearScript isn't new enough to contain `Array.prototype.find` :( You could polyfill it - For example, see the polyfill at the bottom of the page at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find, or this one on npm: https://www.npmjs.com/package/array.prototype.find

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
