### ISSUE TITLE
Server-side i18n

### ISSUE THREAD

**Issue by deevus** [reactjs/React.NET#185]
Any suggestions on how to do this? Is there a suggested framework for integrating i18n? If I was using Razor it would be something like `R.SomeResource`. 

Currently I'm passing the required resources to `@Html.React` as props, but this is not ideal as it looks messy.

**Comment by Daniel15** [comment]
Sorry, I'm not too sure, I don't have much experience with i18n in JavaScript. This seems like a broader question though, rather than something specific to ReactJS.NET. Perhaps ask on StackOverflow? :)

**Comment by joshburgess** [comment]
@deevus Consider checking these out: 

https://github.com/yahoo/react-intl
https://github.com/mashpie/i18n-node
https://github.com/jeresig/i18n-node-2

**Comment by huan086** [comment]
I'm using https://github.com/jquery/globalize. 

# Preparation

2 gulp tasks is required to generate the files for React.NET to consume

1. Pass the runtime modules through browserify
2. For each locale, pass the formatters, parsers etc through globalize-compiler

The generated files from the gulp tasks are included in both React config and layout.cshtml.

# Usage

Within the jsx files, use the Globalize.formatMessage to localize strings

# Setting language

In layout.cshtml, set the language by adding a script tag and calling Globalize.locale("the locale")

Create a custom HtmlHelperExtension that runs Globalize.locale("the locale") on the current ReactEnvironment before calling Html.React

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
