### ISSUE TITLE
ReactDOM is not defined server side by default

### ISSUE THREAD

**Issue by SoonDead** [reactjs/React.NET#186]
I'm using React.NET with Webpack.

The internals of my `ReactConfig`:

    ReactSiteConfiguration.Configuration.SetLoadBabel(false)
        .AddScriptWithoutTransform("~/Scripts/build/server.bundle.js");

The server bundle does not contain React. Therefore I put this in my `webpack.config.js`:

    externals: {
        react: 'React',
        "react-dom": 'ReactDOM',
    }

ReactDOM is undefined on the serverside.

The workaround will get me fired :(

    externals: {
        react: 'React',
        "react-dom": 'React.__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED',
    }

**Comment by PeteDuncanson** [comment]
I went through all this too for several days with Browserify, in the end I just included React in my bundle (via Webpack which is far easier to use and reason about than Browserify). I understand this might not be ideal (which is why I worked on it for days) but in the end it solved a lot of my issues. Is that something you can do?

**Comment by SoonDead** [comment]
I might be able to pack react-dom into my bundle, only React needs to be in he global scope. I will try that on monday.

The woraround I mention works fine too, it is just ugly.

**Comment by Daniel15** [comment]
How are you loading React? If you're loading it from a CDN, you just need to load ReactDOM in addition to React:

```
<script src="https://fb.me/react-0.14.2.js"></script>
<script src="https://fb.me/react-dom-0.14.2.js"></script>
```

**Comment by SoonDead** [comment]
On the client side I'm referencing react.js and react-dom.js locally.

On the server side I'm using whatever ReactJS.NET uses by default.

My issue is only a server-side one. I'll explain it in more detail on monday.

**Comment by Daniel15** [comment]
ReactDOM shouldn't be used server-side, it's only for client-side stuff. Perhaps something is unintentionally using it server-side. Are you able to provide a stack trace of the error you're encountering?

**Comment by SoonDead** [comment]
It is used by the modal component of react-bootstrap. There is a `var ReactDOM = require('react-dom')` at the start of a file and although the server does not actually call anything on it the require fails.

**Comment by Daniel15** [comment]
To be honest I think your workaround is fine for now, even with the scary `SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` :laughing: 

I'll probably end up doing something like this in `shims.js`:
```
var ReactDOM = React.__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;
```

At which point you could do `'react-dom': 'ReactDOM'`in your Webpack `externals`

**Comment by shadowii** [comment]
@PeteDuncanson How were you able to avoid an invariant violation/"multiple copies of React error" doing it that way (since you'll need to import React/ReactDOM again to get the client-side working)?

**Comment by markau** [comment]
Can anyone enlighten me on what is dodgy about using Webpack `externals`?  I don't know much about Webpack (other than whether it works to produce my bundles or not!).
