### ISSUE TITLE
How to provide my own version of React

### ISSUE THREAD

**Issue by NaorShlomi** [reactjs/React.NET#187]
I read the documentation of Facebook about the option to load the React production version without the error/warnings messages.

When i try load my own version of React (production) i get the following error:
 > TypeError: Cannot read property 'createClass' of undefined

I have gulp task that concatenate the React files with my other files.

This is my ReactConfig.cs:
```
ReactSiteConfiguration.Configuration = new ReactSiteConfiguration()
                .SetAllowMsieEngine(false)
                .SetLoadBabel(false)
                .SetLoadReact(false)
		.AddScriptWithoutTransform("~/dist/scripts/react-server.js");
```

**Comment by Daniel15** [comment]
Make sure your `react-server.js` exposes React globally - This is also required for the React dev tools to work. 

How are you building `react-server.js`? If you're using Webpack, you should use [expose-loader](https://github.com/webpack/expose-loader) to expose React.

**Comment by NaorShlomi** [comment]
Thanks..it's works :)

**Comment by Daniel15** [comment]
:+1:
