### ISSUE TITLE
In production! Object doesn't support this property or method

### ISSUE THREAD

**Issue by cloudybrain** [reactjs/React.NET#188]
I have deployed this project with reactjs.net on 4 different environments (works on my machine, works on a dev cloud machine - aws), works in a dev box environment, and works in a dev remote dev box environment, but when we deployed to the machine that really matters - in production we're getting a very weird error.

We updated to the latest ReactJS.NET using Babel bundling v 2.0.1

And we're getting a yellow page of death:

    Object doesn't support this property or method

    Exception Details: MsieJavaScriptEngine.JsRuntimeException: Object doesn't support this property or method

Going down the page I see more hints:

    ...
    [TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory]
    ...
    [TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment]
    ...

I can't replicate this error on any of my dev boxes, and I'm not entirely sure what setting in IIS I have to enable to get this to work.

**Comment by PeteDuncanson** [comment]
I suspect the TinyIoC errors are a symptom not the cause.

Have you tried running it with the V8 engine instead? The MS one can be flakey (we had similar issues with it but much early on in our dev cycle). The fact it works on 3 other enviros means there has to be a difference between those and the 4th one. Could be its got a different version IE on the production server for instance? Tricky one to track down hence switching to V8 might be a quicker option.

**Comment by Daniel15** [comment]
What differs between your production box and your dev cloud machine? Is it a different operating system?

**Comment by cloudybrain** [comment]
I'll try switching to V8. As far as the difference, I'm really not sure. The network admin says that the only difference is production is external facing, and the dev box is not. Same OS,  same .NET framework version, same IIS version.

**Comment by Daniel15** [comment]
Hmm, really strange that the behaviour would differ between the two then...

Do you have a full stack trace of the error?

**Comment by cloudybrain** [comment]
Btw, @peteducanson,  does having a different IE version installed play a factor in displaying the yellow screen of death? I wouldn't think that'd be a difference..

**Comment by Daniel15** [comment]
Different IE version has an effect on the behaviour of `MsieJavaScriptEngine` :)

**Comment by Daniel15** [comment]
Different IE version has an effect on the behaviour of `MsieJavaScriptEngine` - For example you could have code that only works in newer IE versions :)

**Comment by cloudybrain** [comment]
Hmm, well we did check other browsers like chrome and android, same difference. For stacktrace, when I get into work tomorrow, I'll see what if there is any more details I can give you.

**Comment by Daniel15** [comment]
The `MsieJavaScriptEngine` is actually what executes the JavaScript code server-side; the client-side environment doesn't affect that. Normally V8 is used server-side, but the MSIE engine is used as a fallback.

As a test, I'd suggest doing `.SetAllowMsieEngine(false)` in your `ReactConfig.cs`, and then test that out on both your dev machine and prod machine. Most likely V8 is failing to initialise in prod for some reason, so it's falling back to the MSIE engine. Disallowing usage of the MSIE engine will show you the actual V8 error.

**Comment by cloudybrain** [comment]
Alright thanks,  I'll show you what I'll come up with within the next two days (maybe tomorrow). Thanks for your time and patience in this.

**Comment by Daniel15** [comment]
Closing this out since I haven't heard back, but please feel free to reopen this issue if you're still encountering problems. Thanks!
