### ISSUE TITLE
React.Exceptions.ReactScriptLoadException shuts down debugging and IIS Express

### ISSUE THREAD

**Issue by SoonDead** [reactjs/React.NET#189]
Nowadays whenever I have a ReactScriptLoadException my debugging session shuts down.

I feed a webpack bundle to reactjs.net and whenever it changes (there is a separate webpack -w console that recompiles it) reactjs.net tries to reexecute it, throws an exception and that shuts down my iis express.

So basically everytime I hit ctrl+s on a jsx halfway through writing a function (where some variables are not declared yet for example) the debugging session shuts down. Since the project is large and needs around 30 seconds to start up, this is very annoying.

I'm asking for help on why this is happening and how to turn it off.

**Comment by Daniel15** [comment]
Wow, that's terrible :/

Try calling `.SetReuseJavaScriptEngines(false)` in your `ReactConfig.cs` and see if that helps.  It will make page loads a bit slower, but it should be more reliable in this case.

**Comment by SoonDead** [comment]
Yes it actually helps, thanks.

Also to try to nail down the exact issue:

Debugging only shuts down if the exception happens outside of a request (if it happens during (or more precisely as a result of) a request the error page is properly shown).

It is happening for both syntax errors and execution errors.

**Comment by Daniel15** [comment]
I have a feeling this is happening because the exception is happening on a background thread. ReactJS.NET watches all files you load, and recycles the JavaScript engines if any of those files change. If any errors are encountered while loading the JS file, an exception is thrown. This approach is fine for initial load (as it's fine to throw exceptions on the request thread), but not for background stuff. I'll look into a better approach here.

**Comment by Daniel15** [comment]
this should only be an issue with how scripts are loaded when you use `AddScriptWithoutTransform`. If you instead use `AddScript`, the error is handled correctly (as those scripts are loaded as part of the request, if they haven't already been loaded).

**Comment by SoonDead** [comment]
Yes, I'm using `AddScriptWithoutTransform` because I already transform my scripts with webpack.

**Comment by Daniel15** [comment]
@SoonDead  - Can you please try out the latest dev build and see if it's any better? You can add `https://ci.appveyor.com/nuget/reactjs.net` as a NuGet package source to get the dev packages. Use version `2.0.2-dev-20151116-0644

**Comment by Daniel15** [comment]
@SoonDead  - Can you please try out the latest dev build and see if it's any better? You can add `https://ci.appveyor.com/nuget/reactjs.net` as a NuGet package source to get the dev packages. Use version `2.0.2-dev-20151116-0644` or higher.

**Comment by SoonDead** [comment]
I'll try it when I get to work (in about 1-2 hours).

**Comment by SoonDead** [comment]
It seems to be working OK (it's not throwing exceptions when on a background thread).

I have no idea if the javascript engine is properly reused or not, but the react component properly renders upon subsequent requests when the error is fixed.

**Comment by Daniel15** [comment]
Thanks for the confirmation!
