### ISSUE TITLE
ReactJS.NET has not been initialised correctly on Azure Web app

### ISSUE THREAD

**Issue by chadangerer** [reactjs/React.NET#191]
I have an existing MVC website and am starting to convert some of the UI to react components.  Locally everything is working fine.

When I deployed to azure I got the error message
`ReactJS.NET has not been initialised correctly.;StackTrace:   at React.Web.Mvc.HtmlHelperExtensions.get_Environment()
   at React.Web.Mvc.HtmlHelperExtensions.ReactInitJavaScript(HtmlHelper htmlHelper)`

I am pretty much following the sample line for line.

I am using webpack to create a server and client bundle. Both are deployed.

My ReactConfig looks like this

`ReactSiteConfiguration.Configuration.SetReuseJavaScriptEngines(false).SetLoadBabel(false)
.AddScriptWithoutTransform("~/Scripts/build/server.bundle.js");`

And this is added to my _DefaultLayout.cshtml.

`@Html.ReactInitJavaScript()` 

Are there known issues with certain versions in Azure?

**Comment by Daniel15** [comment]
Which version of ASP.NET MVC are you using? What version of .NET are you using in Azure?

**Comment by chadangerer** [comment]
MVC 5 and .NET 4.6

**Comment by chadangerer** [comment]
Interestingly enough, I originally had the React.Owin package installed and wasn't using it. I removed it via nuget redeployed and Reactjs.Net seems to be working properly on Azure now.  Any thoughts on that?

**Comment by Daniel15** [comment]
Interesting, I'm not sure why the React.Owin package would cause that.  Anyways, it sounds like it's fixed after uninstalling React.Owin, so I'm going to close this issue. I'll try to figure out why the OWIN package results in issues like this.
