### ISSUE TITLE
Shouldn't AddScriptWithoutTransform already imply no Babel?

### ISSUE THREAD

**Issue by shadowii** [reactjs/React.NET#192]
I just noticed I have to specify `ReactSiteConfiguration.Configuration
                .SetLoadBabel(false)` to the ReactConfig if I want to add a script that's already been transformed by something like webpack. 

However, even though I'm using webpack, sometimes I just want to include a jsx file directly in my html for some quick testing. But that will throw an error: `Babel has not been loaded, so JSX transformation can not be done. Please either transform your JavaScript files through an external tool (such as Babel, Webpack, Browserify or Gulp) and use the "AddScriptWithoutTransform" method to load them for server-side rendering, or enable the "LoadBabel" option in the ReactJS.NET configuration. Refer to the ReactJS.NET documentation for more details.`, because Babel hasn't been loaded due to the aforementioned configuration. Just thinking aloud, but shouldn't the two be separate? It seems to me the babel setting is global, but I really only want it to not Babelize my already transformed file (and if I do enable Babel, it will break). 

I would think the AddScriptWithoutTransform should already imply that Babel is not wanted for further transforms.

**Comment by Daniel15** [comment]
You need `LoadBabel` turned on if you ever want to hit JSX files directly. Babel will still be lazy-loaded only as needed. I could probably even remove the `LoadBabel` flag now as it's not really useful. Babel used to be loaded upfront as soon as the JavaScript engine was initialised, but I changed it fairly late during development of 2.0 to only load as-needed, when you actually try to transform a file (see 12b8d53da7ddffae78f1275a7ba9df543079214d). This means that if you only do `AddScriptWithoutTransform`, Babel will never be loaded, regardless of what the `LoadBabel` flag is set to.

**Comment by Daniel15** [comment]
Closing this out since I don't think there's anything to actually do here, as per my comment :smile:
