### ISSUE TITLE
Please add support for Babel 6.0

### ISSUE THREAD

**Issue by aeleftheriadis** [reactjs/React.NET#193]
Since the release of Babel 6 the package doesn't work with webpack example.

I receive the following error on my browser 

Error while rendering "Components.HelloWorld" to "react1": Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
   at invariant (Script Document [2]:20215:15) ->     throw error;
   at instantiateReactComponent (Script Document [2]:18233:127)
   at Script Document [2]:13840:31
   at Mixin.perform (Script Document [2]:17235:20)
   at renderToString (Script Document [2]:13839:24)
   at newFn (Script Document [2]:17611:17)
   at Script Document [8] [temp]:1:7
Line: 20215
Column:15

My component name is apparently HelloWorld.
I have added inside .babelrc the following
{
  "presets": ["es2015", "react"]
}

Among others I have included the following packages 
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "babel-core": "^6.1.20",
    "babel-loader": "^6.1.0"

My workaround is to work with latest babel 5.0 version where everything work fine

**Comment by Daniel15** [comment]
I started working on this, but I'm currently blocked by https://phabricator.babeljs.io/T6643

**Comment by drobinson-inter-est** [comment]
Should this not be considered a bug? Also, are we likely to see a fix for it anytime soon? My entire rationale for using the React.NET integration was to give me server-side rendering within the .NET stack.

**Comment by jslatts** [comment]
As @aeleftheriadis mentioned, it works fine with Babel 5. You can also just avoid doing any JSX compiling in React.NET and use any external tools (Browserify, webpack, babel, etc) to do your JS compile stage and then use AddScriptWithoutTransform to bypass React.NET's transformation step.

You will probably end up wanting to do your own compile anyway so you have the control over your build as your project progresses (minification, sourcemaps, etc).

**Comment by Daniel15** [comment]
> Should this not be considered a bug? 

It's not a bug, because Babel 5 works fine. There's a bunch of changes in Babel 6 that I need to adapt ReactJS.NET to handle. Babel no longer has a "browser" build so I need to build my own build of Babel. Many of the Babel integrations are still using Babel 5, as is the ["try now" page on their site](http://babeljs.io/repl).

> Also, are we likely to see a fix for it anytime soon?

Depends on how quickly I can determine how to get Babel 6 working. I'm the only developer on ReactJS.NET. I do appreciate pull requests though, in case anyone implements it before I get to it :smile: 

In the meantime, you can just use Babel 5, which works fine.

**Comment by drobinson-inter-est** [comment]
I'm already pointing at compiled JS, @jslatts. 

@Daniel15 Thanks for the prompt response - I'm going to shelve .NET server-side processing for now and wait for the update, as I'm just building boilerplate at the moment and it isn't currently a priority: I also don't want to have to make the webpack.config.js file I've been working on work for React, es2015, postcss, tape.js etc on Babel 5 if I can help it.

I'll revisit this, and resolve it, in a few weeks time.

**Comment by Daniel15** [comment]
I just committed d0b14d32daa77261be7e08f64203c30c674465ba, which upgrades to Babel 6. It should be available on the [development NuGet server](http://reactjs.net/getting-started/download.html#development-builds) soon as version 2.2.0-dev.

@drobinson-inter-est - Note that if you're already precompiling your JavaScript, your issues probably aren't related to the version of Babel bundled by ReactJS.NET (as Babel is not even loaded at runtime if you don't compile your JS using ReactJS.NET). It might be a different issue :)
