### ISSUE TITLE
No recompile of JSX file when debugging

### ISSUE THREAD

**Issue by ovatsug25** [reactjs/React.NET#194]
ReactJS.NET is not recompiling when debugging.

It compiles once, and then it remains static.

Strangely, when I make an error in my and my app is already built, I can fix the JSX and it will compile without having to rebuild my app but it will only do that once.

Where should I be looking to fix it?

My Web.config has

    <system.web>
        <httpHandlers>
          <add verb="GET" path="*.jsx" type="React.Web.JsxHandlerFactory, React.Web" />
    </stem.web
    <system.webServer>
          <remove name="Babel" />
          <add name="Babel" verb="GET" path="*.jsx" type="React.Web.BabelHandlerFactory, React.Web" preCondition="integratedMode" />
        </handlers>
    </system.webServer>

and I've call the JSX in my view with all three methods

    <script src="..."></scripts>
    @Scripts.Render("...")
    @Url.Content("...")

What should I be doing to fix this?

Running on VMWare. Help me give you more info on this!

**Comment by Daniel15** [comment]
Are you doing server-side rendering at all (ie. `Html.React` calls in your views)? 
If you hit the .jsx file in your browser directly, do you see the changes? What if you press Ctrl+F5 (ie. bypass the cache)?

**Comment by Daniel15** [comment]
I didn't hear back so I'm going to close this out, but please feel free to reopen if you're still encountering this issue. Thanks!
