### ISSUE TITLE
Incorrect line number when debugging in browser

### ISSUE THREAD

**Issue by virtualsurfer** [reactjs/React.NET#196]
Hi, we found an issue when debugging javascript inside jsx, with chrome, firefox or IE.
Dev tools seems to be showing different execution line numbers, and doesn't match with expected line numbers.

Next image shows that first breakpoint hit after call "_onSubmitClick" is an empty line. 

![image](https://cloud.githubusercontent.com/assets/13456485/11182667/2b69372a-8c4b-11e5-9be8-05a5f8b9d271.png)

This behavior changes between jsx files and browsers.
We are using VS2013 ASP.NET MVC 4 with reactjs.net nuget package.

By the way, Great job! 
We are evaluating product in order to use it in production environment.

Thanks in advance

**Comment by Daniel15** [comment]
Interesting, sounds like the source map is incorrect. For now you can disable source maps in the Chrome dev tools settings - The code won't be as pretty (as it'll show you the code after transformation rather than your original code) but should still be sufficient for debugging.

**Comment by virtualsurfer** [comment]
Disabling source maps works just fine.
Thanks

**Comment by Daniel15** [comment]
This should be fixed in version 2.1.2, let me know if you still experience any issues!
