### ISSUE TITLE
adding in TransformBabel proj then compiling issue

### ISSUE THREAD

**Issue by bstaks** [reactjs/React.NET#200]
Hi 
 I am getting prob then add i am not compile our project always getting error this

Severity	Code	Description	Project	File	Line
Error		The command ""C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe" TransformBabel.proj /nr:false /p:Configuration=Debug" exited with code 1.	React.Sample.Mvc4	C:\Anguler\React.NET-master\src\React.Sample.Mvc4\React.Sample.Mvc4.csproj	232

I am adding also React.MsBuild.dll through nuget manager please tell me, what's problem?

**Comment by Daniel15** [comment]
What output do you get when you run that same command yourself?

**Comment by Daniel15** [comment]
Closing this out since I haven't heard back, but please feel free to reopen this issue if you're still encountering problems.
