### ISSUE TITLE
JSX source maps not loading for MVC5.2.3+ReactJS.Net2.1..0

### ISSUE THREAD

**Issue by joaker** [reactjs/React.NET#201]
I have an MVC.Net application that recently upgraded from MVC4 and ReactJS.Net 1.5 to MVC 5.2.3 and React 2.1.0.  The source maps, which previously loaded fine with version 1.5, no longer load at all.

When using ReactJS.Net 1.5, if I requested a JSX content file I would see the original source.  Now if I make the same request using 2.1.0, I see the javascript which has been compiled from the JSX by Babel.

I'm using Visual Studio 2013 and I recently installed Update 5.  I'm using Chrome for debugging, and source maps are enabled.

I created a blank project and ran through the tutorial, to see if source maps for JSX were available there.  They were not.  I rolled that project back to ReactJS.Net 1.5, and source maps worked fine again (I was still using MVC 5.2.3).  For the time being I am going to roll back to the previous project.

I don't know if it's worth mentioning, but I use a lot of ES6 array functions in my JSX code, but every one is polyfilled.

By the way, thanks for this package.  On the level it definitely expedites MVC.Net and React integration.

**Comment by Daniel15** [comment]
Hey @joaker, as I mentioned via email, try look at the request to the `.jsx` file in your browser's dev tools and see if the response contains an `X-SourceMap` header. If it does, try hitting that URL and see if the source map file is being returned correctly.

**Comment by joaker** [comment]
Hey @Daniel15 , 

It looks like this problem is limited to Chrome.  Firefox loads the source map just fine.  There is a screenshot of Firefox with the source correctly mapped, and a second of from Chrome with the generated JS file without the source.

The screenshots came from a new MVC5 project I just created with VS2015 and ReactJS.Net 2.1.2.

![reactjsnetsourcemap_chrome](https://cloud.githubusercontent.com/assets/626162/11703056/e77a6ffe-9ea9-11e5-93ed-73c2abe2fbd3.png)
![reactjsnetsourcemap_firefox](https://cloud.githubusercontent.com/assets/626162/11703057/e77bb42c-9ea9-11e5-920d-55b55db3498a.png)

A909A9300432621CC0D4

I took a look at teh X-SourceMap header on the request in Chrome.  It looked like this:
X-SourceMap:/Scripts/jsx/Page.jsx?map=1C06B553AB98F1960147


I went to that URL and found a JSON object which had a "sourceContents" property that contained a string with the original source file's text.

**Comment by Daniel15** [comment]
@joaker - Okay, in that case it sounds like the source map file is being built correctly :smile:. Could you please check that source maps are definitely enabled in Chrome?

1. Click the "three vertical dots" button next to the x at the top right
2. Click "Settings" 
3. On the "General" tab, make sure "Enable JavaScript source maps" is ticked.

**Comment by joaker** [comment]
Yes, source maps are definitely enabled in Chrome.  

![chromesourcemapsettings](https://cloud.githubusercontent.com/assets/626162/11706308/65775ba4-9ec5-11e5-9974-e1b701f4ca4a.png)

Below is the source X-SourceMap JSON object:
{"version":3,"file":"/Scripts/jsx/Page.jsx","sourceRoot":null,"sources":["/Scripts/jsx/Page.jsx"],"sourcesContent":["var Page = React.createClass({\r\n    render: function () {\r\n        return <strong className={'text-muted'}>React application {(new Date()).toISOString()}</strong>;\r\n    }\r\n});\r\n\r\nReactDOM.render(\r\n  <Page />,\r\n  document.getElementById('content')\r\n);"],"names":[],"mappings":";;;;;AAAA,IAAI,IAAI,GAAG,KAAK,CAAC,WAAW,CAAC;;;AACzB,UAAM,EAAE,kBAAY;AAChB,eAAO;;cAAQ,SAAS,EAAE,YAAY,AAAC;;YAAoB,AAAC,IAAI,IAAI,EAAE,CAAE,WAAW,EAAE;SAAU,CAAC;KACnG;CACJ,CAAC,CAAC;;AAEH,QAAQ,CAAC,MAAM,CACb,oBAAC,IAAI,OAAG,EACR,QAAQ,CAAC,cAAc,CAAC,SAAS,CAAC,CACnC,CAAC"}

**Comment by Daniel15** [comment]
Since source maps are working in Firefox, and the option is enabled in Chrome, I'd say this may be a bug in Chrome. I'm not quite sure how to debug that though! Maybe try other sites or libraries that use source maps and see if they work?

**Comment by Ackhuman** [comment]
We're having the same issue.  Source maps were working before updating the React.NET package, now we are 2.1 and they no longer work in Chrome.  If this were a bug in Chrome, it seems to me that this would happen regardless of the React.NET version.

**Comment by joaker** [comment]
Upgrading chrome to version 49.0.2623.54 beta-m (64-bit) resolved this issue for me

JSX source was always available in Firefox with from applications using ReactJS.NET, and was visible in Chrome v48 from applications using babel+webpack (and not ReactJS.NET)

**Comment by Daniel15** [comment]
Thanks, sounds like it was a Chrome bug of some sort then :/
