### ISSUE TITLE
libvroomjs fails to build on linux

### ISSUE THREAD

**Issue by sladiri** [reactjs/React.NET#202]
I followed the guide to use ReactJS on Linux, http://reactjs.net/guides/mono.html
I  checked out V8 tag/3.17.16.2 and built it.

Building libvroomjs failed, attached is the console output from the command
`g++ jscontext.cpp jsengine.cpp managedref.cpp bridge.cpp jsscript.cpp -o libVroomJsNative.so -shared -L /home/sladjan/ReactJS/v8-3.17/out/native/lib.target/ -I /home/sladjan/ReactJS/v8-3.17/include/ -fPIC -Wl,--no-as-needed -L:/usr/local/lib/libv8.so.3.17.16.2 2> err.txt`
The error:
```
jsengine.cpp:260:34: error: ‘memset’ was not declared in this scope
  memset(error, 0, sizeof(jserror));
                                  ^
```
I added `#include <cstring>` which allowed me to build `libVroomJsNative.so`.
[err.txt](https://github.com/reactjs/React.NET/files/45678/err.txt)

**Comment by Daniel15** [comment]
So you were able to compile it once you added `#include <cstring>`? If so, I can update the code and/or the instructions.

**Comment by sladiri** [comment]
Yes, I was. It compiled fine, the output file was there.

**Comment by Daniel15** [comment]
Thanks, I've added the missing `#include <cstring>` and also updated the instructions on the site to explicitly check out V8 version 3.17.16.2. Let me know if you see any other issues. Thanks!
