### ISSUE TITLE
Compiler doesn't understand arrow functions?

### ISSUE THREAD

**Issue by ss108** [reactjs/React.NET#203]
Hi, I am declaring a component in a .jsx file in the following manner:

```
class SearchBox extends React.Component {

    constructor(props){
        super(props);
    }

     onChange = (e) => {
         console.log('CHANGED');
     }


    render (){
        return <input type="text" className="form-control" placeholder={this.props.placeholder} onChange= {this.onChange} />
    }
}
```

I get the attached compiler error with this code. Is there something I am doing wrong/need to change, or is it not possible to use arrow functions in jsx files with React.NET?

Thanks!

![babel-compiler-problem](https://cloud.githubusercontent.com/assets/5439659/11548931/66e9bdba-9916-11e5-814d-55465d3de21e.png)

**Comment by Daniel15** [comment]
These are not regular arrow functions, they're [an experimental proposal for class instance fields](https://github.com/jeffmo/es-class-fields-and-static-properties) by @jeffmo. Experimental features like this are not enabled by default. You'll need to set Babel to stage 0 in your config:
```
config.BabelConfig.Stage = 0;
```

(this config syntax will be changing a bit with Babel 6, but it'll be configured similarly)
