### ISSUE TITLE
The file name is too long

### ISSUE THREAD

**Issue by mycall** [reactjs/React.NET#205]
I had to copy repository to root (e.g. C:\R) in order to compile it without Babel errors.   I was getting compile error under a C:\dev\mvc4\react.net directory, so the repository should consider this in the README or refactor with not so deep paths.

**Comment by Daniel15** [comment]
Interesting... I've got mine at `C:\Users\danlo\Documents\Visual Studio 2015\Projects\ReactJS.NET\` and I haven't had any issues with paths being too long. At which point of the build is the error thrown?

**Comment by mycall** [comment]
I can't seem to reproduce the build errors and I didn't save the errors or shell session output.  It could have been error with stale global nodejs packages.

 I'll close the issue but will report back if I see it again.
