### ISSUE TITLE
Problem with ReactCSSTransitionGroup and webpack

### ISSUE THREAD

**Issue by aeleftheriadis** [reactjs/React.NET#206]
I have added ReactCSSTransitionGroup with

import ReactCSSTransitionGroup from 'react-addons-css-transition-group';

When my component loads I get the error described on the following link

https://gist.github.com/jimfb/4faa6cbfb1ef476bd105.

**Comment by aeleftheriadis** [comment]
I was using ReactCSSTransitionGroup.
I used React.addons.CSSTransitionGroup instead and everything worked as a charm

**Comment by cnaa97** [comment]
Hi. I had same problem. but your solution also encountered.
