### ISSUE TITLE
Could not find a part of the path 'C:\React.NET\src\React.Sample.Webpack\build\server.bundle.js

### ISSUE THREAD

**Issue by mycall** [reactjs/React.NET#207]
Is there a setting I need to change to create this bundle?  I've tried this on two different systems, same result when I run the React.Sample.Webpack under iisexpress.

**Comment by Daniel15** [comment]
Did you run webpack first? You need to run webpack to build the bundle.
Perhaps I should add that to the build script.

**Comment by mycall** [comment]
doing so returned "Unknown option: base.loose" for both client.js and server.js

**Comment by Daniel15** [comment]
Ah, sounds like the build is broken for the Webpack example, and I didn't
notice since it doesn't run Webpack as part of the build. I'll fix it :)

**Comment by mycall** [comment]
grazie mille
