### ISSUE TITLE
Add support for htmlAttributes (or className) parameter.

### ISSUE THREAD

**Issue by jovnas** [reactjs/React.NET#210]
Unless there already is a way to add classes to the containing div, I would suggest adding support for the (pretty common) htmlAttributes parameter.
```
@Html.React("MyComponent", new { data = Model }, htmlTag: "div", containerId: "my-container", htmlAttributes: new { @class = "my-class-needed-on-container" })
```
I can see this could be problematic if one should try to add an id using the htmlAttributes even if containerId is provided.

An alternative solution is to add a specific parameter className that takes a string of classes to add to the container. This is probably the most "sane" way to do it, since you probably do not want to allow other attributes than class to a React-container.
```
@Html.React("MyComponent", new { data = Model }, htmlTag: "div", containerId: "my-container", className: "my-class-needed-on-container" )
```

**Comment by Daniel15** [comment]
Feel free to send a pull request adding this if you want :)

Are there any use cases that can be solved by this that can't be solved simply by adding the attributes onto the React component instead?

**Comment by jovnas** [comment]
My current problem is the use of child selectors in css. Since React.NET "adds an extra element" around the component, the child selector does not work unless I add another child level in the css. I could of course rewrite my other "components" to include the extra child level in the HTML also, but adding a class to the container seems like the easier path. (If you're lazy like me... ;-) )

I will try to submit a pull request. It's my first ever, so I hope I get it right! :-)

**Comment by Daniel15** [comment]
Added in #211, thanks @jovnas
