### ISSUE TITLE
global.Object is undefined

### ISSUE THREAD

**Issue by huan086** [reactjs/React.NET#212]
I'm using browserify to bundle my scripts. Browserify expects the global object to be called `global`, `self` or `window`.

React.NET environment defines `global` (`self` and `window` are undefined). However, `global` did not contain `Object`, `Array` and other properties. Thus, when I use `global.Object` in my scripts, I get `TypeError: Cannot read property 'prototype' of undefined. var objectProto = global.Object.prototype`.

Interestingly, these properties are on a mysterious global object, which can be retrieved via `new Function("return this")()`.

How can I configure React.NET to have this mysterious global object be merged into `global`?

**Comment by Daniel15** [comment]
Can you just use `Object` rather than `global.Object`? Is there a reason you need to access it as a property on the `global` object? Object is a standard part of the JavaScript environment, as is Array.

**Comment by huan086** [comment]
I'm bundling the lodash library. They used global.Object instead of just Object. Thus having this problem.

**Comment by Daniel15** [comment]
I guess you could add `global.Object = Object` to the [shims.js file](https://github.com/reactjs/React.NET/blob/master/src/React.Core/Resources/shims.js) (you'll have to build your own copy of ReactJS.NET if you do this). You could add `global.Object = Object` to your own script bundle, before loading lodash.

I don't think the `global` object is a standard JavaScript engine thing, normally it's referenced just via `Object`.

**Comment by huan086** [comment]
So there is no way to refer to the global object used in the JavaScript engine, other than `new Function("return this")()`?

**Comment by Daniel15** [comment]
Not that I'm aware of, I think `new Function("return this")()` is the standard way of doing that. I could be wrong though :)
