### ISSUE TITLE
ReactSiteConfiguration.Configuration SetJsonSerializerSettings when set throws EntryPointNotFoundException

### ISSUE THREAD

**Issue by dmitrikartashov** [reactjs/React.NET#214]
Here is my react config file

var configuration = new ReactSiteConfiguration();
configuration.SetLoadBabel(false);
configuration.AddScriptWithoutTransform("~/webs/vbs/Content/Scripts/main.js");
          
configuration.SetJsonSerializerSettings(new JsonSerializerSettings
{
     StringEscapeHandling = StringEscapeHandling.EscapeHtml,
     ContractResolver = new CamelCasePropertyNamesContractResolver()
});

ReactSiteConfiguration.Configuration = configuration;

When I set custom ContractResolver to i.e. CamelCasePropertyNamesContractResolver and then run the site, it throws EntryPointNotFoundException. Below is the strack trace: 

Server Error in '/' Application.

Entry point was not found.

Description: An unhandled exception occurred. 

Exception Details: System.EntryPointNotFoundException: Entry point was not found.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[EntryPointNotFoundException: Entry point was not found.]
   System.Collections.Generic.ICollection`1.get_Count() +0
   Newtonsoft.Json.JsonSerializer.ApplySerializerSettings(JsonSerializer serializer, JsonSerializerSettings settings) +62
   Newtonsoft.Json.JsonSerializer.CreateDefault(JsonSerializerSettings settings) +33
   React.ReactComponent.GetComponentInitialiser() +60
   React.ReactComponent.RenderHtml(Boolean renderContainerOnly, Boolean renderServerOnly) +125
   React.Web.Mvc.HtmlHelperExtensions.React(HtmlHelper htmlHelper, String componentName, T props, String htmlTag, String containerId, Boolean clientOnly, Boolean serverOnly) +211
   Volvo.Vbs.Website.webs.vbs.Views.CarCategories.Index.Execute() in c:\git\volvo\vbs\src\Volvo.Vbs.Website\obj\CodeGen\webs\vbs\webs\vbs\views\carcategories\Index.cshtml:4
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +253
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +148
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +107
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +375
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +90
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +81
   System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName) +710

**Comment by Daniel15** [comment]
Hmm that's really strange... I'm not too sure what that error message means...

**Comment by Daniel15** [comment]
@dmitrikartashov - Are you still seeing this? I haven't seen any other reports of it so I'm going to close this out, but please feel free to reopen if you're still experiencing this.
