### ISSUE TITLE
The ref returned from ReactDOM.render

### ISSUE THREAD

**Issue by lambert-velir** [reactjs/React.NET#215]
Hi!

Great work on this!  We just used it for the first time and it went smoothly.  

However, I now have the requirement of triggering an event in my React app externally.  Is it possible to get a reference to the component returned from ReactDOM.render?

Like this? 

``` js
var myComponentInstance = ReactDOM.render(myComponentElement, myContainer);
myComponentInstance.doSomething();
```

https://facebook.github.io/react/docs/more-about-refs.html#the-ref-returned-from-reactdom.render

**Comment by lambert-velir** [comment]
For anyone with this issue, I've worked around this by adding `window.myComponentInstance = this;` inside of  `componentDidMount`

**Comment by Daniel15** [comment]
Depending on how you're triggering the event, another approach is to attach an event listener in `componentDidMount` and unattach it in `componentWillUnmount`. This reverses the dependency - It means that whatever is triggering the event doesn't need to know about the component.

**Comment by dustinsoftware** [comment]
Agreed, using `componentDidMount` is the right approach here.
