### ISSUE TITLE
React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment

### ISSUE THREAD

**Issue by eugeneniemand** [reactjs/React.NET#218]
I'm running MVC 6 on OS X and trying to use ReactJS.Net I'm Getting the following error 
```
An unhandled exception was thrown by the application.
      React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory ---> React.Exceptions.VroomJsInitialisationException: Failed to initialise VroomJs. This is most likely caused by the native library (libVroomJsNative.so) being out of date or your system lacking a compatible version of V8. Please run Mono with the `MONO_LOG_LEVEL=debug` environment variable for more debugging information, and refer to the ReactJS.NET Mono documentation at http://reactjs.net/guides/mono.html for further debugging hints.
      
       More details: Exception has been thrown by the target of an invocation.
        at React.JavaScriptEngineUtils.EnsureEngineFunctional[TEngine,TException] (System.Func`2 exceptionFactory) <0x5858a48 + 0x0009f> in <filename unknown>:0 
        at React.JavaScriptEngineFactory.GetFactory (IEnumerable`1 availableFactories, Boolean allowMsie) <0x58105a8 + 0x0045b> in <filename unknown>:0 
        at React.JavaScriptEngineFactory..ctor (IEnumerable`1 availableFactories, IReactSiteConfiguration config, IFileSystem fileSystem) <0x580ff98 + 0x000b7> in <filename unknown>:0 
        at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object[])
        at React.TinyIoC.TinyIoCContainer.ConstructType (System.Type requestedType, System.Type implementationType, System.Reflection.ConstructorInfo constructor, React.TinyIoC.NamedParameterOverloads parameters, React.TinyIoC.ResolveOptions options) <0x5809b80 + 0x0034f> in <filename unknown>:0 
```

I also tried running the React.Sample.Mvc6 sample and that tried to reference local assemblies???
``` 
Application startup exception: System.IO.DirectoryNotFoundException: Could not find a part of the path "/Users/eugeneniemand/Projects/reacjsnet/React.NET/src/React.Core/obj/Debug/React.Core.dll".
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) <0x1a03aa0 + 0x0021d> in <filename unknown>:0 
```

Any assistance would be appreciated

**Comment by Daniel15** [comment]
Hmm, I haven't done much testing on OS X due to its small market share. My testing is mainly on Windows and Linux.

Did you see the error message? :)
> Failed to initialise VroomJs. This is most likely caused by the native library (libVroomJsNative.so) being out of date or your system lacking a compatible version of V8. Please run Mono with the `MONO_LOG_LEVEL=debug` environment variable for more debugging information, and refer to the ReactJS.NET Mono documentation at http://reactjs.net/guides/mono.html for further debugging hints.

Using `MONO_LOG_LEVEL=debug` may help with determining why VroomJs isn't initialising. You need V8 installed.

**Comment by Daniel15** [comment]
Closing this out since I haven't heard back, but please feel free to reopen this issue if you're still encountering problems. Thanks!

**Comment by nhannguyen29** [comment]
Hi, I'm using macOS Sierra and ASP.NET Core 1.0 for my website. I got the same error and some more after adding and configuring React.AspNet package to my website. Can you help me how to resolve it? Thank you so much.

Here is the 500 Internal Error I'm getting:

>VroomJsInitialisationException: Failed to initialise VroomJs. This is most likely caused by the native library (libVroomJsNative.so) being out of date or your system lacking a compatible version of V8. Please run Mono with the `MONO_LOG_LEVEL=debug` environment variable for more debugging information, and refer to the ReactJS.NET Mono documentation at http://reactjs.net/guides/mono.html for further debugging hints.

>More details: Exception has been thrown by the target of an invocation.
>ConstructType

>TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory
>ConstructType

>TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment
>ConstructType

**Comment by sigmundholm** [comment]
Hi, I'm also using macOS Sierra and ASP.NET Core. I got the exact same error. I tried to follow the guide in the link, but without luck. @nhannguyen29, were you able to solve the problem?
