### ISSUE TITLE
Unable to communicate with JSX parser.

### ISSUE THREAD

**Issue by hexcrab** [reactjs/React.NET#219]
Running MVC6 project, and trying to create .jsx file. But receiving message 
"JSX Parser: Unable to communicate with JSX Parser". 
I found no answers in Google. Someone have this problem too?

**Comment by rosdi** [comment]
I am having this problem too.. but I think this only affect the syntax highlighting...

**Comment by Daniel15** [comment]
This is part of Visual Studio or one of its extensions, not ReactJS.NET. You'll need to report it as a bug to Microsoft :)

**Comment by rosdi** [comment]
@Daniel15 Not sure this is coincidence or not, but when I downgraded to ReactJS.NET 2.1 it works!.. the syntax highlighting works and there is no more "JSX Parser: Unable to communicate with JSX Parser" error..

**Comment by Daniel15** [comment]
That's really odd... The version of ReactJS.NET shouldn't affect the JSX parser in Visual Studio :confused:

**Comment by cessationoftime** [comment]
I believe this is caused by the use of Babel in version 2.0 of ReactJs.net.

See solutions here: https://stackoverflow.com/questions/34097915/visual-studio-2015-jsx-es2015-syntax-highlighting
