### ISSUE TITLE
Could not use React.Core as one of the file missing SharedAssemblyVersionInfo

### ISSUE THREAD

**Issue by ptpavankumar** [reactjs/React.NET#225]
Looks like React.Core does not have SharedAssemblyVersionInfo.cs

**Comment by sfadeev** [comment]
Take a look at project README.md at https://github.com/reactjs/React.NET/blob/master/README.md#building-manually-and-contributing, it may help:

> When building your own copy of ReactJS.NET (for example, if implementing a new feature or fixing a bug), your first build always needs to be done using the build script (dev-build.bat) as this generates a few files required by the build (such as SharedAssemblyVersionInfo.cs)

**Comment by Daniel15** [comment]
Yep, covered in the readme. Use the full build script for the first build and the file will be generated :)
