### ISSUE TITLE
Ability to unit test components

### ISSUE THREAD

**Issue by stevenguh** [reactjs/React.NET#227]
Hi, I am wondering is there any way to unit tests react components? I am evaluating React.NET in ASP.NET MVC, this is the last piece of the puzzle that seems to be missing. Thanks.

**Comment by stevenguh** [comment]
I am able to use chutzpah(see mmanela/chutzpah#475) with React.MSbuild to perform unit test, which it looks a little bit like a hack right now. FYI, My environment is Visual Studio 2012 with ASP.NET MVC 5.

**Comment by Daniel15** [comment]
Looks like you got a reply in the Chutzpah repo (https://github.com/mmanela/chutzpah/issues/475) so I'm going to close this out. As an alternative, you can use `React.MSBuild` to compile your code, and then run the unit tests against the resulting `.generated.js` files.
