### ISSUE TITLE
dev-build.bat failing

### ISSUE THREAD

**Issue by gdennie** [reactjs/React.NET#228]
dev-build.bat does not detect the absence of "dnu" (apparently resolved by invoke "dnvm upgrade") but problems persists. The following solution does not work, "dnvm upgrade & dnvm upgrade -r CoreClr". Performing "dev-build.bat" produces the following:

"C:\openSource\React.NET\build.proj" (default target) (1) ->
"C:\openSource\React.NET\src\React.VS2015.sln" (Rebuild target) (2) ->
"C:\openSource\React.NET\src\React.AspNet\React.AspNet.xproj" (Rebuild target) (17) ->
(GetRuntimeToolingPathTarget target) ->
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(126,5): error : The Dnx Runtime package needs to be installed. See output window for more details. [C:\openSource\React.NET\src\Rea
ct.AspNet\React.AspNet.xproj]

**Comment by Daniel15** [comment]
What version of ASP.NET / .NET Core do you have installed? You can check by using `dnvm list`. You need RC1 installed.

**Comment by gdennie** [comment]
Prior to receiving your response, I went ahead and launch `React.VS2015.sln`. It prompted to download a missing dnx runtime version, `dnx-clr-win-x86.1.0.0-rc1-final` was downloaded. Subsequently the build completed without failures or updates or skips. Thanks for your suggestion, however.

**Comment by Daniel15** [comment]
Thanks, sounds like this is resolved then? :)

**Comment by gdennie** [comment]
Yes. 
Don't know if any documentation modification would help.

**Comment by Daniel15** [comment]
I can document common issues, and include this in the docs :)

**Comment by gdennie** [comment]
Excellent.
