### ISSUE TITLE
Add support for TargetDir to React.MSBuild

### ISSUE THREAD

**Issue by stevenguh** [reactjs/React.NET#229]
I added React.MSBuild and added 

```
<UsingTask AssemblyFile="$(OutputPath)\React.MSBuild.dll" TaskName="TransformBabel" />
  <Target Name="TransformBabel">
  <TransformBabel SourceDir="$(MSBuildProjectDirectory)" />
</Target>
```

to the .csproj file and tried to restart the Visual Studio and reload the project. Building the project after all those steps doesn't seems to compile any jsx to js. Am I missing any step?

**Comment by Daniel15** [comment]
You need to actually call the `TransformBabel` target. Try running `msbuild foo.csproj /t:TransformBabel` and see if that works. If it does, you should be able to change the target to `<Target Name="TransformBabel" BeforeTargets="Build">` which will automatically run it before the build target.

**Comment by stevenguh** [comment]
Thanks, it works.

FYI, I have to change to command to `msbuild foo.csproj /t:TransformBabel /p:Platform=x64 /p:Configuration=Debug` in order to try out the transform. Once I got that working, I added `BeforeTargets="Build"` in the foo.csproj to transform before build.

However, is there any way to specify the output of the transform? it seems like it used to have the option of `TargetDir` to target the output I assume.

**Comment by Daniel15** [comment]
Currently the output is always in the same directory as the input file, with a `.generated.js` suffix: https://github.com/reactjs/React.NET/blob/master/src/React.Core/Babel.cs#L318-L329. That's a good feature request though, maybe create a separate issue for it :)

**Comment by stevenguh** [comment]
In that case I think the [document](http://reactjs.net/guides/msbuild.html) on MSBuild needs to be updated before the feature is completed, namely the `TargetDir=""` options is invalid.

Do you want me to create a separate issue about the output path and close out this one?

**Comment by Daniel15** [comment]
I'll keep this task open for adding `TargetDir` support. Sorry for the delay in replying!

**Comment by dustinsoftware** [comment]
Since it's been over a year, I'm closing issues for future tasks like this that aren't actively being worked on, but would be open to adding support for this!

#655
