### ISSUE TITLE
The container id generation causes problems icw caching

### ISSUE THREAD

**Issue by Jonne** [reactjs/React.NET#230]
Of some components we cache the HTML output on the server. However, the current container id generation is based on identity. This results in duplicate ids in the HTML, causing components to be instantiated in the wrong divs. We solved this by using a non-deterministic algorithm:

System.Convert.ToBase64String(Guid.NewGuid().ToByteArray()).TrimEnd('=');

**Comment by Daniel15** [comment]
Good catch, thanks!

**Comment by thebuilder** [comment]
Any ETA of when the next version will be released to Nuget with this fix? We just ran into when enabled caching on our site.

Thanks! :smiley:

**Comment by Daniel15** [comment]
Sorry, didn't see your comment. I'll push a new build tonight.

**Comment by Daniel15** [comment]
ReactJS.NET 2.3 was pushed on 11th April
