### ISSUE TITLE
Babel react preset support coming?

### ISSUE THREAD

**Issue by Solyad** [reactjs/React.NET#231]
Hi 

Just a quick question to ask if support for the babel react preset is coming to reactjs.net

Currently the below gives an unexpected import token error and I'm having to run node+webpack server to get it to transpile. 

(Just a general example)

`import React from 'react';`

`class Hello extends React.Component`

**Comment by Daniel15** [comment]
Which presets do you want to use? The `es2015`, `stage-1` and `react` presets are enabled by default, and you can enable additional presets or plugins through the config:

```
ReactSiteConfiguration.Configuration.BabelConfig.Presets = new HashSet<string> { "react" };
```

Defaults are set here: https://github.com/reactjs/React.NET/blob/master/src/React.Core/BabelConfig.cs#L30-L34

**Comment by Solyad** [comment]
Ah thats great, I didnt realise. Ill give that a go
Thanks!

**Comment by Daniel15** [comment]
Feel free to reopen if you encounter any issues.
