### ISSUE TITLE
Input lose focus on re-render

### ISSUE THREAD

**Issue by WirthAware** [reactjs/React.NET#232]
I'm rendering grouped Informations with Html.React on the serverside. 
In an input field tag you could change a value. 
If the value has changed an action will dispatched with redux in onChange which will re-render the view.
After it the focus is lost. 
But when the focus was lost 1-times you could use again the input as expected without lose focus. 

I detected the data-reactid on the server has changed after the re-render on the client. 

Before:
data-reactid=".25kcmfhomdy.1.2.0.$21.1.$24.1.$268.1.2.0"

After:
data-reactid=".4.1.2.0.$21.1.$24.1.$268.1.2.0"

I'm now guessing the focus is lost because the id has changed?

**Comment by Daniel15** [comment]
Hmm, interesting... Do you see any errors in the browser developer tools? I don't think the `data-reactid` should affect focus.

**Comment by WirthAware** [comment]
Thanks for your reply. 

The only thing i got was a warning 
"[.NET] Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `...`. See https://fb.me/react-warning-keys for more information."
But i already fixed that warning. 

I'm not an React expert yet, but after re-rendering, somewhat should keep the input focus. 
I found some similar issues in the web and it seems the key indicates the focused input field. 
And the key has an influence to the reactid? And when the key changed may i lose my focus? 
Does this make sense? 
 
http://stackoverflow.com/questions/22573494/react-js-input-losing-focus-when-rerendering
http://reactkungfu.com/2015/09/react-js-loses-input-focus-on-typing/

The key's i'm binding are uniq but the generated reactid is different on the server side as on the client side. I was guessing thats the issue.  

I have the following structure. A list of Group Components that has a List of SubGroup Components wich has a list of EditItems which includes the input field. As i mentioned, when i'm now change the input the focus is losed. After clicking the input again and change the value it works as expected. The only difference is, its now rendering client side instead of server side. 

Any other ideas?

**Comment by WirthAware** [comment]
Seems to be fixed with 2.3.0
