### ISSUE TITLE
Decorators are not supported yet in 6.x pending proposal update.

### ISSUE THREAD

**Issue by PrimeObjects** [reactjs/React.NET#234]
When I use the following way to define a component

**export default class anyname extends React.Component**

Script threw an exception: unknown: Decorators are not supported yet in 6.x pending proposal update.
The export and default Decorators are not supported.

---This is the code in C#
var reactEnvironment = React.AssemblyRegistration.Container.Resolve<React.IReactEnvironment>();
content = reactEnvironment.Babel.Transform(content);
How can I export a default class?

Thanks
Gary

**Comment by Daniel15** [comment]
ReactJS.NET doesn't support ES6 modules (the "export" statement) so I suspect that could be what's causing your issue. You could try just using `class anyname extends React.Component` which should create `anyname` in global scope.

I'd like to add module support eventually, but not people can just use something like Webpack to compile their code.

**Comment by PrimeObjects** [comment]
Hi Daniel, 
Thank you for the update.
