### ISSUE TITLE
MVC 6, random results on server side JSX caching

### ISSUE THREAD

**Issue by defcon84** [reactjs/React.NET#235]
In an Asp.NET MVC 6 project, ReactJS.NET uses the System.Runtime.Caching.MemoryCache.Default to cache transpiled jsx files.
But it seems like it doesnt invalidate/update them when the jsx file is changed, because i'm getting a random version of the jsx file server side. Which is weird.

When i set the ICache to NullCache, everything seems to work fine.

**Comment by Daniel15** [comment]
Interesting, it should be purging the cache when the files change: https://github.com/reactjs/React.NET/blob/4c840f7e45aaf03c10f242ab723cea32acf14b0a/src/React.Core/MemoryFileCache.cs#L73-L77

I'll take a look.

**Comment by Daniel15** [comment]
@defcon84 I'm having some trouble replicating this issue. I tested both with the `React.Sample.Mvc6` project in this repo, as well as a brand new project. Steps were roughly:

1. Create `test.jsx` containing `var test = 'Hello world 1'
2. Hit http://localhost:49171/js/test.jsx and saw this:
```
// @hash v3-911310ED098ECB155443223B0C54E4A7A74CA18E
// Automatically generated by ReactJS.NET. Do not edit, your changes will be overridden.
// Version: 2.2.1 (build 5682fd4) with Babel 6.3.13
// Generated at: 5/03/2016 5:04:48 PM
///////////////////////////////////////////////////////////////////////////////
var foo = 'Hello world 1';
```

3. Changed the file to `var test = 'Hello world 2'`
4. Refreshed and saw the updates to the file:
```
// @hash v3-99CEA3EF7ED44A896E380E7582BD596BE44F0D72
// Automatically generated by ReactJS.NET. Do not edit, your changes will be overridden.
// Version: 2.2.1 (build 5682fd4) with Babel 6.3.13
// Generated at: 5/03/2016 5:05:45 PM
///////////////////////////////////////////////////////////////////////////////
var foo = 'Hello world 2';
```

Try clearing your cache (eg. refreshing with Shift+F5) and see if that works? You may want to add ` asp-append-version="true"` to your `script` tag, which will make the framework automatically append a [cache-busting parameter](http://www.davepaquette.com/archive/2015/05/06/link-and-script-tag-helpers-in-mvc6.aspx#Cache_Busting) to the URL.

**Comment by defcon84** [comment]
Hmm that's weird.
I've attached my tutorial project: [ReactTest.zip](https://github.com/reactjs/React.NET/files/161086/ReactTest.zip)
I might have a setting wrong somewhere.

If i change row 89 of Comment.jsx, to eg "DELETE xx", i still get the "DELETE yy" from time to time if i keep refreshing that page.
The browser console shows this:

```
HTML1300: Navigation occurred.
localhost:29051
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) f8cd71caf.2">DELETE xx</span></div><div 
 (server) f8cd71caf.2">DELETE yy</span></div><div 
```

**Comment by defcon84** [comment]
@Daniel15 where you able to recreate this with my project?

**Comment by Daniel15** [comment]
Hey @defcon84, sorry for the delay in replying. I took a look at your example project. It looks like you're using Gulp to build a `site.min.js` file that the site is loading. When you edit the `Comment.jsx` file, the server side is correctly reloading it, but the client side still receives the old `site.min.js` file. This file is outside of ReactJS.NET's control since it's being built by Gulp. If you wish to use Gulp to build the `site.min.js` file, you'll need to use something like `gulp.watch` to ensure Gulp rebuilds it whenever you modify any of the files. Alternatively, you can link directly to http://localhost:5000/js/Comment.jsx in dev, and only use the Gulp'd `site.min.js` in prod. You already have `<environment>` tags in `_Layout.cshtml` to do different things based on layout, you could do that there.

Hope that helps!

**Comment by defcon84** [comment]
No, the server seems to not update its cache.
As the error says:
> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server.

When i have the time, i'll do some more testing.
