### ISSUE TITLE
Issue with block scoping: We found a path that isn't a NodePath instance. Possiblly due to bad serialisation.

### ISSUE THREAD

**Issue by StasPerekrestov** [reactjs/React.NET#242]
If we try to transform js code that contains a block scope, e.g.
```
for(var i =0; i<3; ++i) {
  let a = i;
  $("#login-id").click(e => a = a + 1);
}
```
then we get the following error:
**We found a path that isn't a NodePath instance. Possiblly due to bad serialisation.**

There is a UnitTest for this issue https://github.com/StasPerekrestov/ReactJsNodeIssue

We've done some research and found that if we remove the
`.pipe(uglify())` here
https://github.com/reactjs/React.NET/blob/master/src/React.Core/gulpfile.js#L67
then it fixes the issue.

**Comment by StasPerekrestov** [comment]
Related issue https://phabricator.babeljs.io/T7198

**Comment by Daniel15** [comment]
Yeah, unfortunately this seems like a Babel issue. I'm going to close this out in favour of the Babel issue you linked to above. Thanks for reporting it :)

**Comment by StasPerekrestov** [comment]
@Daniel15 
I suppose that the issue not in babel itself, but in the uglification process.
Here is a solution of the current issue:
```
.pipe(uglify({mangle: { keep_fnames: true} }))
```

**Comment by Daniel15** [comment]
ReactJS.NET 2.3 upgrades the version of Babel, which should fix this issue.

**Comment by StasPerekrestov** [comment]
Daniel, thanks a lot for the update.
