### ISSUE TITLE
react-router - Server side rendering

### ISSUE THREAD

**Issue by alesdvorakcz** [reactjs/React.NET#243]
Hi, is it now possible to render react-router on server side in MVC5? I read some discussions more than year old that there is some modificated version of ReactJS.NET. Is it possible/planned to support this in 'official' React.NET?

**Comment by pauldotknopf** [comment]
In case your interested, [react-aspnet-boilerplate](https://github.com/pauldotknopf/react-aspnet-boilerplate) handles this.

**Comment by alesdvorakcz** [comment]
I have seen yours boilerplate but I have to use MVC5/ASP.NET 4.x so I can't use this solution.

**Comment by BrumoMiguelAS** [comment]
I have the same problem, the Javascriptviewengine only supports MVC 6. Is there any development in this area?

**Comment by pauldotknopf** [comment]
@BrumoMiguelAS Not as of now, no. I'd like to, just don't have the time.

**Comment by pauldotknopf** [comment]
@BrumoMiguelAS @alesdvorakcz [JavaScriptViewEngine](https://github.com/pauldotknopf/JavaScriptViewEngine) now supports MVC Core 1 (MVC 6) and MVC 5.

**Comment by gunnim** [comment]
@BrumoMiguelAS @alesdvorakcz and others who might stumble upon this issue, if you would like to use ReactJS.NET as the core for a server side rendering solution you might be interested in my solution.

https://github.com/gunnim/GMO.ReactRouterNet
This package extends upon the core features of ReactJS.NET and offers a way to render a React Router component with context object.

https://github.com/gunnim/Umbraco-React-Router-SSR
This repo contains a full working MVC 5 solution built on top of Umbraco, the js closely mirrors the current server side rendering [tutorial ](https://reacttraining.com/react-router/web/guides/server-rendering)from React Router.

**Comment by dustinsoftware** [comment]
Docs are here for React Router integration: https://reactjs.net/bundling/webpack.html
