### ISSUE TITLE
Unable to Build Solution

### ISSUE THREAD

**Issue by joshburgess** [reactjs/React.NET#244]
I'm having a tough time trying to actually build the solution hosted here in the master branch. After restoring all nuget packages in the various projects (which was fairly difficult) I still can't seem to build the solution.

For some reason, it seems the React.Core library is not building properly, and other files seem to not be referencing the SharedAssemblyVersionInfo.cs file correctly. I've attached a screenshot. Any idea what's wrong?

<img width="1353" alt="reactneterrors" src="https://cloud.githubusercontent.com/assets/5396631/13752426/0675a8c0-e9e5-11e5-8523-1cc07a4f5484.png">

**Comment by Daniel15** [comment]
> and other files seem to not be referencing the SharedAssemblyVersionInfo.cs file correctly

Did you read the readme? :) 

> When building your own copy of ReactJS.NET (for example, if implementing a new feature or fixing a bug), your first build always needs to be done using the build script (dev-build.bat) as this generates a few files required by the build (such as SharedAssemblyVersionInfo.cs). Once this build is completed, you can open React.sln in Visual Studio and compile directly from Visual Studio.

**Comment by joshburgess** [comment]
Whoops, sorry! That makes a lot more sense. I see the first step there is auto-restoring all of the nuget packages. That would have saved me some time. haha.

I was really just trying to run & look through the sample projects to get a feel for how they are working. Do you know if anyone has been able to successfully serve up an ASP.NET Core app with an MVC view (just loading the initial state of the app with a home controller) while at the same time integrating webpack with all hot reloading & build functionality fully working? 

I'm trying to lay the foundations for a project utilizing this sort of workflow for a team right now. I would prefer to just use Node for this, but using MVC for that initial load (and talking to an OAuth server) will make others more comfortable... However, I really want to keep the nice front-end workflow with webpack & hot reloading, if possible.

**Comment by Daniel15** [comment]
Sorry for the delay in replying, @joshburgess!

> while at the same time integrating webpack with all hot reloading & build functionality fully working?

Webpack hot reloading runs a completely separate server on a separate port, purely for serving the JavaScript files. Using ASP.NET MVC to render the page and Webpack dev server to serve the JavaScript should work with no issues, you just need to change your `<script>` tag to load the script from the Webpack dev server.

I'm going to close this issue since it's more of a conversation rather than a bug report, but feel free to post more comments if you like :)
