### ISSUE TITLE
SSR issue with MVC 6 RC1

### ISSUE THREAD

**Issue by eadbhard** [reactjs/React.NET#245]
Hi there! I've followed the tutorial using MVC 6 RC1 and everything worked perfectly. However, when I reached the Optimizations section and tried SSR, the app stopped working. I've modified the .jsx file and the view to look just like the tutorial's, added config.AddScript("~/Scripts/Tutorial.jsx"); to StartUp.cs, and modified the Index() action method in the Home controller to pass _comments (now declared in the HomeController class) as the View's model.

When I run the app I get a 500 (internal server error) in Chrome's console.

Any ideas? Thanks in advance.

**Comment by Daniel15** [comment]
Do you see an error message? This error is pretty hard to diagnose without
an error message or stack trace.

**Comment by Daniel15** [comment]
I'm going to close this out since I haven't heard back, but please feel free to reopen this issue once you've added extra information (eg. stack trace). Thanks!

**Comment by eadbhard** [comment]
Sure. Thanks a lot for your help.

Best regards,

-Eduardo

2016-04-12 22:52 GMT-05:00 Daniel Lo Nigro <notifications@github.com>:
