### ISSUE TITLE
How to enable third party plugins for BabelConfig?

### ISSUE THREAD

**Issue by joskoanicic** [reactjs/React.NET#248]
I am trying to use [transform-decorators-legacy] (https://www.npmjs.com/package/babel-plugin-transform-decorators-legacy) plugin, but because it's not part of the preset plugins I get this error:

 `Invalid plugin specified in Babel options: "transform-decorators-legacy"`

Is there a way to include or set the path to the plugin js?

Thank you.

P.S. Forgot to mention that I am using .NET Bundling and Minification

**Comment by Daniel15** [comment]
`transform-decorators-legacy` was added to babel-standalone in 78ad50a8068771b9fa07ac162d37f910d9245b44, so I just need to update the version of babel-standalone bundled with ReactJS.NET.

Currently, there's no way to use custom Babel transforms with ReactJS.NET if they're not bundled with babel-standalone.
