### ISSUE TITLE
Server Side Rendering - SetTimeout is undefined

### ISSUE THREAD

**Issue by joff1979** [reactjs/React.NET#249]
Hi,

I have been playing around with using the Server side rendering (ASP.CORE) and I have come up against the above  issue when trying to use fixed-data-table on the server side. 

I am getting the Stack trace below -

> ReactScriptLoadException:
> 
>  Error while loading "lib/fixed-data-table/dist/fixed-data-table.js": Script threw an exception: 'setTimeout' is undefined
>  Line: 0
>  Column:0
> React.ReactEnvironment.EnsureUserScriptsLoaded()
> React.ReactEnvironment.CreateComponent[T](String componentName, T props, String containerId)
> React.AspNet.HtmlHelperExtensions.React[T](IHtmlHelper htmlHelper, String componentName, T props, String htmlTag, String containerId, Boolean clientOnly, Boolean serverOnly, String containerClass)
> Asp.ASPV__Views_Home_Index_cshtml.<ExecuteAsync>d__22.MoveNext() in Index.cshtml
>     @Html.React("CommentBox", new
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Mvc.Razor.RazorView.<RenderPageAsync>d__17.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
> Microsoft.AspNet.Mvc.Razor.RazorView.<RenderAsync>d__16.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__14.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Mvc.ViewResult.<ExecuteResultAsync>d__24.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResultAsync>d__56.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResultFilterAsync>d__55.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAllResultFiltersAsync>d__54.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResourceFilterAsync>d__49.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__27.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> React.AspNet.BabelFileMiddleware.<Invoke>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()`

 Is this a general problem with server side rendering? I also tried to switch the Javascript engine by setting the `.SetAllowMsieEngine(false)` in the start up but I get the following issue when setting this flag. All Packages and dependencies have installed correctly -
 

> DirectoryNotFoundException: Failed to load the ClearScriptV8 assembly, because the directory 'C:\Users\xxx\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\ClearScript.V8' does not exist.
> System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
> System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
> System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
> System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
> System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
> System.Reflection.Assembly.Load(String assemblyString)
> Microsoft.ClearScript.V8.V8Proxy.LoadAssembly()
> Microsoft.ClearScript.V8.V8Proxy.GetAssembly()
> Microsoft.ClearScript.V8.V8Proxy.GetImplType(Type type)
> Microsoft.ClearScript.V8.V8Proxy.CreateImpl[T](Object[] args)
> Microsoft.ClearScript.V8.V8IsolateProxy.Create(String name, V8RuntimeConstraints constraints, Boolean enableDebugging, Int32 debugPort)
> Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags, Int32 debugPort)
> Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags)
> Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints)
> Microsoft.ClearScript.V8.V8ScriptEngine..ctor(V8Runtime runtime, String name, V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)
> Microsoft.ClearScript.V8.V8ScriptEngine..ctor(String name, V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)
> Microsoft.ClearScript.V8.V8ScriptEngine..ctor(V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)
> JavaScriptEngineSwitcher.V8.V8JsEngine..ctor(V8Configuration config)
> 

> 
> Show raw exception details
> JsEngineLoadException: During loading of V8 JavaScript engine error has occurred.	
>  See more details:
>  
>  Failed to load the ClearScriptV8 assembly, because the directory 'C:\Users\xxx\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\ClearScript.V8' does not exist.
> JavaScriptEngineSwitcher.V8.V8JsEngine..ctor(V8Configuration config)
> JavaScriptEngineSwitcher.V8.V8JsEngine..ctor()
> 
> Show raw exception details
> TargetInvocationException: Exception has been thrown by the target of an invocation.
> System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
> System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
> System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
> System.Activator.CreateInstance[T]()
> React.JavaScriptEngineUtils.EnsureEngineFunctional[TEngine,TException](Func`2 exceptionFactory)
> 
> Show raw exception details
> ClearScriptV8InitialisationException: Failed to initialise ClearScript V8. This is most likely caused by the native libraries (ClearScriptV8-64.dll and v8-x64.dll) missing from your app's Bin directory, or the Visual C++ runtime not being installed. Please ensure your app is referencing the JavaScriptEngineSwitcher.V8 NuGet package, and refer to the ReactJS.NET site for moredebugging tips. More details: Exception has been thrown by the target of an invocation.
> React.JavaScriptEngineUtils.EnsureEngineFunctional[TEngine,TException](Func`2 exceptionFactory)
> React.JavaScriptEngineFactory.GetFactory(IEnumerable`1 availableFactories, Boolean allowMsie)
> React.JavaScriptEngineFactory..ctor(IEnumerable`1 availableFactories, IReactSiteConfiguration config, IFileSystem fileSystem)
> lambda_method(Closure , Object[] )
> React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
> 
> Show raw exception details
> TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory
> React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
> React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options)
> React.TinyIoC.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
> React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
> React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
> 
> Show raw exception details
> TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment
> React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
> React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options)
> React.TinyIoC.TinyIoCContainer.CustomObjectLifetimeFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
> React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
> React.TinyIoC.TinyIoCContainer.Resolve(Type resolveType)
> React.TinyIoC.TinyIoCContainer.Resolve[ResolveType]()
> React.ReactEnvironment.get_Current()
> React.AspNet.HtmlHelperExtensions.get_Environment()
> 
> Show raw exception details
> ReactNotInitialisedException: ReactJS.NET has not been initialised correctly. Please ensure you have called app.AddReact() and app.UseReact() in your Startup.cs file.
> React.AspNet.HtmlHelperExtensions.get_Environment()
> React.AspNet.HtmlHelperExtensions.React[T](IHtmlHelper htmlHelper, String componentName, T props, String htmlTag, String containerId, Boolean clientOnly, Boolean serverOnly, String containerClass)
> Asp.ASPV__Views_Home_Index_cshtml.<ExecuteAsync>d__22.MoveNext() in Index.cshtml
>     @Html.React("CommentBox", new
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Mvc.Razor.RazorView.<RenderPageAsync>d__17.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
> Microsoft.AspNet.Mvc.Razor.RazorView.<RenderAsync>d__16.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__14.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Mvc.ViewResult.<ExecuteResultAsync>d__24.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResultAsync>d__56.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResultFilterAsync>d__55.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAllResultFiltersAsync>d__54.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResourceFilterAsync>d__49.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__27.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> React.AspNet.BabelFileMiddleware.<Invoke>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
> `
> 
>

**Comment by huan086** [comment]
It's a problem with FixedDataTable. There's an issue opened there

https://github.com/facebook/fixed-data-table/issues/350

**Comment by joekrie** [comment]
I have had a similar problem, and I am not using FixedDataTable. I am using ReactDnD, however, and it appears that setTimeout and setInterval are undefined in both MSIE engine and ClearScript V8: http://clearscript5.rssing.com/chan-14849447/all_p26.html#item513 
After adding no-op implementations to global, I no longer received the errors:
```
global.setTimeout = () => {};
global.setInterval = () => {};
```

**Comment by Daniel15** [comment]
This is expected. `setTimeout` and `setInterval` are part of the BOM (Browser Object Model) which doesn't exist in a server-side rendering environment, although I think Node.js polyfills them. Any non-Node.js server JavaScript environment will have the same issue. You'll need to remove the `setInterval` or `setTimeout` calls from your code to use server-side rendering.

**Comment by joekrie** [comment]
@joff1979 I ran into 2 of the same issues you did. One being setTimeout, the other being that V8 didn't load after adding SetAllowMsieEngine(false). For the latter, I was able to work around it using the instructions here: http://www.samulihaverinen.com/web-development/dotnet/2016/01/19/how-to-run-clearscript-v8-javascript-engine-in-azure/

**Comment by Daniel15** [comment]
As mentioned in that article, you shouldn't need any workarounds for running V8 in Azure any more. : ReactJS.NET 2.2+ uses a version of JavaScriptEngineSwitcher + ClearScript that should work out-of-the-box on Azure.

**Comment by joekrie** [comment]
To get V8 working locally I had to follow the instructions under "Running V8 locally", even with the latest version of React.AspNet, ClearScript, and JavaScriptEngineSwitcher.V8 installed. Maybe I'll try deleting all the packages from my machine, then reinstalling them.

**Comment by wub** [comment]
I got around this by doing:

Old:
`window.setTimeout()`

New:
`typeof window !== "undefined" && window.setTimeout()`
