### ISSUE TITLE
React 15 support - "attempted to reuse markup"

### ISSUE THREAD

**Issue by wub** [reactjs/React.NET#252]
https://facebook.github.io/react/blog/2016/04/07/react-v15.html

React 15 changed the way components are rendered (regarding `react-id` etc), which causes this error for me when using `@Html.React`:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid.
This generally means that you are using server rendering and the markup generated on the
server was not what the client was expecting. React injected new markup to compensate which
works but you have lost many of the benefits of server rendering. Instead, figure out why the
markup being generated is different on the client or server:
 (client) <div data-reactroot="" data-reactid
 (server) <div data-reactid=".1hrhaz20mio"
```

When I downgrade to React 0.14.x, this is resolved.

**Comment by Daniel15** [comment]
Yes, ReactJS.NET doesn't use React 15 yet. I'll update it shortly.

**Comment by rnjailamba** [comment]
Thanks for this , it solved my issue.

**Comment by dgpedro** [comment]
I got a question... If react 15 no longer needs the attribute data-reactid, why react.net keeps rendering elements with this attribute?

So far I was using Html.React( ... , serverOnly: true ) so the server renders nice and clean html without any of these attributes, but now I got confused if I'm doing it properly and I'm not taking advantage of server rendering at all by doing it this way!?

Could someone please clarify?

Thanks.
