### ISSUE TITLE
JSPool watching entire user directory?

### ISSUE THREAD

**Issue by mcintyre321** [reactjs/React.NET#253]
I've been using the Owin demo app as a base for my own project, and although everything is working, the  console for the app is full of 100s of messages like 

`JSPool] Watched file '[JSPool] Watched file '/\Users\Harry\AppData\Local\Google\Chrome\User Data\Default\Cookies-journal' changed'`. 

It seems to be watching my entire user directory.

Given that I'm using 

```

            var contentFileSystem = new PhysicalFileSystem(@"..\..\Content");
            obj.UseBabel(new BabelFileOptions()
            {
                StaticFileOptions = new StaticFileOptions()
                {
                    FileSystem = contentFileSystem,
                },
            });
            obj.UseFileServer(new FileServerOptions() { FileSystem = contentFileSystem });
```

shouldn't it only be watching under my Content directory? Apologies if this is user error somewhere!

**Comment by Daniel15** [comment]
This may be fixed by f450bac13a4eb1e643144733ce6e70d01702dad7. Could you please try it out and let me know if that fixes it? The build should be available on the development server shortly (see http://reactjs.net/getting-started/download.html#development-builds for instructions).

**Comment by Daniel15** [comment]
Please let me know if you still encounter this, it should have been fixed in ReactJS.NET 2.4.0

**Comment by Daxito** [comment]
This is still an issue for me, using React.Net 3.1.0 like this, am I missing something? Thanks

Public Sub ConfigureAuth(app As IAppBuilder)
        Dim contentFileSystem = New PhysicalFileSystem(HttpContext.Current.Server.MapPath("Content"))
        app.UseBabel(New BabelFileOptions() With
        {
            .StaticFileOptions = New StaticFileOptions() With
            {
                .FileSystem = contentFileSystem
            }
        })
        app.UseFileServer(New FileServerOptions() With {.FileSystem = contentFileSystem})
