### ISSUE TITLE
ReactConfig.cs is recreated on every update

### ISSUE THREAD

**Issue by SoonDead** [reactjs/React.NET#255]
Could you check if it exists before recreating it?

Not that much of a bother if you use a VCS, but still.

**Comment by Daniel15** [comment]
I think NuGet should be asking whether you want to override the file? As far as I'm aware, I'm handling this the same way that every other NuGet package that bundles a default config handles it.

**Comment by SoonDead** [comment]
You are right. 
1. Updating other packages (like nlog config) works the same way.
2. I have tried the update in a test project and it does ask if I want to replace the file. Not sure what happened the first time around, I might have clicked on in while VS was in a semi-frozen state, or something similar.
