### ISSUE TITLE
Server Side standard library missing problem on ASP.NET 5

### ISSUE THREAD

**Issue by ShikiGami** [reactjs/React.NET#256]
I'm trying to run my script first by Server Side rendering, but I'm getting this error:

> ReactServerRenderingException: Error while rendering "ContentListBox" to "react_TIUoUhrslke9R0HhtlwNzw": Script threw an exception: 'XMLHttpRequest' is undefined

The code is actually very similar to the one on the tutorial.

```
var ContentListBox = React.createClass({
    getInitialState: function () {
        return { data: [] };
    },
    componentWillMount: function () {
        var xhr = new XMLHttpRequest();
        xhr.open('get', this.props.data.url, true);
        xhr.onload = function () {
            var data = JSON.parse(xhr.responseText);
            this.setState({ data: data });
        }.bind(this);
        xhr.send();
    },
    render: function () {
        return (
            <ContentListBox>
                <ContentListHeader icon={this.props.data.contentIcon} selectionList={this.props.data.contentSelectionList}>{this.props.data.contentName}</ContentListHeader>
                <ContentList data={this.state.data} />
            </ContentListBox>
        );
    }
});
```

I'm using Visual Studio 2015 Update 2 with the ASP.NET 5 RC1 update SDK.

**Comment by Daniel15** [comment]
`XMLHttpRequest` only exists in browsers, not in server-side JavaScript as in ReactJS.NET. You can only use `XMLHttpRequest` in component**Did**Mount (only called client-side), not component**Will**mount (which is called both server- and client-side). If you want to load data server-side, you'll need to load it in your C# code and pass it into the component via props.

**Comment by kromakollision** [comment]
I was looking for fetch or XMLHttpRequest in the server-side Javascript as well. I read about ChakraBridge [here](https://www.sitepoint.com/using-javascript-frameworks-inside-c-with-chakrabridge/), which implements XMLHttpRequest like a browser would. Is there any chance that ReactJS.NET could use this ChakraBridge or use a similiar approach?
