### ISSUE TITLE
Transpiling for js files via ASP.NET Bundling and Minification not working

### ISSUE THREAD

**Issue by smithybc** [reactjs/React.NET#257]
Hi

I'm not using react at present but wanted to use the bundling system with Babel to transpile es2015 scripts to es5 (this is very handy). It doesn't seem to be working despite updating the bundles to use BabelBundle.

The issue might be a bug or simply to update the documentation so it's a little clearer for people like me. Anyway Daniel said to log it as an issue for debugging purposes.

Cheers
Ben

**Comment by Daniel15** [comment]
Hey @smithybc, are you seeing any error messages, or are the scripts just not being transpiled? Do you see the ReactJS.NET comment header at the top of the output file?

**Comment by blandau** [comment]
I'm having a similar issue when I follow only the steps presented here http://reactjs.net/guides/weboptimizer.html. Please know that a Google search brought me directly to this page. I'm curious if the steps presented on this page are standalone or are apart of an overall step-by-step process. Either way, here is the testing I did and the results:

```
    public class BundleConfig
    {
        public static void RegisterBundles(BundleCollection bundles)
        {
            bundles.Add(new Bundle("~/bundles/main", new BabelTransform(), new JsMinify())
                .IncludeDirectory("~/js/exports", "*.js")
                .IncludeDirectory("~/js", "*.js"));

            BundleTable.EnableOptimizations = true;
        }
    }
```
If I do _not_ include JsMinify(), I get the following bundle:
```
export function addition(a, b) {
    return a + b;
}
import { addition as adder } from 'exports/myMath';

console.log("2 + 3", adder(2, 3));
```
When I include JsMinify():
```
/* Minification failed. Returning unminified contents.
(1,1-7): run-time error JS1195: Expected expression: export
(1,32-33): run-time error JS1004: Expected ';': {
(4,1-7): run-time error JS1195: Expected expression: import
(4,19-21): run-time error JS1004: Expected ';': as
(2,5-17): run-time error JS1018: 'return' statement outside of function: return a + b
 */
export function addition(a, b) {
    return a + b;
};
import { addition as adder } from 'exports/myMath';

console.log("2 + 3", adder(2, 3));;
```

As I said at the top, I only followed the instructions on that web page only. I also tried using BabelBundle but got the same minifcation error output above.

The included directories for the bundle above only include single JS files each: myMath.js - which is the single export function - and main.js - which is the import and console log.

If you have any questions or need anything else, then please let me know.

**Comment by Daniel15** [comment]
@blandau - ReactJS.NET does not support JavaScript modules at this point in time. If you want to use modules, you'd need to use a bundler like Webpack or Browserify. If you want to just use ReactJS.NET, you can't use ES6 modules.

**Comment by siulca** [comment]
> @blandau - ReactJS.NET does not support JavaScript modules at this point in time. If you want to use modules, you'd need to use a bundler like Webpack or Browserify. If you want to just use ReactJS.NET, you can't use ES6 modules.

Is this still the case today? 

I am seeing the following error in the output file, while attempting to do a simple `Import`:

```
/* Minification failed. Returning unminified contents.
(9,1-7): run-time error JS1195: Expected expression: import
 */
```

**Comment by dustinsoftware** [comment]
Yes, you still have to use webpack if you want to use ES modules. https://reactjs.net/bundling/webpack.html
