### ISSUE TITLE
Unable to load one or more of the requested types.

### ISSUE THREAD

**Issue by damiangreen** [reactjs/React.NET#258]
This runtime error occurs after ading the optimization package.
[link](http://stackoverflow.com/questions/33215711/adding-react-js-reference-to-existing-net-mvc-project)

**Comment by Daniel15** [comment]
Try looking at the `LoaderExceptions` property on the exception to see what the actual error message is.

**Comment by Daniel15** [comment]
Closing this out as I haven't heard back, but please feel free to reopen this issue if you're still encountering problems.

**Comment by simbs** [comment]
@Daniel15 same error here. I made a new solution following the MVC5 tutorial, and the error didn't come up. I fixed it in the old one by upgrading to ReactJS.NET v3.0 . There doesn't seem to a way of accessing LoaderExceptions property from our code, it's some pre-application start stuff handled somewhere in the react dll, probably here: React.Web.WebInitializer.Initialize()
