### ISSUE TITLE
React.AspNet - Won't install on .Net Framework 4.5.2

### ISSUE THREAD

**Issue by stevieboy84** [reactjs/React.NET#261]
I'm trying to install the React.AspNet package off nuget (version 2.3.0) but it won't install due to it not containing binaries for .Net 4.5.2.

The other packages (Web.Mvc4 and Web) both install fine..

**Comment by Daniel15** [comment]
Interesting... Does it install on 4.5 fine? I might just need to update the `project.json`, currently it's using `dnx451`: https://github.com/reactjs/React.NET/blob/master/src/React.AspNet/project.json#L31

**Comment by stevieboy84** [comment]
Sorry I think I was being stupid and trying to install it on a MVC 5 app instead of MVC 6.  Ignore me!

**Comment by Daniel15** [comment]
If you do want to use ReactJS.NET on an MVC 5 project, `React.Web.Mvc4
