### ISSUE TITLE
React.NET on Dnx Core

### ISSUE THREAD

**Issue by ar27111994** [reactjs/React.NET#264]
Is there any chance of running & using React.NET on Dnx Core in the **near future**? An update on timeframe of release will help. Thanks.

**Comment by Daniel15** [comment]
Unfortunately, this won't be possible until there's a JavaScript engine that runs on .NET Core. Currently, the main engines (V8 via ClearScript and VroomJs, and Chakra) don't support .NET Core.

**Comment by pauldotknopf** [comment]
@ar27111994, the [react-aspnet-boilerplate](https://github.com/pauldotknopf/react-aspnet-boilerplate) project supports .NET Core/RC2.

**Comment by ar27111994** [comment]
@pauldotknopf  can I run it on rc1?

**Comment by pauldotknopf** [comment]
@ar27111994, it isn't supported going forward, but if you checkout the repo at ```36001a4b1f5a11119fe0f71cb26a36a2e3b18a50```, you can.
