### ISSUE TITLE
Error when compiling solution

### ISSUE THREAD

**Issue by davidinbcn** [reactjs/React.NET#265]
I download the solution (git clone https://github.com/reactjs/React.NET.git) and run dev-build.bat and receive the following errors:

RestorePackages:
  tools\NuGet\nuget.exe restore src\React.sln
  Unable to find version '2.6.3' of package 'NUnit.Runners'.

If I remove the package from .nuget\packages.config, I receive the following errors

  Unable to find version '3.5.0.2' of package 'Antlr'.
  Unable to find version '1.5.0' of package 'JavaScriptEngineSwitcher.Core'.
  Unable to find version '1.5.0' of package 'JavaScriptEngineSwitcher.Msie'.
  Unable to find version '1.5.2' of package 'JavaScriptEngineSwitcher.V8'.
  Unable to find version '4.0.30506.0' of package 'Microsoft.AspNet.Mvc'.
  Unable to find version '2.0.30506.0' of package 'Microsoft.AspNet.Razor'.
  Unable to find version '1.1.3' of package 'Microsoft.AspNet.Web.Optimization'.
  Unable to find version '2.0.30506.0' of package 'Microsoft.AspNet.WebPages'.
  Unable to find version '1.0.0.0' of package 'Microsoft.Web.Infrastructure'.
  Unable to find version '1.7.0' of package 'MsieJavaScriptEngine'.
  Unable to find version '6.0.8' of package 'Newtonsoft.Json'.
  Unable to find version '2.1.0' of package 'WebActivatorEx'.
  Unable to find version '1.6.0' of package 'WebGrease'.
  Unable to find version '0.4.1' of package 'JSPool'.
  Unable to find version '2.0.20710.0' of package 'Microsoft.AspNet.Razor'.
  Unable to find version '2.0.20710.0' of package 'Microsoft.AspNet.WebPages'.
  Unable to find version '4.2.1510.2205' of package 'Moq'.
  Unable to find version '3.0.1' of package 'NUnit'.
  Unable to find version '4.0.20710.0' of package 'Microsoft.AspNet.Mvc'.
  Unable to find version '5.14.5506.26202' of package 'AjaxMin'.
  Unable to find version '2.4.2' of package 'Cassette'.
  Unable to find version '2.4.2' of package 'Cassette.Aspnet'.
  Unable to find version '2.4.2' of package 'Cassette.MSBuild'.
  Unable to find version '2.4.2' of package 'Cassette.Views'.
  Unable to find version '1.0.0' of package 'Microsoft.AspNet.Mvc.FixedDisplayModes'.
  Unable to find version '3.0.1' of package 'Microsoft.Owin'.
  Unable to find version '3.0.1' of package 'Microsoft.Owin.Diagnostics'.
  Unable to find version '3.0.1' of package 'Microsoft.Owin.FileSystems'.
  Unable to find version '3.0.1' of package 'Microsoft.Owin.Host.HttpListener'.
  Unable to find version '3.0.1' of package 'Microsoft.Owin.Hosting'.
  Unable to find version '3.0.1' of package 'Microsoft.Owin.SelfHost'.
  Unable to find version '3.0.1' of package 'Microsoft.Owin.StaticFiles'.
  Unable to find version '1.0' of package 'Owin'.

**Comment by Daniel15** [comment]
That's bizarre... All those packages definitely exist! Do you have custom NuGet sources configured? What happens if you try to install one of those packages in a brand new project in Visual Studio?

**Comment by davidinbcn** [comment]
works fine in a blank project...

PM> Install-Package NUnit.Runners -Version 2.6.3
  GET https://api.nuget.org/v3-flatcontainer/nunit.runners/2.6.3/nunit.runners.2.6.3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/nunit.runners/2.6.3/nunit.runners.2.6.3.nupkg 507ms
Installing NUnit.Runners 2.6.3.
Installing NuGet package NUnit.Runners.2.6.3.
Successfully installed 'NUnit.Runners 2.6.3' to Test.Mvc6
PM> Install-Package Antlr -Version 3.5.0.2
Installing NuGet package Antlr.3.5.0.2.
Successfully installed 'Antlr 3.5.0.2' to Test.Mvc6

I don't have any custom NuGet sources. It's a fresh install of Windows 10 and VS 2015

**Comment by Daniel15** [comment]
Really strange that it works on a blank project... to me this sounds like a NuGet issue rather than a ReactJS.NET issue :confused:

**Comment by Daniel15** [comment]
Looks like the older version of NuGet I had bundled in `tools\NuGet\NuGet.exe` no longer works properly. I've upgraded it to a newer version and it should be fine now. I can probably just totally delete it and rely on the user to have a locally-installed version of NuGet.exe, but this will do for now.
