### ISSUE TITLE
Passing Model to @Html.React

### ISSUE THREAD

**Issue by Kantuz001** [reactjs/React.NET#274]
We can pass simple types such as string, int and etc to @Html.React and List<>,
but we have complex object and want to use it client side without duplication of fields

```
@Html.React("CCCard", new
{
    readOnly = true,
    IdCourtCase = Model.IdCourtCase,
    IdCurrency = Model.IdCurrency
    //...
}) 
```

So, the best way is to pass entire Model, but it doesn't work

```
@Html.React("CCCard", new
{
    data = Model
}) 
```

No data is avalible on client, but on server side Model is not empty

**Comment by Daniel15** [comment]
This should work, it should JSON serialize `Model`. Are you seeing any errors?

**Comment by Kantuz001** [comment]
Problem in DataContract attribute of Model class.
If class has DataContract then Model would be empty on client side.
Any ideas?

**Comment by wub** [comment]
Does it work if you do ```@Html.React("CcCard", Model)``` instead?

**Comment by Daniel15** [comment]
Closing out this issue as it's stale.
