### ISSUE TITLE
React.AspNet 2.4.0 is not compatible with netcoreapp1.0

### ISSUE THREAD

**Issue by drobertson123** [reactjs/React.NET#275]
When loading the package via Nuget for an ASP.NET core RC2 project as per the quickstart;

Install-Package React.AspNet 

The result is an incompatibility notice in the project.json file;

    Package React.AspNet 2.4.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package React.AspNet 2.4.0 supports: net451 (.NETFramework,Version=v4.5.1)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

At this point it won't run.

**Comment by Daniel15** [comment]
This is expected at the moment. There's currently no JavaScript engine that runs on .NET Core. You will need to switch to using the full .NET Framework ("net451" rather than "netcoreapp1.0" in your project.json). Hopefully someone can get Clearscript running on .NET Core at some point.

**Comment by drobertson123** [comment]
Note - by adding "net451" to the framework imports I was able to make it work.

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "net451",
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  }, 

BTW, we were writing these at the same time. Thanks for the amazingly quick response.

**Comment by pauldotknopf** [comment]
@Daniel15,

I updated VroomJs to support .NET Core.

https://github.com/pauldotknopf/vroomjs-core
