### ISSUE TITLE
Access Violation Exception when running JSX handler in Visual Studio debugging session

### ISSUE THREAD

**Issue by paulirwin** [reactjs/React.NET#28]
Please note that this is not a consistently reproducible issue AFAICT.

Occasionally, and this seems to be about on average once an hour or so during active development, when going through this process (my normal react.js dev workflow) it results in a catastrophic Access Violation Exception:
1. Start the Visual Studio 2013 debugger for my ASP.NET MVC project that uses React.NET.
2. Make some changes to my JSX file in Sublime. Hit Save.
3. Go over to Chrome, hit refresh. This requests the JSX file from the React.NET JSX handler again.
4. If successful, the JSX handler will return the compiled JS, then I'll test it and probably go back to step 2 again, keeping the same debugger session active. But occasionally here I'll get Visual Studio popping up saying that the "Unknown Handler" had an Access Violation Exception. After clicking OK, the process crashes, and Visual Studio stops debugging.
5. After a crash like this, without modifying the JSX file, I'll re-start the debugging session in VS, call the .jsx URL again executing the handler, and it will compile the JS just fine (meaning there's nothing wrong with the JSX itself).

Due to the obscure nature of the exception, that it says "Unknown Handler", and that I have no call stack or target site, I can't give any further information about the exception itself. I assume it is occurring in the MSIE integration layer, but that is just a guess. I also have yet to deploy this app to any kind of production environment, so this is at least a developer environment / IIS Express issue. I can not confirm if this does or does not happen using full IIS.

While I can't do anything explicitly to reproduce this, I can say that this happens at least under this criteria:
- Keeping the Visual Studio debugging session active across multiple JSX file changes 
- This exception has not yet occurred on the first load -- it has always been after I've saved the JSX file a couple times and reloaded the page/called the JSX handler again a few times.
- If it matters, I am not editing the file in Visual Studio (using Sublime 3)

And, if it's relevant (due to the MSIE engine), here's my system info:
- Windows 8.1 update
- IE 11.0.9600.17126

If you would like me to try anything explicitly on my machine to try to reproduce this issue, let me know and I'd be happy to help. Also, I'm interested to know if anyone else has encountered this issue.

**Comment by Shreeyam** [comment]
Any update on this? I get a System.AccessViolationError consistently when running my application in IIS 10, but not when debugging using IIS Express.

**Comment by beruic** [comment]
I get this consistently in VisualStudio 2015 using both IIS Express and running the program + running it from console.

I use  the sample project from https://github.com/reactjs/React.NET/tree/master/src/React.Sample.Mvc6. Only change I made is in `project.json` where I put

    "React.Core": "2.4.0",
    "React.AspNet": "2.4.0"

instead of the existing dependencies.

**Comment by mwethington** [comment]
We get crashes all the time in IIS even with V8. Same stuff.

**Comment by Daniel15** [comment]
@mwethington - Could you please provide a stack trace? So far I've only seen this error with the MSIE JS engine in the stack trace.

**Comment by paulirwin** [comment]
Original issue creator here. Wow, I can't believe it's been over 2 years since I originally filed this! Unfortunately I can't help validate with the latest changes as we no longer use this library, we now use either Webpack/Babel or the TypeScript compiler to transform our JSX. But I can say that in the last weeks that we were using this library we did still encounter this issue from time to time with V8 as our only engine in our web.config file.

**Comment by rickywang1981** [comment]
Hi Daniel: we also encounter this with V8 from time to time. The error cannot be catched by ASP.NET. Could you look into this urgent issue? This is error log while ASP.NET crashes:

Version=1
EventType=CLR20r3
EventTime=131185943235051992
ReportType=2
Consent=1
ReportIdentifier=d7a3d85c-7cde-11e6-80d8-005056853a8a
IntegratorReportIdentifier=d7a3d85b-7cde-11e6-80d8-005056853a8a
WOW64=1
NsAppName=w3wp.exe
Response.type=4
Sig[0].Name=Problem Signature 01
Sig[0].Value=w3wp.exe
Sig[1].Name=Problem Signature 02
Sig[1].Value=8.5.9600.16384
Sig[2].Name=Problem Signature 03
Sig[2].Value=52157ba0
Sig[3].Name=Problem Signature 04
Sig[3].Value=ClearScriptV8-32
Sig[4].Name=Problem Signature 05
Sig[4].Value=5.4.5.0
Sig[5].Name=Problem Signature 06
Sig[5].Value=56e184c1
Sig[6].Name=Problem Signature 07
Sig[6].Value=f7
Sig[7].Name=Problem Signature 08
Sig[7].Value=4f
Sig[8].Name=Problem Signature 09
Sig[8].Value=System.AccessViolationException
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.3.9600.2.0.0.272.7
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=f4b8
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=f4b83f39e04b97afc15f0c96e3a7c9c3
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=00a3
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=00a37bc75e5534558a731b6ec5129823
UI[2]=C:\Windows\SysWOW64\inetsrv\w3wp.exe
UI[5]=Check online for a solution (recommended)
UI[6]=Check for a solution later (recommended)
UI[7]=Close
UI[8]=IIS Worker Process stopped working and was closed
UI[9]=A problem caused the application to stop working correctly. Windows will notify you if a solution is available.
UI[10]=&Close
LoadedModule[0]=C:\Windows\SysWOW64\inetsrv\w3wp.exe
...
...
LoadedModule[172]=X:\AgileBet\web.login.star3\bin\ClearScript.V8\ClearScriptV8-32.dll
LoadedModule[173]=X:\AgileBet\web.login.star3\bin\ClearScript.V8\v8-ia32.dll
LoadedModule[174]=C:\Windows\SYSTEM32\MSVCP120.dll
LoadedModule[175]=C:\Windows\SYSTEM32\MSVCR120.dll
LoadedModule[176]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrcompression.dll
