### ISSUE TITLE
Use react component as prop

### ISSUE THREAD

**Issue by wmaca** [reactjs/React.NET#280]
I would like to pass a react component as a prop, but I could not find a way using the current implementation. After reading the code, my solution would be to create a custom converter to serialize an IReactComponent to "React.craeteElement(..., ...)". 

Any suggestions?

**Comment by daiduongbian44** [comment]
Using webpack, you can import the component to others over props. Besides that, you can import third-parties :D

**Comment by doterme** [comment]
@daiduongbian44 how can import third-parties in reactjs.net?can you give a example?

**Comment by daiduongbian44** [comment]
@doterme yep, let's download `webpack` and `npm`, each components that you should put on one file (maybe .js or .jsx). In a component, we could use `require` function of nodejs to import third-parties. Ex: `var React = require('react');
var Slider = require('react-slick');

var SimpleSlider = React.createClass({
  render: function () {
    var settings = {
      dots: true,
      infinite: true,
      speed: 500,
      slidesToShow: 1,
      slidesToScroll: 1
    };
    return (
      <Slider {...settings}>
        <div><h3>1</h3></div>
        <div><h3>2</h3></div>
        <div><h3>3</h3></div>
        <div><h3>4</h3></div>
        <div><h3>5</h3></div>
        <div><h3>6</h3></div>
      </Slider>
    );
  }
});`
then using webpack to bundle your components to one file. This file will be import to ReactConfig
P/s: Example copy from here: https://github.com/akiran/react-slick

**Comment by waltermacambira** [comment]
@daiduongbian44 What I mean is to pass an IReactComponent as a property. The IReactComponent will be created in C#, not in JS.

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
