### ISSUE TITLE
Tutorial Page JSX - Error by Omission

### ISSUE THREAD

**Issue by brentarias** [reactjs/React.NET#284]
After a painful investigation, I figured out that:

 * For some people, the "Hello, world! I am a ComponentBox" sample doesn't work.  I was one of those people.
 * The problem has to do with the presence of middleware, and the order in which middleware is installed.

Most notably, assuming a ASP.NET Core RC2 project, if `UseStaticFiles` is inserted above `UseReact`, then JSX transforms will not work.  

Broadly speaking, there are two fixes the React.Net tutorial should incorporate:

 * The tutorial does not mention that JSX transpiling (in the absence of webpack or other bundlers) is accomplished by adding React.Net middleware.  Perhaps adding the NuGet package in ASP.NET 4 will automatically modify the web.config, causing the middleware to be added.  But in ASP.NET Core RC2, an automatic transformation of the web.config does not occur.  Furthermore, in RC2 the proper means to add the middleware is manually, in the startup.cs file.  This leads to the next point.
 * The tutorial does not warn about the importance of what order the middleware is inserted.  As stated earlier, if present, the `UseStaticFiles` must be inserted after `UseReact`.

**Comment by Daniel15** [comment]
Hi @brentarias! There's a separate page at http://reactjs.net/getting-started/aspnet5.html that documents what's needed to use ReactJS.NET with ASP.NET Core. I do need to update the page a bit as it was written around the time of ASP.NET 5 Beta 8, but it should still mostly be relevant. It does document where to insert the middleware (above `UseStaticFiles`).

I added that page when ASP.NET 5 wasn't very popular. Now that it's growing in popularity, I should link to it from the tutorial, or even update the tutorial to have two versions (one for ASP.NET 4 and one for ASP.NET Core).

**Comment by Daniel15** [comment]
Tutorial has been updated for ASP.NET Core
