### ISSUE TITLE
Update documentation for ASP.NET Core 1.0

### ISSUE THREAD

**Issue by Daniel15** [reactjs/React.NET#288]
- Add blog post about ASP.NET Core 1.0 final release
 - Update references to RC2 (and older references to Beta 8) on the site
 - Verify getting started instructions for ASP.NET Core still work 
 - Rename page from `aspnet5.md` to `aspnetcore.md` and add redirect from old URL
 - Maybe update "getting started" guide to use ASP.NET Core rather than ASP.NET 4.0

**Comment by mrtrandinhvn** [comment]
Please write a more detail guide for using server-side rendering. The current document only works for the old MVC.
I figured myself how to use in .NET core but it only works if the <script> tag for jsx file is in the same file with the "@Html.ReactInitJavaScript()" line (in my case, this line is put right above </body> tag of the layout file). When I split the <script> tag for jsx file to my partial view, I received a javascript error said that my component (var XXX) is undefined.
I'm not sure if this is a bug or my configuration is just wrong.

**Comment by Daniel15** [comment]
Docs have been updated, see the new tutorial at https://reactjs.net/getting-started/tutorial.html.
