### ISSUE TITLE
Mono setup no longer works

### ISSUE THREAD

**Issue by WereDev** [reactjs/React.NET#289]
Following the guide to get ReactJS.Net running on Mono no longer works (http://reactjs.net/guides/mono.html).  When running 'make dependencies' I get the following output:

svn checkout --force http://gyp.googlecode.com/svn/trunk build/gyp \
    --revision 1501
svn: E170013: Unable to connect to a repository at URL 'http://gyp.googlecode.com/svn/trunk'
svn: E160013: '/svn/trunk' path not found
Makefile:301: recipe for target 'dependencies' failed
make: **\* [dependencies] Error 1

The referenced repository appears to no longer be working:  https://github.com/Homebrew/homebrew-versions/issues/1275

I am looking to see if the information in this other ticket resolves the issue here.

**Comment by WereDev** [comment]
Seems if I replace

`make dependencies`

with

`git clone https://chromium.googlesource.com/external/gyp`

And then continue on, the next `make native ...` line will succeed.

**Comment by WereDev** [comment]
At step `g++ jscontext.cpp jsengine.cpp managedref.cpp bridge.cpp jsscript.cpp -o libVroomJsNative.so -shared -L /usr/local/src/v8-3.17/out/native/lib.target/ -I /usr/local/src/v8-3.17/include/ -fPIC -Wl,--no-as-needed -l:/usr/local/lib/libv8.so.3.17.16.2`

Getting error `/usr/bin/ld: cannot find -l:/usr/local/lib/libv8.so.3.17.16.2`

File does exist, however:
'-rwxr-xr-x 1 root root  7999056 Jul  2 12:44 libv8.so.3.17.16.2
drwxrwsr-x 4 root staff    4096 Apr 20 17:13 python2.7
drwxrwsr-x 3 root staff    4096 Apr 20 17:08 python3.5'

Not sure where to go from here...

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
