### ISSUE TITLE
ReflectionTypeLoadException when upgrading to from 2.2.1 to 2.4.0/2.5.0

### ISSUE THREAD

**Issue by ematipico** [reactjs/React.NET#290]
Hi, 

I had installed the plugin (2.2.1) onto my project and everything works fine but when I upgrade the plugin using nuGet to 2.4.0/2.5.0 I got the following stacktrace when I kick off my application

`[ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.]
   System.Reflection.RuntimeModule.GetTypes(RuntimeModule module) +0
   System.Reflection.RuntimeModule.GetTypes() +9
   System.Reflection.Assembly.GetTypes() +70
   React.<>c.<InitializeIoC>b__2_0(Assembly assembly) +50
   System.Linq.<SelectManyIterator>d__16'2.MoveNext() +188
   System.Linq.WhereEnumerableIterator'1.MoveNext() +77
   React.Initializer.InitializeIoC(Func'2 requestLifetimeRegistration) +446
   React.Initializer.Initialize(Func'2 requestLifetimeRegistration) +41
   React.Web.WebInitializer.Initialize() +81
[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +192
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +101
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +21
   WebActivatorEx.BaseActivationMethodAttribute.InvokeMethod() +209
   WebActivatorEx.ActivationManager.RunActivationMethods(Boolean designerMode) +903
   WebActivatorEx.ActivationManager.RunPreStartMethods(Boolean designerMode) +47
   WebActivatorEx.ActivationManager.Run() +130
[InvalidOperationException: The pre-application start initialization method Run on type WebActivatorEx.ActivationManager threw an exception with the following error message: Exception has been thrown by the target of an invocation..]
   System.Web.Compilation.BuildManager.InvokePreStartInitMethodsCore(ICollection'1 methods, Func'1 setHostingEnvironmentCultures) +622
   System.Web.Compilation.BuildManager.InvokePreStartInitMethods(ICollection'1 methods) +141
   System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +102
   System.Web.Compilation.BuildManager.ExecutePreAppStart() +157
   System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +531
[HttpException (0x80004005): The pre-application start initialization method Run on type WebActivatorEx.ActivationManager threw an exception with the following error message: Exception has been thrown by the target of an invocation..]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9947380
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261`

I can't even have access to the LoaderExceptions object

**Comment by Daniel15** [comment]
Hmm, this is super tricky to debug without looking at the `LoaderExceptions` property of the exception, as that's where all the useful information is.

**Comment by Daniel15** [comment]
Closing this since I never heard back, but feel free to reopen if you still need assistance with it. It would be ideal to get the `LoaderExceptions` in order to debug this further.

**Comment by eos87** [comment]
I was having the same issue. I fixed it updating libraries to 3.0
