### ISSUE TITLE
ReactJS.MSBuild cannot find Newtonsoft.Json Version 6.0.0.0

### ISSUE THREAD

**Issue by wmaca** [reactjs/React.NET#291]
When build, when msbuild calls TransformBabel.proj, it cannot find Newtonsoft.Json Version 6.0.0.0
In my project, Newtonsoft.Json is version 9.0.1 and there is a assembly redirection to it.

I am using React.MSBuild 2.5.0

[TransformBabel] Exec
      [Exec] "C:\Program Files (x86)\MSBuild\12.0\bin\amd64\msbuild.exe" TransformBabel.proj /p:OutputPath=bin\ /nr:false
      [Exec] Microsoft (R) Build Engine version 12.0.21005.1
      [Exec] [Microsoft .NET Framework, version 4.0.30319.42000]
      [Exec] Copyright (C) Microsoft Corporation. All rights reserved.
      [Exec] 
      [Exec] Build started 7/15/2016 11:13:14 AM.
      [Exec] Project "TransformBabel.proj" on node 1 (default targets).
      [Exec] TransformBabel.proj(6, 3): error MSB4018: The "TransformBabel" task failed unexpectedly.
      [Exec] TransformBabel.proj(6, 3): error MSB4018: React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.IReactSiteConfiguration ---> System.TypeInitializationException: The type initializer for 'React.ReactSiteConfiguration' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.ReactSiteConfiguration..ctor()
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.ReactSiteConfiguration..cctor()
      [Exec] TransformBabel.proj(6, 3): error MSB4018: --- End of inner exception stack trace ---
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.ReactSiteConfiguration.get_Configuration()
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.TinyIoC.TinyIoCContainer.<>c__DisplayClass29_0`1.<Register>b__0(TinyIoCContainer c, NamedParameterOverloads o)
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.TinyIoC.TinyIoCContainer.DelegateFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
      [Exec] TransformBabel.proj(6, 3): error MSB4018: --- End of inner exception stack trace ---
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.TinyIoC.TinyIoCContainer.DelegateFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.TinyIoC.TinyIoCContainer.Resolve[ResolveType]()
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.MSBuild.TransformBabel.Execute()
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()
      [Exec] Done Building Project "TransformBabel.proj" (default targets) -- FAILED.
      [Exec] 
      [Exec] Build FAILED.
      [Exec] 
      [Exec] "TransformBabel.proj" (default target) (1) ->
      [Exec] (TransformBabel target) -> 
      [Exec] TransformBabel.proj(6, 3): error MSB4018: The "TransformBabel" task failed unexpectedly.
      [Exec] TransformBabel.proj(6, 3): error MSB4018: React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.IReactSiteConfiguration ---> System.TypeInitializationException: The type initializer for 'React.ReactSiteConfiguration' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.ReactSiteConfiguration..ctor()
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.ReactSiteConfiguration..cctor()
      [Exec] TransformBabel.proj(6, 3): error MSB4018: --- End of inner exception stack trace ---
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.ReactSiteConfiguration.get_Configuration()
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.TinyIoC.TinyIoCContainer.<>c__DisplayClass29_0`1.<Register>b__0(TinyIoCContainer c, NamedParameterOverloads o)
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.TinyIoC.TinyIoCContainer.DelegateFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
      [Exec] TransformBabel.proj(6, 3): error MSB4018: --- End of inner exception stack trace ---
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.TinyIoC.TinyIoCContainer.DelegateFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.TinyIoC.TinyIoCContainer.Resolve[ResolveType]()
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at React.MSBuild.TransformBabel.Execute()
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
      [Exec] TransformBabel.proj(6, 3): error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()
      [Exec] 
      [Exec]     0 Warning(s)
      [Exec]     1 Error(s)
      [Exec] 
      [Exec] Time Elapsed 00:00:00.37
      [Exec] Site.csproj(2608, 5): error MSB3073: The command ""C:\Program Files (x86)\MSBuild\12.0\bin\amd64\msbuild.exe" TransformBabel.proj /p:OutputPath=bin\ /nr:false" exited with code 1.

**Comment by Daniel15** [comment]
Interesting, I wonder if upgrading the dependency would be enough to make this error go away...

**Comment by lucamazzanti** [comment]
open the transformBabel.proj and change the assemlbyFile path to an external folder containing all the necessary dlls for React.MSBuild.dll. In this way you can keep separated your dlls from theirs.

` <UsingTask AssemblyFile="$(OutputPath)\React.MSBuild.dll" TaskName="TransformBabel" />`

**Comment by waltermacambira** [comment]
@lucamazzanti I know that we can work around it by putting all dependencies in a separate folder. The actual problem is that, by default, using different version of NewtonSoft is enough to break your build.

**Comment by lucamazzanti** [comment]
My solution is temporary just to let @waltermacambira continue work. For example, I needed your React.Net MSBuild just to transform my js files with babel, but i don't use at the time React in my project, so i think is useful for me don't add the packages through nuget (i really appreciate it) but move them in an external MSBuild folder.

**Comment by dustinsoftware** [comment]
We've updated the JSON.NET version in the latest release.
