### ISSUE TITLE
Reactjs 2.5 was released to Nuget but no tagging?

### ISSUE THREAD

**Issue by mwethington** [reactjs/React.NET#292]
https://www.nuget.org/packages/React.Web.Mvc4/

It appears it is 2.5?

**Comment by Daniel15** [comment]
Sorry about that, looks like I forgot to push the changes to the repo. The only change in 2.5 is adding support for ASP.NET Core 1.0. This change is not relevant for React.Web.Mvc4, so don't worry too much :)

At the moment, I use the exact same version number for every package, so sometimes the version number is incremented even if there's no changes in that particular package. I might change it in the future.

**Comment by Daniel15** [comment]
`release-2.5.0` has been tagged in the repo for a while, closing this issue. Thanks!
