### ISSUE TITLE
Javascript.Net

### ISSUE THREAD

**Issue by mwethington** [reactjs/React.NET#293]
Is there a way to use JavaScript.net instead of ClearScript with React.net?
It appears it runs faster and with less overhead than ClearScript.

See comparison: https://rushfrisby.com/which-net-javascript-engine-is-the-fastest/

Thoughts? How to use Javascript.net?

**Comment by Daniel15** [comment]
Interesting. This should be possible, we'd just need a [JavaScriptEngineSwitcher](https://github.com/Taritsyn/JavaScriptEngineSwitcher) wrapper around JavaScript.net.

I created an issue for the JavaScriptEngineSwitcher project to add support for JavaScript.net: https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/17

**Comment by Daniel15** [comment]
This is the response I got over in the JavaScriptEngineSwitcher repo:

> This is yet another wrapper around V8. Not updated for more than a year, and, most likely, will not support of .NET Core.
> Moreover, “Which .NET JavaScript Engine is the fastest?” review is already old - 18 June, 2015.
> In addition, I have a negative experience of using the Noesis.Javascript.
> Therefore, I see no reason to create module for it.

Closing this out - You can follow up with the JavaScriptEngineSwitcher developer at https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/17 if you like.
