### ISSUE TITLE
ETA for .NET Core Standard Dependency?

### ISSUE THREAD

**Issue by lightrefracted** [reactjs/React.NET#294]
Hello,
I wanted to verify that this is still an issue and a fix is in the works. There have been a couple of related issues that have been closed without a full resolution. #278 and #275.

In the related issues, it was mentioned that the Js rendering engine was the holdup. There are now a few options available, including VroomJs, which @pauldotknopf has ported to .NET Core.

Thanks,
Clayton

**Comment by Daniel15** [comment]
@RichardD012 is working on porting the dependencies as well as ReactJS.NET itself to .NET Core :smile:

**Comment by rameshsubramanian** [comment]
@Daniel15  Any update on @RichardD012's effort to port it to .NET Core?

**Comment by RichardD012** [comment]
I currently have a working version if you look at my fork. The required dependencies work in Windows using the Vroom Js renderer. 

Currently what is holding back a PR is that the dotnet solution hasn't been completely rebuilt to match the exiting legacy solution. However, they both work independently and the MVC6 Sample uses that. 

I'm actually using it in a side project with a custom Nuget config for the solution pointing to local versioned packages. This is also present in the example as it using the unnerved JSpool for dot net core.

**Comment by rameshsubramanian** [comment]
Thanks @RichardD012 !!

I attempted to get your code working my dev machine. But I get these errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1001	The dependency Microsoft.AspNetCore.Http.Abstractions >= 1.0.0 could not be resolved.	React.AspNet	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.AspNet\project.json	17	
Error	NU1001	The dependency Microsoft.AspNetCore.Hosting.Abstractions >= 1.0.0 could not be resolved.	React.AspNet	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.AspNet\project.json	16	
Error	NU1001	The dependency Microsoft.AspNetCore.Mvc.ViewFeatures >= 1.0.0 could not be resolved.	React.AspNet	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.AspNet\project.json	18	
Error	NU1001	The dependency Microsoft.Extensions.FileProviders.Physical >= 1.0.0 could not be resolved.	React.AspNet	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.AspNet\project.json	19	
Error	NU1001	The dependency Microsoft.AspNetCore.StaticFiles >= 1.0.0 could not be resolved.	React.AspNet	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.AspNet\project.json	20	
Error	NU1001	The dependency Microsoft.Extensions.DependencyInjection >= 1.0.0 could not be resolved.	React.AspNet	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.AspNet\project.json	21	
Error	NU1001	The dependency Microsoft.Extensions.PlatformAbstractions >= 1.0.0 could not be resolved.	React.AspNet	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.AspNet\project.json	22	
Error	NU1001	The dependency NETStandard.Library >= 1.6.0 could not be resolved.	React.AspNet	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.AspNet\project.json	23	
Error	NU1001	The dependency React.Core could not be resolved.	React.AspNet	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.AspNet\project.json	24	
Error	NU1001	The dependency JSPool >= 0.4.1 could not be resolved.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.json	11	
Error	NU1001	The dependency Newtonsoft.Json >= 9.0.1 could not be resolved.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.json	12	
Error	NU1001	The dependency VroomJs >= 1.2.2 could not be resolved.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.json	13	
Error	NU1001	The dependency JavaScriptEngineSwitcher.Dotnet.Core.Unofficial >= 1.0.2 could not be resolved.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.json	20	
Error	NU1001	The dependency Microsoft.Extensions.Caching.Memory >= 1.0.0 could not be resolved.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.json	21	
Error	NU1001	The dependency Microsoft.Extensions.DependencyModel >= 1.0.0 could not be resolved.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.json	22	
Error	NU1001	The dependency NETStandard.Library >= 1.6.0 could not be resolved.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.json	23	
Error	NU1001	The dependency System.Diagnostics.FileVersionInfo >= 4.0.0 could not be resolved.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.json	24	
Error	NU1001	The dependency System.Diagnostics.TraceSource >= 4.0.0 could not be resolved.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.json	25	
Error	NU1001	The dependency System.Reflection >= 4.1.0 could not be resolved.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.json	26	
Error	NU1001	The dependency System.Threading.Thread >= 4.0.0 could not be resolved.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.json	27	
Error	NU1001	The dependency JavaScriptEngineSwitcher.Core >= 1.5.0 could not be resolved.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.json	42	
Error	NU1001	The dependency JavaScriptEngineSwitcher.Msie >= 1.5.0 could not be resolved.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.json	43	
Error	NU1001	The dependency JavaScriptEngineSwitcher.V8 >= 1.5.0 could not be resolved.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.json	44	
Error	NU1001	The dependency MsieJavaScriptEngine >= 1.7.1 could not be resolved.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.json	45	
Error	NU1009	The expected lock file doesn't exist. Please run "dotnet restore" to generate a new lock file.	React.Core	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Core\project.lock.json	1	
Error	NU1001	The dependency React.Core could not be resolved.	React.Owin	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Owin\project.json	16	
Error	NU1001	The dependency Owin >= 1.0.0 could not be resolved.	React.Owin	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Owin\project.json	41	
Error	NU1001	The dependency Microsoft.Owin >= 3.0.1 could not be resolved.	React.Owin	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Owin\project.json	42	
Error	NU1001	The dependency Microsoft.Owin.FileSystems >= 3.0.1 could not be resolved.	React.Owin	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Owin\project.json	43	
Error	NU1001	The dependency Microsoft.Owin.StaticFiles >= 3.0.1 could not be resolved.	React.Owin	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Owin\project.json	44	
Error	NU1009	The expected lock file doesn't exist. Please run "dotnet restore" to generate a new lock file.	React.Owin	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Owin\project.lock.json	1	
Error	NU1001	The dependency Microsoft.NETCore.App >= 1.0.0 could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	5	
Error	NU1001	The dependency Microsoft.AspNetCore.Diagnostics >= 1.0.0 could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	9	
Error	NU1001	The dependency Microsoft.AspNetCore.Mvc >= 1.0.0 could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	10	
Error	NU1001	The dependency Microsoft.AspNetCore.Razor.Tools >= 1.0.0-preview2-final could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	11	
Error	NU1001	The dependency Microsoft.AspNetCore.Server.IISIntegration >= 1.0.0 could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	15	
Error	NU1001	The dependency Microsoft.AspNetCore.Server.Kestrel >= 1.0.0 could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	16	
Error	NU1001	The dependency Microsoft.AspNetCore.StaticFiles >= 1.0.0 could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	17	
Error	NU1001	The dependency Microsoft.Extensions.Configuration.EnvironmentVariables >= 1.0.0 could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	18	
Error	NU1001	The dependency Microsoft.Extensions.Configuration.Json >= 1.0.0 could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	19	
Error	NU1001	The dependency Microsoft.Extensions.Logging >= 1.0.0 could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	20	
Error	NU1001	The dependency Microsoft.Extensions.Logging.Console >= 1.0.0 could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	21	
Error	NU1001	The dependency Microsoft.Extensions.Logging.Debug >= 1.0.0 could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	22	
Error	NU1001	The dependency Microsoft.Extensions.Options.ConfigurationExtensions >= 1.0.0 could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	23	
Error	NU1001	The dependency Microsoft.VisualStudio.Web.BrowserLink.Loader >= 14.0.0 could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	24	
Error	NU1001	The dependency React.Core could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	25	
Error	NU1001	The dependency React.AspNet could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	28	
Error	NU1001	The dependency VroomJs >= 1.2.1 could not be resolved.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.json	31	
Error	NU1009	The expected lock file doesn't exist. Please run "dotnet restore" to generate a new lock file.	React.Sample.Mvc6	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Sample.Mvc6\project.lock.json	1	
Error	NU1001	The dependency React.Core could not be resolved.	React.Web	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Web\project.json	37	
Error	NU1001	The dependency WebActivatorEx >= 2.1.0 could not be resolved.	React.Web	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Web\project.json	40	
Error	NU1001	The dependency Microsoft.Web.Infrastructure >= 1.0.0 could not be resolved.	React.Web	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Web\project.json	45	
Error	NU1009	The expected lock file doesn't exist. Please run "dotnet restore" to generate a new lock file.	React.Web	C:\Users\rames\Downloads\React.NET-master_DotNet\React.NET-master\src\React.Web\project.lock.json	1	
Error		NuGet Package Restore failed for one or more packages. See details in the Output window.			0	

Ihave been unable to resolve these errors for 2 days now. Any idea why I am getting these?

**Comment by RichardD012** [comment]
Which version of the ASP.Net Core are you running?  If you `dotnet --version` what is the output?

**Comment by rameshsubramanian** [comment]
@RichardD012, I get this when I run the version command 1.0.0-preview2-003121

**Comment by kataik** [comment]
Same here, would gladly have a solution which works with RC2.

**Comment by Daniel15** [comment]
Now that JavaScriptEngineSwitcher officially supports ASP.NET Core, I'm going to release an official build of ReactJS.NET for ASP.NET Core. First step is an official release of JSPool for ASP.NET Core, which I've started working on. The JavaScriptEngineSwitcher release is just an alpha version, so this will probably be an alpha version too.

**Comment by andrewl913** [comment]
Hey all! My team is looking to include this in our enterprise solution. Any progress on the netcoreapp1.0  framework?

**Comment by Daniel15** [comment]
First step is done, I just added a .NET Core build for JSPool here: https://github.com/Daniel15/JSPool/commit/4e1ecb28c74ac136cb5b926d93f30f7dc4e04113. I just need to do more testing, and then update ReactJS.NET to use it too.

Since JavaScriptEngineSwitcher 2.0 is currently an alpha release, this will also most likely be labelled as an alpha too.

**Comment by Daniel15** [comment]
All tasks for ASP.NET Core support are being tracked in this milestone: https://github.com/reactjs/React.NET/milestone/4

**Comment by chikehenderson** [comment]
I just want to use React with my MVC project..

**Comment by Daniel15** [comment]
I just released ReactJS.NET 3.0 RC1, which has support for .NET Core. Documentation and an updated tutorial will come before the final release. :smile:

**Comment by chikehenderson** [comment]
I like it.. will check it out asap..

**Comment by chikehenderson** [comment]
"does not specify any target frameworks in"

**Comment by digitalsaurus** [comment]
Daniel15, worked right out of the box for me! Thanks so much for pushing this out!

**Comment by Daniel15** [comment]
Stable release of ReactJS.NET 3.0 is out, with support for .NET Core: https://reactjs.net/2016/10/3.0.0-release.html

**Comment by Daniel15** [comment]
@chikehenderson - Please try with ReactJS.NET 3.0 and let me know if you still encounter issues. You might find the tutorial useful: https://reactjs.net/getting-started/tutorial.html

**Comment by chikehenderson** [comment]
@Daniel15 - I almost gave up, I will check it out.. thanks

**Comment by etrpreddy** [comment]
Awesome. It worked out of the box with 3.0. Thanks

**Comment by chriscamplejohn** [comment]
I had to add VroomJs.AssemblyLoader.EnsureLoaded(); in my startup on windows to prevent this error. Using React.AspNet 3.0.0 in a Microsoft.NETCore.App 1.1.0.

**Comment by Daniel15** [comment]
Good catch @chriscamplejohn! Would you like to send a pull request to add that to the documentation?
