### ISSUE TITLE
Isomorphic/universal app using webpack 

### ISSUE THREAD

**Issue by RJN368** [reactjs/React.NET#297]
I'm trying to pull together an universal web application.  The problem I have encountered is in the use of the npm fetch, I can use different versions depending on if it is server or client side.  So on the server I am using node-fetch and on the client whatwg-fetch.  To get the server to work and not complain about a missing window reference I have to tell webpack to use node in it's configuration, but when I do that it assumes that it supports node modules and then fails when the java calls the require() method.  I'm trying to get my head around how what I can do to support this (this is not a stack I am used to) any ideas helps, explanations would be happily received

**Comment by thebuilder** [comment]
Do you need to call fetch on the server? If not, you should just check if running serverside and return instead of triggering the fetch. 

```js
if (!global.window) return;
```

You could provide initial data in the props, so fetch would not need to be invoked.

**Comment by dustinsoftware** [comment]
Agreed, passing down the initial data in props or doing the fetch in `componentDidMount` is the right approach here.
