### ISSUE TITLE
MSBuild: Only transpile when file has changed

### ISSUE THREAD

**Issue by TorbenRahbekKoch** [reactjs/React.NET#299]
Since the transpiling does take a considerable amount of time, it would be awesome if the files were only transpiled when changed (or the target file is missing).

It could be as simple as just comparing the timestamps on the original file and the generated file, or something more advanced as storing a hash for the original file. That would probably be overkill, though.

**Comment by Daniel15** [comment]
This is a good idea. The file actually already has a hash (see [Babel.LoadFromFileCache](https://github.com/reactjs/React.NET/blob/master/src/React.Core/Babel.cs#L160)) so the MSBuild task would just need to check the cache before transforming the file.

The best solution is probably to update [Babel.TransformAndSaveFile](https://github.com/reactjs/React.NET/blob/master/src/React.Core/Babel.cs#L348) to check the cache via `LoadFromFileCache` before doing the transformation. If the cached data is valid, we don't need to do the transformation.

**Comment by Daniel15** [comment]
Fixed in #313, thanks @TorbenRahbekKoch!
