### ISSUE TITLE
Visual Studio tooling

### ISSUE THREAD

**Issue by Daniel15** [reactjs/React.NET#3]
Some sort of Visual Studio tooling for JSX where the standard JavaScript navigation and refactoring tools still work. This is a long time ambitious task. I have no experience with creating tooling for Visual Studio. Assistance would be fantastic!

Alternatively, some ReSharper tooling could be made instead, if it's easier. This would give syntax highlighting and ReSharper's tooling at least. See [ForTea](https://github.com/MrJul/ForTea), which is a plugin for ReSharper to implement support for T4 templates. T4 is very similar in that it's a new syntax with existing syntax embedded in it. T4 is a custom syntax with embedded C# code, JSX could be seen as a custom syntax with embedded JavaScript.

**Comment by mjw56** [comment]
Hey, is there any update on this? Is anyone using react with Visual Studio? If so, what is your setup?
