### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by Sheng-Long** [reactjs/React.NET#300]
Do none of your tutorials work in Visual Studio 2015?  I can't follow your mvc5 tutorial because of cleartype and v8 dependency issues and your mvc4 tutorial doesn't work in vs2015 at all.  From the get-go there is no ASP.NET MVC 4 Web Application project template, then later there is no way to add a controller file.  Your mvc4 tutorial is misleading as you say it works in vs2010 and on.  This is extremely frustrating, I can't get anything in this repo working.

**Comment by Daniel15** [comment]
I originally wrote the tutorial using Visual Studio 2013. Thanks for the report, I'll do another run-through of the tutorial and ensure it still works.

> I can't follow your mvc5 tutorial because of cleartype and v8 dependency issues

What's the issues you're encountering? ASP.NET MVC 5 is near-identical to ASP.NET MVC 4 so it should still work fine.

**Comment by Sheng-Long** [comment]
I had the same issue explained in this thread: https://github.com/reactjs/React.NET/issues/281
I attempted the solutions provided, but couldn't get it working.  I've given up on this for now, but I plan to revisit once the .net core is released as you mentioned in the readme that you would update the tutorial (I think).  I'm sure this is just a user issue rather than a problem on your end, I was just very frustrated yesterday when I posted this.  Sorry to muck up your issue board with my venting.

**Comment by Daniel15** [comment]
For the issue in #281, please refer to the blog post I just wrote today: http://reactjs.net/2016/08/protected-memory-exceptions-and-dotnet-core.html

As for the tutorial on the site, I added a notice to the top explaining that it was originally written for ASP.NET MVC 4: http://reactjs.net/getting-started/tutorial.html. I'll update it to ASP.NET Core soon, but in the meantime pull requests to tweak the website content are definitely appreciated :+1:

**Comment by Daniel15** [comment]
Tutorial has been updated for ASP.NET Core 😄
