### ISSUE TITLE
Cannot make server-side rendering works properly along with client-side

### ISSUE THREAD

**Issue by StefanoSega** [reactjs/React.NET#301]
Hallo!!
First of all, congrats for this great project!

Actually I've a problem I cannot fix.

my Razor View inside the body looks like this (the 2 scripts I render are bundles, the first with the react js files and the second is a BabelBundle with the jsx file):

```
<div id="mainContent">
@Html.React("HelloWorldComponent", new {})
</div>
@Scripts.Render("~/js/reactjs")
@Scripts.Render("~/jsx/Home/Index")
@Html.ReactInitJavaScript()
```

my jsx file included is:

```
var HelloWorldComponent = React.createClass({
render: function() {
return (
<h2>
Hello World!
</h2>
);
}
});

if (typeof window !== "undefined") {
ReactDOM.render(
<HelloWorldComponent />,
document.getElementById("mainContent"));
};
```

and the resulting html inside the body is:

```
<div id="mainContent"><h2 data-reactid=".0">Hello World!</h2></div>
<script src="/scripts/react/react.js"></script>
<script src="/scripts/react/react-dom.js"></script>
<script src="/scripts/web/Home/Index.jsx"></script>

<script>ReactDOM.render(React.createElement(HelloWorldComponent, {}), document.getElementById("react_121ndICRlkSIkGBYsIfRFA"));
</script>
```

... but actually I get a js error on Chrome console:

> react.js:18357 Uncaught Invariant Violation: _registerComponent(...): Target container is not a DOM element.

seems like the code get rendered before html?
why there's no DOM "react_121ndICRlkSIkGBYsIfRFA"?

Thanks a lot!
Stefano

**Comment by Futourism** [comment]
Ok got it, seems there's now way to leave ReactDOM.render with SSR without getting errors, even checking for window !== undefined or whatever other hack :P

removed ReactDOM.render I get anyway this warning:

> react.js:18794 Warning: render(...): Replacing React-rendered children with a new root component. If you intended to update the children of this node, you should instead have the existing children update their state and render the new components instead of calling ReactDOM.render.

**Comment by Daniel15** [comment]
> seems there's now way to leave ReactDOM.render with SSR without getting errors,

That's right. `@Html.ReactInitJavaScript` will output the correct `ReactDOM.render` call for you.

> removed ReactDOM.render I get anyway this warning:

Hmm, that's interesting. What does your view code look like now?

**Comment by Futourism** [comment]
Great, thanks for the answers Daniel!

my rendered view looks like this:

```
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    




<h2>Index</h2>

<div id="mainContent">
    <div id="react_AnwTQ65duEOKt6fLAePlA"><h2 data-reactroot="" data-reactid="1" data-react-checksum="355013189">Hello World!</h2></div>
</div>

    
    <script src="/scripts/react/react.js"></script>
<script src="/scripts/react/react-dom.js"></script>

    <script src="/scripts/web/Home/Index.jsx"></script>

    <script>ReactDOM.render(React.createElement(HelloWorldComponent, {}), document.getElementById("react_AnwTQ65duEOKt6fLAePlA"));
</script>


<!-- Visual Studio Browser Link -->
<script type="application/json" id="__browserLink_initializationData">
    {"appName":"Chrome","requestId":"6de36a5d692e47cebe1fa18cfec2bdd4"}
</script>
<script type="text/javascript" src="http://localhost:55109/c5fc6b237f4a4dc4820e1ee6ed8255f1/browserLink" async="async"></script>
<!-- End Browser Link -->

</body>
</html>
```

and the JS error expanded using ReactJS Dev tools for Chrome looks like:

```
react.js:18794 Warning: render(...): Replacing React-rendered children with a new root component. If you intended to update the children of this node, you should instead have the existing children update their state and render the new components instead of calling ReactDOM.render.

warning @ react.js:18794
_renderSubtreeIntoContainer @ react.js:11131
render @ react.js:11166
React_render @ react.js:12349
(anonymous function) @ (index):26
```

... the line (index):26 is:
```
<script>ReactDOM.render(React.createElement(HelloWorldComponent, {}), document.getElementById("react_AnwTQ65duEOKt6fLAePlA"));
</script>
```

... also as a next step I'll try to create more components in different files and to make them to communicate with each other through props and the state ...

what you advise me to use Daniel for a scalable architecture that anyway can use SSR?
Is it possible with a module loader like SystemJS/Common/Require?
How I can create a babelified bundle of JSX using BabelBundle class and then use the bundle with ReactSiteConfiguration.Configuration for the SSR?

At the moment I just created a bundle with the single JSX and included the bundle in the html page, while in the ReactSiteConfiguration.Configuration I added as a script no the bundle but directly the lone jsx file that compose the bundle itself.

Thanks a lot and I wish the best for this great project!

**Comment by martinhorvath** [comment]
Hey guys,
did you figure out how to fix the SSR? I am facing the same issue since my last reactjs.net update and even the most simple jsx throws the error. I've created a stackoverflow question a couple of days ago but got no answer there :-/ --> 

[http://stackoverflow.com/questions/40058754/reactjs-net-server-side-rendering-with-client-initialization-throws-warning](http://stackoverflow.com/questions/40058754/reactjs-net-server-side-rendering-with-client-initialization-throws-warning)

Best regards,
Martin

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
