### ISSUE TITLE
Pass javascript as parameter

### ISSUE THREAD

**Issue by ricardopolo** [reactjs/React.NET#303]
In razor we have something like this
````js
@Html.React("Components.Pricing", new
{
    maxEmployees = 10,
})
````

Thats pure razor (c#).
How can we send javascript as parameter?
As example... I would like to send a javascript function as prop to the component I am rendering. Any way?
Thanks @Daniel15

**Comment by Daniel15** [comment]
Use `JRaw` from `Newtonsoft.Json`: http://www.newtonsoft.com/json/help/html/serializerawjson.htm
