### ISSUE TITLE
How to locale string in server side rendering

### ISSUE THREAD

**Issue by ricardopolo** [reactjs/React.NET#304]
If you do this in the client it changes a number to a currency value

``` js
    var grandTotalLocalized = parseInt(grandTotal).toLocaleString('es-CO',  {
      style           : 'currency',
      currency        : 'COP',
      currencyDisplay : 'symbol',
      useGrouping     : true
    });
```

You enter`1000` and it returns `1.000 COP'.
However using server side rendering`1000`returns`1000`. Any advice for getting the localization in the server side @Daniel15 ?

**Comment by Daniel15** [comment]
Hmm, I'm not too sure. Perhaps this functionality is provided by the browser, and "vanilla" V8 (as used by ReactJS.NET) doesn't have it.

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
