### ISSUE TITLE
Add support for ASP.NET Core bundler/minifier if possible

### ISSUE THREAD

**Issue by Daniel15** [reactjs/React.NET#305]
ASP.NET Core seems to ship with a new bundler/minifier out-of-the-box: `BundlerMinifier.Core`:  https://go.microsoft.com/fwlink/?LinkId=808241

**Comment by Daniel15** [comment]
Need to work out if this is actually possible: https://github.com/madskristensen/BundlerMinifier/issues/190

**Comment by ageddesi** [comment]
Has anyone looked into this ? I would really like to use the bundler to compile the jsx files.

**Comment by Daniel15** [comment]
The bundler is very inflexible and it looks like there's no easy way to integrate additional build steps. The old ASP.NET bundler and minifier (from ASP.NET 4.0) was much more flexible.

**Comment by ageddesi** [comment]
Its ok, I am using web.compiler to compile the jsx files and then using BundlerMinifier.Core to bundle them and minify into one file. I am sure this is not the best approach but I am brand new to react and core (been web dev for 7 years) :P so I see how it grows. I hope to be able to contribute to this project one day.

**Comment by dustinsoftware** [comment]
Tracking future work in #655
