### ISSUE TITLE
How do I get current state of ReactSiteConfiguration.Configuration.MaxEngines?

### ISSUE THREAD

**Issue by mwethington** [reactjs/React.NET#307]
Is there an easy way to get the value of the MaxEngines?

Also, what # of MaxEngines are people using? We moved from 50 to 100 and it helped. It is an 8 virtual core box at Amazon: c4.2xlarge.

Very large web site. Concurrent is 30-100 rps.

**Comment by dustinsoftware** [comment]
30-100 requests *per second*? Are all of these requests rendering react components, or does that also include XHR's? Maybe consider adding more nodes if your app is getting overwhelmed. The default is `25` engines, which has worked well for me.

**Comment by mwethington** [comment]
Yes that is per second

Bill Bell
Sent from mobile


On Aug 24, 2016, at 9:52 AM, Dustin Masters <notifications@github.com<mailto:notifications@github.com>> wrote:


30-100 requests per second? Are all of these requests rendering react components, or does that also include XHR's? Maybe consider adding more nodes if your app is getting overwhelmed. The default is 25 engines, which has worked well for me.

-

**Comment by mwethington** [comment]
How do I view number of engines running ? Example code ?



Bill Bell
Sent from mobile


On Aug 24, 2016, at 9:52 AM, Dustin Masters <notifications@github.com<mailto:notifications@github.com>> wrote:


30-100 requests per second? Are all of these requests rendering react components, or does that also include XHR's? Maybe consider adding more nodes if your app is getting overwhelmed. The default is 25 engines, which has worked well for me.

-

**Comment by Daniel15** [comment]
> Is there an easy way to get the value of the MaxEngines?

The MaxEngines as you have it configured is available in `ReactSiteConfiguration.Configuration.MaxEngines`

> How do I view number of engines running ?

The `JsPool` instance used by ReactJS.NET is stored in an instance of `JavaScriptEngineFactory`, but unfortunately it's not exposed publicly. For now, you could use reflection to get the private `_pool` property:
```csharp
var factory = AssemblyRegistration.Container.Resolve<IJavaScriptEngineFactory>();
var poolField = factory.GetType().GetField("_pool", BindingFlags.Instance | BindingFlags.NonPublic);
var pool = (IJsPool)poolField.GetValue(factory);
```

Then you can use the `Engines` property to see how many engines have been created (somewhere between the number created at startup and the max), and `AvailableEngines` to see how many engines are free (ie. currently unused).

**Comment by Daniel15** [comment]
How's ReactJS.NET going for you in production, by the way? I haven't heard from many users with very large deployments!

**Comment by mwethington** [comment]
We had to revert ClearScript.V8 from 5.4.8 to 5.4.5. It was literally crashing IIS on Windows 2012 R2. ClearScript.V8 CPU is more stable than Msie engine, but we are seeing some thread locking even on 5.4.5. We are unsure what causes it, but it looks like JS Pool

**Comment by dustinsoftware** [comment]
I don't know if my deployment counts as very large - the app itself serves 1-3k RPM depending on the day, but a lot of those are requests that ask for JSON. I've been using this project in production for over a year and have been very happy with it.

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
