### ISSUE TITLE
Clarity during ASP.Net Core setup

### ISSUE THREAD

**Issue by Sheng-Long** [reactjs/React.NET#309]
When trying to set this tutorial up, I went to New Project -> ASP.NET Core Web Application (.NET Framework) -> ?.  The template is not specified in the tutorial.  I first tried an empty template.  This template did not include some of the code you talk about in the next step such as:
"Directly above:

// Add framework services.
services.AddMvc();"

I think adding the template you used will add to clarity for this guide.  Adding the line: "New Project -> ASP.NET Core Web Application (.NET Framework) -> Web Application" would clear up a lot.  Once I used "Web Application" instead of empty project, everything seemed to start lining up.

**Comment by Daniel15** [comment]
Thanks for the feedback! I'm going to revamp the tutorial soon, and update it for ASP.NET Core in the process. I do have a full end-to-end tutorial (http://reactjs.net/getting-started/tutorial.html) but it's based off Visual Studio 2013 + ASP.NET MVC 4 so it's a bit outdated now.

**Comment by Sheng-Long** [comment]
Now that I got further into the tutorial, I have been having dependency problems.  Specifically an error message very similar to this: https://github.com/reactjs/React.NET/issues/268.  I'll keep trying different things to get this working, but I'm waiting on baited breath for your new tutorial.

**Comment by Daniel15** [comment]
What's the exact error message you're getting?

**Comment by Sheng-Long** [comment]
NU1002: "The dependency Microsoft.NETCore.App 1.0.0 does not support framework .NETFramework,Version=v4.6.1".  This error is found on line 14 in my project.json file.

**Comment by Sheng-Long** [comment]
I see in your tutorial that you mention ensuring my project does not reference .NetCore.  Is that my problem?  I thought ensuring that my project.json file said "net452 in its frameworks section, not netcoreapp" was what you meant, but must I remove other references as well?  I'm installing VS2013 right now to attempt your other tutorial so I am unable to try removing all references to .NetCore right now.

**Comment by Daniel15** [comment]
Yeah you have to use the "full" .NET Framework rather than .NET Core. Using the "ASP.NET Core Web Application (.NET Framework)" project template should do that, otherwise you can change the frameworks section to use `net452` and remove all references to `Mcrosoft.NETCore.App`. Here's an example `project.json` for an ASP.NET Core site that uses the .NET Framework and ReactJS.NET: https://github.com/Daniel15/Website/blob/master/Daniel15.Web/project.json#L50

**Comment by Sheng-Long** [comment]
Ok, that worked.  However, I am now having a problem with the next part of the tutorial in the next section.

When adding the lines to startup.cs: 
"services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
services.AddReact();"

Visual studios errors occur:  "Error CS0246 - The type or namespace name 'IHttpContextAccessor' could not be found (are you missing a using directive or an assembly reference?) "
and
"Error CS0246 - The type or namespace name 'HttpContextAccessor' could not be found (are you missing a using directive or an assembly reference?)"

Am I missing a reference?

**Comment by Daniel15** [comment]
`HttpContextAccessor` is part of `Microsoft.AspNetCore.Http.Abstractions` which should already be referenced by your app. You might need to add the right `using` statement

```
using Microsoft.AspNetCore.Http.Internal;
```

**Comment by Daniel15** [comment]
Tutorial has been updated for ASP.NET Core, let me know if you still encounter any issues.
