### ISSUE TITLE
Clarity during ASP.NET MVC 4 Tutorial

### ISSUE THREAD

**Issue by Sheng-Long** [reactjs/React.NET#310]
Though these are minor, these small changes could help others, especially newbies like me:

During "Install ReactJS.NET" - from a fresh installation, the nuget.com source is not enabled by default, you could add a small note about this.

During "Your First Component" - After adding the js code, running the code yields no content within the page and the js console shows "ReferenceError: React is not defined."

So far, I am stuck on this step.

**Comment by Sheng-Long** [comment]
For now, my solution was to use the following links instead of the <script src="" links provided:
    <script src="https://npmcdn.com/react@15.3.1/dist/react.js"></script>
    <script src="https://npmcdn.com/react-dom@15.3.1/dist/react-dom.js"></script>

Instead of:

    <script src="https://fb.me/react-15.0.1.js"></script>
    <script src="https://fb.me/react-dom-15.0.1.js"></script>

I don't understand why what I assume to be the npm sources work and the facebook sources don't, but at least the "Hello, world! I am a CommentBox." is now loading.

**Comment by Daniel15** [comment]
Hey @Sheng-Long - What happens if you go to https://fb.me/react-15.0.1.js in your browser? You might be behind a firewall that blocks `fb.me` (sometimes corporate firewalls block access to the Facebook CDN). I might need to update the tutorial and example code to use CDNJS or jsDelivr instead.

> , the nuget.com source is not enabled by default,

What do you mean by this? Was NuGet disabled in Visual Studio? It should be enabled by default.

**Comment by Sheng-Long** [comment]
Ah, you are likely correct.  I am behind a firewall.  Thank you for that insight.

And yes, upon installing VS2013, the only source enabled by default for me was the "Microsoft Offline..." something or other.  I don't see the source anymore, so perhaps it was just a configuration problem after the installation was done.  Thanks for all of your help today Daniel.

**Comment by Daniel15** [comment]
I updated the URLs to use CDNJS instead, and have also updated the tutorial to use ASP.NET Core (I've kept the existing MVC 4/5 tutorial around for reference, though).
