### ISSUE TITLE
BabelBundle leads to Uncaught SyntaxError: Unexpected token import in the browser.

### ISSUE THREAD

**Issue by gunnarsireus** [reactjs/React.NET#311]
Hello.
I'm quite new to React and BabelBundle so there is probably something I have missunderstood. I'm doing bundling with BabelBundle and     
in the view I do:

 @Scripts.Render("~/bundles/react")

Then  I get 
Uncaught SyntaxError: Unexpected token import in the browser.

The JSX filelooks like this: 

import  ChatApp from './components/ChatApp.jsx';
import  ChatExampleData  from './ChatExampleData';
import  ChatWebAPIUtils from './utils/ChatWebAPIUtils';
import React from 'react';
window.React = React; // export for http://fb.me/react-devtools

ChatExampleData.init(); // load example data into localstorage

ChatWebAPIUtils.getAllMessages();

React.render(
    <ChatApp />,
    document.getElementById('react')
);

Can anyone please explain?
Thanks in advance, Gunnar

**Comment by Daniel15** [comment]
Hi @gunnarsireus! At the moment, ReactJS.NET does **not** support JavaScript modules. You can not use `import` statements with ReactJS.NET and instead need to rely on your JavaScript being somewhere in the global scope. Alternatively, you could use something like Webpack, but that's more effort.
