### ISSUE TITLE
Client Only Rendering

### ISSUE THREAD

**Issue by ricardopolo** [reactjs/React.NET#312]
We are doing server side rendering

However fur our devs that is sooooo slock while compiles the bundle.
So, any way to do Client only rendering as parameter of @Html.React()?

That means server wont take time compiling the JSX, just send the autogenereated div with the model and when calling  `@Html.ReactInitJavaScript()` the component will be render.

I know that is not optimal but could be much faster during development.

**Comment by jslatts** [comment]
There is a clientOnly flag, but that won't save you the initial JSX compiling. We use browserify (or webpack) to incremental JS compiling outside of React.NET which makes the development loop much quicker. It also gives us much more control over the process.

**Comment by ricardopolo** [comment]
We also have webpack.

And we put that webpack compiled script into a bundle.
````
bundles.Add(new ScriptBundle("~/Bundles/React").Include("~/webpackBundle.js"));
````

 I dont know if the slowness is causes by the bundle creation...

**Comment by ricardopolo** [comment]
@jslatts We also have webpack.

And we put that webpack compiled script into a bundle.
````
bundles.Add(new ScriptBundle("~/Bundles/React").Include("~/webpackBundle.js"));
````

 I dont know if the slowness is causes by the bundle creation...

**Comment by jslatts** [comment]
@ricardopolo We don't use the asp.net bundles at all since we do our own minification using browserify. You can add your compiled code to react without transformation. This is our ReactConfig.cs:

    ReactSiteConfiguration.Configuration.AddScriptWithoutTransform("~/wwwroot/js/server.bundle.js");
    ReactSiteConfiguration.Configuration.AddScriptWithoutTransform("~/wwwroot/js/core.bundle.js");

    // Don't use slower IE engine
    ReactSiteConfiguration.Configuration.AllowMsieEngine = false;

    // Don't use built in babel
    ReactSiteConfiguration.Configuration.LoadBabel = false;

    // Don't use built in react
    ReactSiteConfiguration.Configuration.LoadReact = false;
                
We just reference the code directly in our master layout via a script tag:

    <script src="@Url.Content("~/wwwroot/js/vendor.bundle.js")"></script>
    <script src="@Url.Content("~/wwwroot/js/core.bundle.js")"></script>

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
