### ISSUE TITLE
New ClearScript V8

### ISSUE THREAD

**Issue by mwethington** [reactjs/React.NET#314]
Can we get the new clearscript V8 integrated ? There is a new version.

**Comment by Daniel15** [comment]
Hi @mwethington! The version of V8 that ReactJS.NET uses is controlled by JavaScriptEngineSwitcher (https://github.com/Taritsyn/JavaScriptEngineSwitcher). To upgrade the version of V8 or ClearScript, you'll need to ask the developer of JavaScriptEngineSwitcher :smile:
