### ISSUE TITLE
Updating JavaScriptEngineSwitcher to latest 2.0.0 breaks Babel bundles

### ISSUE THREAD

**Issue by badiuoanaalexandra** [reactjs/React.NET#319]
I am using System.Web.Optimization.React to minify my jsx files. I just ugraded JavaScriptEngineSwitcher packages to 2.0.0 and now the bundles don't work anymore. 

[MissingMethodException: Method not found: 'JavaScriptEngineSwitcher.Core.JsEngineSwitcher JavaScriptEngineSwitcher.Core.JsEngineSwitcher.get_Current()'.]
   JSPool.JsPoolConfig..ctor() +0
   React.JavaScriptEngineFactory.CreatePool() +146
   React.JavaScriptEngineFactory..ctor(IEnumerable`1 availableFactories, IReactSiteConfiguration config, IFileSystem fileSystem) +109
   lambda_method(Closure , Object[] ) +112
   React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) +682

[TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory]
   React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) +717
   React.TinyIoC.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options) +122
   React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) +85
   React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) +386

[TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment]

**Comment by Daniel15** [comment]
ReactJS.NET does not yet support JavaScriptEngineSwitcher 2.0. The API has breaking changes, so you'll have to wait for #306 to be closed and a new major version of ReactJS.NET to be pushed before upgrading. I'm currently working on that so it should be available soon.
