### ISSUE TITLE
React cilent-side scripts directly from server?

### ISSUE THREAD

**Issue by NuclearFishin** [reactjs/React.NET#320]
Hi React.NET team,

Firstly, thanks very much for developing this great library. The JSX compilation a fantastic feature and I'm using it extensively on my website.

Secondly, apologies if this is more of a question than an issue, but I did some honest Googling and couldn't find any links to forums etc, so here goes!

Yesterday I came across an issue whereby some organisations have blocked Facebook in their workplaces, so the React client-side scripts failed to load from `fb.me`:

```
<script src="https://fb.me/react-15.0.1.js"></script>
<script src="https://fb.me/react-dom-15.0.1.js"></script>
```

I've resolved the issue by switching to `unpkg.com`, but I was wondering if it's possible to serve the React scripts directly from the server using the same scripts referenced by the server-side compilation feature? Serving these scripts would also ensure there is always parity between server-side and client-side behaviour should the React scripts change.

Thanks again for the great work with React.NET!

**Comment by Daniel15** [comment]
Hi @NuclearFishin! You could load React from CDNJS instead, if you like.

>  serve the React scripts directly from the server using the same scripts referenced by the server-side compilation feature

This is tricky. The scripts used for server-side compilation are stored as embedded resources in the `React.Core.dll` assembly. Serving them would mean there'd have to be a controller that loads the resource and serves it. A controller to do that could be added, but it's easier to just have a copy of React in your project and reference that directly (or use CDNJS).

I'm going to close this issue since it's a question, but feel free to ask if you have any other questions.

**Comment by NuclearFishin** [comment]
Thanks @Daniel15 for your quick response! I went for `unpkg.com` because it's the source used in the [React getting started guide](https://facebook.github.io/react/docs/getting-started.html), but yes CDNJS would work just as fine!

Indeed my requirement for loading server-side may be too esoteric for inclusion in the main libraries, but I am thinking that some kind of mechanism for maintaining parity with my server-side scripts would be a useful feature? The use-case I'm thinking of is that I update my React.NET Nuget packages, and now the server-side React scripts would be out of sync with my client-side ones.

A very minimal way to address this concern would be to expose a property detailing the React version used by the server-side? Then consumers like me could use that in our script references, such as:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/react/@(reactVersion)/react.min.js"></script>`

What do you think? Does such a property exist?
