### ISSUE TITLE
JSX Compilation Failure w/ Cassette

### ISSUE THREAD

**Issue by agscala** [reactjs/React.NET#325]
I'm switching my project over to use Cassette to manage static content. I need JSX support, but when it tries to compile a file it fails pretty hard.

```
var FAQComponent = React.createClass({
    mixins: [],

    getInitialState() {
        return {
            categories: [],
            selectedCategories: ["All"],
            faqs: [],
        };
    },

    componentDidMount() {
    }
   // more code cut for brevity //

});
```

Here's the entirety of the compiled output.  It only output a bit of the final compilation, and the stuff that it did output really makes no sense. 

```
return FAQComponent=React.createClass({mixins:[],getInitialState:}),{categories:[],selectedCategories:["All"],faqs:[]};var categories
```

I was using Web Compiler previously, and it compiles the file with no issue.

Any ideas?

**Comment by Daniel15** [comment]
Huh, that's strange. What if you remove the JSX in your test file and *only* use plain JavaScript? What does the output look like in that case?

**Comment by agscala** [comment]
I'm not sure what you're asking for. Do you want me to remove all the JSX tags and ES6 also? In that case I wouldn't need to compile anything

**Comment by Daniel15** [comment]
>  Do you want me to remove all the JSX tags and ES6 also?

Yeah, just to test it out. What I mean is keep the configuration as-is, but remove all JSX from the file, and see if it still happens. I'm wondering if the issue is specific to JSX, or if it happens with all the Cassette bundles even if they don't contain JSX.

**Comment by Daniel15** [comment]
Closing this out as it's stale.
