### ISSUE TITLE
Considering adding model/form validation to tutorial (server-side DataAnnotations + client-side JS)

### ISSUE THREAD

**Issue by antmdvs** [reactjs/React.NET#333]
I couldn't find a recipe (or proposal) yet for serializing a model's DataAnnotation Validation attributes (`[Required]`, `[MaxLength]`, `[Compare]`, etc.) so that they can ultimately be applied client-side. I'm not sure how this would be accomplished. Have there been any discussions on this?

**Comment by Daniel15** [comment]
Good question... Maybe they could be serialized as props on the component, or something like that. I'm not sure what the best approach would be.

**Comment by ageddesi** [comment]
For me this is the final piece for forms :) I would like to input on this as well as I can see the option of adding them as props...

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
