### ISSUE TITLE
Can't add attributes to `ReactInitJavaScript` script tag

### ISSUE THREAD

**Issue by wub** [reactjs/React.NET#334]
We'd like to be able to add extra attributes to the `ReactInitJavaScript` tag:

*Current output:*
`<script>ReactStuff()</script>`

*Possible desired output:*
`<script async foo="bar" nonce="Fo0/B4r">ReactStuff()</script>`

If it's a simple case of adding another parameter to the helper, and adding more to the TagBuilder, I'm happy to take a stab at this.

**Comment by Daniel15** [comment]
What's an example of attributes you'd like to add, and for what purpose?

**Comment by wub** [comment]
Hey @Daniel15, I managed to just reuse some code from inside ReactInitJavaScript and made my own helper. I'll  post it here tomorrow when I'm back at work.

I needed to add both "async" and "nonce" (we're slowly moving to CSP).

Cheers!

**Comment by Daniel15** [comment]
I could be wrong, but I don't think "async" would make a difference since it's an inline script.

**Comment by wub** [comment]
You are not wrong :0)
