### ISSUE TITLE
 React.AspNet 3.0.0 is not compatible with netcoreapp1.0 

### ISSUE THREAD

**Issue by DanielDziubecki** [reactjs/React.NET#337]
Hello, I get this error when im trying to install React.NET to my project.

>  Package React.AspNet 3.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0).

How to fix that ? I thought .NET Core is supported.

**Comment by Daniel15** [comment]
Hmm this is strange! I can't replicate the issue. When I create a brand new .NET Core site in Visual Studio 2015, I can add `React.AspNet` with no problems.

Are you trying this on a new site, or an existing one? Could you please provide your `project.json`? Alsom, could you please ensure you have the latest updates installed for Visual Studio 2015?

**Comment by DanielDziubecki** [comment]
I solved this by downloading newest .Net Core. But  sometimes I get this exception

> An unhandled exception of type 'System.AccessViolationException' occurred in System.Private.CoreLib.ni.dll

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

I have followed your instructions about it. I paste this `"copyToOutput": {
      "include": [
        "ClearScript.V8"
      ]
    }` 
to my project.json and then I copied ClearScript.V8 dlls folder to my application. After build there is ClearScript.V8 folder in my bin. But like I sad sometimes I get this error again. Specially in debug mode.

**Comment by Taritsyn** [comment]
> I have followed your instructions about it. I have pasted this `"copyToOutput": { "include": [ "ClearScript.V8" ] }`
> to my project.json and then I copied ClearScript.V8 dlls folder to my application. After build there is ClearScript.V8 folder in my bin. But like I sad sometimes I get this error again. Specially in debug mode.

@DanielDziubecki In ReactJS.NET 3.0.0 and JavaScript Engine Switcher 2.X no longer need to do this.

**Comment by rahamohebbi** [comment]
I am also getting this error:

An unhandled exception of type 'System.AccessViolationException' occurred in System.Private.CoreLib.ni.dll
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

I tried to add this in my startup.cs but it didn't fix the problem:

            JsEngineSwitcher engineSwitcher = JsEngineSwitcher.Instance;
            engineSwitcher.EngineFactories
            .AddChakraCore()
            .AddMsie(new MsieSettings() { EngineMode = JsEngineMode.Auto });

Any ideas ?

**Comment by dustinsoftware** [comment]
This should be working with .NET Core 2.1
