### ISSUE TITLE
How can I render the react app with redux using the React.JS.NET?

### ISSUE THREAD

**Issue by Jenan** [reactjs/React.NET#339]
Hello,

I have a SPA where I've used the React and Redux, React-Router.

I want to render this SPA application which is compiled as one bundle.js using React.JS.NET.

How can I do that? I can't find any project where is solved this combination of the libraries.

Thank you for help/example.

**Comment by Jenan** [comment]
https://stackoverflow.com/questions/40238903/how-can-i-render-the-react-app-with-redux-using-the-reactjs-net

**Comment by Daniel15** [comment]
There's now a `React.Router` package available that should help with using React-Router. Unfortunately I don't think there's any docs yet.
