### ISSUE TITLE
Html.ReactInitJavaScript() outputs server only components in initialization code

### ISSUE THREAD

**Issue by heinzmuller** [reactjs/React.NET#340]
Using `@Html.React("Component", ..., serverOnly: true)` still adds the `ReactDOM.render()` calls to the `@Html.ReactInitJavaScript()` output which breaks pages using server only components. (It also wraps the output in an unnecessary container element)

Looking through the code there seems to be missing a bool in the ReactEnvironment `CreateComponent` method that sets the component to be server only and thus skipped when outputting the init code for all components

**Comment by scokmen** [comment]
I encountered the same problem. The parameter **serverOnly** don't work.

**Comment by heinzmuller** [comment]
I don't think this would be that difficult to "fix", but it would be nice to know if this is indeed a bug/problem or if I have misunderstood the parameter before I attempt to fix it with a PR

**Comment by heinzmuller** [comment]
Any input on this @Daniel15 ?

**Comment by Daniel15** [comment]
Interesting, this does sound like a bug to me. Feel free to submit a pull request if you like 😃

**Comment by DaniilSokolyuk** [comment]
+1, parameter serverOnly don't work.
append hydrate to ReactInitJavaScript
