### ISSUE TITLE
"BYO React" page no longer exists

### ISSUE THREAD

**Issue by wub** [reactjs/React.NET#341]
When I tried to load my own React, I got this error:

```
React has not been loaded correctly.
Please expose your version of React as global variables named 'React', 'ReactDOM' and 'ReactDOMServer', or enable the 'LoadReact' configuration option to use the built-in version of React.
See http://reactjs.net/guides/byo-react.html for more information.
```

I ended up loading the built-in version, but I'm more concerned that the documentation no longer exists to fix it (at this URL at least!)

https://github.com/reactjs/React.NET/blob/e12020b1f99f99d71f22a92401a2e23913e891bc/src/React.Core/JavaScriptEngineFactory.cs#L185

**Comment by Daniel15** [comment]
Oops, I don't think I ever actually wrote the documentation! I think that was just a placeholder URL 😛

**Comment by szarouski** [comment]
@Daniel15 I can customize react version by applying changes like shown here (webpack file):
https://github.com/reactjs/React.NET/commit/27df77f84f2ea95994452b82f0d55c48493ba2df

My only problem is that things don't work when I set .SetLoadReact(false), but without it I can see custom version of react. Do you think there might be any concerns regarding not using `.SetLoadReact(false)`?

Thank you.

**Comment by wub** [comment]
https://github.com/reactjs/React.NET/pull/454 🤙
