### ISSUE TITLE
Working with static files middleware.

### ISSUE THREAD

**Issue by DanielDziubecki** [reactjs/React.NET#347]
Hello. I had a problem with my wwwroot folder in my app. I post a question on stackoverflow http://stackoverflow.com/questions/40451245/how-to-specify-routing-for-wwwroot-resources-in-net-core?noredirect=1#comment68147994_40451245
It works fine but when I put my .jsx files to this static files resource React.NET doesnt compile this on the fly.
Of course I get this error in my web browser which is fully understandable because jsx wasn't compiled.

> Uncaught SyntaxError: Unexpected token <

So there is any work around ?

**Comment by Daniel15** [comment]
> So there is any work around ?

Make sure you call `app.UseReact` **above** `app.UseStaticFiles`, so the ReactJS.NET middleware is executed **before** the regular static file middleware.

**Comment by Daniel15** [comment]
Going to close this out for now, but feel free to reopen this issue if you still encounter problems
