### ISSUE TITLE
ReactDemo doesnt add new items to the commentList

### ISSUE THREAD

**Issue by pepepaco** [reactjs/React.NET#349]
I created a new proyect, followed tutorial step by stem it didnt work , then downloaded the demo code, didnt work oob had to copy everything to a new project but it didnt work items added using the button dont get listed, the mvc AddComment action is not even called from the client side, anyone having the same issue?

thanks.

**Comment by pepepaco** [comment]
yes thats exactly whats happening, how do I fix it? should I remove Remarkable completely? 

thanks!

**Comment by pepepaco** [comment]
any clue why the demos dont work? I need an example how to add third party js into the project,  thanks

**Comment by chriscamplejohn** [comment]
I have a fix for this. I will create a PR. Add an additional function in tutorial.jsx

`function createRemarkable() {
    var remarkable = (("undefined" != typeof global) && (global.Remarkable)) ? global.Remarkable : window.Remarkable;    return new remarkable();
}`

then use that to create the instance e.g.

`var md = createRemarkable();
var rawMarkup = md.render(this.props.children.toString());`

**Comment by pepepaco** [comment]
great! is working now, thank you.
