### ISSUE TITLE
Build VroomJs natives for Mono

### ISSUE THREAD

**Issue by skaryshev** [reactjs/React.NET#370]
I am trying to build VroomJs library for Mono following a build script published on https://reactjs.net/guides/mono.html on Ubuntu 16.04.
"make dependencies" step for V8 build encounters an error:

`vbx:/usr/local/src/v8-3.17$ sudo make dependencies`
`svn checkout --force http://gyp.googlecode.com/svn/trunk build/gyp \`
`    --revision 1501`
`svn: E170013: Unable to connect to a repository at URL 'http://gyp.googlecode.com/svn/trunk'`
`svn: E160013: '/svn/trunk' path not found`
`Makefile:301: recipe for target 'dependencies' failed`
`make: *** [dependencies] Error 1`

It looks like Google archived some repositories older V8 builds depend on.

**Comment by Daniel15** [comment]
Try using ChakraCore (just install the package) rather than VroomJs and see if that works.

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
