### ISSUE TITLE
ReactJS.NET Core 3.0 with Newtonsoft.Json (8.0.3)

### ISSUE THREAD

**Issue by ashkansiroos** [reactjs/React.NET#371]
Hi
I have a problem using reactjs.net. One of the nuget packages that I use need to work with Newtonsoft.Json (< 9.0.0) and ReactJS.NET Core 3.0  needs Newtonsoft.Json (>= 9.0.1) which is the latest version. Isn't it possible to work with Newtonsoft.Json (8.0.3) ?

**Comment by dustinsoftware** [comment]
Can you use an assembly binding redirect to work around your issue?

http://blog.rytmis.net/2016/03/29/asp-net-core-and-assembly-binding-redirects/

**Comment by Daniel15** [comment]
Yeah an assembly binding should help here, as @dustinsoftware pointed out. Otherwise, get the developer of the other NuGet package to upgrade their Newtonsoft.Json reference. I think older versions of Newtonsoft.Json don't support ASP.NET Core properly.

**Comment by ashkansiroos** [comment]
Thanks :)
