### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by DanielDziubecki** [reactjs/React.NET#373]
> import ImageGallery from 'react-image-gallery';

I have problem with this keyword in my jsx. How to solve that? Iam using .NET 4.6 and React.NET 3.0 
Same with require keyword. 

> ReferenceError: require is not defined

**Comment by dustinsoftware** [comment]
Are you using a module bundler, such as webpack? You'll need to reference the bundled JS.

**Comment by DanielDziubecki** [comment]
I have referenced my bundled JS. My other components working well but now I need to import one.

**Comment by dustinsoftware** [comment]
Import is new syntax, try using require instead. You can also add babel to
webpack if you want to use ES2015 features.

**Comment by DanielDziubecki** [comment]
But requrie doesnt work either. Is React.NET not using babel ?

**Comment by Daniel15** [comment]
ReactJS.NET does not support modules at this point in time. It was originally built at a time when JS modules were very very rarely used. Happy to accept pull request adding support, but it's non-trivial. 

Right now you need to use something like Webpack or Browserify if you want to use JS modules.

**Comment by starwed** [comment]
>Right now you need to use something like Webpack or Browserify if you want to use JS modules.

Since they're in common use now, perhaps a quick note about this should be added to the docs/readme?

**Comment by matthew-a-thomas** [comment]
> perhaps a quick note about this should be added to the docs/readme?

Documentation would be great to have. Any pointers?

**Comment by dustinsoftware** [comment]
Yep! Those docs should be up to date.

**Comment by devgibsonsp** [comment]
I think it would be a lot easier for novices like myself if the webpack documentation was implemented somewhere so that people like me can actually understand how it is being used in a .net application. Currently that documentation is very confusing for someone unfamiliar with the technology.
