### ISSUE TITLE
Error using server-side rendering

### ISSUE THREAD

**Issue by kuebelkasten** [reactjs/React.NET#374]
As it can be read in this SO-thread [here](http://stackoverflow.com/questions/42209440/server-side-rendering-of-component-fails-using-reactjs-net) I'm trying to get server-side rendering to work using TypeScript.

I guess it may be related to the final javascript-file that is emitted via tsc & webpack but I really don't get a point to start from. 
Any help, idea, point to start from would be greatly appreciated.

**Comment by dustinsoftware** [comment]
You'll need to use `ts-loader` with `webpack` to get typescript to work. https://reactjs.net/bundling/webpack.html
