### ISSUE TITLE
Can't resolve references of tutorial-code

### ISSUE THREAD

**Issue by MarioAraya** [reactjs/React.NET#375]
After downloading the tutorial project, and compiling it, Visual Studio 2015 couldn't resolve the dependencies specified in project.json

![clipboard02](https://cloud.githubusercontent.com/assets/1564554/22986119/4778724a-f389-11e6-9c90-d54351de986b.jpg)

**Comment by lilwayne470** [comment]
Havin the same issue, can someone help us.

**Comment by Daniel15** [comment]
Hmm that's strange, it definitely worked when I built the example. Maybe some of the version numbers are wrong. I'll try to take a look when I get a chance.

What you can do is create a new ASP.NET Core MVC project and compare the project.json files.

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.

The tutorial project restores successfully for me, it's possible we fixed this issue when updating to .NET Core 2.0
