### ISSUE TITLE
dev-build.bat fails with "target Restore does not exist"

### ISSUE THREAD

**Issue by WilkaH** [reactjs/React.NET#377]
After cloning the repo, on branch `master` (at 5892e51a57038ae1b829d0de79974ca6) I ran `dev-build.bat` and got

```Microsoft (R) Build Engine version 14.0.25420.1                                                                            
Copyright (C) Microsoft Corporation. All rights reserved.                                                                  
                                                                                                                           
Build started 21/02/2017 17:22:28.                                                                                         
Project "C:\Dev\3rdParty\React.NET\build.proj" on node 1 (default targets).                                                
RestorePackages:                                                                                                           
  dotnet restore                                                                                                           
C:\Dev\3rdParty\React.NET\build.proj : error MSB4057: The target "Restore" does not exist in the project.                  
C:\Dev\3rdParty\React.NET\build.proj(38,3): error MSB3073: The command "dotnet restore" exited with code 1.                
Done Building Project "C:\Dev\3rdParty\React.NET\build.proj" (default targets) -- FAILED.                                  

                                                                                             
Build FAILED.                                                                                                              

"C:\Dev\3rdParty\React.NET\build.proj" (default target) (1) ->                                                             
(RestorePackages target) ->                                                                                                
  C:\Dev\3rdParty\React.NET\build.proj : error MSB4057: The target "Restore" does not exist in the project.                
  C:\Dev\3rdParty\React.NET\build.proj(38,3): error MSB3073: The command "dotnet restore" exited with code 1.              

    0 Warning(s)
    2 Error(s)
```

I tried turning diagnostics output for MSBuild, which gives a bit more info  

<details>
  <summary>diagnostics  MSBuild output</summary>
Building with tools version "14.0".                                                                                                                    
Project file contains ToolsVersion="4.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appr 
opriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had Tools 
Version="14.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=293424.                                                        
Target "Clean: (TargetId:2)" in project "C:\Dev\3rdParty\React.NET\build.proj" (target "RestorePackages" depends on it):                               
Using "DeleteTree" task from assembly "C:\Dev\3rdParty\React.NET\tools\MSBuildTasks\MSBuild.Community.Tasks.dll".                                      
Task "DeleteTree" (TaskId:2)                                                                                                                           
  Task Parameter:Directories=src/artifacts (TaskId:2)                                                                                                  
Done executing task "DeleteTree". (TaskId:2)                                                                                                           
Task "DeleteTree" (TaskId:3)                                                                                                                           
  Task Parameter:Directories=src/Cassette.React/bin (TaskId:3)                                                                                         
Done executing task "DeleteTree". (TaskId:3)                                                                                                           
Task "DeleteTree" (TaskId:4)                                                                                                                           
  Task Parameter:Directories=src/React.AspNet/bin (TaskId:4)                                                                                           
Done executing task "DeleteTree". (TaskId:4)                                                                                                           
Task "DeleteTree" (TaskId:5)                                                                                                                           
  Task Parameter:Directories=src/React.Core/bin (TaskId:5)                                                                                             
Done executing task "DeleteTree". (TaskId:5)                                                                                                           
Task "DeleteTree" (TaskId:6)                                                                                                                           
  Task Parameter:Directories=src/React.MSBuild/bin (TaskId:6)                                                                                          
Done executing task "DeleteTree". (TaskId:6)                                                                                                           
Task "DeleteTree" (TaskId:7)                                                                                                                           
  Task Parameter:Directories=src/React.Owin/bin (TaskId:7)                                                                                             
Done executing task "DeleteTree". (TaskId:7)                                                                                                           
Task "DeleteTree" (TaskId:8)                                                                                                                           
  Task Parameter:Directories=src/React.Web/bin (TaskId:8)                                                                                              
Done executing task "DeleteTree". (TaskId:8)                                                                                                           
Task "DeleteTree" (TaskId:9)                                                                                                                           
  Task Parameter:Directories=src/React.Web.Mvc4/bin (TaskId:9)                                                                                         
Done executing task "DeleteTree". (TaskId:9)                                                                                                           
Task "DeleteTree" (TaskId:10)                                                                                                                          
  Task Parameter:Directories=src/System.Web.Optimization.React/bin (TaskId:10)                                                                         
Done executing task "DeleteTree". (TaskId:10)                                                                                                          
Done building target "Clean" in project "build.proj".: (TargetId:2)                                                                                    
Target "RestorePackages: (TargetId:3)" in project "C:\Dev\3rdParty\React.NET\build.proj" (target "Build" depends on it):                               
Using "Exec" task from assembly "Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".                      
Task "Exec" (TaskId:11)                                                                                                                                
  Task Parameter:WorkingDirectory=C:\Dev\3rdParty\React.NET (TaskId:11)                                                                                
  Task Parameter:Command=dotnet restore (TaskId:11)                                                                                                    
  dotnet restore (TaskId:11)                                                                                                                           
C:\Dev\3rdParty\React.NET\build.proj : error MSB4057: The target "Restore" does not exist in the project.                                              
C:\Dev\3rdParty\React.NET\build.proj(38,3): error MSB3073: The command "dotnet restore" exited with code 1.                                            
Done executing task "Exec" -- FAILED. (TaskId:11)                                                                                                      
Done building target "RestorePackages" in project "build.proj" -- FAILED.: (TargetId:3)                                                                
Done Building Project "C:\Dev\3rdParty\React.NET\build.proj" (default targets) -- FAILED.
</details>

**Comment by yamachu** [comment]
Maybe your dotnet core cli tools version is 1.0.0-rc4-004616 or after.
1.0.0-rc4-004616 or after use msbuild with .cproj as build system, but React.NET use project.json and .xproj .
As you can see this repo's [global.json](https://github.com/reactjs/React.NET/blob/master/global.json) is pinning .net core sdk version to 1.0.0-preview2-003121 

So I think you should install older dotnet core cli and deactivating newer one for complete build task.

**Comment by WilkaH** [comment]
Ah, yes. That's the issue. I'm using RC4 of donet core cli tools.

**Comment by Daniel15** [comment]
Good catch, I'll need to upgrade ReactJS.NET to the latest version of the dotnet tooling.
