### ISSUE TITLE
NU1001 The dependency System.Data.Common >= 4.3.0 couldn't be resolved

### ISSUE THREAD

**Issue by Mythreyeehr** [reactjs/React.NET#380]
## Steps to reproduce
1.Create a new .Net Core class lib project. Edit the frameworks node of project.json file to target .net 4.5.1(This is done to be able to add reference of other dlls built on .net framework 4.5)
2. Try to install System.Data.Common nuget package
## Expected  behavior
- Sussess result in Output window/Pakage manager console and reference is added

## Actual behavior
- Sussess result in Output window/Pakage manager console but error messsage on the reference added, NU1001 The dependency System.Data.Common >= 4.3.0 couldn't be resolved

## Environment data
`dotnet core --info` output:

**Comment by Daniel15** [comment]
I don't think this is related to ReactJS.NET... Maybe you should open this in Microsoft's bug tracker instead?

**Comment by Mythreyeehr** [comment]
No it is not. Sorry to post it here. A wrong forum
