### ISSUE TITLE
Is React.NET ready for production in Enterprise Applications?

### ISSUE THREAD

**Issue by prajwal78** [reactjs/React.NET#382]

**Comment by jslatts** [comment]
My company makes a product that utilizes React.NET heavily and we sell to enterprises, so I would say yes.

**Comment by prajwal78** [comment]
How can you convince me?

**Comment by jslatts** [comment]
I'm afraid all I can offer is my own opinion based on my experience. I would also mention that you don't actually need React.NET to use react with a .NET web application, especially if you don't need server side rendering.

**Comment by prajwal78** [comment]
I am going to use React.NET. Can you provide/suggest me the sample folder architecture you have implemented?

**Comment by joalcava** [comment]
I feel the project is abondoned or receives very little maintenance. However is just my impresión.

**Comment by Daniel15** [comment]
> I feel the project is abondoned or receives very little maintenance

I'm the only developer on ReactJS.NET... I'm still around, I'm just not as active these days. I'm still happy to accept pull requests though.

**Comment by joalcava** [comment]
I'm glad to hear that the project is active, I think I'm not at the level but I'll try to help. For me this is a great project.

**Comment by jslatts** [comment]
Honestly, other than updating things as new versions of .NET are released, ReactJS.NET feels pretty feature complete to me. It just does what it is supposed to do and I rarely have to think about it.

**Comment by wub** [comment]
FWIW, we use React.NET at [StarNow](https://www.starnow.com), on every page, for millions of members.

**Comment by mashaal** [comment]
We are using React.NET on [Mazda AU](https://www.mazda.com.au) 🐨

**Comment by RichardWright** [comment]
With the performance of .net core becoming popularised, a high performance react rendering library I think could get popular. 

Is this library good enough or it 'blazing'?

**Comment by dustinsoftware** [comment]
The server render and Babel support is pretty stable at this point. We should probably update the docs so they don’t say “experimental” anymore.  I’ve also used library in a production application for a couple years now and it’s been great. 

.NET core now ships with server render support for React (SpaServices) so if you need an alternate lib, that is available.
