### ISSUE TITLE
Server rendered components break in IE 9, 10 and 11

### ISSUE THREAD

**Issue by dylandupreez** [reactjs/React.NET#385]
Hi, I cannot get our server rendered components to work in any version of IE. They work perfectly in all other browsers (including Edge). The issue comes from the ReactDom.render scripts that are rendered by the Html.ReactInitJavascript helper method. The error is an invariant violation: "HomePageAutoComplete.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object." I have stepped though the code and it is breaking deep in the bowels of react. This doesn't happen if I render the exact same component client side, even in IE. The component listed here is just the first one on the page. This happens on all React components that are server rendered. They do all return valid react components all the time. Since they are server side rendered they do appear fine they just don't have any client functionality, which is crucial in most cases

**Comment by dylandupreez** [comment]
I've managed to fix this by hacking the generated script. I started by getting the string generated. Extracting the actual script. Removing the ReactDOM.render and React.createClass methods. Then using the remaining, code I found the elements that were contained the server rendered components, emptied them and the client rendered the elements again. Dirty hack I know, but it solves the problem. See code snippet below:

`import React from "react";
import ReactDOM from "react-dom";
import { assign } from "lodash";

declare var initScript: string;

document.addEventListener("DOMContentLoaded", (e) => {
    cleanScript(initScript);
});


const cleanScript = (escapedScript:string) => {
    let cleanedScript = escapedScript.replace(/&lt;\/?script&gt;/g, '');
    cleanedScript = cleanedScript.replace(/ReactDOM.render\(/g, "");
    cleanedScript = cleanedScript.replace(/React.createElement\(/g, "");
    cleanedScript = cleanedScript.replace(/\),/g, ",");
    cleanedScript = cleanedScript.replace(/\)\)/g, ")");
    cleanedScript = cleanedScript.replace(/&quot;/g, "\"");
    cleanedScript = cleanedScript.replace(/;$/, "");
    let componentStrings = cleanedScript.split(";");
    componentStrings.forEach(string => {
        let scriptParts = string.split(", ");
        reRenderReactComponent(scriptParts);
    })
}

const reRenderReactComponent = (scriptParts: Array<string>) => {
    const component = eval(scriptParts[0]);
    const props = JSON.parse(scriptParts[1]);
    const element = eval(scriptParts[2]) as HTMLElement;
    console.log(component);
    element.innerHTML = "";
    ReactDOM.render(React.createElement(component, assign({},props), null), element);
}`

**Comment by gunnim** [comment]
I can confirm that React.NET works with at least IE 10.
Are you sure the problem you are facing does not have to do with ES6 support in the IE browsers?
Are you using babel and/or webpack in your build process?

**Comment by Daniel15** [comment]
Hmmm that's strange. I'm not too sure what could be causing this 😕 

If you like, you could compile ReactJS.NET from source and see if you can tweak the code to get it working?

> Are you using babel and/or webpack in your build process?

ReactJS.NET runs Babel for you, so it shouldn't be an issue.

**Comment by dylandupreez** [comment]
Hi, yes it is strange. We are using Babel and Webpack, however it seems unlikely that it is related since all the same components work fine when client side rendered in IE. As I mentioned I have found a way to get it working, albeit in a very hackey way, and the project goes live tomorrow so that'll have to do for now. I will fork the repo and try figure out what is causing this. 

One thing I'm not sure about is whether I need to include the IE rendering engine in the server side config since I am only using the V8 engine. Could this be the issue? If so does the server rendering engine figure when to use this renderer or will it always use that instead of V8?

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
