### ISSUE TITLE
Poor exception handling in JavaScriptEngineFactory

### ISSUE THREAD

**Issue by chaoaretasty** [reactjs/React.NET#386]
I've been struggling with getting React.NET working on deployment but the thing that caused the greatest problem was the exception being raised by `JavaScriptEngineFactory`.

`GetFactory` swallows the actual exceptions and replaces it was unhelpful ones based on environment. This makes assumptions on configuration and makes it much harder to actually try and debug the situation. (getting an exception talking about assumed problems with ClearScript when I've used JavaScriptEngineSwitcher to only use ChakraCore for example).

The information in these exceptions should be moved to documentation where you also have more space to go into details on solving it and the exceptions here replaced with an aggregate exception so that the proper exceptions can be logged.

**Comment by Daniel15** [comment]
I'm happy to take a pull request improving this if you like.

**Comment by dustinsoftware** [comment]
We recently made some changes for how JS engines are registered in 4.0 and updated the docs. Please re-open this issue if you still need help.
