### ISSUE TITLE
Please move the middleware-related classes into a separate nuget package

### ISSUE THREAD

**Issue by dima117** [reactjs/React.NET#388]
Hi
I need to use the react middleware in the console application to convert JSX files on-the-fly. But I do not need to use ASP.NET MVC (and I hurt because ASP.NET MVC packages are in the dependency list of my project). Could you move the middleware-related classes into a separate nuget package?

**Comment by Daniel15** [comment]
Interesting idea. I could move the MVC classes into a new `React.AspNet.Mvc` package, and change `React.AspNet` to just contain the middleware. What do you think?

**Comment by dima117** [comment]
Yes, it sounds reasonable. Also should keeping in mind that this will be a breaking change for the current users of the `React.AspNet` package.

**Comment by Daniel15** [comment]
This is included in the 3.1 release: https://reactjs.net/2017/07/3.1.0-release.html. You can now install `React.AspNet.Middleware` to just get the middleware.
