### ISSUE TITLE
Preact?

### ISSUE THREAD

**Issue by wub** [reactjs/React.NET#389]
Would it be helpful/feasible to add an option to allow [Preact](https://preactjs.com/) as a renderer? Preact is almost 100% compatible with the React API.

[preact-redux-isomorphic](https://github.com/BerndWessels/preact-redux-isomorphic) may have some ideas - I'll check it out.

Would this be better suited as a completely different project? It would be a shame to waste all the work done on managing JS engines, etc.

I'm happy to work on this.

**Comment by Daniel15** [comment]
I won't work on that, but feel free to send some pull requests if you're interested 😃
