### ISSUE TITLE
V8 JavaScriptEngine is not work for my solution(VS2013 64bit)

### ISSUE THREAD

**Issue by billschen** [reactjs/React.NET#390]
@Daniel15 
I'm use this project  ,my dev envirement is Win 10 +vs 2013 64 bit .I created a asp.mvc project base on .NET 4.5. the install React.NET by  Install-Package React.Web ,It work fine.
but when add code `ReactSiteConfiguration.Configuration.SetAllowMsieEngine(false);`
the project become error :
Cannot load V8 interface assembly. Load failure information for v8-ia32.dll

then i try copy ClearScriptV8-32.dll v8-x64.dll  to the bind folder  but the become 
Load failure information for ClearScriptV8-32.dll
I haved installed Visual C++ Redistributable Packages for Visual Studio 2013 (32 and 64 bit)

What Can it do ? thand you!

**Comment by Taritsyn** [comment]
@billschen Starting with [version 2.2.0](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v2.2.0) JavaScriptEngineSwitcher.V8 requires `msvcp140.dll` assembly from the [Visual C++ Redistributable for Visual Studio 2015](http://www.microsoft.com/en-us/download/details.aspx?id=48145).

**Comment by billschen** [comment]
@Taritsyn,  thank you for you suggetion. I will try tomorrow.

**Comment by billschen** [comment]
@Taritsyn I have install  all  c++resditributable(2013 32bit,2013 64bit ,2015 23bit ,201564bit) .
I create a console project and rum pm command
Install-Package ClearScript.V8
and run  copy code copy  from [clearscript](https://clearscript.codeplex.com/)  ,no error the snapshot like this 
![qq20 20170328091704](https://cloud.githubusercontent.com/assets/19528399/24384574/648dd1bc-1397-11e7-8319-ee267a1d47ae.png)

but when I create a mvc 4 project and first  run command Install-Package React.Web.Mvc4 to use React.NET 
second run Install-Package [ ClearScript.V8  ](https://www.nuget.org/packages/ClearScript.V8/) command  the command fail
I guess the reason is:
the verson of  ClearScript confliction.
React.Web.Mvc4 use version **5.4.8** 
 ClearScript.V8    use version **5.4.7**

my be i don't nee to  install [ ClearScript.V8  ](https://www.nuget.org/packages/ClearScript.V8/) but install [JavaScriptEngineSwitcher.V8.Native.win-x64](https://www.nuget.org/packages/JavaScriptEngineSwitcher.V8.Native.win-x64/2.2.0)??

**Comment by Taritsyn** [comment]
@billschen [ClearScript.V8](https://www.nuget.org/packages/ClearScript.V8/) is a third-party package, that has no relation to the [JavaScript Engine Switcher](https://github.com/Taritsyn/JavaScriptEngineSwitcher).

> my be i don't nee to install ClearScript.V8 but install JavaScriptEngineSwitcher.V8.Native.win-x64??

You need to install the [JavaScriptEngineSwitcher.V8](https://www.nuget.org/packages/JavaScriptEngineSwitcher.V8) package. Information about this is in [description of package](https://www.nuget.org/packages/JavaScriptEngineSwitcher.V8) and [documentation](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-V8):

> This package does not contain the native ClearScript and V8 assemblies. Therefore, you need to choose and install the most appropriate package(s) for your platform. The following packages are available:
>
> * JavaScriptEngineSwitcher.V8.Native.win-x86
> * JavaScriptEngineSwitcher.V8.Native.win-x64

**Comment by billschen** [comment]
@Taritsyn 👍 
after a lot of try，I solve my problem just now，make my asp.net mvc project with [React.Web.Mvc4](https://www.nuget.org/packages/React.Web.Mvc4) and V8 work on dev enviroment (vs2013 and vs2015) and IIS 7.5. 
next is my experience:

1. make sure install [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) ,I work on 64bit windows,but I install 32bit redistributable also
2. install [reactjs.net](https://reactjs.net/getting-started/download.html) by command Install-Package React.Web.Mvc4。
3. Install  [JS Engine Switcher: V8 for Windows (x64)](https://www.nuget.org/packages/JavaScriptEngineSwitcher.V8.Native.win-x64/)  the package author is @Taritsyn 
4. Install [JS Engine Switcher: V8 for Windows (x86) ](https://www.nuget.org/packages/JavaScriptEngineSwitcher.V8.Native.win-x86/) the package author is @Taritsyn 
5. follow the [ClearStrip Read Me](https://clearscript.codeplex.com/SourceControl/latest#ReadMe.txt) instruction：For ASP.NET projects, we recommend that you add these assemblies( _these assemblies can be found in ..\packages\JavaScriptEngineSwitcher.V8.Native.win-x64.2.2.0\runtimes\win7-x64\native and ..\\packages\JavaScriptEngineSwitcher.V8.Native.win-x86.2.2.0\runtimes\win7-x86\native_ )  as content
6.   files at the root of your web application and set their "Copy to Output
7.   Directory" properties to "Do not copy". Like this:
 ![qq3322 20170328155948](https://cloud.githubusercontent.com/assets/19528399/24394709/9dba255c-13cf-11e7-8288-5d3fe6f31eee.png)
9. Add one line code to d:\documents\visual studio ..\App_Start\ReactConfig.cs `ReactSiteConfiguration.Configuration.SetAllowMsieEngine(false);`

@Taritsyn 👍 thank you for your quick reply~

**Comment by Taritsyn** [comment]
> 5. follow the ClearStrip Read Me instruction：For ASP.NET projects, we recommend that you add these assemblies( these assemblies can be found in ..\packages\JavaScriptEngineSwitcher.V8.Native.win-x64.2.2.0\runtimes\win7-x64\native and ..\packages\JavaScriptEngineSwitcher.V8.Native.win-x86.2.2.0\runtimes\win7-x86\native ) as content
> 6. files at the root of your web application and set their "Copy to Output
> 7. Directory" properties to "Do not copy". Like this:

For JavaScriptEngineSwitcher.V8 this is not needed. During installation of `JavaScriptEngineSwitcher.V8.Native.*` packages all necessary settings will be made automatically.

You are too much complicated the installation process. A simpler and more universal installation method is described in the [official documentation](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-V8).

**Comment by billschen** [comment]
@Taritsyn~  I try not copy these assemblies to the root of my web application。but it fail
I willl try again later

**Comment by billschen** [comment]
@Taritsyn  I try again just now, if i don't copy files to  the root folder  ,error happen like
![aac20](https://cloud.githubusercontent.com/assets/19528399/24397011/ab7869ee-13d7-11e7-8e22-0962d1eae414.png).

**Comment by Taritsyn** [comment]
> I try not copy these assemblies to the root of my web application。but it fail

@billschen Most likely, your `csproj` file already contains errors.

To fix these errors you need to do the following:

1. Remove the following packages: ClearScript.V8, JavaScriptEngineSwitcher.V8, JavaScriptEngineSwitcher.V8.Native.win-x86 and JavaScriptEngineSwitcher.V8.Native.win-x64.
2. Save a project file.
3. Clean a `bin` directory.
4. Install the following packages: JavaScriptEngineSwitcher.V8, JavaScriptEngineSwitcher.V8.Native.win-x86 and JavaScriptEngineSwitcher.V8.Native.win-x64.
5. Save a project file.

**Comment by billschen** [comment]
@Taritsyn.my be my csprj file contains errors cause by React.NET.because I tested on a new mvc 4 project.  
I will try steps later.

**Comment by Taritsyn** [comment]
@billschen Better try to create a project from scratch.
