### ISSUE TITLE
Setting META or TITLE tags during Server-side rendering?

### ISSUE THREAD

**Issue by bherila** [reactjs/React.NET#391]
Is there a way to impact the <head> in such a way as to set <meta> or <title> tags on the document from the react.js app? I am looking for the ability to use something like https://github.com/kodyl/react-document-meta

Thanks,
Ben

**Comment by srmagura** [comment]
Here's what I did to solve the same problem. My top-level react components adds a data-title attribue to the outermost &lt;div&gt;, and the server-side C# parses that title out and puts in the &lt;head&gt;. May not be ideal, but it works.

    var componentHtml = Html.React($"Views.{Model.View}.Page", new { model = Model.ViewModel }).ToString();

    string title;

    if (ReactSiteConfiguration.Configuration.UseServerSideRendering)
    {

        // Second div tag has an attribute data-title containing the title for the page
        var withoutReactDiv = componentHtml.Substring(componentHtml.IndexOf('>') + 1);
        var secondDiv = withoutReactDiv.Substring(0, withoutReactDiv.IndexOf('>') + 1);
        var divWithClosing = secondDiv + "</div>"; // Get just the tag we want so we don't have to parse everything
        var xelement = XElement.Parse(divWithClosing);
        var titleAttribute = xelement.Attributes().FirstOrDefault(a => a.Name.ToString().Equals("data-title", StringComparison.OrdinalIgnoreCase));

        if (titleAttribute == null)
        {
            throw new Exception("Could not find data-title attribute. Check that all components in your page are within the <Layout>.");
        }

        title = titleAttribute.Value;
    }
    else
    {
        title = null;
    }

**Comment by dustinsoftware** [comment]
@bherila support for react-helmet has been added

https://reactjs.net/features/react-helmet.html
