### ISSUE TITLE
Server-side data is not binding in the ASP.NET Core

### ISSUE THREAD

**Issue by ktmanikanta** [reactjs/React.NET#393]
Hi,
I am following the steps mentioned in the tutorial and when I specify the below code in React.render, the method defined in HomeController is not getting triggered.
  <CommentBox url="/comments" />

**Comment by WilkaH** [comment]
@ktmanikanta can you include you're expecting to work please.

**Comment by ktmanikanta** [comment]
Hi @WilkaH ,

In Tutorial.jsx ->

ReactDOM.render(
    <CommentBox url="/comments" />,
    document.getElementById('content')
);

In HomeController.cs - >

  [Route("comments")]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public ActionResult Comments()
        {
            return Json(_comments);
        }

Please let me know if you need more details.

**Comment by Daniel15** [comment]
Are you seeing any error messages?

**Comment by ktmanikanta** [comment]
I did not include componentWillMount call, which is mentioned later in the tutorial. After adding this, the data is loading from server. Thanks all for your comments.

**Comment by Zagoshipda** [comment]
I also had a same problem but in fact I misunderstood the tutorial  : )
