### ISSUE TITLE
Transpile js files with React.NET

### ISSUE THREAD

**Issue by aviklai** [reactjs/React.NET#395]
Is it possible to transpile js files with  React.NET babel version, and not just jsx files?
Is it possible to configure React.NET to do so?
The use case is using es6 features in js files in browsers the support es5.

When I use BabelBundle in an ASP.NET MVC project with the  ASP.NET Bundling and Minification library like this:
```
bundles.Add(new BabelBundle("~/bundles/myBundle").Include(
    "~/Scripts/React/Component1.jsx",
    "~/Scripts/jsFile.js
));
```
Only the jsx file is transpiled.
Is it possible to transpile the js file as well to convert es6 features to es5?

**Comment by Daniel15** [comment]
Hmm, this should work out of the box... Are you having issues with it? Does it work fine if you rename `jsFile.js` to `jsFile.jsx`?

**Comment by aviklai** [comment]
Yes - if I change to jsFile.jsx, it works.
It just doesn't work on files with the .js extension.

**Comment by will-e-yams** [comment]
I spied this in the `web.config` and tried `path="*.js*"` and `path="*.js"` both to no avail.

```
<system.webServer>
    <handlers>
        <remove name="Babel" />
        <add name="Babel" verb="GET" path="*.jsx" type="React.Web.BabelHandlerFactory, React.Web" preCondition="integratedMode" />
   </handlers>
</system.webServer>
```

**Comment by dustinsoftware** [comment]
Unfortunately I didn't get around to investigating this one, please re-open if you still need help with this.
