### ISSUE TITLE
IIS hanging on app pool recycle in version React.NET 3.X

### ISSUE THREAD

**Issue by jslatts** [reactjs/React.NET#399]
I am consistently seeing an issue where anything that causes IIS to recycle the app pool after an initial load is resulting in no response. The only way to recover it is by killing the IIS worker process. I have only found one other person experiencing this issue via a bug filed at ClearScript's project page: https://clearscript.codeplex.com/workitem/119

I downgraded back to React.NET 2.5 and more importantly the previous version of JSEnginerSwitcher (1.5.X) and the issue is gone. I don't really think this has anything to do with React.NET directly, but I wanted to file this issue so other people experiencing this issue after upgrade to 3.X have a place to start.

**Comment by hanssonfredrik** [comment]
Having the same problem. Anyone found a solution for this yet?

**Comment by jslatts** [comment]
The bug I linked to was closed as fixed. Upgrading to JavaScriptEnginerSwitcher 2.4.X seems to have resolved the issue, though I still get more IIS crashing than I used to. It is not hanging anymore though, so it may be an unrelated memory issue. I'm closing this, since it has bee fixed.

**Comment by hanssonfredrik** [comment]
I haven't got a single crash since I downgraded. It does not sound like a great fix if it still hangs...

**Comment by jslatts** [comment]
Well, previously I was getting a hang that required me to kill IIS express worker process manually using task manager. That isn't happening anymore. Just occasional (1/20?) IIS crashes during development work.

**Comment by Daniel15** [comment]
Hmmm...  I guess it's an issue with newer JavaScriptEngineSwitcher versions. I'm not too sure though.
