### ISSUE TITLE
ReactEngineNotFoundException on Azure

### ISSUE THREAD

**Issue by andpoulsen** [reactjs/React.NET#400]
I'm building an asp.net mvc core application with server side rendering and I get ReactEngineNotFoundException, when I deploy to Azure.
You might see the entire callstack yourself here: http://dotnetopeniddemo.azurewebsites.net
I have created an Azure web app, and I'm deploying to it from Visual Studio. It works locally in IIS Express, but not on Azure.

**Comment by jyee117** [comment]
I'm running into the same issue. My .NET Core 1.1 web application works locally, but throws an exception when published:

`
ReactEngineNotFoundException: No usable JavaScript engine was found.
Please install a JavaScript engine such as React.JavaScriptEngine.ClearScriptV8 (on Windows) or React.JavaScriptEngine.VroomJs (on Linux and Mac OS X).
Refer to the ReactJS.NET documentation for more details.
`

Since it seems to be an issue with the JavaScript engine, I thought adding `.DisableServerSideRendering()` to `app.UseReact(config => { })` might be a work around, but the exception occurs with or without server side rendering.

I think we may need to do something along the lines of this article, but the last few steps are outdated: http://www.samulihaverinen.com/web-development/dotnet/2016/01/19/how-to-run-clearscript-v8-javascript-engine-in-azure/

**Comment by jyee117** [comment]
I was able to get the application working when published to Azure using a combination of these guides:
http://www.samulihaverinen.com/web-development/dotnet/2016/01/19/how-to-run-clearscript-v8-javascript-engine-in-azure/
https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/Registration-of-JS-engines

From the first guide, I installed dependencies separately:
`Uninstall-Package React.AspNet`
`Install-Package JavaScriptEngineSwitcher.Core`
`Install-Package JavaScriptEngineSwitcher.Msie` (May not be needed)
`Install-Package JavaScriptEngineSwitcher.ChakraCore`
`Install-Package JavaScriptEngineSwitcher.ChakraCore.Native.win-x64` (Selected native implementation)
`Install-Package Microsoft.ChakraCore` **(I think this is key to enabling ChakraCore on the server)**
`Install-Package React.AspNet -IgnoreDependencies`

From the second guide, I installed a package to enable JavaScriptEngineSwitcher configuration in .NET Core 1.X:
`Install-Package JavaScriptEngineSwitcher.Extensions.MsDependencyInjection`

In Startup.cs ConfigureServices():
`services.AddJsEngineSwitcher(options => options.DefaultEngineName = ChakraCoreJsEngine.EngineName).AddChakraCore();`

**Comment by Taritsyn** [comment]
```
Install-Package Microsoft.ChakraCore
```
@jyee117 This package is not needed. I recommend you to read the [documentation](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-ChakraCore).

**Comment by Taritsyn** [comment]
@andpoulsen @jyee117  I recommend to read the [“Misconceptions about the JavaScript Engine Switcher version 2.X”](https://github.com/reactjs/React.NET/issues/409) post.

**Comment by andrewwang1tw** [comment]
> I was able to get the application working when published to Azure using a combination of these guides:
> http://www.samulihaverinen.com/web-development/dotnet/2016/01/19/how-to-run-clearscript-v8-javascript-engine-in-azure/
> https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/Registration-of-JS-engines
> 
> From the first guide, I installed dependencies separately:
> `Uninstall-Package React.AspNet`
> `Install-Package JavaScriptEngineSwitcher.Core`
> `Install-Package JavaScriptEngineSwitcher.Msie` (May not be needed)
> `Install-Package JSPool`
> `Install-Package JavaScriptEngineSwitcher.ChakraCore`
> `Install-Package JavaScriptEngineSwitcher.ChakraCore.Native.win-x64` (Selected native implementation)
> `Install-Package Microsoft.ChakraCore` **(I think this is key to enabling ChakraCore on the server)**
> `Install-Package React.AspNet -IgnoreDependencies`
> 
> From the second guide, I installed a package to enable JavaScriptEngineSwitcher configuration in .NET Core 1.X:
> `Install-Package JavaScriptEngineSwitcher.Extensions.MsDependencyInjection`
> 
> In Startup.cs ConfigureServices():
> `services.AddJsEngineSwitcher(options => options.DefaultEngineName = ChakraCoreJsEngine.EngineName).AddChakraCore();`

This save me, thanks.

**Comment by Taritsyn** [comment]
> `Install-Package Microsoft.ChakraCore` (**I think this is key to enabling ChakraCore on the server**)

@andrewwang1tw I recommend you to read the “ChakraCore” section of [“Misconceptions about the JavaScript Engine Switcher version 2.X”](https://github.com/reactjs/React.NET/issues/409) discussion.

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
