### ISSUE TITLE
Getting 404 when attempting to load JSX file from MVC 4 project

### ISSUE THREAD

**Issue by kbanashek** [reactjs/React.NET#401]
When attempting to load a .jsx within a razor view via   @Scripts.Render("~/bundles/foo"), I'm getting a 404 error. I've checked the path numerous times and am registering the babel bundle correctly as well. Is there any known issues that could cause the app to block loading jsx files?

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
