### ISSUE TITLE
Is it possible to have a hyphen in property name?

### ISSUE THREAD

**Issue by klick-barakgall** [reactjs/React.NET#402]
Hello, so I see that I can supply an anonymous object as a second parameter to `@Html.React` however I am failing to see how I can provide a data attribute through this, I have tried:
```
data-initial-data
@data-initial-data
data\u002dinitial\u002ddata
@data\u002dinitial\u002ddata
data_initial_data //(this compiles but creates an attribute named "data_initial_data" instead of "data-initial-data")
```

Is there something obvious I'm missing?

**Comment by Daniel15** [comment]
Ahh, good catch! I think the regular ASP.NET MVC helpers convert underscores to hyphens, maybe ReactJS.NET should do that too.

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
