### ISSUE TITLE
Unable to resolve type: React.ReactEnvironmentUnable to resolve type

### ISSUE THREAD

**Issue by mattgross76** [reactjs/React.NET#410]
Hello,  I am able to reference a .jsx file from a page when running in debug mode on my local machine. If, however, I switch to IIS Express in debug mode, I begin to notice 500 errors when inspecting the generated page.   

This problem also occurs when I perform "Start without debugging."

Lastly, when deploying to Windows Azure via automated VSTS builds, I also receive the 500 errors when inspecting the page where my .jsx component should be.  I am able to obtain the following details from Azure application insights:

**ERROR:**
Unable to resolve type: React.ReactEnvironmentUnable to resolve type: React.JavaScriptEngineFactoryNo usable JavaScript engine was found. Please install a JavaScript engine such as React.JavaScriptEngine.ClearScriptV8 (on Windows) or React.JavaScriptEngine.VroomJs (on Linux and Mac OS X). Refer to the ReactJS.NET documentation for more details.

**FAILED METHOD:**  React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType

I am using Visual Studio 2017 to build a MVC web application.  I am using .NET Core version 1.1.

Any thoughts on why I am seeing different behaviors?  Suggestions for making this work more consistently?

**Comment by mattgross76** [comment]
Well, I was able to solve the local issue by adding a bit to my project file regarding which javascript engine to use based upon .net framework.

**NOTE**, I am still receiving the same error once deployed to Azure.  Is there something special we need to do to make the solution work for .NET Core applications in Azure?

**Comment by Taritsyn** [comment]
@mattgross76 I recommend you to read the [“Misconceptions about the JavaScript Engine Switcher version 2.X”](https://github.com/reactjs/React.NET/issues/409) post.

**Comment by mattgross76** [comment]
@Taritsyn Thank you for the article and for the many nuget packages you have developed.  I read it and have tried a few things, but still have the issue in Azure running a .NET Core 1.1 application.  I am going to try to use Chakra instead of V8 to see if that makes a difference.  

Do you have a recommendation regarding which engine to use with .NET Core 1.1 and Windows Azure?  I'm having trouble finding documentation on that particular use case.

Thanks!
Matt

**Comment by Taritsyn** [comment]
.NET Core is supported by four JS engines: [JavaScriptEngineSwitcher.ChakraCore](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-ChakraCore), [JavaScriptEngineSwitcher.Msie](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-MSIE) (only works in JsRT modes), [JavaScriptEngineSwitcher.Jint](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-Jint) and [JavaScriptEngineSwitcher.Vroom](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-Vroom). But the JavaScriptEngineSwitcher.ChakraCore is the best choice at the moment.

I also recommend you to read [this comment](https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/27#issuecomment-292753537).

**Comment by Taritsyn** [comment]
And read about [registration of JS engines in ASP.NET Core 1.X](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/Registration-of-JS-engines#aspnet-core-1x).

**Comment by mattgross76** [comment]
@Taritsyn Thank you so much!  I think it is fixed now.  My small experiment is at least now working within Azure.  That second link regarding the "registration of JS engines in ASP.NET Core 1.X" was the key!

I added the following code to the Startup class, and it works now:
`services.AddJsEngineSwitcher(options =>
				options.DefaultEngineName = ChakraCoreJsEngine.EngineName
			)
				.AddChakraCore()`

For now, I am holding off on the other options.

Thanks again.  I will close the issue.

**Comment by JoshuaKGoldberg** [comment]
@mattgross76 what was the bit you added to your project file?
