### ISSUE TITLE
Unable to resolve type: React.IReactEnvironment

### ISSUE THREAD

**Issue by cw-gawdeprasad** [reactjs/React.NET#412]
Hi Team,

As per the instructions given on [link1](https://reactjs.net/getting-started/tutorial_aspnet4.html). I created a sample React.Net application in Visual Studio 2013. Then I opened it in VS2015 (I wanted to use MVC4 setup). But when I run the application I get error `Unable to resolve type: React.IReactEnvironment`.

I am sharing the zipped solution with this so that you can reproduce it easily. It can be accessed at [link2](https://drive.google.com/file/d/0B_dJXdMt2I3nSmFvcGJ6djJkSTA/view?usp=sharing)

![image](https://cloud.githubusercontent.com/assets/14074555/26546276/ce9836b8-4486-11e7-8b88-74c727518cd8.png)

**Comment by cw-gawdeprasad** [comment]
I worked on it further and figured out that `ReactEnvironment` will not be available when `ReactConfig.Configure()` is executing so I moved the statement to resolve `IReactEnvironment` within `App_Start()` of  `Gobal.asax` and it is working fine on my local box (Windows 8 .Net 4.5.2 framework) but when I move it to the testing machine (Windows Server 2008 R2 .Net 4.5.2), it gives following exception

![image](https://cloud.githubusercontent.com/assets/14074555/26626722/cdae6d36-4615-11e7-8b55-598bf77a6092.png)


I checked it on Server 2012 and 2016 as well, where it works fine but only 2008 seems to have some issues which I am not able to figure out yet. Luckily all production servers are on Server 2016 but for testing I have disabled ReactJs.Net till I figure out the issue.

You can check my sample code at [link1](https://drive.google.com/file/d/0B_dJXdMt2I3nUzdFMUxUTUdxU2M/view?usp=sharing)

Any direction where I can look into would be of great help.

**Comment by Taritsyn** [comment]
@cw-gawdeprasad I recommend you to read the “MSIE” section of [“Misconceptions about the JavaScript Engine Switcher version 2.X”](https://github.com/reactjs/React.NET/issues/409) discussion.

**Comment by cw-gawdeprasad** [comment]
Thanks a lot @Taritsyn . I should have first read your article. IE is the culprit.
