### ISSUE TITLE
Updating JavascriptEngineSwitcher.V8 breaks React.Net

### ISSUE THREAD

**Issue by Neorth** [reactjs/React.NET#414]
I don't know if this is related to #409 or not but I got the following error when updating JavascriptEngineSwitcher.V8 from 2.2.0 to 2.4.0: 
"Method 'Evaluate' in type 'JSPool.JsEngineWithOwnThread' from assembly 'JSPool, Version=2.0.1.0, Culture=neutral, PublicKeyToken=2fc7775f73072640' does not have an implementation."

Here's the stack trace:

![image](https://cloud.githubusercontent.com/assets/8577089/26672372/37b39280-46b9-11e7-9276-121b556f76e2.png)

**Comment by Taritsyn** [comment]
@Neorth This error has already been [discussed in the JSPool repository](https://github.com/Daniel15/JSPool/issues/23).

You have two variants for solving this problem:
 1. Roll back the JavaScript Engine Switcher to version 2.3.X.
 2. Explicitly specify the JS engine (any except the `MsieJsEngine`). About how to do it read in [Daniel's comment](https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/27#issuecomment-292753537).

**Comment by Neorth** [comment]
Thanks! Missed that one.

**Comment by Daniel15** [comment]
I have a new version of JSPool (2.x beta) that fixes this too, but I haven't had a chance to release it + a new ReactJS.NET version yet.
