### ISSUE TITLE
Running 'tutorial-code' on Visual Studio Community for Mac

### ISSUE THREAD

**Issue by fgaleano** [reactjs/React.NET#415]
Has anybody been able to run the tutorial code on a Mac using Visual Studio Community? I just tried and I get "project is not compatible with Visual Studio Community".

And to go even broader, anyone able to run ReactJS.NET on a Mac at all?

Thanks!

P.S.: I just learned about Mono. Would ReactJS.NET run with Mono ASP.NET and Apache instead of the .NET Core setup I have?

**Comment by Daniel15** [comment]
I haven't tried any IDEs on Mac. I am hosting sites that use ReactJS.NET on Linux via Mono though, and that works fine.

If you make a brand new site in Visual Studio for Mac, adding ReactJS.NET to the site should work fine.

**Comment by fgaleano** [comment]
@Daniel15 I tried a brand new project and added ReactJS.NET but I can't build it. I get this error:

`System.Web.Optimization does not exist`

I'm using WebForms for this, unfortunately, and from what I gather, WebForms require the full .NET Framework not just .NET Core, which is what I installed to use VS Community. I think I'm going to need to go with the Mono route after all. Guess I should have gone with Mono in the first place 😅

**Comment by Daniel15** [comment]
Yeah, you'll need to use Mono or the full .NET Framework (on Windows) if you want to use WebForms. The newer ASP.NET Core tooling doesn't support WebForms.

**Comment by almeynman** [comment]
I was able to successfully run the project without JSX. I am also new to .Net and cannot understand what is wrong...

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
