### ISSUE TITLE
On-the-fly JSX to JavaScript compilation is not working on ASP.NET Boilerplate project

### ISSUE THREAD

**Issue by heavenwing** [reactjs/React.NET#418]
1, create solution in https://aspnetboilerplate.com/Templates, select ASP.NET MVC 5.x/MPA/EF/Module-Zero
2, add tutorial code following https://reactjs.net/getting-started/tutorial_aspnet4.html
3, run solution, found jsx is not be transpiler to js, and browser get a error

**Comment by Daniel15** [comment]
Could you please check that Web.config was modified correctly? It should have a handler for `*.jsx`.

**Comment by Znow** [comment]
I have the same issue, just with .NET Core (.NET Framework) sample from Aspnetboilerplate.

Regards

**Comment by arunr14** [comment]
@Daniel15 i am following your https://reactjs.net/getting-started/tutorial_aspnet4.html and i have the same issue where my jsx is not trans piling and i cant get past the first sample step in the tutorial

 I have even added `<remove name="Babel" />
      <add name="Babel" verb="GET" path="*.jsx" type="React.Web.BabelHandlerFactory, React.Web" preCondition="integratedMode" />`  to my webconfig   . Any idea whats going on?

**Comment by fmartin40** [comment]
Same issue for me with ASP.NET MVC 5.x/MPA/EF/Module-Zero
My webconfig:

<system.webServer>
  <handlers>
     <remove name="BlockViewHandler"/>
     <remove name="Babel" /><add name="Babel" verb="GET" path="*.jsx" type="React.Web.BabelHandlerFactory, React.Web" preCondition="integratedMode" />
   </handlers>
</system.webServer>

**Comment by billschen** [comment]
I have the same issue today(2018/5/26).
I have [Install-Package React.Web.Mvc4 -Version 3.3.0](https://www.nuget.org/packages/React.Web.Mvc4/)
an the .NET Version is 4.5.2 ,Use VS 2013 Update 5

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.

**Comment by dustinsoftware** [comment]
Also, we can't provide support for third party boilerplate projects. The best we can do for now is provide sample code and tutorial documentation for how to add this project with the templates provided by Microsoft.
