### ISSUE TITLE
WrapJavaScriptRuntimeException hides the stack-trace from log

### ISSUE THREAD

**Issue by ashkansiroos** [reactjs/React.NET#420]
Hi Daniel,

First, Thanks a lot for the great library. It is just awesome, specially that it works very well with the engine switcher. 
Secondly, I've tried to do some stress testing on my website and I've got an exception saying:

> JavaScriptEngineSwitcher.Core.JsRuntimeException: Out of memory.
> Line: 0
> Column:0
>    at React.ReactEnvironment.Execute[T](String code)

I've looked it up and ended up in WrapJavaScriptRuntimeException where it hides the stack-trace. Could you please let the exception come up, or log it so we can see what is causing the error?

Since the log says that JavaScriptEngineSwitcher is throwing the exception, I've opened an issue here:
https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/35

but I cannot be sure that JavaScriptEngineSwitcher is the one causing the problem specially since the error is more like if the memory is not released with concurrent threads which can be caused by something else like JSPool. :(

**Comment by Taritsyn** [comment]
@ashkansiroos @Daniel15 In principle, now there is no need to use the `WrapJavaScriptRuntimeException` method, because since version 2.4.0 of the JavaScript Engine Switcher in error message displays a information about error location:

```
------------------------------------------------------------
ChakraCoreJsEngine
------------------------------------------------------------
ReferenceError: 'n' is not defined
   at f (temp.js:9:4)
   at Global code (temp.js:16:2)

------------------------------------------------------------
JintJsEngine
------------------------------------------------------------
ReferenceError: n is not defined
    at temp.js:9:4

------------------------------------------------------------
JurassicJsEngine
------------------------------------------------------------
ReferenceError: n is not defined
    at f (temp.js:9)
    at temp.js:16

------------------------------------------------------------
MsieJsEngine
------------------------------------------------------------
ReferenceError: 'n' is undefined
   at f (temp.js:9:4)
   at Unknown script code (temp.js:16:2)

------------------------------------------------------------
V8JsEngine
------------------------------------------------------------
ReferenceError: n is not defined
    at f (temp.js:9:4) ->                       n();
    at temp.js:16:2

------------------------------------------------------------
VroomJsEngine
------------------------------------------------------------
temp.js: Uncaught ReferenceError: n is not defined at line: 9 column: 4.
```

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
