### ISSUE TITLE
Replace XMLHttpRequest by fetch in tutorials

### ISSUE THREAD

**Issue by JulianKowalczuk** [reactjs/React.NET#423]
Hi there.
Since we have fetch, we shouldn't go old way to exchange data with API.
It would be nice to improve tutorials by this new feature.

**Comment by Daniel15** [comment]
Fetch is only available to ~74% of visitors: https://caniuse.com/#feat=fetch. XMLHttpRequest is available pretty much everywhere. I don't think it's worth changing it yet.
