### ISSUE TITLE
onClick get lost

### ISSUE THREAD

**Issue by CN-jaycee** [reactjs/React.NET#424]
tutorial.jsx
`var MyComponent = React.createClass({
    getInitialState: function () {
        return { clickNum: 0 };
    },
    handleClick: function () {
        var num = this.state.clickNum;
        num++;
        this.setState({ clickNum: num });
    },
    render: function () {
        return (
            <div>
                <h1 onClick={this.handleClick}>Hello {this.props.name}!</h1>
                <h2 style={{ color: 'red' }}>点击{this.props.name}次数：{this.state.clickNum}</h2>
            </div>
        );
    }
});`
render a component server-side:
`@Html.React("MyComponent", new { name = "111" },"div","content1")`

server-rendered:
`<div id="content1"><div data-reactroot="" data-reactid="1" data-react-checksum="1625689842"><h1 data-reactid="2">Hello 111!</h1><h2 style="color:red;" data-reactid="6">点击111次数：0</h2></div></div>
`

onClick get lost……

**Comment by WilliamNever** [comment]
have you invoked the function @Html.ReactInitJavaScript()

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
