### ISSUE TITLE
React.net on osX

### ISSUE THREAD

**Issue by aurokk** [reactjs/React.NET#425]
Hello!
We are trying to run a net core app with react.net on os X, but instruction - https://reactjs.net/guides/mono.html is out of date and not working. Update it please :)

Regards

**Comment by aurokk** [comment]
The solution for osx is adding of https://www.nuget.org/packages/JavaScriptEngineSwitcher.ChakraCore.Native.osx-x64/ :)

**Comment by Daniel15** [comment]
Yeah, using ChakraCore should work! Let me know if you still have issues with it
