### ISSUE TITLE
Memory leak when editing .jsx files

### ISSUE THREAD

**Issue by kthayer424** [reactjs/React.NET#426]
Hi, I'm noticing memory increases pretty often when I edit a .jsx file that is server-side rendered that don't get released. Most of the time after the memory increases, the resources are released but it doesn't happen each time and often I'm left with a lot less memory and eventually an exception while debugging. I'm using Visual Studio 2017 and can see the jump in memory each time using the process monitor.

The exception is 
`React.Exceptions.BabelException: 'Exception of type 'System.OutOfMemoryException' was thrown.'`

I'm not sure if it's related to server-side rendering or the BabelBundle. Here's my configuration:

`````
    var previewScripts = new BabelBundle("~/js/preview");
    previewScripts.Include("~/Scripts/react/react.js")
                .Include("~/Scripts/react/react-dom.js")
                .Include("~/Content/js/react/preview/Preview.jsx");

    ReactSiteConfiguration.Configuration
                .SetMaxEngines(5)
                .SetStartEngines(3)
                .AddScript("~/Content/js/react/preview/Preview.jsx");
     ReactSiteConfiguration.Configuration.MaxUsagesPerEngine = 10;
`````
Any help would be great, thanks!

**Comment by kthayer424** [comment]
Update: I changed my BabelBundle to just

`````
previewScripts.Include("~/Content/js/react/preview/Preview.jsx");
`````
And the amount of memory being used on each edit of Preview.jsx is less now (probably because there's less in the bundle) but still gradually increases until VS runs out of memory.

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.

**Comment by dustinsoftware** [comment]
(sorry we never got to this one, I'm interested if you're still encountering memory leak problems!)
