### ISSUE TITLE
confuse to build ASP.NET Bundling and Minification

### ISSUE THREAD

**Issue by WilliamNever** [reactjs/React.NET#428]
Hi,
bundles.Add(new Bundle("~/bundles/main",.....
Here, the the path 'main' is unchanged? i use other path to build the jsx file, but nothing is returned.

**Comment by awayken** [comment]
@WilliamNever For help with bundling and minification, I'd recomment you check out Microsoft's documentation: https://docs.microsoft.com/en-us/aspnet/mvc/overview/performance/bundling-and-minification

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
