### ISSUE TITLE
Cant run correctly in the enveronment of centos 7

### ISSUE THREAD

**Issue by lizhenzhaofirst** [reactjs/React.NET#429]
I can't continue with the commond 'make dependencies' of  <a href='https://reactjs.net/guides/mono.html' >page</a>,please update the docs.I will be very appreciated.

**Comment by Daniel15** [comment]
You might have better luck using .NET Core 2.0 + ChakraCore, instead of VroomJs :)

**Comment by Taritsyn** [comment]
@lizhenzhaofirst Try to install a preview version of the [JavaScriptEngineSwitcher.ChakraCore.Native.linux-x64](https://www.nuget.org/packages/JavaScriptEngineSwitcher.ChakraCore.Native.linux-x64/) package.

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
