### ISSUE TITLE
Cannot  found React.NET Unable to load DLL 'ChakraCore' on Mac

### ISSUE THREAD

**Issue by radjivC** [reactjs/React.NET#431]
Hi, 

My application cannot handle React, but my colleagues laptop are alright.
It looks like I mess up the setup of .NET, any ideas?

```Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Unable to resolve type: React.ReactEnvironment
React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory ---> JavaScriptEngineSwitcher.Core.JsEngineLoadException: During loading of ChakraCoreJsEngine error has occurred.
See more details:

Unable to load DLL 'ChakraCore': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E) ---> System.DllNotFoundException: Unable to load DLL 'ChakraCore': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)```

**Comment by Daniel15** [comment]
Make sure you have installed the [JavaScriptEngineSwitcher.ChakraCore.Native.osx-x64](https://www.nuget.org/packages/JavaScriptEngineSwitcher.ChakraCore.Native.osx-x64) package.

**Comment by radjivC** [comment]
I only get ```-bash: Install-Package: command not found```

**Comment by Daniel15** [comment]
Install-Package is a PowerShell cmdlet, not a Bash command. You need to install the JavaScriptEngineSwitcher.ChakraCore.Native.osx-x64 package in your app, in the same way that you installed ReactJS.NET itself.

**Comment by radjivC** [comment]
How do you do that on mac?

**Comment by Daniel15** [comment]
If you're using ASP.NET Core, try:

dotnet add package JavaScriptEngineSwitcher.ChakraCore.Native.osx-x64

How did you install ReactJS.NET initially?

--
Regards,
Daniel Lo Nigro
http://dan.cx/ | Twitter <http://twitter.com/Daniel15> | Facebook
<http://www.facebook.com/daaniel>

**Comment by Taritsyn** [comment]
@radjivC And don't forget to install the ICU4C library. To install this library, simply run in your terminal the following command:

```
brew install icu4c
```

**Comment by radjivC** [comment]
@Taritsyn Amzing it work for me, thanks

**Comment by Daniel15** [comment]
Glad to hear you got it sorted :)
