### ISSUE TITLE
how combine react.net and react-router-dom v4  for render server side 

### ISSUE THREAD

**Issue by mahdiporkar** [reactjs/React.NET#434]
Dear i have two question
first :how combine react.net and routing for render server side ?
second :how can render server side dynamic component or dynamic import  in reactjs.net

**Comment by gunnim** [comment]
React Router support will likely be included in the next release, 

https://github.com/reactjs/React.NET/commit/5d1bd9d73d32d07f42abbc0060f90cb38b988070

as soon as this update gets released i'll update the following examples
https://github.com/gunnim/AspNetCore-React-SSR/
https://github.com/gunnim/Umbraco-React-Router-SSR

in the mean time you could build the react source and copy the code from either the asp.net Core or Umbraco example

**Comment by dustinsoftware** [comment]
React Router support has been merged.

To use dynamic imports, you will need to use [webpack](https://reactjs.net/guides/webpack.html).
