### ISSUE TITLE
React.js with asp.net core 2.0

### ISSUE THREAD

**Issue by patsadow2** [reactjs/React.NET#435]
Hello, could anyone link a good template to start hacking with react + asp.net 2.0. I am interested in jsx no tsx ;))) Thanks ;)

**Comment by aurokk** [comment]
I recommend u to start with javascript services instead of react.net :) https://github.com/aurokk/netcore-react-spa

**Comment by dustinsoftware** [comment]
Good news! There is an open PR for this #436

**Comment by makcakaya** [comment]
@aurokk Can you elaborate more please? Why do you recommend JavaScriptServices instead of Reactjs.Net?

**Comment by Daniel15** [comment]
Should be fixed by #436
