### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by wub** [reactjs/React.NET#439]
Now that [React 16's out](https://github.com/facebook/react/releases/tag/v16.0.0), will there be any way to use it with React.NET?

I've tried loading it myself, with `SetLoadReact(false)` & `AddScriptWithoutTransform("react+react-dom")`, but it says that React isn't exposed properly (so I can't begin to debug issues).

Is there some way to tell React.NET which major version of React to work with? Or will the project only ever support one at a time? I understand the maintenance and complexity implications! Cheers.

**Comment by Daniel15** [comment]
> I've tried loading it myself, with SetLoadReact(false) & AddScriptWithoutTransform("react+react-dom"), but it says that React isn't exposed properly (so I can't begin to debug issues).

When using your own version of React, it expects `React`, `ReactDOM` and `ReactDOMServer` globals, or `global.React`, `global.ReactDOM` and `global.ReactDOMServer` to be set correctly:

https://github.com/reactjs/React.NET/blob/5d1bd9d73d32d07f42abbc0060f90cb38b988070/src/React.Core/Resources/shims.js#L52-L68

https://github.com/reactjs/React.NET/blob/5cdd2f4cac80368f1666a5cfc2c90510613e608d/src/React.Core/JavaScriptEngineFactory.cs#L182-L191

You can see how ReactJS.NET builds the built-in React version:

https://github.com/reactjs/React.NET/blob/5d1bd9d73d32d07f42abbc0060f90cb38b988070/src/React.Core/gulpfile.js

https://github.com/reactjs/React.NET/blob/5d1bd9d73d32d07f42abbc0060f90cb38b988070/src/React.Core/Resources/react.js

> Is there some way to tell React.NET which major version of React to work with? Or will the project only ever support one at a time?

Not supported at the moment, but it's a good idea. I don't have time to build it myself, but I'd be happy to review a pull request adding this functionality.

**Comment by dustinsoftware** [comment]
Hey @wub you can use React.NET with React 16 by bundling it ahead of time along with your components, and then passing the component bundle to the engine. As long as the globals are exposed correctly, it should just work.

React.NET does not currently handle `componentDidCatch` very well.. going to investigate if that can be easily added. Right now if a component throws, the server render gives up immediately.

**Comment by wub** [comment]
Thanks @dustinsoftware and @Daniel15 - it works!

**Comment by Daniel15** [comment]
Let's keep this issue open as ReactJS.NET still needs to be updated to ship with React 16 😃

**Comment by hybridappdev** [comment]
@dustinsoftware , I want to use React 16 error boundary feature to log javascript error but it's not working with ReactJS.NET. do you have any fix?

**Comment by dustinsoftware** [comment]
Yes, although I didn’t push it since it was out of scope. I’ll open another
PR.

In my project server render for that component gets skipped if an error is
thrown (this includes those with error boundaries). This introduced a
problem - I had to hack around it a bit since react.net tries to hydrate to
a div that isn’t there when this happens. My fix was to find the generated
ID in the exception that’s thrown and manually render a div, which fixes
the hydrate step.

Since this is an error condition the right thing to do would be to still
throw an exception so you can know about and fix the bug, but still allow
client render to happen. So my PR would just allow more graceful handling
of this error condition.

**Comment by hybridappdev** [comment]
@dustinsoftware Thanks. :+1:

**Comment by Daniel15** [comment]
I didn't get around to publishing a new version of ReactJS.NET this weekend (had too many other things to get done) but I'll try to release one tomorrow night. In the meantime, you can get a build from the build server. Instructions are on the site :)

**Comment by wub** [comment]
https://github.com/reactjs/React.NET/pull/445 🍾 

Thanks @dustinsoftware and @Daniel15.

**Comment by Daniel15** [comment]
@dustinsoftware did all the work 😛 Thanks Dustin!

**Comment by srdjanRakic** [comment]
Does ReactJS.NET now supports React 16? Thanks in advance.

**Comment by dustinsoftware** [comment]
Yep!
