### ISSUE TITLE
componentDidMoount not working

### ISSUE THREAD

**Issue by dfhincapiem** [reactjs/React.NET#440]
Does anyboy knows if I run this in reactjs.net I get as result a 0 but when I try in another compilers as https://jscomplete.com/repl/ I get a 1

class First extends React.Component {

constructor(props) {

super(props)
this.state = { counter: 0 }

}

componentDidMount() {

this.setState({
counter : 1
})

}

render() {
return `<h1>{this.state.counter}</h1>`
}

}

**Comment by dustinsoftware** [comment]
Hey @dfhincapiem, unfortunately I could not replicate this issue. Could you provide a sample app showing the problem?

**Comment by Daniel15** [comment]
Note that `componentDidMount` is only called client-side, not server-side. View source on your page and check that the JavaScript is being rendered correctly.

**Comment by dfhincapiem** [comment]
Yes, you were right
