### ISSUE TITLE
Does this work with the latest JsEngineSwitcher?

### ISSUE THREAD

**Issue by srmagura** [reactjs/React.NET#441]
Getting the following error after upgrading ReactJS.NET (Core, Web, and Mvc4) and JsEngineSwitcher to the lastest versions:

Could not load file or assembly 'JavaScriptEngineSwitcher.V8, Version=2.4.2.0, Culture=neutral, PublicKeyToken=c608b2a8cc9e4472' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

It's looking for 2.4.2.0, but the current version is 2.4.10.0. 

I had previously been using ReactJS.NET with JsEngineSwitcher and V8 without any problem.

**Comment by Daniel15** [comment]
Should work, it just sounds like you're missing an assembly binding redirect in your Web.config file. NuGet should update that automatically.

**Comment by srmagura** [comment]
Thank you Daniel! After manually adding several binding redirects and references, I have server rendering working with the latest versions of all of the packages.
