### ISSUE TITLE
JavaScriptEngineSwitcher.Core.JsRuntimeException: RangeError: Maximum call stack size exceede

### ISSUE THREAD

**Issue by cw-gawdeprasad** [reactjs/React.NET#444]
Hi,

I am using React.NET with following settings

> JsEngineSwitcher.Instance.EngineFactories.AddV8();
> IJsEngine engine = JsEngineSwitcher.Instance.CreateEngine(V8JsEngine.EngineName);
> 
> ReactSiteConfiguration.Configuration
> .SetLoadBabel(false)
> .SetUseDebugReact(false)
> .AddScriptWithoutTransform("~/Scripts/server.bundle.js")
> .SetStartEngines(25)
> .SetMaxEngines(100)
> .SetReuseJavaScriptEngines(true)             
> ;

Now I am getting following error for few of the cases. 

> [29] Pwa-Logger-Renderengine - JavaScriptEngineSwitcher.Core.JsRuntimeException: RangeError: Maximum call stack size exceeded ---> Microsoft.ClearScript.ScriptEngineException: RangeError: Maximum call stack size exceeded
>    at V8Exception.ThrowScriptEngineException(V8Exception* )
>    at Microsoft.ClearScript.V8.V8ContextProxyImpl.Execute(String gcDocumentName, String gcCode, Boolean evaluate, Boolean discard)
>    at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass63_0.<Execute>b__0()
>    at Microsoft.ClearScript.ScriptEngine.ScriptInvoke[T](Func`1 func)
>    at Microsoft.ClearScript.V8.V8ScriptEngine.BaseScriptInvoke[T](Func`1 func)
>    at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass68_0`1.<ScriptInvoke>b__0()
>    at Microsoft.ClearScript.V8.?A0x792c8756.LockCallback(Void* pvArg)
>    at Microsoft.ClearScript.V8.V8ContextProxyImpl.InvokeWithLock(Action gcAction)
>    at Microsoft.ClearScript.V8.V8ScriptEngine.ScriptInvoke[T](Func`1 func)
>    at Microsoft.ClearScript.V8.V8ScriptEngine.Execute(String documentName, String code, Boolean evaluate, Boolean discard)
>    at Microsoft.ClearScript.ScriptEngine.Evaluate(String documentName, Boolean discard, String code, Boolean marshalResult)
>    at JavaScriptEngineSwitcher.V8.V8JsEngine.InnerEvaluate(String expression, String documentName)
>    --- End of inner exception stack trace ---
>    at JavaScriptEngineSwitcher.V8.V8JsEngine.InnerEvaluate(String expression, String documentName)
>    at JavaScriptEngineSwitcher.V8.V8JsEngine.InnerEvaluate[T](String expression, String documentName)
>    at JavaScriptEngineSwitcher.V8.V8JsEngine.InnerEvaluate[T](String expression)
>    at JavaScriptEngineSwitcher.V8.V8JsEngine.InnerHasVariable(String variableName)
>    at JavaScriptEngineSwitcher.Core.JsEngineBase.HasVariable(String variableName)
>    at JSPool.PooledJsEngine.HasVariable(String variableName)
>    at React.ReactEnvironment.EnsureUserScriptsLoaded()
>    at React.ReactEnvironment.CreateComponent[T](String componentName, T props, String containerId, Boolean clientOnly)
>    at BAL.PWA.CMS.PWACMSRenderedData.React[T](String componentName, T props, String htmlTag, String containerId, Boolean clientOnly, Boolean serverOnly, String containerClass)
>    at BAL.PWA.CMS.PWACMSRenderedData.GetNewsDetails(PwaNewsDetailReducer reducer, String url, String containerId, String componentName)

It's like I get it 3/4 times a day in 1000s of instances. I am not able to understand it as when I log the specific component for which this is coming and try to reproduce the same, then it does not reproduce. So it's an intermittent issue which is not consistently reproducing. Can any one of you help put more light on this?

PS: I have copied the React() function from HTMLHelpers to my class as I am caching the rendered page to memcached.

**Comment by Taritsyn** [comment]
```csharp
IJsEngine engine = JsEngineSwitcher.Instance.CreateEngine(V8JsEngine.EngineName);
```

Why did you create a separate instance of JS engine?

**Comment by cw-gawdeprasad** [comment]
It's a mistake @Taritsyn . I had copied the code earlier from some online solution to make V8 work with the new libraries. Just checked that it's useless to do this. Thanks for pointing out. But do you think that this is causing the issue?

**Comment by Taritsyn** [comment]
> But do you think that this is causing the issue?

No, problem is not this. Very similar to the lack of memory on the server. Try to change pool settings to the following:

```csharp
…
.SetStartEngines(3)
.SetMaxEngines(15)
…
```

**Comment by cw-gawdeprasad** [comment]
Sure will try with this. But do you think that max 15 engines will be able to handle the load of 8000 render requests/ minute? I will also do the load testing to check the same. Any inputs in handling the things better would be of great help.

**Comment by Taritsyn** [comment]
I believe, that 100 JS engines is too much (maximum is to use 25). Can you imagine how much memory is spending this amount of JS engines? Usually even a pool of `StringBuilder`s is limited to 20.

**Comment by cw-gawdeprasad** [comment]
I will do some load-testing with the settings you have provided and will update it here. It will be good learning and I second the thought that I should not create more than 25 engines in a pool.

**Comment by ArgonAlex** [comment]
I'm using JSPool directly, not React.NET, but I have also started running into this since a week and half ago. Actually looks like it was right as we added more RAM to our servers, which is pretty counterintuitive. We also updated to the latest JSPool/JavaScriptEngineSwitcher/ClearScript a week before that.

For reference, we've been running with 32 engine pools for a year now, which we arrived at based on testing at ~8000 requests/min, but your needs will vary depending on other factors, including how long a render takes.

**Comment by cw-gawdeprasad** [comment]
@Taritsyn I have set the minsize to 3 and max size to 20 but I am still getting the errors (twice a day). The RAM for the Server is 8GB and is underutilized. Do you think something else is the issue?

**Comment by Taritsyn** [comment]
> Do you think something else is the issue?

@cw-gawdeprasad In this case, I recommend to check your JSX code on presence of recursion.

**Comment by cw-gawdeprasad** [comment]
The recursion is not there for sure as when I run the code for the same component with the same rout for which issue came, it runs fine. Also the issue is intermittent, does not reproduce all the time. I wanted to know if RAM is the only possible culprit if there is no Recursion?

**Comment by Taritsyn** [comment]
> I wanted to know if RAM is the only possible culprit if there is no Recursion?

Thinking, that there is not, because you have enough RAM.

Also check the `~/Scripts/server.bundle.js` file. See examples of such errors: [“Maximum call stack size exceeded error”](https://stackoverflow.com/questions/6095530/maximum-call-stack-size-exceeded-error) and [““RangeError: Maximum call stack size exceeded” Why?”](https://stackoverflow.com/questions/22123769/rangeerror-maximum-call-stack-size-exceeded-why).

**Comment by cw-gawdeprasad** [comment]
I checked both these pages before creating an issue here. For sure there is no recursion problem in the code as I logged the component and the URL for the which the issue came up and tried reproducing the same with the same to render the same URL and component but it did not reproduce. I also did the load testing where I set the max engines to 100 and tried to fill up the RAM but even then the error did not reproduce. So I am wondering as what's the cause.

**Comment by srmagura** [comment]
I have been getting the same error, but only in Azure after pushing changes with web deploy. This is with server side rendering enabled. The error is intermittent, affecting about 1/3 of requests. I never get this error in development. 

Is it possible that the JavaScript engines are not getting destroyed+recreated when I do a web deploy? I am also using V8.

**Comment by srmagura** [comment]
By the way, my error is resolved by restarting the App Service.

**Comment by Daniel15** [comment]
This error is coming from the JS engine, which makes it hard to debug 😕  You could try using the ChakraCore JS engine rather than ClearScript and see if that helps.

**Comment by Daniel15** [comment]
@Taritsyn Is it possible to get the JavaScript stack trace when this occurs?

**Comment by Taritsyn** [comment]
@Daniel15 Yes, it is possible. I already [wrote about this](https://github.com/reactjs/React.NET/issues/420#issuecomment-312480398).

**Comment by Taritsyn** [comment]
@Daniel15 But here is another problem, that the “Maximum call stack size exceeded” error may not have a stack trace.

**Comment by ArgonAlex** [comment]
Yes the fact that there is no indication of where in the code the exception is happening, combined with the fact that it only happens on few renders, makes this very hard to debug.

**Comment by cw-gawdeprasad** [comment]
@Daniel15 @Taritsyn I changed the engine to ChakraCore (1.5.2) using JavaScriptEngineSwitcher.ChakraCore and the problem has disappeared but not I am seeing that Chakra eats memory in some cases and the memory consumption goes up to 3GB. I never had this issue with V8. Any suggestions on why this might happen? Also the consumption is not consistent. It happens 3/4 times a week when the w3wp process takes around 3GB memory.

**Comment by dustinsoftware** [comment]
@cw-gawdeprasad it sounds like you have a memory leak somewhere in your code. I'd recommend getting a heap dump from the server when the problem occurs and diagnosing it with a debugging tool (such as WinDbg) to see where the leak is coming from.

**Comment by Taritsyn** [comment]
@cw-gawdeprasad I moved part of functionality from [3.X branch](https://github.com/Taritsyn/JavaScriptEngineSwitcher/tree/3.X) to [2.4.12](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v2.4.12) and [2.4.13](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v2.4.13) versions. It is possible, that new configuration properties in the JavaScriptEngineSwitcher.V8 (`HeapSizeSampleInterval`, `MaxHeapSize` and `MaxStackUsage`) and the JavaScriptEngineSwitcher.ChakraCore (`DisableFatalOnOOM` and `MemoryLimit`) modules will help to solve your problems.

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
