### ISSUE TITLE
Please do not pollute my DOM

### ISSUE THREAD

**Issue by MasodSaidi** [reactjs/React.NET#45]
Really like the server-side rendering but got one problem with it. Is it possible to not include the extra "react1" container div since it messes with the CSS. Would be great if there was an additional optional parameter on the helper like this:

@Html.React("HelloWorld", new {name = "Daniel"}, "my-own-container")

If the optional parameter is specified no "react1" div is rendered and the optional is used when doing:

document.getElementById("my-own-container")

**Comment by jboliveira** [comment]
Hi @Daniel15, on the same issue, is it possible include another additional optional parameter on the helper like this:

`@Html.React("HelloWorld", new {name = "Daniel"}, "my-own-container", "my-own-class1 my-own-class2");`

*Situation:*
I have to render a list of comments, like:
```
<div id="comment-27299" class="item comment"></div>
<div id="comment-27300" class="item comment"></div>
<div id="comment-27301" class="item comment"></div>
```
It has a class applied to it that you may want for styling all comments on the page, but it also has a unique ID value (dynamically generated, nicely enough). This ID value is useful for direct linking. Now I can link directly to a particular comment on a particular page easily and keep a standard.

To set a style for each id in my css will be a little ugly, like:
```
#comment-27299{
...
}
#comment-27300{
...
}
```

So, if have a possibility to set a class-name in _@Html.React_ will be great.

Thanks.

**Comment by mocanSergiu666** [comment]
Why when I use setInterval function with server-side rendering, I get an error that setInterval is undefined?

**Comment by Daniel15** [comment]
@mocanSergiu666 - `setInterval` can not be used when doing server rendering. setInterval is part of the BOM (Browser Object Model) which is not available in server-side JavaScript.

**Comment by oivindhagen** [comment]
To render just the component (with an optional reactId), the following extension method should do the trick:

```
using System.Web.Mvc;
using System.Web;
using System;
using React;
using Newtonsoft.Json;

namespace YourProject.Extensions
{
    public static class HtmlHelperExtensions
    {
        public static IHtmlString ReactWithoutContainer(this HtmlHelper helper, string componentName, object props)
        {
            var serializedProps = JsonConvert.SerializeObject(props, ReactSiteConfiguration.Configuration.JsonSerializerSettings);
            
			//If you want to add a reactId to the top level element, uncomment the following line and render the 
			//reactId property as an id attribute on the top level element in your component like this:
			//<div id={reactId}>
			//<!-- component content -->
			//<div/>
			dynamic deserialized = JsonConvert.DeserializeObject(serializedProps, ReactSiteConfiguration.Configuration.JsonSerializerSettings);
            deserialized.reactId = "react_" + Guid.NewGuid().ToShortGuid();
            
			serializedProps = JsonConvert.SerializeObject(deserialized, ReactSiteConfiguration.Configuration.JsonSerializerSettings);
            var initializedCode = string.Format("React.createElement({0}, {1})", componentName, serializedProps);
            var code = string.Format("ReactDOMServer.renderToStaticMarkup({0})", initializedCode);
            return helper.Raw(React.ReactEnvironment.Current.Execute<string>(code));
        }
    }
}
```

To use it in your cshtml, just write the following:
```
    @Html.ReactWithoutContainer("Components.YourComponent", new
        {
            property1 = "value1",
            property2 = "value2"
        })
```

Please note that this extension method reaches quite far into ReactJs.net. It might get you into trouble down the road.
