### ISSUE TITLE
dev-build.bat assumes VS 2017 Community to exist

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [reactjs/React.NET#452]
I'm using Enterprise. Would you mind if it checked for the existence of `MSBuild.exe` under Enterprise, Professional, or Community?

For example, it might exist under C:\Program Files (x86)\MSBuild\14.0\Bin.

**Comment by Daniel15** [comment]
Sure, feel free to update it. I wasn't entirely sure of the proper way to
do it.
