### ISSUE TITLE
Document technical requirements to contribute

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [reactjs/React.NET#453]
Just from running `dev-build.bat`, it looks like you need at the very least:
* `dotnet` on the CLI
* MSBuild.exe from VS 2017

It'd be useful to mention these and any other requirements on https://reactjs.net/dev/contributing.html.

**Comment by Daniel15** [comment]
Yeah, good idea, I haven't updated that page in a while :(

Feel free to submit a pull request if you like. The source for that page is located at https://github.com/reactjs/React.NET/blob/master/site/jekyll/dev/contributing.md.
