### ISSUE TITLE
Can't install with dotnet SDK 1.X; 2.X can't install some sample projects

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [reactjs/React.NET#458]
When I try to use `dotnet restore` with a 1.X SDK install, a `dotnet restore error: Invalid input 'src\React.sln'. The file type was not recognized.` pops up as part of `dev-build.bat`.

When I uninstall that and use a 2.X install, `dotnet restore src\React.sln etc.` fails with `The specified SDK version [1.0.0] from global.json [C:\Code\React.NET\global.json] not found; install specified SDK version`.

When I change `global.json` to reference `"version": "2.0.0"` instead of `"version": "1.0.0"`, it complains about a trio of missing targets in sample projects, then installs the rest:

```
C:\Code\React.NET\src\React.Sample.Mvc4\React.Sample.Mvc4.csproj(198,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.2\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\Code\React.NET\src\React.Sample.Cassette\React.Sample.Cassette.csproj(204,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.2\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\Code\React.NET\src\React.Sample.Webpack\React.Sample.Webpack.csproj(181,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.2\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\Code\React.NET\src\React.Sample.Mvc4\React.Sample.Mvc4.csproj : warning NU1503: Skipping restore for project 'C:\Code\React.NET\src\React.Sample.Mvc4\React.Sample.Mvc4.csproj'. The project file may be invalid or missing targets required for restore. [C:\Code\React.NET\src\React.sln]
C:\Code\React.NET\src\React.Sample.Cassette\React.Sample.Cassette.csproj : warning NU1503: Skipping restore for project 'C:\Code\React.NET\src\React.Sample.Cassette\React.Sample.Cassette.csproj'. The project file may be invalid or missing targets required for restore. [C:\Code\React.NET\src\React.sln]
C:\Code\React.NET\src\React.Sample.Webpack\React.Sample.Webpack.csproj : warning NU1503: Skipping restore for project 'C:\Code\React.NET\src\React.Sample.Webpack\React.Sample.Webpack.csproj'. The project file may be invalid or missing targets required for restore. [C:\Code\React.NET\src\React.sln]
```

I'm guessing there's some part of the VS/dotnet install I'm missing?

**Comment by JoshuaKGoldberg** [comment]
Note: to get the rest of the installs running in the `PackageRestore` task, I commented out the dotnet restores in `build.proj`:

```
	<Target Name="RestorePackages" DependsOnTargets="Clean;UpdateVersion">
		<!-- NuGet packages for "legacy" projects (eg. React.Samples.Mvc4) -->
		<!-- <Exec
			WorkingDirectory="$(MSBuildProjectDirectory)"
			Command="tools\NuGet\nuget.exe restore $(SolutionFile)"
		/> -->
		<!-- NuGet packages for modern .csproj projects -->
		<!-- <Exec
			WorkingDirectory="$(MSBuildProjectDirectory)"
			Command="dotnet restore $(SolutionFile) /p:Version=$(VersionString)"
		/> -->
```

**Comment by JoshuaKGoldberg** [comment]
> ```
> The imported project
> "C:\Program Files\dotnet\sdk\2.0.2\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets" 
> was not found
> ```

This actually exists in two locations on my machine:
* `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\WebApplications\Microsoft.WebApplication.targets"`
* `"C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\WebApplications\Microsoft.WebApplication.targets"`

**Comment by Daniel15** [comment]
The project hasn't been updated to the .NET Core 2.0 SDK yet. There's a pull request to do so: https://github.com/reactjs/React.NET/pull/436. I might work on completing that PR and merge it, which should resolve some issues here.

**Comment by Daniel15** [comment]
> C:\Code\React.NET\src\React.Sample.Mvc4\React.Sample.Mvc4.csproj(198,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.2\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.


This is the same issue I'm hitting while trying to get #436 working. It looks like the same issue as https://github.com/dotnet/sdk/issues/1385.

**Comment by Daniel15** [comment]
https://github.com/reactjs/React.NET/commit/dd4e5048a26eb517c195a5ed8af7eaa9f1d8d35c should fix the issue with Microsoft.WebApplication.targets
