### ISSUE TITLE
Allow transpilers other than Babel

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [reactjs/React.NET#462]
It would be nice to be able to use TypeScript or Flow to transform source files.

For the most part, just looking at `IBabel`, it looks like it could just be renamed  without any other non-comment refactors in that file. Other files would also just need renames of members.
* `JavaScriptWithSourceMap` would have to rename its `BabelVersion`. Perhaps an `ITranspilerIdentifier` class with `Name` and `Version`, with the member renamed to `TranspilerIdentifier`.
* `IReactEnvironment`'s `Babel` could be renamed to `Transpiler`.
* `BabelException` could stay, since it's only used in `Babel`.

The only Babel-specific construct in the code I can find are the `LoadBabel` and `BabelConfig` members of `IReactSiteConfiguration`. I think the best route here would be to let it take in an `ITranspiler` optionally instead of `LoadBabel` and the like. That would abstract tranpilation details away from the config.

**Comment by Daniel15** [comment]
Interesting idea... Would you like to play around with some ideas to accomplish this?

**Comment by JoshuaKGoldberg** [comment]
If I have time, sure. No promises though :(

Assuming this works, what would you prefer as a way of merging it in? Would a PR from me go against master, or a `next` branch, or...?

**Comment by Daniel15** [comment]
Against `master` is fine. No rush either... Don't feel pressured to do anything. 😃

**Comment by dustinsoftware** [comment]
I'm closing issues for future tasks like this that aren't actively being worked on, but would be open to adding support for this!

#655
