### ISSUE TITLE
Standardize source linting: spaces vs tabs; common copyright header

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [reactjs/React.NET#463]
_(this issue is motivated 50% by code quality, 50% by me familiarizing myself with the code base)_

I couldn't help but notice a few files with spaces intermixed with the tabs :smile:. There are also...

* A few different copyright header variations
* At least one file (`Babel.cs`) with nonstandard line endings.
* Trailing whitespace occasionally

**Comment by Daniel15** [comment]
It's supposed to use tabs in most places, and spaces in .json files. See the editorconfig: https://github.com/reactjs/React.NET/blob/master/.editorconfig

The copyright header is supposed to be 2014-Present, someone updated it via a pull request a while back. Maybe they missed some of the files

**Comment by dustinsoftware** [comment]
Line endings should be fixed now
