### ISSUE TITLE
Split React.Core source files into common namespaces

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [reactjs/React.NET#464]
_(this issue is motivated 50% by code quality, 50% by me familiarizing myself with the code base)_

There are a few clusterings of files that could be moved into their own `namespace` and directory. IMO doing so would make the code a bit cleaner and easier to search through.

* `Caching`:
	* `ICache`
	* `MemoryFileCache`
	* `NullCache`
	* `IFileCacheHash`+`FileCacheHash`
* `Files`:
	* `IFileSystemBase`+`FileSystemBase`
	* `FileSystemExtensions`
	* `SimpleFileSystem`
* `Transpilation`
	* `IBabel`+`Babel`
	* `BabelHandler`
	* `BabelConfig`
	* `JavaScriptWithSourceMap`
	* `SourceMap`

**Comment by Daniel15** [comment]
> There are a few clusterings of files that could be moved into their own namespace and director

There's so few files that I'm not sure that this would actually be advantageous.

When I was initially building out the repository, I copied the model of ASP.NET MVC, which had most of its files in a single directory (eg. see the ASP.NET MVC 5 codebase at https://github.com/aspnet/AspNetWebStack/tree/master/src/System.Web.Mvc). I don't know many people that actually browse using the file tree - Most use some sort of fancy navigation in their IDE to navigate only by name (like Ctrl+T "Go to Everything" in ReSharper) and thus the directory layout is not too important.

**Comment by dustinsoftware** [comment]
This project is simple enough that it seems this isn’t worth the effort. :)
