### ISSUE TITLE
Use dependency injection instead of abstract/virtual properties for FileSystemBase

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [reactjs/React.NET#465]
_(this issue is motivated 50% by code quality, 50% by me familiarizing myself with the code base)_

There's only one `abstract` method, `MapPath`, which could be replaced by a lambda.

The remaining properties could also be made not `virtual`. None of them are overriden in this repository, and the only real reason I see for allowing them to be overriden would be to mock out file operations. An `IFileIO` interface for interacting dirctly with files could be injected instead of the dependencies on `System.IO.Directory` and `System.IO.File`. The default (used) implementation would just wrap around `File`, while tests could then define their own file system. That would let tests test all the behavior of the class.

You'd probably then want to rename it to `FileSystem`.

**Comment by dustinsoftware** [comment]
Sorry this is late... We could do this but it seems like the code is fine as it is.. you can send a PR if you’d like but it would be nice to get help in other areas too :)
