### ISSUE TITLE
Publishing pdb files in the NuGet packages?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [reactjs/React.NET#467]
In an ideal world, we'd never need to debug into library code... but there are times when it can be useful.

For example, trying to learn how React.NET loads or reloads .js files to understand its performance (and to fix project-specific caching issues). I'm debugging through my locally built `.pdb`s now, but it would be convenient to be able to just use what's in the NuGet package.

The only downside I've heard of beyond "you shouldn't need them!" is to keep your source code secure... but that's not really relevant for OSS right?

**Comment by Daniel15** [comment]
Hmm, it should already be publishing .pdb files, but I wonder if something broke when I switched to the newer ASP.NET Core tooling. Also, I believe NuGet publishes the source code to a symbol server, which should also help with debugging (as long as the symbol server is configured in Visual Studio)

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
