### ISSUE TITLE
How to use router with server side rendering

### ISSUE THREAD

**Issue by optimatex** [reactjs/React.NET#477]
As I know, isomorphic apps use the same routing as on a client. That's means server should always return index.html page and routes should be handled by react-router or something like this when are rendered on the server side. Otherwise, after the page is loaded any future route change will lead to page reload. 
How can I implement this tenet in the approach described [here  ](https://reactjs.net/guides/server-side-rendering.html) since I need to pass the appropriate model to `@Html.React`? Should it be something like server side routing with the single concern to retrieve the corresponding model based on the current route?
thank you for your hard work

**Comment by Daniel15** [comment]
The newly-added `React.Router` package should help you use React Router with server-side rendering. #476 tracks adding a sample project.

**Comment by optimatex** [comment]
Thanks

**Comment by dustinsoftware** [comment]
@optimatex I opened a PR here, hope it is helpful #479

**Comment by dustinsoftware** [comment]
Closing because this question has been answered, please re-open if you'd like some more help 😄
