### ISSUE TITLE
 ReactDOM is not defined

### ISSUE THREAD

**Issue by optimatex** [reactjs/React.NET#480]
I looked through all similar issues in this repo, but my case is really strange. I reduce my code as much as possible but this error is still there
My current bundle file (I use webpack)

```
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import ReactDOMServer from 'react-dom/server';

global.React = React;
global.ReactDOM = ReactDOM;
global.ReactDOMServer = ReactDOMServer;
global.__SERVER__ = true;

require('expose?Post!./post');
require('expose?React!react');
require('expose?ReactDOM!react-dom');
```
and here is my simple component

```
class Post extends Component {
   render() {
      return <div>Post title</div>;
   }
}

module.exports = Post;
```

and finally in `.cshtml` file
```
<div id="appRoot">
        @Html.React("Post", new
    {
        Title = @Model.Title
    })        
    </div>
    @Html.ReactInitJavaScript();
```
that's all. But I still get those error. What can cause it? When I remove @Html.React error stop appears

**Comment by dustinsoftware** [comment]
It sounds like you aren't referencing your component bundle first in your razor file, which is required for `Html.ReactInitJavaScript` to work.

Something like this in the body, before the init is called:
`<script src="./bundle.js"></script>`

**Comment by optimatex** [comment]
thanks, it works. That's strange, cuz the official [tutorial code ](https://github.com/reactjs/React.NET/blob/master/tutorial-code/Views/Home/Index.cshtml) places `@Html.ReactInitJavaScript()` at the end of the file

**Comment by dustinsoftware** [comment]
Would you mind posting a code sample that demonstrates issue you're running into?

The order of the calls is important.  It should look something like this:
```
@Html.React(...)

<script src="./bundle.js"></script>
@Html.ReactInitJavaScript()
```

[Here's an example](https://github.com/reactjs/React.NET/blob/fcf35f659402ce6936a47a3b18f76bd426d17098/tutorial-code/Views/Home/Index.cshtml)

**Comment by optimatex** [comment]
Sorry for the late response
My code is next:
template files:
```
<body>
    @RenderBody()
    <script src="@Url.Content("~/public/main.js")"></script>        
</body>
```

and the direct page for certain route:
```
@model Gistair.WebApi.Models.ServerSideRendering.TagModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="appRoot">
    @Html.React("ServerComponent", new
{
    CurrentRoute = new
    {
        pathname = Context.Request.RawUrl
    },
    nodeListModel = Model.Nodes,
    tagsListModel = Model.RelatedTags
})
</div>

<script>
    window.initialState = {
        nodeListModel: @Html.Raw(Json.Encode(Model.Nodes)),
        tagsListModel: @Html.Raw(Json.Encode(Model.RelatedTags)),
    }
</script>

@Html.ReactInitJavaScript()
```

**Comment by dustinsoftware** [comment]
Try this instead:
```
<body>
    <script src="@Url.Content("~/public/main.js")"></script>        
    @RenderBody()
</body>
```

Note that the script tag is placed before the call to `ReactInitJavaScript`.

**Comment by dustinsoftware** [comment]
Closing for now, please re-open if you'd like some more help.

**Comment by za-ek** [comment]
For me the error was putting "react" and "react-dom" on "devDependencies" block. The right solution is remove these packages and add it on "dependencies" block. Then `npm i`. (--save-dev option add package to "devDependencies" block)

**Comment by mahaleroshan00** [comment]
import React, { Component } from 'react';
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
configure({ adapter: new Adapter() });



class App extends React.Component {
    constructor(props){
        super(props);
        this.state = {
            count : 0
        };
this.handlelick = this.handleClick.bind(this);    
}
    handleClick(e){
       this.setState((preState) => {
    return {
      count : preState.count + 1
      };
   });
    }

   render(){
        return(
        <button type="button" onClick={this.handleClick}> Click</button> );
   }
}

ReactDOM.render(<App />, document.getElementById('root'));

**Comment by mahaleroshan00** [comment]
Above code structure i am using, but getting ReactDOM is not defined error.  Please somebody help on this

**Comment by dustinsoftware** [comment]
It looks like this question is about React itself, not ReactJS.NET, which is a server-side rendering library for ASP.NET and React. I recommend checking out the excellent documentation here on how to get started: https://reactjs.org/tutorial/tutorial.html

**Comment by EhsanSarshar** [comment]
in my case I just changed the ReactDom namespace. and it solved!

I just modified the react-dom.js file and added this simple code at the end of it.
windows.XReactDom = ReactDom;

or you can do like this "import YReactDom from 'react-dom'
