### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by justinkauai** [reactjs/React.NET#485]
I am trying to use Typescript,Webpack3, and mvc4 with ReactJS.net.

I get the following error using 3.4.1 and react15

> Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Hello.tsx
`import * as React from "react";

export default class Hello extends React.Component<any, any> {
    render() {
        return (<div>Hello</div>);
    }
}`

index.tsx
`module.exports = {
    // All the components you'd like to render server-side
    Hello: require('./Hello').Hello
};

var Components = require('expose-loader?Hello!./Hello');`

.tsconfig
`{
  "compilerOptions": {
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "target": "es5",
    "jsx": "react"
  }
}`

.webpack.config.ts
`module.exports = {
    entry: "./Scripts/app/src/index.tsx",
    output: {
        filename: "./Scripts/app/dist/bundle.js"
    },

    // Enable sourcemaps for debugging webpack's output.
    devtool: "source-map",

    resolve: {
        // Allow require('./blah') to require blah.jsx
        extensions: ['.tsx','.js', '.jsx']
    },
    module: {
        loaders: [
      // Transform JSX in .jsx files
      { test: /\.jsx$/, loader: 'jsx-loader?harmony' },
             {
                 test: /\.tsx?$/,
                 exclude: /(node_modules|bower_components)/,
                 loader: 'ts-loader'
             }
        ],
    },

    // When importing a module whose path matches one of the following, just
    // assume a corresponding global variable exists and use that instead.
    // This is important because it allows us to avoid bundling all of our
    // dependencies, which allows browsers to cache those libraries between builds.
    externals: {
        react: "React"
    },
};`

Any suggestions?? I have also tried 3.4.2 with react 16 and I get the following error.
`TypeError: Object doesn't support property or method 'toLowerCase'`

Any suggestions would help, Thanks!!

**Comment by dustinsoftware** [comment]
From your example you are not returning a valid dom element- you are
returning the class ‘Hello’ which is an object. If you return a string or a
div instead does the error go away?

**Comment by dustinsoftware** [comment]
Also try using require('./Hello').default instead. Mixing common js syntax
with es6 default exports doesn’t work without using a webpack plugin.

**Comment by justinkauai** [comment]
I ended up downgrading webpack and using ts-loader and refactoring the files like the mvc webpack example.

Removing the 
export default 
and using 
module.exports = Hello 
seems to have solved my issues.

Ill update if I revisit webpack3

Excited to be writing react typescript in mvc4!
Thanks!
