### ISSUE TITLE
Compile jsx and Store js

### ISSUE THREAD

**Issue by jefferson5** [reactjs/React.NET#486]
What's the best way to use the Babel transform engine to manually compile jsx so that I can store the resulting javascript for use later?  This is what I came up with so far in a simple vb.net example that seems to work.  Is there a better way?

`			
Dim babel = New React.Babel( _
				New React.ReactEnvironment( _
					New React.JavaScriptEngineFactory(JavaScriptEngineSwitcher.Core.JsEngineSwitcher.Instance, New ReactSiteConfiguration(), New React.SimpleFileSystem()), _
					New React.ReactSiteConfiguration(), _
					New React.NullCache(), _
					New React.SimpleFileSystem(), _
					New React.FileCacheHash()), _
				New React.NullCache(),
				New React.SimpleFileSystem(),
				New React.FileCacheHash(),
				New ReactSiteConfiguration()
				)

			Dim jsxString = "ReactDOM.render( <h1>Hello, world!</h1>, document.getElementById('root') );"

			Dim result = babel.Transform(jsxString)
`

**Comment by Daniel15** [comment]
`ReactEnvironment.Current.Babel.Transform` should work. There's also an MSBuild task you can use, that stores the generated file as `.generated.js` beside the original file.

**Comment by jefferson5** [comment]
Thanks!  I must have missed Current.  Much better.
