### ISSUE TITLE
Site should mention that React.AspNet requires newer NuGet

### ISSUE THREAD

**Issue by foxandrewj** [reactjs/React.NET#488]
I just started with the tutorial here: [https://reactjs.net/getting-started/tutorial.html](https://reactjs.net/getting-started/tutorial.html), using React.AspNet 3.2.
After I run "install-package react.aspnet" I get: 

> Install-Package : Package React.AspNet 3.2.0 is not compatible with net46 (.NETFramework,Version=v4.6). Package React.AspNet 3.2.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
> At line:1 char:16
> + install-package <<<<  react.aspnet
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : One or more packages are incompatible with .NETFramework,Version=v4.6.
> At line:1 char:16
> + install-package <<<<  react.aspnet
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : Package React.AspNet 3.2.0 is not compatible with net46 (.NETFramework,Version=v4.6) / win7-x86. Package React.AspNet 3.2.0 supports: netstandard2.0 (.NETStandard,Version=v2.
> 0)
> At line:1 char:16
> + install-package <<<<  react.aspnet
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : One or more packages are incompatible with .NETFramework,Version=v4.6 (win7-x86).
> At line:1 char:16
> + install-package <<<<  react.aspnet
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : Package restore failed. Rolling back package changes for 'ReactDemo46'.
> At line:1 char:16
> + install-package <<<<  react.aspnet
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

I have creating projects with Framework 4.6, 4.6.1, 4.7, and 4.7.1, all with the same results.
I am running VS 2017 Community

Installing React.AspNet v.3.1 does install.  I am going to continue with the tutorial on this version, but would love some assistance so I can eventually get onto the latest version.

Let me know if there is any more information I can provide.

**Comment by Daniel15** [comment]
That's pretty strange, as `netstandard2.0` definitely supports .NET Framework 4.6.1 and above (https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-standard-2-0/).

Please check your NuGet version, as you might have a very old one. I think you need at least NuGet 4.3.x in order to use .NET Standard 2.0 packages. If that doesn't work, I'd suggest maybe asking in the NuGet repo (https://github.com/NuGet/Home).

**Comment by Daniel15** [comment]
We should likely update the tutorial to use `dotnet add package` rather than `Install-Package`.

**Comment by foxandrewj** [comment]
That was probably it.
Nuget is packaged with VS 2017.  But I did not have the latest VS update.  After updating I can create a 4.7.1 project and install latest React 3.2
Sorry for the hassle.
Thanks!

**Comment by Daniel15** [comment]
Let's update the site to mention this :)

**Comment by dustinsoftware** [comment]
Docs have been updated since this issue was opened, I think this is resolved now.
