### ISSUE TITLE
Create a vue compatible library

### ISSUE THREAD

**Issue by mika76** [reactjs/React.NET#491]
This is great! But I already use vue quite a bit and this would be great for it. It seems to me that it would work very similarly for vue as well? Maybe with minor changes?

**Comment by dustinsoftware** [comment]
This is an interesting idea. Does on-the-fly compilation with babel, similar to JSX? Were you interested in just the server-render pieces of this library?

**Comment by mika76** [comment]
Mostly I would just like VS to internally support .vue files (which include the template, script and css) and bundle them for use - this would mean compilation with babel. Server side rendering would also be great. But I have not actually used this library so I'm not sure of all of it's features. 

But anything that can make the process of compiling and working with vue easier from VS would be great in my book. Currently for every build a webpack build has to be run too.

Sounds like it's very similar from what I've seen of the library though.

**Comment by dustinsoftware** [comment]
I think this a great idea! Unfortunately I don't think that's within the scope of this library, so I'm closing this issue, but it sounds like it would be relatively straight forward to fork babel compiler and server rendering logic! Let me know if you have questions about the internals or where to start for doing this.
