### ISSUE TITLE
ReactNotInitialisedException hides errors thrown during script load

### ISSUE THREAD

**Issue by LachlanStuart** [reactjs/React.NET#494]
When using `.SetLoadReact(false)`, if there are any JS errors during load of the user scripts, they won't be rethrown until after the check for an `React` global. This is problematic because usually the JS errors are the cause of the `ReactNotInitialisedException`.

#### Example
```c#
ReactSiteConfiguration.Configuration
    .SetLoadReact(false)
    .AddScript("~/server.js"); // server.js just contains "throw new Error()"
```

#### Expected result 

The `JsRuntimeException` that was caught is rethrown

#### Actual result 

This is thrown:

```
ReactNotInitialisedException: React has not been loaded correctly. Please expose your version of React as global variables named 'React', 'ReactDOM' and 'ReactDOMServer', or enable the 'LoadReact' configuration option to use the built-in version of React.
   React.JavaScriptEngineFactory.EnsureReactLoaded(IJsEngine engine) +151
   React.JavaScriptEngineFactory.InitialiseEngine(IJsEngine engine) +215
   ...
```

A related issue (though this hasn't affected me): due to the way that [JavaScriptEngineFactory.LoadUserScripts](https://github.com/reactjs/React.NET/blob/dd0bd7afd0ee42bf38105980d884891179ac017b/src/React.Core/JavaScriptEngineFactory.cs#L150) is written, if there are multiple user scripts and each throws an error, only the last exception will be rethrown. It would be more helpful if it was the first exception that was rethrown (or an `AggregateException`), as usually the first error causes all subsequent errors.

**Comment by dustinsoftware** [comment]
Yeah, it would be good if there was some better validation here. I've run into this before as well.

**Comment by dustinsoftware** [comment]
We added some better exception re-throwing in the latest 4.0.0 rc.
