### ISSUE TITLE
Append CSS to <Head>

### ISSUE THREAD

**Issue by NickSevens** [reactjs/React.NET#495]
Hi,
I'm trying to include `office-ui-fabric-react` with React.NET server side rendering.
For the CSS to render server-side, I need to call the function `configureLoadStyles((styles) => { ... })` which basically allows me to load the styles in a _custom_ way, so the default functionality of trying to add the CSS into `document.head` does not run - since `document` is not available server side.

However, I can't find a good way to add the styles to the `head` myself, so for now, I render the `styles` tag inside the rendered react container, which is not ideal I think...

Do you see any way how I could append the Head of the server-rendered html, from within the react app?

Thanks in advance, and thanks for the awesome work!

**Comment by dustinsoftware** [comment]
At the moment, this isn't possible. However, it looks like a custom handler can be provided per the docs [here](https://github.com/OfficeDev/office-ui-fabric-react#server-side-rendering). If we were able to build up a list of styles and emit an inline style next to the inline script, then that sounds like it solves your use case.

`Html.React("ComponentName")` => 

```
<style>
.myStyle {
}
</style>
<div id="react_randomid">
  <div class="myStyle">Component contents</div>
</div>
<script>
  ReactDOM.render(...)
</script>
```

(or something similar0

**Comment by dustinsoftware** [comment]
After further thought, I think rendering the styles inside the container is the best approach here, as you suggested. I don't know that it would be feasible to add some global style handling logic to the library without a pretty significant restructuring of how rendering works. Sorry I don't have a better answer for you 😄
