### ISSUE TITLE
Allow control of the container ID

### ISSUE THREAD

**Issue by jhemminger** [reactjs/React.NET#50]
Hi - I need to be able to control the value of the ID that is currently being generated as "react#" - I thought you may have fixed this as part of https://github.com/reactjs/React.NET/issues/45 but instead that change allows the user to define the element type.  Any chance you could include the ability to change the id?  I think others would be happy to have this ability as well.

Your code is setup well to allow for this change easily, something like so is all I need:

<h3>Addition on the Extension:</h3>

public static IHtmlString React<T>(
            this HtmlHelper htmlHelper, 
            string componentName, 
            T props,
            string htmlTag = null,
                        <b>string htmlId = null</b>
        )
        {
            var reactComponent = Environment.CreateComponent(componentName, <b>htmlId</b>, props);
            if (!string.IsNullOrEmpty(htmlTag))
            {
                reactComponent.ContainerTag = htmlTag;
            }
            var result = reactComponent.RenderHtml();
            return new HtmlString(result);
        }

<h3>Addition on ReactEnvironment:</h3>

public virtual IReactComponent CreateComponent<T>(string componentName, <b>string componentDomId</b>, T props)
        {
            EnsureUserScriptsLoaded();
<b>
            if (string.IsNullOrEmpty(componentDomId))
            {
                _maxContainerId++;
                componentDomId = string.Format(CONTAINER_ELEMENT_NAME, _maxContainerId);
            }
</b>
            var component = new ReactComponent(this, _config, componentName, <b>componentDomId</b>)
            {
                Props = props
            };
            _components.Add(component);
            return component;
        }

Thanks!

**Comment by jboliveira** [comment]
Hi @Daniel15, on the same issue, is it possible include another additional optional parameter on the helper like this:

`@Html.React("HelloWorld", new {name = "Daniel"}, "my-own-container", "my-own-class1 my-own-class2");`

*Situation:*
I have to render a list of comments, like:
```
<div id="comment-27299" class="item comment"></div>
<div id="comment-27300" class="item comment"></div>
<div id="comment-27301" class="item comment"></div>
```
It has a class applied to it that you may want for styling all comments on the page, but it also has a unique ID value (dynamically generated, nicely enough). This ID value is useful for direct linking. Now I can link directly to a particular comment on a particular page easily and keep a standard.

To set a style for each id in my css will be a little ugly, like:
```
#comment-27299{
...
}
#comment-27300{
...
}
```

So, if have a possibility to set a class-name in _@Html.React_ will be great.

Thanks.
