### ISSUE TITLE
Could not load file or assembly 'ClearScriptV8-64.DLL'

### ISSUE THREAD

**Issue by jameskraus** [reactjs/React.NET#504]
After following the directions on the ReactJS.NET site, I've been unable to get this to work. I've referenced a few threads here (e.g. https://github.com/reactjs/React.NET/issues/409), but wasn't able to resolve the issue.

Here's the error:
![image](https://user-images.githubusercontent.com/415057/35703709-0f928734-076b-11e8-87b0-2d262b8be33f.png)

ClearScriptV8-64.dll is in the bin directory of the site.

FWIW, here's Dependecy walker's view of ClearScriptV8-64.dll:
![image](https://user-images.githubusercontent.com/415057/35703980-ecf75f3c-076b-11e8-9a44-35de47f6fcd8.png)

Any ideas what is wrong here?

**Comment by dustinsoftware** [comment]
A few things to try. Does it break if you pick another JS engine like
chakra core? Do you have the Visual C++ runtime installed?

**Comment by jameskraus** [comment]
It does not break on Chakra core. (I was hoping to use V8 to get some more
info out of an error message I've had with server side rendering.)

I've got the visual c++ 2015 & 2013 x64 runtimes installed. The site is
also set up to run only x64.

On Feb 1, 2018 8:16 PM, "Dustin Masters" <notifications@github.com> wrote:

A few things to try. Does it break if you pick another JS engine like
chakra core? Do you have the Visual C++ runtime installed?

On Thu, Feb 1, 2018 at 13:25, James Kraus <notifications@github.com> wrote:

> After following the directions on the ReactJS.NET site, I've been unable
> to get this to work. I've referenced a few threads here (e.g. #409
> <https://github.com/reactjs/React.NET/issues/409>), but wasn't able to
> resolve the issue.
>
> Here's the error:
> [image: image]
> <https://user-images.githubusercontent.com/415057/
35703709-0f928734-076b-11e8-87b0-2d262b8be33f.png>
>
> ClearScriptV8-64.dll is in the bin directory of the site.
>
> FWIW, here's Dependecy walker's view of ClearScriptV8-64.dll:
> [image: image]
> <https://user-images.githubusercontent.com/415057/
35703980-ecf75f3c-076b-11e8-9a44-35de47f6fcd8.png>
>
> Any ideas what is wrong here?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/reactjs/React.NET/issues/504>, or mute the thread
> <https://github.com/notifications/unsubscribe-
auth/AA5hFqM4NysxuoPazz6bJOO_WM-GabVqks5tQivAgaJpZM4R2TqV>
> .
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/reactjs/React.NET/issues/504#issuecomment-362455363>,
or mute the thread

**Comment by Taritsyn** [comment]
Hello, James!

What version of the JavaScriptEngineSwitcher.V8 are you using?
In which of subdirectories of `bin` directory is located the `ClearScriptV8-64.dll` file?

**Comment by jameskraus** [comment]
Hey Taritsyn,

Well thanks for the questions about the subdirectory. I found that placing the ClearScriptV8-64.dll & v8-64.dll in a x64 subdirectory got rid of the error and brought my React component to life! (Originally I had them just in the root /bin directory).

It seems I misunderstood this part of your misconceptions post: 

> In this case, native assemblies are located in the x86 and x64 subdirectories of bin\[Debug|Release] directory (**_for web applications and sites just the bin directory_**).

Thank you!

**Comment by Taritsyn** [comment]
> … (Originally I had them in the root /bin directory).

Why do it manually, if the JavaScriptEngineSwitcher.V8.Native.win-x64 package itself copies everything to the right place?

**Comment by jameskraus** [comment]
It didn't copy everything into the right place for me I guess? I suppose it's supposed to copy to /x64, but I found the DLLs in the root /bin directory. Everything was installed with nuget and we're using msbuild to build our solution. I'm currently trying to figure out how to get the DLLs to show up in the correct place automatically.

**Comment by Taritsyn** [comment]
> (And yet for some reason, the ru-ru directory comes out fine??)

It uses a completely different mechanism (`lib` directory of NuGet package).

**Offtopic:** Yesterday you were wrong about the “mebibytes -> megabytes”. I recommend you to see the [following code](https://github.com/Microsoft/ClearScript/blob/044733cd76be208c9a9269b0cced21f46092499c/ClearScript/V8/V8RuntimeConstraints.cs).

**Comment by jameskraus** [comment]
> Offtopic: Yesterday you were wrong about the “mebibytes -> megabytes”. I recommend you to see the following code.

Huh, never heard of it. That's what I get for not google-checking Mebibytes.
