### ISSUE TITLE
ASP.NET MVC Tutorial Files?

### ISSUE THREAD

**Issue by JohnBergman** [reactjs/React.NET#506]
Where are the tutorial files for the ASP.NET MVC tutorial?  The ones in the tutorial folder are for ASP.NET Code.  I cannot seem to get the project to work, I am having an error while running it

Compiler Error Message: CS0115: '_Page_Views_Home_Index_cshtml.Execute()': no suitable method found to override

And have been unable to determine quite what the issue is.

**Comment by dustinsoftware** [comment]
Hi @JohnBergman 

There was a package error in the tutorial project that I just merged a fix for, please let me know if you're still having trouble.
