### ISSUE TITLE
Babel Presets

### ISSUE THREAD

**Issue by Samywamy10** [reactjs/React.NET#507]
Can I include Babel presets with the included Babel installation? For example: https://babeljs.io/docs/plugins/preset-es2017/

**Comment by dustinsoftware** [comment]
I don't think that's possible with the included babel compiler - you can use webpack with your own babel presets, though. [Here's an example](https://github.com/reactjs/React.NET/blob/master/src/React.Sample.Router.CoreMvc/.babelrc)

We could include a few babel popular babel presets if that would be useful to consumers.

**Comment by Daniel15** [comment]
The bundled Babel presets all come from babel-standalone (https://github.com/babel/babel/tree/master/packages/babel-standalone). It should come with all the standard Babel presets.

To change the presets used for ReactJS.NET's JS compilation, you can use the `BabelConfig` property of the `IReactSiteConfiguration`:

```
configuration.BabelConfig.Presets = new HashSet<string> { "es2017" };
```
