### ISSUE TITLE
Not able to identify the component with web pack bundle

### ISSUE THREAD

**Issue by nsivaji61** [reactjs/React.NET#508]
I am trying to load the bundle that have built using web pack and i am getting error saying it is not able to identify the component. I am using latest web pack and react modules. Please find my webpack.config and packages.json and routeconfig.cs file. Please let me know if i am doing some thing wrong.

const path = require('path');

const config = {
  entry: './content/server.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'server.min.js'
  },
  module: {
    rules: [
     {
        test: /\.jsx$/,
        use:[
			{
                            loader: 'babel-loader',
                            options: {
                                babelrc: false,
                                presets: [
                                    ['env', {
                                        "targets": {
                                            "browsers": ["last 2 versions", "safari >= 7"]
                                        }
                                    }],
                                    'react',
                                    'stage-2'
                                ]
                            }
            }
		],
        exclude: /node_modules/,
      },
    ]
  }
};

module.exports = config;

**package.json**
{
  "name": "React.Sample.Webpack",
  "version": "0.0.1",
  "description": "Webpack + ASP.NET MVC 4 sample for ReactJS.NET",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack"
  },
  "author": "",
  "license": "BSD",
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "~6.5.0",
    "expose-loader": "^0.7.1",
    "react": "^16.0.0",
    "webpack": "^3.5.6"
  }
}

**package.json**

{
  "name": "React.Sample.Webpack",
  "version": "0.0.1",
  "description": "Webpack + ASP.NET MVC 4 sample for ReactJS.NET",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack"
  },
  "author": "",
  "license": "BSD",
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "~6.5.0",
    "expose-loader": "^0.7.1",
    "react": "^16.0.0",
    "webpack": "^3.5.6"
  }
}

**ReactConfig.cs**
  ReactSiteConfiguration.Configuration
		        .SetLoadBabel(false)
		        .AddScriptWithoutTransform("~/dist/server.min.js");

**Comment by gazab** [comment]
What does your content/server.js look like?

**Comment by nsivaji61** [comment]
var Components = require('expose-loader?Components!./components');

**Comment by nsivaji61** [comment]
Now i am seeing different exceptions . Please find the new exceptions below .
React has not been loaded correctly. Please expose your version of React as global variables named 'React', 'ReactDOM' and 'ReactDOMServer', or enable the 'LoadReact' configuration option to use the built-in version of React.

**Comment by dustinsoftware** [comment]
Hi @nsivaji61 

Please try loading your component bundle either in a standalone Chrome page or Node instance, and verify that `React` is present on the global scope. If it's not, then it hasn't been exposed properly. You can take a look at the `React.Sample.Router.CoreMvc` project in this repo, it's probably the closest to your set up.

Feel free to reply, but I'm going to close this issue since it doesn't seem to be a bug in the library.
