### ISSUE TITLE
[Help wanted] Server side render get ReactInvalidComponentException: Could not find a component named.Did you forget to add it to App_Start\ReactConfig.cs?

### ISSUE THREAD

**Issue by ngohungphuc** [reactjs/React.NET#510]
I have a question that I have already add `config.AddScript("~/wwwroot/dist/login.js");` in [Starup](https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/blob/c2aa39486cd8f1452087661f31f0b4a817f3a69d/src/AwesomeCMSCore/AwesomeCMSCore/Extension/ApplicationBuilderExtensions.cs#L109)

And [In my view](https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/blob/c2aa39486cd8f1452087661f31f0b4a817f3a69d/src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Views/Account/Login.cshtml) I add  `@Html.ReactInitJavaScript()` but seem like the web doesnt boost up faster than I just add only script tag in the view.

Is my config right ? If not am I missing something to make server side render work as expected

**Comment by dustinsoftware** [comment]
Hi tony,

Are you calling HTML.React() where you want your component to render?
ReactWithInit is used only at the very bottom of the page to initialize all
of the rendered components.

**Comment by ngohungphuc** [comment]
@dustinsoftware I just have the login form so that user can login to the system and doesnt have any init data

**Comment by ngohungphuc** [comment]
@dustinsoftware I just want to render a login form for user to login. That's all

**Comment by ngohungphuc** [comment]
I get the following error though I'm using ASP.Net Core 2.0
`ReactInvalidComponentException: Could not find a component named 'LoginForm'. Did you forget to add it to App_Start\ReactConfig.cs?`

My view
```
<div id="loginForm">
</div>

@section Scripts {
    @Html.React("LoginForm", new { })
    <script src="@Url.Content("~/dist/login.js")"></script>
    @Html.ReactInitJavaScript()
}
```

**Comment by ngohungphuc** [comment]
@dustinsoftware I just want to render a login form for user to login. That's all

I get the following error though I'm using ASP.Net Core 2.0
`ReactInvalidComponentException: Could not find a component named 'LoginForm'. Did you forget to add it to App_Start\ReactConfig.cs?`

My view
```
<div id="loginForm">
</div>

@section Scripts {
    @Html.React("LoginForm", new { })
    <script src="@Url.Content("~/dist/login.js")"></script>
    @Html.ReactInitJavaScript()
}
```

**Comment by ngohungphuc** [comment]
The problem I get is webpack mangle options still not find a way to fix it

**Comment by ngohungphuc** [comment]
@dustinsoftware any suggest
