### ISSUE TITLE
Missing parentheses: tutorial.jsx

### ISSUE THREAD

**Issue by kwhjvdkamp** [reactjs/React.NET#511]
return (
    <div className="commentList">
        {commentNodes}
    </div> 
);

**Comment by dustinsoftware** [comment]
@kwhjvdkamp thanks, would you mind linking to the source where the typo is, or submit a pull request?

**Comment by kwhjvdkamp** [comment]
Hi Dustin (@dustinsoftware), if I remember well on your blog (tutorial) at React.Net website (not your github code)

**Comment by dustinsoftware** [comment]
Can't repro this on latest master, maybe it's already fixed...
