### ISSUE TITLE
ReactJS.MSBuild cannot find Newtonsoft.Json Version=9.0.0.

### ISSUE THREAD

**Issue by jadebayo** [reactjs/React.NET#512]
Trying to add React.MSBuild, but when the TransfomrBabel Task is called i get this issue. My project uses Newtonsoft.Json 11.0 and there is a assembly redirect to it.  

1> : error MSB4018: The "TransformBabel" task failed unexpectedly.
1> : error MSB4018: React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.IReactSiteConfiguration ---> System.TypeInitializationException: The type initializer for 'React.ReactSiteConfiguration' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
1> : error MSB4018: at React.ReactSiteConfiguration..ctor()
1> : error MSB4018: at React.ReactSiteConfiguration..cctor()
1> : error MSB4018: --- End of inner exception stack trace ---
1> : error MSB4018: at React.ReactSiteConfiguration.get_Configuration()
1> : error MSB4018: at React.AssemblyRegistration.<>c.<Register>b__2_0(TinyIoCContainer c, NamedParameterOverloads o)
1> : error MSB4018: at React.TinyIoC.TinyIoCContainer.<>c__DisplayClass29_0`1.<Register>b__0(TinyIoCContainer c, NamedParameterOverloads o)
1> : error MSB4018: at React.TinyIoC.TinyIoCContainer.DelegateFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
1> : error MSB4018: --- End of inner exception stack trace ---
1> : error MSB4018: at React.TinyIoC.TinyIoCContainer.DelegateFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
1> : error MSB4018: at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
1> : error MSB4018: at React.TinyIoC.TinyIoCContainer.Resolve(Type resolveType)
1> : error MSB4018: at React.TinyIoC.TinyIoCContainer.Resolve[ResolveType]()
1> : error MSB4018: at React.MSBuild.TransformBabel.Execute()
1> : error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1> : error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1> (default targets) -- FAILED.

**Comment by dustinsoftware** [comment]
Hi there, I'm not sure if `React.MSBuild` will work with binding redirects, you might have better luck using a webpack build step instead (see the samples in this repo). Unfortunately I don't have time right now to investigate support for this :/

**Comment by Daniel15** [comment]
Unfortunately, MSBuild does not easily support assembly redirects. You'd need to add them to `MSBuild.exe.config`, and they'd affect **all** MSBuild calls (not just builds of your project).

ReactJS.NET does have a super hacky binding redirect for JavaScriptEngineSwitcher, where we override `AppDomain.CurrentDomain.AssemblyResolve` and manually perform the redirect ourselves (https://github.com/reactjs/React.NET/commit/c366e3dd75c45777cb6e78c755b2e9ed063e6033). We could likely do that for Newtonsoft.Json too. I'm worried about breaking stuff, as that assembly binding stuff is very fragile.

**Comment by Daniel15** [comment]
Unfortunately, MSBuild does not easily support assembly redirects. You'd need to add them to `MSBuild.exe.config`, and they'd affect **all** MSBuild calls (not just builds of your project).

Having said that, ReactJS.NET does have a super hacky binding redirect for JavaScriptEngineSwitcher. The way it's implemented is that we override `AppDomain.CurrentDomain.AssemblyResolve` and manually perform the redirect ourselves (https://github.com/reactjs/React.NET/commit/c366e3dd75c45777cb6e78c755b2e9ed063e6033). We could likely do that for Newtonsoft.Json too. I'm worried about breaking stuff, as that assembly binding stuff is very fragile.

References:
https://github.com/Microsoft/msbuild/issues/1309
http://blog.slaks.net/2013-12-25/redirecting-assembly-loads-at-runtime/

**Comment by dustinsoftware** [comment]
Closing since this question has been answered, feel free to re-open if you'd like some more help.

**Comment by ssaroiu** [comment]
I'd like to re-open this issue. I have the exact same problem as @jadebayo.

As per this conversation, there are two ways to fix this issue:

1. Add Newtonsoft.Json to the list of assemblies for which manual redirect is resolved by overriding `AppDomain.CurrentDomain.AssemblyResolve' (as per @Daniel15's comment above). I understand this is brittle, but this hack is already present in the code, and it will fix this problem (I checked). 

2. If the solution is to use `webpack` instead (as per @dustinsoftware's comment above), I'd suggest to update the relevant documentation. As is, the documentation for React.MSBuild is silent on `webpack`. Instead, when I follow the documentation, my build fails due to this bug.

References:
[https://reactjs.net/bundling/msbuild.html](url)

**Comment by dustinsoftware** [comment]
I’ll update the docs, thanks

**Comment by dustinsoftware** [comment]
Also there isn’t a reason we should be stuck to an old Json.Net version,
I’ll update that as well

**Comment by ssaroiu** [comment]
Both will work for me. How are these two tracks so that I know when they're ready?

Thanks!

**Comment by dustinsoftware** [comment]
I think we can bump the version of JSON.NET that is used internally to
avoid this problem. 9 is pretty old at this point.

**Comment by kendallb** [comment]
It will keep coming up, and if the build dll is referenced from the NuGet location then it also removes the need for extra dependencies to be added to my project bin directory. The way razor does it works nicely.

**Comment by ssaroiu** [comment]
I agree with @kendallb that bumping out the version number is a band-aid rather than a *fix*. It'll break again couple of months down the road when Newtonsoft updates their JSON.NET nuget.

**Comment by kendallb** [comment]
As mentioned, the right solution is to deploy the build DLL into the nuget directory like they do with Razor Generator and run it from there. Then its dependencies are entirely it's own.

**Comment by dustinsoftware** [comment]
Ok, would you be able to send a pull request? I don’t have time to
investigate unfortunately :)

**Comment by kendallb** [comment]
Yeah I am not sure I am going to go this route anyway. I was desperately trying to avoid using node and packages (gah, I don't like node much!), but I think the better solution for our project is to use Gulp to pre-process all our JSX files at build time and then it will also do all the minification and bundling as well. Just have to bite the bullet I guess and get on the node train ...

**Comment by dustinsoftware** [comment]
Going to roll with bumping JSON.NET to 12 in #779. Apps that still need 9.x can remain on the 4.x branch of this library, which we'll backport fixes to. New features we'll put in 5.x.

**Comment by dustinsoftware** [comment]
5.0.0-alpha1 preview published to NuGet, please install from there if you need this support ahead of the release.

Cheers
