### ISSUE TITLE
Sample or walkthrough of using React.Net with Cordova

### ISSUE THREAD

**Issue by JohnBergman** [reactjs/React.NET#515]
I have been really struggling getting React to work with Cordova within VS2017; anyone point me to a sample of something working (sample-wise) or documentation on how to get it all integrated and working?

**Comment by dustinsoftware** [comment]
Hi @JohnBergman this is a library for rendering React components on ASP.NET and running JSX through Babel on the fly, I'm not sure how this applies to Cordova.. Are you trying to write a server-side app and have a thin client as described [here](https://docs.microsoft.com/en-us/visualstudio/cross-platform/tools-for-cordova/tips-workarounds/run-web-app-in-cordova)?

**Comment by JohnBergman** [comment]
More or less, where the front end is React based.

**Comment by dustinsoftware** [comment]
This issue fell off my radar. Beyond the samples contained in this repo, I'm not sure this library supports your use case.
