### ISSUE TITLE
Cannot resolve React.JavaScriptEngineFactory

### ISSUE THREAD

**Issue by TheFlow0360** [reactjs/React.NET#517]
I'm currently trying to use React.NET Core to enable my minimal webserver implementation to deliver a react app. I don't use ASP or any other web framework.

I initialized everything as recommended in [#178](https://github.com/reactjs/React.NET/issues/178), but the container is unable to resolve the ReactEnvironment when accessing `ReactEnvironment.Current`, because `React.JavaScriptEngineFactory` can't be resolved, either. Exception is:

> System.IO.FileLoadException: Could not load file or assembly 'JavaScriptEngineSwitcher.Core, Version=2.4.0.0, Culture=neutral, PublicKeyToken=c608b2a8cc9e4472' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

My packages.config:

    <packages>
      <package id="JavaScriptEngineSwitcher.ChakraCore" version="2.4.8" targetFramework="net461" />
      <package id="JavaScriptEngineSwitcher.Core" version="2.4.9" targetFramework="net461" />
      <package id="JavaScriptEngineSwitcher.Msie" version="2.4.9" targetFramework="net461" />
      <package id="JavaScriptEngineSwitcher.V8" version="2.4.2" targetFramework="net461" />
      <package id="JSPool" version="3.0.1" targetFramework="net461" />
      <package id="MsieJavaScriptEngine" version="2.2.2" targetFramework="net461" />
      <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net461" />
      <package id="React.Core" version="3.3.0" targetFramework="net461" />
      <package id="System.Dynamic.Runtime" version="4.0.0" targetFramework="net461" />
      <package id="VroomJs" version="1.2.3" targetFramework="net461" />
    </packages>

The project is compiled as dll and dynamically loaded by another service. However, there aren't any other libraries loaded that depend on any of the NuGets I use.

What am I doing wrong?

**Comment by dustinsoftware** [comment]
Do you have any assembly binding redirects in your config file? If not, you
could try adding one to work around the problem.

**Comment by TheFlow0360** [comment]
No I don't have any, the problem is I could only add them to the App.config of my ServiceLoader. However, I don't want this Loader to know about the library that's using react. I already tried to look into providing BindingRedirects from inside my lib, but didn't find anything suitable yet.

**Comment by TheFlow0360** [comment]
I don't really get how the dependencies of these libs work. I checked the dependencies of all the NuGets that got installed with React.Core and they all list "JavaScriptEngineSwitcher.Core (>= 2.4.10)", except for JSPool which has "JavaScriptEngineSwitcher.Core (>= 2.4.9)".The installed version of JavaScriptEngineSwitcher.Core is 2.4.9, too. My guess was, that i just have to update it to 2.4.10, but when I do this, I can't even load my DLL anymore (ReflectionTypLoadException)

**Comment by dustinsoftware** [comment]
A breaking change may have been made in a later version. On my phone so
can’t look right now. Try adding a binding redirect for the version that
react.net wants just to see if it works.

**Comment by TheFlow0360** [comment]
I enabled [Automatic Binding Redirection](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection) and it solved the problem. Thanks for your quick help!
