### ISSUE TITLE
Reactjs NET not initialized correctly

### ISSUE THREAD

**Issue by Upd4ting** [reactjs/React.NET#518]
Hello there,
I'm having trouble trying to host a ASP.NET core using reactjs net on Linux. 
When I run the application in VS all is working fine.
When I host it on Linux, when I try to go on the web page on the server I get an error "Reactjs NET not initialized correctly"

Any idea?

**Comment by Taritsyn** [comment]
Hello, Rizzitelli!

Try to install the [JavaScriptEngineSwitcher.ChakraCore.Native.linux-x64](https://www.nuget.org/packages/JavaScriptEngineSwitcher.ChakraCore.Native.linux-x64/2.4.14) package.

**Comment by Upd4ting** [comment]
How do you install that on linux?

**Comment by Taritsyn** [comment]
```
dotnet add package JavaScriptEngineSwitcher.ChakraCore.Native.linux-x64 --version 2.4.14 
```

**Comment by Upd4ting** [comment]
I added it via nugget on VS, now when I start the APP on Linux that's telling me that the package is not found, how do I install it on linux?

**Comment by Taritsyn** [comment]
This is problem of deployment.

You have the following code in `*.csproj` file?

```xml
<PropertyGroup>
	<RuntimeIdentifiers>…;linux-x64</RuntimeIdentifiers>
</PropertyGroup>
```

**Comment by Upd4ting** [comment]
I added it manually and republished in a folder, transfered it on my linux server and I have still the same error :/

**Comment by Taritsyn** [comment]
Show me a full error message with stack trace.

**Comment by Upd4ting** [comment]
Here is the stack trace: https://gyazo.com/b9c20979423865e42a39c91cb7a48806

**Comment by Taritsyn** [comment]
Check a existence of the `runtimes/linux-x64/native/libChakraCore.so` file in web application directory.

**Comment by Upd4ting** [comment]
I can't find a fold "runtimes" https://gyazo.com/89dc1f71dbb3e068903bc6bdecc0d590

**Comment by Taritsyn** [comment]
This directory must exist. You have some kind of deployment error. When you deploy by using а Visual Studio, this directory is created. I recommend you to read the [“Publish your Hello World application with Visual Studio 2017”](https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio) article.

If you did not use a Visual Studio deployment tools, but simply copied the directory with source code and the `bin` directory, then you need to run the following command on web application directory:

```
dotnet restore
```

**Comment by Upd4ting** [comment]
Yes that was a deployment error all is working fine now!
My react initialization problem has been fixed by installing JavaScriptEngineSwitcher like you told me.
A big thanks to you! @Taritsyn

**Comment by Taritsyn** [comment]
Excellent!
