### ISSUE TITLE
SSR with React Router

### ISSUE THREAD

**Issue by aventic** [reactjs/React.NET#519]
Is it possible to get a working example (possibly a github repo) of a simple ASP.NET MVC site, including React and React Router? No matter what I do I end up with the following in the console "Text content did not match. Server: "X" Client: "XX"", when refreshing on a new url which is not the home "/" url

I even had to rewrite the mvc routes to get my subpages to render from:

```
routes.MapRoute(
  name: "Default",
  url: "{controller}/{action}/{id}",
  defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
);
```

to: 

```
routes.MapRoute(
  name: "Default",
  url: "{*url}"
  defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
);
```

Something the documentation does not explain - or am I simply missing something?

**Comment by dustinsoftware** [comment]
There are samples in this repo, have you looked at those yet?

**Comment by aventic** [comment]
@dustinsoftware - Yes I have but sadly there is only the one under "tutorial-code" - which seems to be for ASP.NET Core - right?

**Comment by dustinsoftware** [comment]
There are more samples in the src directory

**Comment by aventic** [comment]
I see, but none of those is React Router and ASP.NET MVC only Core

**Comment by aventic** [comment]
Furthermore do I have to pass current url down via prop like this `@Html.ReactRouter("Routing", new { path = Request.RawUrl })` it seem to work, but can't seem to find any documentation on that?

**Comment by dustinsoftware** [comment]
Router support is pretty new. I'd like to get the docs updated and some of
the samples unified but we're not there yet.

The only sample we have that has Router support is
React.Sample.Router.CoreMvc. It would be trivial to port that example to
full ASP.NET (just use some kind of wildcard route and pass the path down
to the component).

**Comment by aventic** [comment]
Aha okay I see. I just took a glance at the React.Sample.Router.CoreMvc you mention. Which I took some inspiration from, just confused that it can resolve the path without it being passed down as a prop.

**Comment by dustinsoftware** [comment]
Closing since this question has been answered, feel free to re-open if you'd like some more help 😄
