### ISSUE TITLE
How to install npm modules 

### ISSUE THREAD

**Issue by Upd4ting** [reactjs/React.NET#523]
Hello i'm having a little problem, i'm trying to install https://github.com/FormidableLabs/react-game-kit
but there is no nuget package for this so I need to install the npm package but I don't know what to import in the ViewImport.cshtml :/

**Comment by Upd4ting** [comment]
Okay so I managed to import the npm modules correctly, see there: https://gyazo.com/b7678f9ef8ba21c442a74dad120fecc1
I have this react component that use some component from react-game-kit https://gyazo.com/afc95f08f09710e887d8e7d98dd0b59f
but I'm having this error: https://gyazo.com/a9891cf28ba5ddc98446051f7c573244

I have to say that if I don't use any react game kit component in my component, that's working

**Comment by Upd4ting** [comment]
Okay I think that my problem come from that: https://gyazo.com/9a32f4c58ad51965bd90ee24d5889a28
The react-game-kit component aren't added there but I don't really know how I should add them

**Comment by dustinsoftware** [comment]
You'll need to use webpack and create a component bundle before you import modules from `npm`. Here's an [example project](https://github.com/reactjs/React.NET/tree/master/src/React.Sample.Webpack). Let me know if you need more help (please upload your source code to github, it will help us diagnose the problem faster! 😄 )

**Comment by Anandks1993** [comment]
@dustinsoftware The link of example project is broken it seems. I am in need of that link. Can you please re-share it. Thank you

**Comment by dustinsoftware** [comment]
Here you go: https://github.com/reactjs/React.NET/tree/master/src/React.Sample.Webpack.CoreMvc

@Anandks1993
