### ISSUE TITLE
Revisit licensing

### ISSUE THREAD

**Issue by pschaeflein** [reactjs/React.NET#524]
Given that ReactJS has [changed to an MIT license](https://github.com/facebook/react/commit/b765fb25ebc6e53bb8de2496d2828d9d01c2774b), will this library also change?

**Comment by MikitaBazhkou** [comment]
Any news? :)

**Comment by Daniel15** [comment]
Sorry for the delay! I changed the license, and the updated license will be in effect as of the upcoming 4.0 release.
