### ISSUE TITLE
Source map request return 500 when using MsieJavaScriptEngine

### ISSUE THREAD

**Issue by lijunle** [reactjs/React.NET#53]
After long time investigation, the following statement returns different output in IE10 and IE11:

```
JSXTransformer.transform("var a = <span className=\"fuck\"/>", {sourceMap:true})
```

In IE11, which looks fine (notices that `sourceMap` object is generated):

```
{code: "var a = Rea...", extra: Object {...}, sourceMap: Object {...}, sourceMapFilename: "source.js"}
```

In IE10, suck... the `sourceMap` gone :(

```
{code: "var a = Rea...", extra: Object {...}}
```

When using MSIE JavaScript switcher in Json.Net, it is running in `ChakraActiveScript` mode, [its document][1] says `ChakraJsRt` mode leverage IE11. While I try with [this way][0], but it does not work, still in `ChakraActiveScript` mode.

Any idea on this?

[0]: https://github.com/Taritsyn/JavaScriptEngineSwitcher/blob/6a2dbb6f58e4fe2b7a4dc4b09dd204e001453c23/JavaScriptEngineSwitcher.Tests/App.config#L24

[1]: https://github.com/Taritsyn/MsieJavaScriptEngine/blob/master/README.md

---

Besides, I think when send transformed JSX, it should check if it can generate source map before set the JSX header.

**Comment by domenu** [comment]
Same here, getting HTTP 500 (Unable to generate source map) in chrome...

**Comment by Daniel15** [comment]
@ashic Installing `React.JavaScriptEngine.ClearScriptV8` should be sufficient to force V8.

**Comment by daniellmb** [comment]
Yep installing ClearScript fixed it for me...

**Comment by evenkiel** [comment]
+1. Installed React.JavaScriptEngine.ClearScriptV8 via nuget to my MVC project and the 500 errors went away. Thanks!

**Comment by Daniel15** [comment]
Closing this out since V8 (ClearScript / VroomJs) is bundled by default now.
