### ISSUE TITLE
Replace html helpers with tag helpers

### ISSUE THREAD

**Issue by tachyon1337** [reactjs/React.NET#536]
Any thoughts of replacing the the html helper syntax with the newer tag helpers feature? Not a biggie, but the syntax would be a bit more elegant.

```html
@Html.React("MyReactComponent", new { initialData = Model })
<react-component id="MyReactComponent" prop="initialData" data=@Model  />
```

**Comment by Daniel15** [comment]
Sure, feel free to submit a pull request for it :D 

Note that ReactJS.NET still supports older versions of ASP.NET, so it couldn't exclusively switch to tag helpers. However, I'd have no problem with supporting tag helpers for newer vesions.

**Comment by tachyon1337** [comment]
> Sure, feel free to submit a pull request for it :D

hah, I thought you might say that. I've thought about writing a package to do it, but it would be a separate nuget package *.TagHelpers with a dependency on React.AspNet. Easier for me that way.

**Comment by Daniel15** [comment]
> hah, I thought you might say that.

I didn't used to, but these days I don't have a lot of free time for open-source work.

> it would be a separate nuget package *.TagHelpers with a dependency on React.AspNet
Sure, that'd be fine. You could add it to the ReactJS.NET repo if you like. The `React.Router` package was another community contribution: https://github.com/reactjs/React.NET/tree/master/src/React.Router

**Comment by tachyon1337** [comment]
> Sure, that'd be fine. You could add it to the ReactJS.NET repo if you like. The React.Router package was another community contribution: 

Ok, I likely will tackle that within the next month or two, given that my development projects are now starting to a have a nontrivial reliance on React.AspNet.

**Comment by dustinsoftware** [comment]
I'm closing issues for future work like this that aren't actively being worked on, but would be open to adding support for this!

#655
