### ISSUE TITLE
Update server-render documentation

### ISSUE THREAD

**Issue by dustinsoftware** [reactjs/React.NET#540]
https://github.com/reactjs/React.NET/blob/master/site/jekyll/guides/mono.md

Server-side render components is also possible on non-Windows platforms with the [JavaScriptEngineSwitcher.ChakraCore](https://www.nuget.org/packages/JavaScriptEngineSwitcher.ChakraCore/) package, without having to compile V8.

For example, add this package to an ASP.NET Core project:
```xml
<PackageReference Include="JavaScriptEngineSwitcher.ChakraCore.Native.osx-x64" Version="2.4.15" />
```

And then set it as the default engine in `Startup.cs`:

```csharp
JsEngineSwitcher.Instance.DefaultEngineName = "ChakraCoreJsEngine";
```

**Comment by Daniel15** [comment]
Good catch, we can likely remove (or archive) that entire page now that ChakraCore works on non-Windows platforms. I haven't tested ChakraCore with Mono, but it works with .NET Core.
