### ISSUE TITLE
Webpack and DotNetCore 2.0

### ISSUE THREAD

**Issue by Neuroforge** [reactjs/React.NET#553]
Hello,

I have followed the Webpack tutorial using a dotnetcore 2.0 app.

`ReactInvalidComponentException: Could not find a component named 'CommentBox'. Did you forget to add it to App_Start\ReactConfig.cs?`

DotNetCore 2.0 doesn't use App_Start for configuration any more.

```
            // Initialise ReactJS.NET. Must be before static files.
            app.UseReact(config =>
            {
                config
                    .SetUseDebugReact(true)
                    .SetLoadBabel(false)
                    .AddScriptWithoutTransform("~/build/server.bundle.js");
            });
```

This appears to be finding the server.bundle.js as if i change that filename i get an error for it's location.

It appears that ReactJs.Net is expecting App_Start\ReactConfig.cs when using dotnetcore 2.0.

Any thoughts or tips on how to solve?

Regards,

Daniel

Same issue, no solution posted.
https://github.com/reactjs/React.NET/issues/510

**Comment by dustinsoftware** [comment]
There are samples in this repo that use .net core 2.0, have you looked at those yet? There is also a tutorial for .net core but it may need updating.

**Comment by Daniel15** [comment]
Make sure you're exposing the components globally, as mentioned on https://reactjs.net/guides/webpack.html.

**Comment by WonSong** [comment]
I had this issue, and thought there was something wrong with the code, but turns out that you have to restart your server app every time you make changes to your code.

**Comment by Daniel15** [comment]
> turns out that you have to restart your server app every time

@WonSong - You shouldn't; ReactJS.NET listens for changes to files and reloads all the files if they're modified. You may be hitting a bug. Can you please file a separate issue for that?

**Comment by Neuroforge** [comment]
Hello,

I tried again with a number of different combinations. It appears the components are being exposed globally.

**Content/server.js**
https://pastebin.com/u2W3ywjt

**Content/Components/Index.js**
https://pastebin.com/p1VaCqTQ

**StartUp.cs**
https://pastebin.com/XaENyJWj

**Components/CommentBox.jsx**
https://pastebin.com/TDJUyrhd

**~/Views/Home/Index.cshtml**
https://pastebin.com/M1XVcnEG

I've looked at the samples in the repo and tried out some of the differences there...

**StartUp.cs** based on https://github.com/reactjs/React.NET/blob/master/src/React.Sample.Router.CoreMvc/Startup.cs
https://pastebin.com/Jm3yuM9X

This returns the following....

> ReactNotInitialisedException: React has not been loaded correctly. Please expose your version of React as global variables named 'React', 'ReactDOM' and 'ReactDOMServer', or enable the 'LoadReact' configuration option to use the built-in version of React.


Also, when running on a mac i recieve the following issue for VroomJs, not sure if related. - https://github.com/reactjs/React.NET/issues/129

**Comment by dustinsoftware** [comment]
I believe your issue is related to #555 . Can you use react and react-dom 16.4.0 to see if the issue goes away?

**Comment by Neuroforge** [comment]
Ok. I've always kept 'LoadReact' as True.

I do get the issue in https://github.com/reactjs/React.NET/issues/555 when i set it to false. I will attempt to use the newer version with LoadReact set to false.

**Comment by WonSong** [comment]
@Neuroforge 

I created this example just for you: https://github.com/WonSong/ReactDotNetTypeScriptWebpackDemo

**Comment by WonSong** [comment]
@naoufal  For vroomjs issue in mac, you need this:

services.AddJsEngineSwitcher(options => options.DefaultEngineName = ChakraCoreJsEngine.EngineName)
				.AddChakraCore();

**Comment by Neuroforge** [comment]
@WonSong Wow! Thank you so much. I will try it out tonight!

**Comment by Neuroforge** [comment]
@WonSong I wasn't able to get your project working as it needs the new .NET Core SDK.

I moved all of your setup into a new branch on my repo. Worked perfectly!

Thank you so much. You should update the tutorial with your code.

**Comment by WonSong** [comment]
@Neuroforge 

I created another sample for using JSX: https://github.com/WonSong/ReactDotNetJSXWebpackDemo
It's still using dotnet 2.1 though

**Comment by Neuroforge** [comment]
@WonSong Amazing.

Works great.
