### ISSUE TITLE
Server side rendered components require server restart to take effect

### ISSUE THREAD

**Issue by WonSong** [reactjs/React.NET#554]
Using ASP.NET Core 2.1
Webpack 4
Typescript 2.9

**Comment by Daniel15** [comment]
@WonSong - If you attach a debugger, do you see messages like this when you change the files?

> [JSPool] Watched file 'foo.js' changed

@dustinsoftware Do you have any ideas on this? We do configure JSPool to recycle the pool on change:

https://github.com/reactjs/React.NET/blob/c90a4a645e493855877fcf8ebde9d0474e9b8a62/src/React.Core/JavaScriptEngineFactory.cs#L93-L94

And then JSPool uses a `FileSystemWatcher`:

https://github.com/Daniel15/JSPool/blob/master/src/JSPool/FileWatcher.cs#L90-L102

Perhaps we're not passing the file names correctly, or passing the wrong path, or something like that.

**Comment by dustinsoftware** [comment]
I was able to repro this issue with webpack 4. Try downgrading to webpack 3 and see if you're still having problems.

**Comment by dustinsoftware** [comment]
The webpack 4 issue I thought I was encountering was a red herring, webpack 4 changed the default destination to `dist` so my changes weren't going to the write folder like I thought they were :) One thing I didn't ask earlier, are you using Windows or another platform?

**Comment by WonSong** [comment]
On Windows

**Comment by WonSong** [comment]
I created a sample app, but seeing the same issue on Mac. Here's the repo: https://github.com/WonSong/ReactDotNetTypeScriptWebpackDemo

**Comment by dustinsoftware** [comment]
Thanks @WonSong. I'll look at this in the next few days.

**Comment by knyzorg** [comment]
I have wasted a lot of time struggling with this. Is there an ETA?

**Comment by dustinsoftware** [comment]
Haven’t had time to look at this one yet. Details about your environment
would be helpful

Can you paste your packages.config in this issue? What version of asp.net
and .net framework are you on? 32 bit or 64 bit process?

**Comment by knyzorg** [comment]
I no longer have a project using it. The general buginess and unreliability of it made me switch away.

**Comment by dustinsoftware** [comment]
Glad you found another solution that fits your needs.

**Comment by dustinsoftware** [comment]
Sorry, that response may have come across as terse. I intend to debug this problem but can’t do so without detailed information about the environment this library runs in, since the bug hasn’t occurred when I have attempted to repro it.

**Comment by WonSong** [comment]
i still have this issue in ASP.NET Core MVC 2.1.301 both on 64bit latest MacoOs and 64bit windows 10. Still using same template as the one I provided above.

**Comment by dustinsoftware** [comment]
Ok, so here's what I did to try and repro the issue (no luck). Please let me know if I am missing something. .NET Core 2.1 on OS X.

1. Cloned your repo
1. `yarn` to restore packages
1. `yarn start` to run webpack
1. `dotnet run` to start the dev server
1. Opened the browser, saw components render successfully
1. Made a component render change in `Hello.tsx`
1. Observe that the server-rendered change worked when reloading the window

**Comment by LinusCenterstrom** [comment]
Having the same issue here, turning off re-use fixed it for me too (I'm running version 3.2 on aspnet core 2.1).
Been running it in a Mvc 4 app for a long time without seeing this issue (exact same configuration and bundle), so it seems to be core-specific. 

I've temporarily turned off re-use of the rendering engine when running locally and I would recommend anyone else to do the same as a workaround until this is fixed.

Let me know if you need anymore information to identify the problem.

**Comment by dustinsoftware** [comment]
Thanks that is very helpful. I’ll take a closer look. This may be a JSPool
specific issue, could you tell me what version is getting used? It is a
downstream package also you may need to look at the project lock file.

**Comment by dustinsoftware** [comment]
Ok I've finally nailed down a repro. Digging further.

**Comment by dustinsoftware** [comment]
Please update to 3.4.1 and let me know if the issue is resolved. @WonSong @knyzorg @LinusCenterstrom @benjamn
