### ISSUE TITLE
Crash when using React 16.4.1

### ISSUE THREAD

**Issue by dustinsoftware** [reactjs/React.NET#555]
While investigating #554, I discovered that React.NET totally breaks when using `react` and `react-dom` 16.4.1, but 16.4.0 seems to be unaffected, so users can pin to that version until we ship a fix.

Unfortunately the crash is obscured by a check that looks for React on the global scope. To see the real exception, patch `ReactNET_initReact` to always return `true` in `shims.js`. I'll open up a separate issue to investigate whether we still need to have that method around (we'd just crash at runtime if one of the globals was missing, right?)

Anyhow. The real crash is `ReactScriptLoadException: Error while loading "~/components-bundle.generated.js": ReferenceError: 'setTimeout' is not defined`

Which corresponds to `SelectEventPlugin`:
```js
// We capture a local reference to any global, in case it gets polyfilled after
// this module is initially evaluated.
// We want to be using a consistent implementation.
var localDate = Date;
var localSetTimeout = setTimeout; // crash!
var localClearTimeout = clearTimeout;
```

The regression appears to be introduced by this change: https://github.com/facebook/react/pull/12931/files#diff-bbebc3357e1fb99ab13ad796e04b69a6L47

I'll open an issue tomorrow and investigate a fix. cc @Daniel15

**Comment by ChadBurggraf** [comment]
As a temporary workaround for folks, you can add the following shim to the beginning of your configuration scripts:

https://gist.github.com/ChadBurggraf/4c4abef515852aa1efee04478a8a8641

**Comment by dustinsoftware** [comment]
I ran out of time to investigate this today, I'll pick it up again in a few days if someone doesn't get to it first. I wanted to repro the issue with the `master` branch of react since it looks like some recent changes have been made in the scheduler.

**Comment by Neuroforge** [comment]
@ChadBurggraf Where in the code do you add that?

I am seeing this error since adding Video.js via npm.

**Comment by Neuroforge** [comment]
@dustinsoftware When will this be released via Nuget? Or do i have to build from source now?

**Comment by dustinsoftware** [comment]
You need to pin to 16.4.0 or add the shim to your scripts. I’ll work on
adding a shim to the library itself but it might take a few days for me to
get to it. The patch to react itself was merged but won’t be available
until the next release.

Dustin

**Comment by Neuroforge** [comment]
@dustinsoftware Awesome. Thank you for the response.

So i've downgraded React and React-Dom to 16.4.0 but still seeing the error.

- Deleted react adn react-dom folders in node_modules
- Called npm install react@16.4.0 and npm install react@16.4.0
- Called webpack --config webpack.config.js

The version number inside of react.development.js is 16.4.0 and same with react-dom.development.js

Still seeing the timeout issue.

Does Webpack or the JsEngineSwitcher affect this?

**Comment by dustinsoftware** [comment]
@Neuroforge do you only see this error when adding Video.js? Are you bundling react with webpack or using the built in react version?

**Comment by Neuroforge** [comment]
I will try using another js library with timeout. Any ideas on a good one to try?

I am using Webpack and ChakraCore js engine.
