### ISSUE TITLE
Unable to npm install create-react-app

### ISSUE THREAD

**Issue by AdelekeIO** [reactjs/React.NET#559]
the folloing error is what i recieved as feed back.
npm ERR! Unexpected end of JSON input while parsing near '....4\r\nComment: https:

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-07-02T14_21_02_674Z-debug.log

kindly help. thanks

**Comment by Daniel15** [comment]
This repository is for the ReactJS.NET project, which integrates React into Microsoft's .NET stack. You probably want to post to the create-react-app repo instead: https://github.com/facebook/create-react-app
