### ISSUE TITLE
Server-side with IIFE 

### ISSUE THREAD

**Issue by dotfelixb** [reactjs/React.NET#56]
If your .js is using the IIFE style ReactJS fail to load the component on the server depending on how the component is scoped

example using var or window fail

(function (){
  var DivBox = React.createElement('div', null, 'Just a div')
}())

this will fail

but
(function (){
  DivBox = React.createElement('div', null, 'Just a div')
}())
without var or window will work.
why this behavior ?

**Comment by Daniel15** [comment]
The documentation page on Webpack touches on this when using Webpack: http://reactjs.net/guides/webpack.html. Documentation for other module systems or "vanilla" IIFEs can be added in the future if we like. Closing this out. Thanks!
