### ISSUE TITLE
No way to view the built-in React library

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [reactjs/React.NET#564]
Context: I'm getting errors that `React.createRef` doesn't exist in server-side rendering. We use the built-in React that comes with React.NET (`setLoadReact(true)`), so it's likely that our version has an old React.

It'd be useful to see where this is set and how:

* Where in the GitHub repo is this stated?
* A runtime API to retrieve it _(useful for showing debug info on crashes)_

**Comment by Daniel15** [comment]
> Where in the GitHub repo is this stated?

It's specified in the `package.json` file of `React.Core`:
https://github.com/reactjs/React.NET/blob/master/src/React.Core/package.json#L15

You can switch to the tag of the release you're using to see the version used in that release:
![](https://d.sb/2018/07/firefox_09-11.20.29.png)

> A runtime API to retrieve it (useful for showing debug info on crashes)

That's a good idea. We should be able to execute `React.version` in JS to get the version number. With the current code, you could probably do `ReactEnvironment.Current.Execute<string>('React.version')`, but it would be good to add a `ReactVersion` property to encapsulate that.

**Comment by dustinsoftware** [comment]
We don't have plans to add support for this, but a PR would be accepted though!
