### ISSUE TITLE
cannot reference npm packages

### ISSUE THREAD

**Issue by mealbarracin10** [reactjs/React.NET#565]
i recently to start with React.NET, i have a file jsx :

```
import { DatePicker } from 'react-datepicker';
class Truck extends React.Component {
    constructor(props) {
        super(props);
    }
    render() {
        return (
            <DatePicker
                selected={this.state.startDate}
                onChange={this.handleChange}
            />
        );
    }
}


React.render(<Truck name="World" />,
    document.getElementById('container')
);
```
And i am trying show a datepicker with a [library](https://www.npmjs.com/package/react-datepicker) 
but it throw an error, when try import a module. 
This module is in package.json and it is install and it is in node_modules

[proposed Label] question

**Comment by dustinsoftware** [comment]
Hi there, we won’t be able to help much without knowing what the error is. It the library crashes during server render, you could update state in componentDidMount to make the component visible only during client render.
