### ISSUE TITLE
Please update the built-in React to 16.3 or higher

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [reactjs/React.NET#566]
Following #564: ~~you're~~ React.Core.3.3.0 is on 16.0. https://github.com/reactjs/React.NET/blob/6f6ae01135f8abd709d80a2b470bcd2dde1f285d/src/React.Core/package.json#L15

React 16.3 added `React.createRef` _(which I happen to rely on)_ and generally newer versions have bug fixes, API improvements, etc.

**Comment by dustinsoftware** [comment]
Done
