### ISSUE TITLE
Consider auto-updating package.json contents

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [reactjs/React.NET#567]
Following #566: I'm particularly fond of [Greenkeeper](https://greenkeeper.io/) for CI and [npm-check-updates](https://github.com/tjunnone/npm-check-updates) for local development. Staying up-to-date on packages is generally a good idea:
* You get the latest bug fixes and improvements, particularly security patches
* You don't fall out of date with API needs (e.g. #566!)
* Users have fewer duplicate npm dependency versions resolved

**Comment by dustinsoftware** [comment]
Considering the bump to 16.4.1 totally broke this library, I agree with having more tests before adding green keeper :)

**Comment by dustinsoftware** [comment]
@Daniel15 looks like I don't have permissions to enable Greenkeeper on this repo, would you mind taking a look?
