### ISSUE TITLE
Working with JSDOM

### ISSUE THREAD

**Issue by knyzorg** [reactjs/React.NET#575]
I am interested in pre-rendering some D3.js charts which have a hard dependency on WHATWG specifics such as `document.querySelector`. 

JSDOM seems to be the recommended approach to work with D3 on the back-end but requires a node environment while React.NET seems to offer some other kind of environment.

Is there something which could be done?

**Comment by dustinsoftware** [comment]
I’m curious what node APIs JSDOM relies on that aren’t part of the ES2015
spec.. you can’t use node right now as a backend although that would be an
interesting experiment! (You can use v8 directly already)

**Comment by knyzorg** [comment]
JSDOM relies on the full node environment. It wants fs, net, tls, etc.

I failed to find a more stripped down version of jsdom which doesn't need these.

**Comment by knyzorg** [comment]
What is the advantage of chakra over node, in theory?

**Comment by dustinsoftware** [comment]
We don’t have bindings to run node in the same process right now. You can
use v8, but some APIs will be missing.

**Comment by dustinsoftware** [comment]
Closing since the question has been answered.
