### ISSUE TITLE
Render component with previous props

### ISSUE THREAD

**Issue by mchound** [reactjs/React.NET#583]
Using 3.4.1 and it's working fine on my local machine, but when I deploy to a azure webapp, I see weird behavior. 

At first, it's all ok, but after a couple of renders on the server I'm starting to get the component rendered with props from previous requests. It seems to work when I set SetReuseJavaScriptEngines(false) in the configuration, but I shouldn't need that, right?

**Comment by dustinsoftware** [comment]
Hmm that’s a new one. are you sure you weren’t seeing that behavior on the
version you were on before? What version was it working for you on?

**Comment by mchound** [comment]
No version I've tried is working. I had this behavior on 3.3.0 as well. The only way I've found, that works, is to set ReuseJavaScriptEngines to false.

Is there any cahing of the rendered result? I'm running .NET Framework 4.7.2 and I know they made some changes regarding caching since earlier framework versions.

**Comment by dustinsoftware** [comment]
I’m a bit confused. This issue is tracking a bug with React.NET on .NET
Core on Windows only. Could you open a new issue with some more details?
Maybe a link to your website that shows the behavior?

**Comment by dustinsoftware** [comment]
Sorry for the previous comment, I mistakenly thought this was another thread. Can you share a link to a repo that demos this bug and a link to your azure website?

**Comment by mchound** [comment]
Sorry but I can't share the repo or the link to the website. But I can share some snippets from the code if that would help?

**Comment by dustinsoftware** [comment]
Closing for lack of additional data, I can't repro this one..
