### ISSUE TITLE
Simply transpile a string of jsx to js during a server/api request?

### ISSUE THREAD

**Issue by 84pennies** [reactjs/React.NET#585]
Basically, given a string of jsx, can I transpile a string containing JSX into ES5 JS?

For more detail.... [stackoverflow question...](https://stackoverflow.com/questions/51938607/transpile-string-with-jsx-into-es5-javascript-in-c-sharp)

**Comment by dustinsoftware** [comment]
Hi there. Sounds like you want to use this function:

`string outputJs = ReactEnvironment.Current.Babel.Transform(inputJs)`

Given an arbitrary string, it will interpret it as JS and output ES5-compatible JS, depending on how you have babel configured.

**Comment by Daniel15** [comment]
You can also name the file .jsx and hit the file's URL directly to transpile it, as long as you've configured the handler in web.config (for .NET Framework) or configured the middleware (for ASP.NET Core)

**Comment by 84pennies** [comment]
@dustinsoftware Hi there! Thanks so much for the straightforward reply. I am new to React.NET but have been using ReactJS for some time with webpack/babel etc.

Where would I go to configure babel in my MVC project? Or would it just use the same config that node uses when it builds my project.
