### ISSUE TITLE
ASP.NET Core Tutorial - Incorrectly named keys in "data" JSON blob

### ISSUE THREAD

**Issue by teimaj** [reactjs/React.NET#586]
In this section of the tutorial : [Hook up the data model](https://reactjs.net/getting-started/tutorial.html#hook-up-the-data-model) the keys are all lowercase.

``` JavaScript
const data = [
  { id: 1, author: "Daniel Lo Nigro", text: "Hello ReactJS.NET World!" },
  { id: 2, author: "Pete Hunt", text: "This is one comment" },
  { id: 3, author: "Jordan Walke", text: "This is *another* comment" }
];
```

However the following code references them as:

``` JSX
const commentNodes = this.props.data.map(comment => (
      <Comment author={comment.Author} key={comment.Id}>
        {comment.Text}
      </Comment>
    ));
```

The tutorial then later removes the JSON blob and uses server side data, the naming convention used is then pascal case, as far as I can see. 

So I believe the data should look like : 

``` JavaScript 
const data = [
  { Id: 1, Author: "Daniel Lo Nigro", Text: "Hello ReactJS.NET World!" },
  { Id: 2, Author: "Pete Hunt", Text: "This is one comment" },
  { Id: 3, Author: "Jordan Walke", Text: "This is *another* comment" }
];
```

I know its minor, but it confused me when I was being lazy and copying and pasting the code into my `tutorial.jsx` file 😅

**Comment by teimaj** [comment]
Created a [PR](https://github.com/reactjs/React.NET/pull/587) that will resolve this

**Comment by dustinsoftware** [comment]
merged a fix
