### ISSUE TITLE
Bootstrap integration with ReactJS.NET

### ISSUE THREAD

**Issue by anti-aguilar** [reactjs/React.NET#588]
Hi there! I was wondering if someone could provide me insight on how to use bootstrap components within my ReactJS.NET project. I've read around and it seems it's not possible to use the "import" keyword withing my project without using webpack (which I would like to avoid). Since I can't use this keyword I'm finding it impossible to use bootstrap's components. I'm pretty novice in this so please let me know if I'm looking at this in the wrong lense :). Any help would be extremely appreciated!

**Comment by dustinsoftware** [comment]
Sure! Use the UMD build of a library like `reactstrap`. Webpack shouldn't be needed for this.
https://github.com/reactstrap/reactstrap#example

**Comment by anti-aguilar** [comment]
Thanks for the quick reply man! I'm again real novice so not sure where to place the UMD build definition with my ReactJS.net project? I'm assuming I place it within my index.cshtml that's housed under my home view?
![capture](https://user-images.githubusercontent.com/15002809/44545711-a95f4d80-a6ca-11e8-8a33-08c8075a0285.PNG)

**Comment by dustinsoftware** [comment]
Hi there. The best place to look would be the tutorial, which describes how to load in a custom script. Remarkable is used as an example, but it should work with any UMD library (such as reactstrap)

https://reactjs.net/getting-started/tutorial.html#optimization-server-side-rendering

Reactstrap is hosted on cdnjs. Download a copy and add it to your app's content directory, and then modify `ReactConfig`

https://cdnjs.com/libraries/reactstrap

How could we update the docs to make this more clear? Would having a dedicated section to "adding third party modules" be helpful?

**Comment by NkosiKee** [comment]
Yes that would be very helpful!

**Comment by dustinsoftware** [comment]
Reactstrap has been added to the samples

https://github.com/reactjs/React.NET/commit/8b9410913675724066b2bcf1ca5fd03202d4fa5a
