### ISSUE TITLE
Error on server side rendering if own version of React is provided

### ISSUE THREAD

**Issue by jyotidhyani** [reactjs/React.NET#593]
Hi,

I want to implement Server Side Rendering with my own version of React. I have set LoadReact to false, and added react files.
![capture1](https://user-images.githubusercontent.com/25761962/44943117-904b5080-adde-11e8-91b1-fbde59c0627a.JPG)

I am getting the error - 'Set' is undefined in react-dom.js at line 9279
![image](https://user-images.githubusercontent.com/25761962/44943133-f6d06e80-adde-11e8-99dd-154c55c79da3.png)

Any help would be appreciated! Thanks.

**Comment by dustinsoftware** [comment]
Try using a different engine, like v8 or chakra core. The tutorial docs on
the website will show you how to do this.
