### ISSUE TITLE
Support for React 16.3 version

### ISSUE THREAD

**Issue by ashwanikumar98** [reactjs/React.NET#596]
Could you please update by when React 16.3 version will be supported so that we can use new Context API.

**Comment by bhagwati1586** [comment]
I noticed that nuget package is not containing the react 16.3. By when can we expect the latest version of react integrated with the nuget package and use context API.

**Comment by jyotidhyani** [comment]
Facing similar issue while using Context API with server side rendering. Please help with the issue so that context API can be used with server side rendering also. Thanks.

**Comment by ridhisood** [comment]
Hi, even I have been looking over in this issue, and will need React 16.3 nuget package on urgent basis. Thank you.

**Comment by dustinsoftware** [comment]
If you need react updates urgently, you can disable LoadReact and provide
your own copy :) I hope we can get to publishing an update soon but can’t
guarantee it.

**Comment by dustinsoftware** [comment]
Merged in fe72ea9ca18793fea75282f0514e969384853d5e. Will release shortly.
