### ISSUE TITLE
Dynamic <head> from React (React-Helmet)

### ISSUE THREAD

**Issue by Saturate** [reactjs/React.NET#605]
Would be nice if the example, showed how to use https://github.com/nfl/react-helmet with the server side rendering.

This would allow users to see how to update meta tags, microdata (`JSON-LD`) ect.

Should be similar to the way CSS-In-JS works, with a `ViewBag` that's rendered out. But maybe a default helper would be nice, as it's used by a lot of people.

**Comment by optimatex** [comment]
@Saturate +1 for such issue. I have been using both `react-helmet` and `React.NET` for a year but didn't manage to find to use it on SSR. I have also opened an issue on `react-helmet` repo but no answer.

**Comment by dustinsoftware** [comment]
There is a PR opened on this repo to add support for this.

**Comment by Saturate** [comment]
To make it easy, I'll add a link: #615

It dosen't build yet, I see.

**Comment by dustinsoftware** [comment]
This is shipped in 4.0.0-beta5.
