### ISSUE TITLE
Question: Component children with React.NET?

### ISSUE THREAD

**Issue by gazab** [reactjs/React.NET#607]
We've run into the issue where we want to wrap some html in a component. The easiest example would probably be something that collapses on click:
```csharp
<CollapseOnClickComponent>
   <p>Hello world!</p>
</CollapseOnClickComponent>
```

The CollapseOnClickComponent would wrap any children passed to it and hide/show them on click. 

This works fine in "normal" React and WITHIN the components I use with React.NET but what if the children come from my Razor view?
What if I have something like this:
```csharp
<ArticlePageComponent>
   @Html.RenderBody()
</ArticlePageComponent>
```

Sure, I could do something hacky like serialize Html.RenderBody() to a raw string and pass it as a prop and use dangerouslySetInnerHTML. But what if Html.RenderBody() uses other views with other React.NET components that needs hydrate and so on?

It would be awesome if you could use children in a React like way with React.NET too!

Am I making any sense? :) Is this something that is even remotely possible?

**Comment by dustinsoftware** [comment]
Unfortunately no, what you described is not possible without hacks :)

**Comment by gazab** [comment]
In its current state yes, but isn't this something that would be nice to support?

**Comment by dustinsoftware** [comment]
A few challenges to overcome:
- Razor and JSX use different parsing libraries
- React doesn't handle child nodes that it doesn't own very well. Even if a placeholder `div` is rendered, you have to be very careful that the node doesn't get destroyed during reconcoliation.

**Comment by Daniel15** [comment]
I think using `dangerouslySetInnerHTML` is the best thing way to do this at the moment. Server-side you can serialize it to an object with a `__html` property, then client side you could do eg. `<div dangerouslySetInnerHTML={this.props.html} />` or something like that.

**Comment by dustinsoftware** [comment]
I don't see a feasible way to implement this. Closing for now.
