### ISSUE TITLE
v4.0 release

### ISSUE THREAD

**Issue by Daniel15** [reactjs/React.NET#609]
- Wait for JavaScriptEngineSwitcher 3.0 to be released as a stable version (currently just an RC)
- Ensure all JavaScriptEngineSwitcher references are updated to 3.0 stable
- Write a blog post with all the changes

cc @dustinsoftware

**Comment by dustinsoftware** [comment]
Yep, I also need to finish updating the docs for the CSS in JS support (and
add some for react router)

**Comment by huan086** [comment]
And it's released! :)

**Comment by Daniel15** [comment]
Awesome! I'm currently in vacation until next week, so I'll look into this next week, unless @dustinsoftware gets to it first. I want to release a new version of JsPool too.

**Comment by dustinsoftware** [comment]
I'm unsure if I'll get to it either, but here's the major changes to cover in blog post:

- CSS-in-JS supported. [Docs](https://reactjs.net/features/css-in-js.html)
- React Helmet supported. [Docs](https://reactjs.net/features/react-helmet.html)
- Lots of fixes
- MIT licensed
- React 16.7.0 bundled
- Updated to JavaScriptEngineSwitcher 3.0, including script precompilation. JS engines no longer automatically registered. Getting started pages for [NetFx](https://reactjs.net/getting-started/aspnet.html) and [NetCore](https://reactjs.net/getting-started/aspnetcore.html) updated to reflect this change.

**Comment by Daniel15** [comment]
I released a new version of JsPool recently, so that's all ready to go. I'll try to look into this soon if you don't get around to it 😃

**Comment by dustinsoftware** [comment]
Just published the Nuget packages now for 4.0, but will hold off making a blog post until this weekend

**Comment by dustinsoftware** [comment]
7e6623dfabf3b970f369cc8df538e30adc441dde

**Comment by Daniel15** [comment]
Thank you!
