### ISSUE TITLE
Question about seeding initial data for server side rendering

### ISSUE THREAD

**Issue by Surreal9** [reactjs/React.NET#61]
First off, thanks for the great library! This has been a great help in getting our .net MVC site working with React. Now on to my question..

We are working on bringing over our site into React. We have wired up server side rendering, which is working great. One thing we've come across now though, is looking at how to pass some "global"  data into the server side rendering context, without it being passed in through every single component. This data is in fact used by many components, through use of React's "mixin" functionality.

In other words, I can see how we can make data available to the server side render by passing in data through Html.React, or Html.ReactWithInit (thanks for this new method btw, we've enjoyed using it in a partial already), and we started going down the path of having a base model which is extended by the model used for any given view, and passing our data through there. This however will start to get ugly as we start to render multiple components to a page, duplicating the information we are storing in the base model. 

After digging around in the source a little bit, it seems like one possible approach would be to find some means to make a call to ReactEnvironment.Execute(string code), and pass in a string from a Razor view that would let us pass in some JSON, etc, to seed our data into some kind of global variable.

Another alternative could be to create some sort of 'invisible' 'global-state-seeding' component which we could pass our data in through, however this would require our developers are all very aware of making sure this component is present in all pages, and only once.. which sounds less attractive than finding some means to have this data automatically wired up.

Do you have any suggestions on this? Are these feasible approaches, and if not, could you offer some insight on any alternatives?

Thanks!

**Comment by Daniel15** [comment]
Going to close this out, but feel free to post more comments if you have any further questions.
