### ISSUE TITLE
Difference between this library and Next.js 

### ISSUE THREAD

**Issue by suarezafelipe** [reactjs/React.NET#616]
Hi, 

Sorry if this is not the place to post this question, feel free to redirect me to the proper place, but I didn't find any community forum for react.net

I am going to create a .net core web app and my chosen front end framework is react. One of the requirements is that it should be 100% server side rendered, I don't want to make a SPA.

From what I've read both React.NET and Next.js could support my use-case. My question is what's the difference between the two libraries? What makes React.NET different or better than next.js for a .net core back end? 

Thanks

**Comment by dustinsoftware** [comment]
Unless you have a specific need to use the ASP.NET stack mixed with Javascript, I recommend using Next.js. This project exists mainly as a bridge between ASP.NET and React, which don't normally work well together.
