### ISSUE TITLE
Uncaught ReferenceError: Map is not defined at line

### ISSUE THREAD

**Issue by ahiyalala** [reactjs/React.NET#617]
I added the server.bundle.js and this error showed up. Upon looking at the bundle I figured out that it came from this line, it must have come from one of the 3rd party libraries that our other devs included but I can't be certain which one. I also figured out that it has something to do with the polyfills but I don't know how to resolve that as well:

`var scheduleWork = void 0;
	var cancelScheduledWork = void 0;

	if (!ExecutionEnvironment.canUseDOM) {
	  var timeoutIds = new Map();

	  scheduleWork = function (callback, options) {
	    // keeping return type consistent
	    var callbackConfig = {
	      scheduledCallback: callback,
	      timeoutTime: 0,
	      next: null,
	      prev: null
	    };`

**Comment by Taritsyn** [comment]
Hello!

You need to use a JS engine that supports ECMAScript 6: [JavaScriptEngineSwitcher.ChakraCore](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/ChakraCore) and [JavaScriptEngineSwitcher.V8](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/V8). I recommend also reading the [“Misconceptions about the JavaScript Engine Switcher version 2.X”](https://github.com/reactjs/React.NET/issues/409) discussion.

**Comment by ahiyalala** [comment]
Hi @Taritsyn ! Thanks for your reply.

ChakraCore and V8 is already included in our solution and I've followed installing the native assemblies (JavaScriptEngineSwitcher.V8.Native.win-x86 and JavaScriptEngineSwitcher.V8.Native.win-x64.) but the app still renders the same error.  Am I missing some steps?

**Comment by ahiyalala** [comment]
Hi!

It's been resolved now. I just have to add this on Configure:

```
engineSwitcher.EngineFactories.AddChakraCore()
                                          .AddV8();
```

**Comment by Taritsyn** [comment]
I would also add the following line after:

```csharp
...
engineSwitcher.DefaultEngineName = V8JsEngine.EngineName;
```
