### ISSUE TITLE
Unable to Install React.js using Nuget

### ISSUE THREAD

**Issue by LakshayDuggal21** [reactjs/React.NET#618]
![image](https://user-images.githubusercontent.com/44532472/47643559-0cd18580-db29-11e8-98e5-6160c30f56b3.png)
Getting above error when trying to Install React.js using Nuget in ASP.NET Core Web application (.NET Framework). Using Visual Studio Community 2017.

**Comment by dustinsoftware** [comment]
Not sure what's going on here. The [Nuget package](https://www.nuget.org/packages/React.AspNet.Middleware/) is published and available for 3.4.1. Have you tried installing it with `dotnet add package`?
