### ISSUE TITLE
ASP.NET MVC 4 - Babel ES6+ Transpile

### ISSUE THREAD

**Issue by unwired4ever** [reactjs/React.NET#620]
I have a javascript file 'math.js' that exports a simple function and variable:
```
// Scripts/lib/math.js
export function sum(x, y) {
    return x + y;
}
export var pi = 3.141593;
```

Then in an another file 'Index.jsx' I have these lines to import the function and variable from 'math.js':

```
//Scripts/Index.jsx
import * as math from "lib/math";
console.log("2π = " + math.sum(math.pi, math.pi));
```
In the BundleConfig class 'Index.jsx' is added to a BabelBundle:

```
        public static void RegisterBundles(BundleCollection bundles)
        {
            bundles.Add(new BabelBundle("~/bundles/main").Include(
                    "~/Scripts/Index.jsx"
                ));
            BundleTable.EnableOptimizations = true;
        }
```

And in the view 'Index.cshtml' the bundle is rendered:

```
<!DOCTYPE html>

<html>
<head>
    <title>Hello React</title>
</head>
<body>
    <script src="@Url.Content("~/Scripts/React/react.development.js")"></script>
    <script src="@Url.Content("~/Scripts/React/react-dom.development.js")"></script>
    @Scripts.Render("~/bundles/main")
</body>
</html>
```
But when I run the application in Firefox it gives following javascript error:
**SyntaxError: import declarations may only appear at top level of a module**

The content of the bundles javascript file looks like this:

/* Minification failed. Returning unminified contents.
(2,8-9): run-time error JS1332: Expected "from": *
(2,8-9): run-time error JS1333: Expected string literal: *
(2,7): run-time error JS1004: Expected ';'
(2,8-9): run-time error JS1195: Expected expression: *
(2,12): run-time error JS1004: Expected ';'
(2,17): run-time error JS1004: Expected ';'
(2,22): run-time error JS1004: Expected ';'
(2,1-7): run-time error JS1328: Import statement must include module name: import
 */
// Index.jsx
import * as math from "lib/math";
console.log("2π = " + math.sum(math.pi, math.pi));

It seems that the Babel transpiling has failed for some reason.

Any idea what is going wrong?

Thanks!

**Comment by dustinsoftware** [comment]
You may not have a Babel plug-in enabled that transforms “import”. Try
using “require” instead.

**Comment by unwired4ever** [comment]
Ok thx, I may try that.
But what about third-party libraries that are using 'import' such as office ui fabric react?
Is there any way to configure the BabelBundle that can transpile that specific syntax?

**Comment by dustinsoftware** [comment]
Generally third party libraries don’t need to be transpired. In case they
do though, you will need to download the library and host it yourself so
Babel can transpire it (or use webpack and Babel-loader)

**Comment by dustinsoftware** [comment]
Transpile*
