### ISSUE TITLE
New feature: dynamic code splitting support

### ISSUE THREAD

**Issue by dustinsoftware** [reactjs/React.NET#622]
I got a prototype working locally of using dynamic import on the server. Here's how it works:

- Use `Engine.EmbedHostObject` to make "WebpackHelper" a globally available function
- Use `target: webworker` in `webpack.config`. Since we have to roll our own file loading mechanism, the one provided by web workers was the easiest to work with.
- Run a polyfill on the server before our scripts
- When webpack encounters a dynamic import, it will generate a call to `importScripts`, which is expected to be synchronous. The polyfill will compile and execute the script, which will invoke the `webpackChunk` callback.
- Tada! You should now be able to use a library like `react-loadable` to do component level code splitting.

I'm going to polish up this approach and do some testing with it before adding support to the library directly. We can release this in 4.1 if all goes well.

The JS server polyfill:
```js
function importScripts(filename) {
	// This might break if the file is huge
	Function(WebpackHelper.ReadFile(filename))();
}

global.importScripts = importScripts;

// Allow local script debugging with Node
global.WebpackHelper = global.WebpackHelper || {
	ReadFile: function(filename) {
		var fs = require('fs');
		var vm = require('vm');
		var code = fs.readFileSync(filename, 'utf-8');
		vm.runInThisContext(code, filename);
	},
};
```

The webpack helper:
```csharp
public sealed class WebpackHelper
{
	readonly IFileSystem _fileSystem;

	public WebpackHelper(IFileSystem fileSystem)
	{
		_fileSystem = fileSystem;
	}

	public string ReadFile(string path)
	{
		if (path == null)
		{
			throw new ArgumentNullException("path");
		}

		Console.WriteLine("Loading " + path);

		return _fileSystem.ReadAsString(path);
	}
}
```

**Comment by dustinsoftware** [comment]
There is a *lot* of cleanup to do, but I pushed up a working prototype here. Obviously it's ready for production, right?  🤔 

https://github.com/dustinsoftware/React.NET/tree/react-loadable

I'll be pushing progress to that branch and do some testing with that approach.

**Comment by dustinsoftware** [comment]
I'll re-open this when I'm focused on finishing react-loadable support. It mostly works, but isn't ready to be merged in yet (needs more polish!)

If anyone has any interest, please comment on this issue :) 

#655

**Comment by olafur164** [comment]
@dustinsoftware 

Have you worked on this any further?
