### ISSUE TITLE
@Html.ReactInitJavaScript() define script tag attributes?

### ISSUE THREAD

**Issue by Saturate** [reactjs/React.NET#623]
I'm looking to implement a [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) on a site using React.NET.

I need to add a `nonce` attribute to the script tag, so that I can whitelist it.
What I want is the output to be something like this:

```
<script nonce="cmVhY3QtbW91bnQtdGFn">
    ReactDOM.render(
        React.createElement(App, {......}, null),
        document.getElementById('root')
    );
</script>
```

In the current verison (even the beta), I can't see how I should achieve this, but something like this would be a great solution for me:

```
Html.ReactInitJavaScript({ nonce: "cmVhY3QtbW91bnQtdGFn" })
```

Am I missing something obvious, or could this be implemented?

**Comment by dustinsoftware** [comment]
In the react site configuration, use SetScriptNonceProvider. We should add
some docs and update the example for this. Provide a func that returns a
cryptographically random string.

**Comment by Saturate** [comment]
Thanks @dustinsoftware couldn't find it, so some docs would be nice. If I find some spare time, I'll make a PR - if someone doesn't beat me to it..
