### ISSUE TITLE
Docs on making production build

### ISSUE THREAD

**Issue by flipdoubt** [reactjs/React.NET#627]
Can someone direct me to the part of the documentation that focuses on creating a [production build](https://reactjs.org/docs/optimizing-performance.html) when from our MSBuild script on the build server? Essentially, I am looking for docs on how to script `npm run build` from MSBuild, but I'm curious to learn how React.NET makes this easier.

**Comment by dustinsoftware** [comment]
Hi @flipdoubt 👋 

Pretty sure you can just add a target with `<Exec Command="npm run build" />` to your project file without using this library. There is an msbuild integration but that's for doing babel compilation directly from msbuild without the need for installing node at all (this library has a hosted Javascript environment that it initializes).
