### ISSUE TITLE
React-Bootstrap integration with ReactJS.net

### ISSUE THREAD

**Issue by VijayakumarNatarajan** [reactjs/React.NET#629]
Is there any documentation available in integrating 'react-bootstrap' with reactjs.net?.
It would also be useful if a there's documentation on how to integrate 3rd party modules as a sample application in the repository.

**Comment by dustinsoftware** [comment]
It would be good to have some better docs on how to do this with libraries like Reactstrap.

**Comment by dustinsoftware** [comment]
The closest thing we have is the Webpack sample project in the repo.

**Comment by dustinsoftware** [comment]
Don't have time to fill out the docs further for this case right now. Try following the webpack docs, adding `reactstrap` library, and import the components you need.

https://reactjs.net/bundling/webpack.html
