### ISSUE TITLE
Allow deferring of scripts

### ISSUE THREAD

**Issue by Saturate** [reactjs/React.NET#630]
To improve the performance of our website, we would like the ability to use deferred scripts.

Example:
```diff
-<script src="/dist/client-41b1e9.js" integrity="..."  crossorigin="anonymous"></script>
+<script defer src="/dist/client-41b1e96.js" integrity="..."  crossorigin="anonymous"></script>
```

But this is not working with the current inline script, as it's executed right away. The right way to do it would be to wrap it in the `DOMContentLoaded`. 

>This Boolean attribute is set to indicate to a browser that the script is meant to be executed after the document has been parsed, but before firing DOMContentLoaded.
Scripts with the defer attribute will prevent the DOMContentLoaded event from firing until the script has loaded and finished evaluating.

So what we really want is to end up with something like this:
```
<script nonce="cmVhY3QtbW91bnQtdGFn">
window.addEventListener('DOMContentLoaded', function() {
   // ReactDOM.hydrate...
});
</script>
```

As far as I can see this is not possible right now, but I might be mistaken. If it's not possible this would be a really helpful feature, as it would allow us to control the loading of our JavaScript.

**Comment by DaniilSokolyuk** [comment]
You can implement your own IHtmlHelper extension like this

`  public static IHtmlString ReactInitJavaScript(this IHtmlHelper htmlHelper, bool clientOnly = false, bool withDelayedLambda = false)
        {
            return new ActionHtmlString(writer =>
            {
                try
                {
                    WriteScriptTag(writer, bodyWriter => Environment.GetInitJavaScript(bodyWriter, clientOnly), withDelayedLambda);
                }
                finally
                {
                    Environment.ReturnEngineToPool(); 
                }
            });
        }

        private static void WriteScriptTag(TextWriter writer, Action<TextWriter> bodyWriter, bool withDelayedLambda = false)
        {
            writer.Write("<script");
            if (Environment.Configuration.ScriptNonceProvider != null)
            {
                writer.Write(" nonce=\"");
                writer.Write(Environment.Configuration.ScriptNonceProvider());
                writer.Write("\"");
            }

            writer.Write(">");

            if (withDelayedLambda)
            {
                writer.Write("window.ReactJsAsyncInit = function() {");
            }

            bodyWriter(writer);

            if (withDelayedLambda)
            {
                writer.Write("};");
            }

            writer.Write("</script>");
        }`

Call in your layout
` @Html.ReactInitJavaScript(clientOnly: false, withDelayedLambda: true)`

And call window.ReactJsAsyncInit() in your entry point in client bundle

**Comment by dustinsoftware** [comment]
That solution should work, please let me know if it doesn’t. :)

**Comment by Saturate** [comment]
From this we were able to do what I wanted. Thanks guys.

I still feel like it would be a pretty common use-case, so maybe consider to include it at some point.

Thanks again!
