### ISSUE TITLE
Bundling and Minification (ASP.NET 4.x) example does not minimize and bundle

### ISSUE THREAD

**Issue by siulca** [reactjs/React.NET#633]
The example [Bundling and Minification (ASP.NET 4.x)](https://reactjs.net/bundling/weboptimizer.html) does not work as advertised. Bundled jsx files are **not bundled** into a single file and they are also **not minified**.

The following:
```js
bundles.Add(new Bundle("~/bundles/main", new IBundleTransform[]
            {
                // This works the same as BabelBundle (transform then minify) but you could
                //add your own transforms as well.
                new BabelTransform(),
                new JsMinify(),
            }).Include(
                // Add your JSX files here
                "~/Scripts/Tutorial.jsx",
                "~/Scripts/Test.jsx"

                // You can include regular JavaScript files in the bundle too
                //"~/Content/ajax.js"
            ));
```

Gets rendered as two files, **not bundled together**:

![image](https://user-images.githubusercontent.com/6707451/49165532-56c8a980-f329-11e8-90d7-2c95b15343d5.png)

Each file contains the full **non-minified** script. In fact there's a further bug. The content of Test.jsx is now inside of Tutorial.jsx and vice-versa!

As it stands Babel Bundling is pointless.

**Comment by dustinsoftware** [comment]
Please verify that `debug=true` is not set in `Web.config` and you are building in Release mode. You can also try installing an older version of ReactJS.NET to see if there was a regression.

**Comment by siulca** [comment]
Thanks for the swift reply, setting `debug=false` in `Web.config` worked! Maybe you should update the tutorial with this info.

Out of curiosity where are the bundled files located? Can't find the `/bundles/` folder.

**Comment by dustinsoftware** [comment]
Off-hand I don't know where the bundled files are located, sorry..
