### ISSUE TITLE
Transient Initialization

### ISSUE THREAD

**Issue by isc30** [reactjs/React.NET#637]
Hi, I need a way to initialize the engine in a transient way, so every time I call `Http.React` a new instance is created.
This is due to some dynamic js files being added to the Configuration **after** calling `Initializer.Initialize()`

Is there any way to invalidate current engine after updating the Configuration?
Thanks

**Comment by dustinsoftware** [comment]
Hmm... not sure. Out of curiosity what is your use case? Are you leveraging
code splitting in your project?

**Comment by isc30** [comment]
I'm using incremental JS dependencies (I only add JS files when I need them by calling `AddScriptWithoutTransform`). The first component gets rendered properly but every next component doesn't take the scripts in consideration because the engine was already instantiated and reused

**Comment by dustinsoftware** [comment]
If you turn off JS engine re-use, does the problem go away? It will also
give you an idea for the perf hit of recreating the JS engine and parsing
scripts. It does seem like there should be a way to empty the JavaScript
engine pool on demand.

**Comment by isc30** [comment]
Emptying the engine pool on demand is exactly what I need for this case.
As a temporary fix, how can I turn off engine reuse?
Thanks

**Comment by dustinsoftware** [comment]
There should be a property in the Configutation type you can set

**Comment by isc30** [comment]
for future readers:
`ReactSiteConfiguration.Configuration.SetReuseJavaScriptEngines(false)`

**Comment by dustinsoftware** [comment]
I'm going to close this issue since we don't have any plans to add better support for this, although I'd be open to a pull request adding support!
