### ISSUE TITLE
How to access components with MVC4(5) server rendering.

### ISSUE THREAD

**Issue by simonssspirit** [reactjs/React.NET#638]
In this article is shown how to load a component and render it server-side:

https://reactjs.net/features/server-side-rendering.html

If I have to include other components inside this parent component is it possible to access them as in this case we do not have Webpack and cannot simply import them?

**Comment by dustinsoftware** [comment]
Sure. Any React class components or function components that are declared
in the global scope should be available to render as child components, even
if they live in separate files. Just make sure to import all of the
components in the AddScripts step in the configuration.

https://github.com/reactjs/React.NET/blob/master/src/React.Sample.Mvc4/Content/Sample.jsx
