### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by mukhtorov** [reactjs/React.NET#654]
`
![screenshot from 2019-01-04 12-04-12](https://user-images.githubusercontent.com/44763931/50721578-db1ff200-1076-11e9-91df-f68222d64db2.png)
![screenshot from 2019-01-04 23-21-32](https://user-images.githubusercontent.com/44763931/50721637-947ec780-1077-11e9-9e3c-16539dd7df33.png)

if import react and react-dom developer console error: require is not defined.
if i dont import react and react dom it is giving reatDom is not defined error.
I am new to react, so i'm confused what to do...
`

**Comment by dustinsoftware** [comment]
Hi there 👋 

A couple things come to mind: 
`React` and `ReactDOM` (case sensitive) are exposed globally. If you aren't using webpack (looks like you're not), you can't yet use `require` or `import` statements in your code. Try removing the import statements and change the casing of `ReactDom` to `ReactDOM`.

I recommend checking out the excellent documentation here on how to get started: https://reactjs.org/tutorial/tutorial.html

I'll be closing this issue, but feel free to re-open if you have questions specific to this library!
