### ISSUE TITLE
@Html.ReactInitJavaScript() the <SCRIPT> tag is incorrect

### ISSUE THREAD

**Issue by ChrisVickers1985** [reactjs/React.NET#656]
When using @Html.ReactInitJavaScript() a <script> tag is created that runs 'ReactDOM.hydrate ', that attaches events to server rendered elements.

The script tag that is written to the DOM is incorrect and should actually be:
<script type="text/babel">. As the type is wrong, an error will be thrown when the code is run on the browser. This prevents event binding from taking place.

**Comment by dustinsoftware** [comment]
This library doesn’t support rendering scripts without transpiling them first. Please read the tutorial or look at the sample projects to see how the rendered script tag is supposed to work.
