### ISSUE TITLE
Version Confusion with JavaScriptEngineSwitcher

### ISSUE THREAD

**Issue by BigBoySamo** [reactjs/React.NET#659]
Hi,

I started using React.NET today and followed the tutorial but either did something wrong or hit a roadblock.

I installed React.AspNet Version: 3.4.1

I also installed the following packets via nuGet:
JavaScriptEngineSwitcher.Extensions.MsDependencyInjection Version: 3.0.0
JavaScriptEngineSwitcher.ChakraCore.Native.win-x64 Version: 3.0.0
JavaScriptEngineSwitcher.ChakraCore Version 3.0.0

Following the tutorial I get compilation errors for my .jsx files : 

**JavaScriptEngineSwitcher.Core.JsEngineSwitcher ---> System.MissingMethodException: Method not found: 'JavaScriptEngineSwitcher.Core.JsEngineSwitcher JavaScriptEngineSwitcher.Core.JsEngineSwitcher.get_Instance()'.**

I tried downgrading the JavaScriptEngineSwitcher packets to the latest 2.x version and then it seems to work. Is this intended behaviour?

**Comment by Taritsyn** [comment]
Yesterday already was a [similar issue](https://github.com/reactjs/React.NET/issues/657).

ReactJS.NET version 3.X only compatible with the JavaScript Engine Switcher version 2.X. If you want to use a JavaScript Engine Switcher version 3.X, then install the ReactJS.NET version 4.0.0 RC 2.

These are problems of transition period.

**Comment by BigBoySamo** [comment]
Alright, thank you for the clarification.

**Comment by Daniel15** [comment]
Sorry about this... We're aiming to release ReactJS.NET 4.0 soon, but just haven't had time to do it yet.
