### ISSUE TITLE
Development workflow?

### ISSUE THREAD

**Issue by jerrywithaz** [reactjs/React.NET#661]
Hi, 

I am new to ReactJS.NET and so far I am loving it. I am testing it out right now to see if my company wants to write our new software using this.

However, I am a little concerned/confused about how the development workflow is supposed to work and I am wondering if you have any tips/suggestions/best practices.

I have followed the documentation and I load our server scripts using ReactSiteConfiguration.Configuration.SetReuseJavaScriptEngines(true).SetLoadBabel(false).SetLoadReact(false).AddScriptWithoutTransform()

I am using webpack to generate both our client and server bundles.

However, it appears that whenever I make changes to our source code and webpack transpiles our code, ReactJS.NET has to recompile as well, this makes development pretty slow.

So, I am wondering if I am missing something. Are there betters way to go about developing? Is Hot Module possible? etc...

Thanks!

**Comment by jerrywithaz** [comment]
Thanks for the response Justin.

I am finally starting to understand how everything things and my development enviroment is coming together thanks to tools like React Storyboard and Webpack Dev Server.

I am going to close this ticket but whenever I have my finally Development to Production Pipeline working how I want it, I will post the information here for anyone else who may be struggling.

Thanks again.

**Comment by baxxos** [comment]
@jerrywithaz I'm sorry to revive this but the official docs provide no clues - have you ever managed to make the auto-reload work (e.g. using `webpack-dev-server`)?
