### ISSUE TITLE
Serving gzipped bundle.js

### ISSUE THREAD

**Issue by Taerarenai** [reactjs/React.NET#663]
Is there any way to serve gzipped JS for the bundle (webpack) using React.NET ?

**Comment by Daniel15** [comment]
If you're using Webpack, the resulting JS file is served directly via your
web server, so you should configure gzip on your server.

**Comment by Taerarenai** [comment]
I'm using SSR to send a token from the back-end. I tried adding compression (like this https://www.softfluent.com/blog/dev/Enabling-gzip-compression-with-ASP-NET-Core )

And serving the .js.gz file like this


```
            app.UseReact(config =>
            {
                config
                    .SetReuseJavaScriptEngines(true)
                    .SetLoadReact(false)
                    .SetLoadBabel(false)
                    .AddScriptWithoutTransform("~/dist/bundle.js.gz");
                //.AddScript("./React/App.jsx");
            });
```

But React.NET is throwing an error because it doesn't like ``.gz``

Is my approach wrong in this situation? Could you perhaps throw me an example ?

**Comment by Taerarenai** [comment]
Hi @dustinsoftware ,

Thanks for the link. Enabling it on the app did the trick, hopefully this saves me some time before i being optimizing it..

**Comment by oudoulj** [comment]
Hi all,
I was wondering if I can add **Brotli compression** with ReactJS.NET SSR on my ASP.NET MVC project (**not Core**).
I was following 2 tutorials [here](https://web.dev/codelab-text-compression-brotli) and [there](https://medium.com/@poshakajay/heres-how-i-reduced-my-bundle-size-by-90-2e14c8a11c11).

I first installed :
`npm install brotli-webpack-plugin --save-dev`
and added to my webpack.config.js : 
```
plugins: [
		new WebpackNotifierPlugin(),
		new BrowserSyncPlugin(),
		new BrotliPlugin({
			asset: '[file].br',
			test: /\.(js|jsx|css|html|svg)$/,
			threshold: 10240,
			minRatio: 0.7
		})
	]
```

But then the next step would be to add something like that 
```
app.get('*.js', (req, res, next) => {
  req.url = req.url + '.br';
  res.set('Content-Encoding', 'br');
  res.set('Content-Type', 'application/javascript; charset=UTF-8');
  next();
});
```
to ["tell the server to send these brotli-compressed files whenever their original JS versions are being requested"](https://web.dev/codelab-text-compression-brotli) 
Is that whole Brotlin compression even supported by ReactJS.NET and if so, where to put that last piece of code ?
Thanks !

**Comment by Taritsyn** [comment]
Hello, Jérôme!

Try to use a solution based on ASP.NET. Implement dynamic compression by using the [Brotli.NET](https://github.com/XieJJ99/brotli.net) or [BrotliSharpLib](https://github.com/master131/BrotliSharpLib) libraries. Only text content needs to be compressed.
