### ISSUE TITLE
Custom react engine initialization and pooling

### ISSUE THREAD

**Issue by LinusCenterstrom** [reactjs/React.NET#665]
In our application we've been using our own pooling strategy (basically it's one pool per locale). 
We do this because we require some locale-specific code to run when the engine is initialized. 
In the version 3.x of the lib I accomplished this by replacing the IJavascriptEngineFactory in the tiny IOC container with my own implementation.

When I tried to upgrade to 4.0 however it broke, most likely because something is done differently internally with how the registrations are set up. 
It seemed to get the wrong instance of JsEngineSwitcher somehow as it got an instance with no factories registered. If I removed my override of the JavascriptEngineFactory it got the right one.

Before I try to fix it, I thought I should ask if there is any other way, or any plans to add the ability to implement a custom pooling strategy and engine initialization?

**Comment by Taritsyn** [comment]
Hello, Linus!

Here is a quote from the [announcement of ReactJS.NET 4.0](https://reactjs.net/2019/01/4.0.0-release.html):

> * Javascript engines are no longer automatically registered. See the getting started pages on [.NET Framework](https://reactjs.net/getting-started/aspnet.html) and [.NET Core](https://reactjs.net/getting-started/aspnetcore.html) for more information about how to register a specific
>   * JavaScriptEngineSwitcher and JSPool have been updated as a part of this change.
>   * Further reading for JavaScriptEngineSwitcher: [How to upgrade applications to version 3.X](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/How-to-upgrade-applications-to-version-3.X)

>

**Comment by LinusCenterstrom** [comment]
Not sure exactly how that helps me. As i said, the registration of JavascriptEngineSwitcher works fine as long as I do not replace the registration of IJavascriptEngineFactory with my own implementation. 
Or is there something in JavascriptEngineSwitcher I can override instead to provide my own pooling and engine initialization strategy?

**Comment by Taritsyn** [comment]
> As i said, the registration of JavascriptEngineSwitcher works fine as long as I do not replace the registration of IJavascriptEngineFactory with my own implementation.

Give an example of the error message.

**Comment by dustinsoftware** [comment]
@LinusCenterstrom the only major changes we made between 3 and 4 were related to the default engine initialization, so I'm not sure why your custom pooling strategy isn't working. From what you described it *sounds* like it should just work.

[ReactEnvironment](https://github.com/reactjs/React.NET/blob/b3faf179c2d06408d06fdf5e31ebe76434cb47b0/src/React.Core/ReactEnvironment.cs) is the primary consumer of `IJavaScriptEngineFactory` so you might look at recent changes there to see if the calls changed in a way that your code isn't handling.

**Comment by LinusCenterstrom** [comment]
Ok, found the issue.
The JavascriptEngineFactory previously took a JsEngineSwitcher in the constructor while the new version takes an IJsEngineSwitcher. 
I had not made this change in my custom JavascriptEngineFactory.
After updating mine to take an IJsEngineSwitcher instead it worked correctly.

Somehow it still seemed to find a registration for JsEngineSwitcher but it was an empty one. No idea where it came from.

Feel free to close this.

**Comment by dustinsoftware** [comment]
👍
