### ISSUE TITLE
Owin support/documentation?

### ISSUE THREAD

**Issue by delaneyj** [reactjs/React.NET#71]
Coming from a node.js world but would love to use ReactJS with Nancy and an Owin container.  Are there any gotchas I should be concerned with?  This might be related to the vNext support issue.

**Comment by Daniel15** [comment]
Hi @delaneyj! OWIN support was only merged last night in #69. Currently there's no documentation on how to use it, and I actually haven't tried it out myself. As far as I can see, this only covers JSX transformation (built on top of `StaticFileMiddleware`), it doesn't cover server-side rendering.

cc @mandrek44 - It would be good to get some basic documentation on this functionality :)

**Comment by mandrek44** [comment]
@delaneyj there's a sample showing the server-side JSX transformation with OWIN: https://github.com/reactjs/React.NET/tree/master/src/React.Sample.Owin 

Regarding the server-side rendering - Katana has no built-in rendering mechanism, however you can use Razor manually and could probably use the same mechanism as in MVC for sever side rendering. I'll investigate.

@Daniel15 I'll try to add some documentation soon!

**Comment by Daniel15** [comment]
Haven't seen any other requests for OWIN documentation and I feel like it's not as popular any more with ASP.NET 5 running on its own stack, so I'm going to close this out.
