### ISSUE TITLE
Can't build latest code from Git?

### ISSUE THREAD

**Issue by kendallb** [reactjs/React.NET#712]
I am trying to get the code to compile, and I run the dev-build.bat file but it fails when it tries to run gulp? Any idea what is going wrong?

```
Build:
  node_modules/.bin/gulp
  internal/util/inspect.js:31
  const types = internalBinding('types');
                ^

  ReferenceError: internalBinding is not defined
      at internal/util/inspect.js:31:15
      at req_ (C:\src\git\React.NET\src\React.Core\node_modules\natives\index.js:140:5)
      at require (C:\src\git\React.NET\src\React.Core\node_modules\natives\index.js:113:12)
      at util.js:25:21
      at req_ (C:\src\git\React.NET\src\React.Core\node_modules\natives\index.js:140:5)
      at require (C:\src\git\React.NET\src\React.Core\node_modules\natives\index.js:113:12)
      at fs.js:42:21
      at req_ (C:\src\git\React.NET\src\React.Core\node_modules\natives\index.js:140:5)
      at Object.req [as require] (C:\src\git\React.NET\src\React.Core\node_modules\natives\index.js:54:10)
      at Object.<anonymous> (C:\src\git\React.NET\src\React.Core\node_modules\graceful-fs\fs.js:1:99)
C:\src\git\React.NET\build.proj(95,3): error MSB3073: The command "node_modules/.bin/gulp" exited with code 1.
Done Building Project "C:\src\git\React.NET\build.proj" (default targets) -- FAILED.
```

**Comment by Daniel15** [comment]
What version of Nodejs are you using?

**Comment by kendallb** [comment]
v10.14.2. Just installed it the other day on Windows.

**Comment by kendallb** [comment]
npm is 6.4.1

**Comment by kendallb** [comment]
I tried changing to the 3.4.1 stable branch and it fails with different errors (dotnet restore is failing there).

**Comment by Daniel15** [comment]
Hmm, the most recent CI build is successful:
https://ci.appveyor.com/project/Daniel15/react-net/branch/master

It's using Node.js 6 though. I wonder if there's a breaking change in a
newer Node.js version. We should likely upgrade the version AppVeyor and
Azure DevOps are using.

**Comment by kendallb** [comment]
Could be something in node as gulp is what is failing. Any idea why the stable branch is failing? Seems to think some configuration json file is missing. I tried to move my project to 4.0.0 but it seems there are some breaking changes in the JavaScript switcher engine I need to sort out.

**Comment by Taritsyn** [comment]
Hello, Kendall!

> I tried to move my project to 4.0.0 but it seems there are some breaking changes in the JavaScript switcher engine I need to sort out.

I recommend you to read the [“How to upgrade applications to version 3.X”](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/How-to-upgrade-applications-to-version-3.X) section of JavaScript Engine Switcher's documentation.

Also I recommend to read a [release notes of ReactJS.NET 4.0](https://reactjs.net/2019/01/4.0.0-release.html).

**Comment by dustinsoftware** [comment]
Hmm, I wonder if gulp up to date? Try running ‘npx gulp’ from the React.Core directory instead of using the globally installed version on your workstation. If that works, we should update the gulp dependency in that project.

**Comment by kendallb** [comment]
I don't use gulp at all, so maybe there is some kind of version issue there. I did an npm install gulp and it did something, so I will see if that makes a difference.

**Comment by kendallb** [comment]
I ran npx gulp in the same directory as dev-build, but it still does not fix it?

```
c:\src\git\react.net>npx gulp
npx: installed 318 in 7.831s
[[90m08:48:02[39m] [31mNo gulpfile found[39m
```

**Comment by dustinsoftware** [comment]
Try to CD into the src\react.core directory and run npx gulp from there.

**Comment by kendallb** [comment]
That does not work:

```
C:\src\git\React.NET\src\React.Core>npx gulp
internalBinding is not defined
```

**Comment by kendallb** [comment]
I installed gulp globally with 'npm install gulp -g' and changed the build.proj file to use that, but it still fails with the exact same command. So must be something to do with the latest version of node/npm/gulp?

**Comment by Daniel15** [comment]
You could try using nvm for Windows (https://github.com/coreybutler/nvm-windows) and switch to an older Node.js version. Perhaps we need to update something so the build works with newer Node.js versions.

**Comment by dustinsoftware** [comment]
Hey @kendallb,

I added a build script so you can use the version of `gulp` that is referenced in `React.Core`. To use, type `npm run build` in the `React.Core` directory. I'll keep investigating if a recent update to Node is breaking the build for you.

**Comment by dustinsoftware** [comment]
Nevermind, just repro'd on Node 11. Try Node 10, which is LTS.

**Comment by kendallb** [comment]
I am using Node 10?

**Comment by dustinsoftware** [comment]
@kendallb I must not have been running Node 10 before I did the update on my workstation, sorry about the confusion. 

Pinning a gulp dependency fixed the issue for me. I pushed a fix to master, would you mind pulling and trying again?

https://github.com/gulpjs/gulp/issues/2246

**Comment by kendallb** [comment]
Note sure why, but when I run dev-build.bat it still fails for me, but it does an npm install which seems to overwrite the package-lock.json file for some reason? It turns the locked versions into unlocked versions, so maybe that's why it keeps failing for me? Any idea what would cause that?

![capture](https://user-images.githubusercontent.com/535825/52547369-0be0fe80-2d7c-11e9-917a-1f90a91113cf.PNG)
