### ISSUE TITLE
Uncaught TypeError: undefined is not an object! When running the project.

### ISSUE THREAD

**Issue by simonssspirit** [reactjs/React.NET#713]
I get the following error when running the project.

I use MVC5 with Webpack and server rendering.

The application has a simple component. Does anybody has an idea why this error could occur.

```import React from 'react'

export default class IndexServer extends React.Component {
    render() {
        return (
            <div>
               Test
            </div>
        )
    }
}
```

This is server.js file:

```import IndexServer from './IndexServer';
import React from 'react';
import ReactDOM from 'react-dom';
import ReactDOMServer from 'react-dom/server';
import "@babel/polyfill";

global.IndexServer = IndexServer;
global.React = React;
global.ReactDOM = ReactDOM;
global.ReactDOMServer = ReactDOMServer;
```

This is the webpack config:

```
"use strict";

var path = require("path");
var WebpackNotifierPlugin = require("webpack-notifier");
var BrowserSyncPlugin = require("browser-sync-webpack-plugin");

module.exports = {

    entry: {
        main: ['babel-polyfill', './Content/components/server.js']
    },
    output: {
        filename: 'server.bundle.js'
    },
    resolve: {
        extensions: ['*', '.js', '.jsx']
    },
    module: {
        rules: [
            {
                test: /\.jsx$/,
                exclude: /node_modules/,
                use: {
                    loader: "babel-loader"
                }
            }
        ]
    },
    devtool: "inline-source-map",
    plugins: [new WebpackNotifierPlugin(), new BrowserSyncPlugin()]
};
````

**Comment by Taritsyn** [comment]
Hello, Stefan!

If this error is not issued by Node.js, then most likely you're using an JS engine that doesn't support the ECMAScript 6. Try installing the [JavaScriptEngineSwitcher.V8](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/V8) or [JavaScriptEngineSwitcher.ChakraCore](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/ChakraCore) module and [register it as the default engine](https://reactjs.net/getting-started/aspnet.html).

**Comment by dustinsoftware** [comment]
Try disabling server render by setting clientOnly: true in the call to @Html.React in your razor file. Then check the JavaScript console for any logged errors in your browser.

**Comment by simonssspirit** [comment]
@Taritsyn Thank you for the suggestions. I tried it but got an error when adding the packages. I checked and I have both installed in version 2.4.1? Is that ok?

@dustinsoftware I tried that, and the application started with no errors.

**Comment by Taritsyn** [comment]
>  I tried it but got an error when adding the packages. I checked and I have both installed in version 2.4.1? Is that ok?

What version of the ReactJS.NET do you use?

**Comment by Taritsyn** [comment]
@simonssspirit Try installing a version 2.4.2 of JavaScriptEngineSwitcher.V8.Native.win-x86 and JavaScriptEngineSwitcher.V8.Native.win-x64 packages:

```
Install-Package JavaScriptEngineSwitcher.V8.Native.win-x86 -Version 2.4.2
Install-Package JavaScriptEngineSwitcher.V8.Native.win-x64 -Version 2.4.2
```

But in the future I still recommend to update the ReactJS.NET to [version 4.0](https://reactjs.net/2019/01/4.0.0-release.html).

**Comment by simonssspirit** [comment]
Thank you, everyone, for the suggestions.
I was able to run the project an render it successfully using this:

```            ReactSiteConfiguration.Configuration
            .SetLoadBabel(false)
            .AddScriptWithoutTransform("~/dist/server.bundle.js");
```
The issue is that now there is no scripts loaded, on the pre rendered HTML which leaves the page with uninteractive components.

**Comment by dustinsoftware** [comment]
Do you have a `<script>` tag in your layout that references the generated bundle? [Something like this](https://github.com/reactjs/React.NET/blob/1f3e45b8494e62f514d4270c41ea886f9dd21f9f/src/React.Sample.Webpack.CoreMvc/Views/Home/Index.cshtml#L19)

**Comment by simonssspirit** [comment]
Yes I do, it is the same one referenced in the ReactConfig.

Is the other matter?

This is how the Index.cshtml looks like:

```
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Hello React</title>
    <link rel="stylesheet" href="@Url.Content("~/Content/KendoStyles.css")"></link>
    
</head>
<body>
    <div id="content"></div>
    <script src="/dist/server.bundle.js" )></script>
    @Html.ReactInitJavaScript()
    @Html.React("IndexServer", new
{
    initialComments = "test"
})
</body>
</html>

**Comment by dustinsoftware** [comment]
`@Html.ReactInitJavaScript()` must be called after `Html.React`, does that work?

**Comment by simonssspirit** [comment]
@dustinsoftware that was it, thank you so much for the assistance to all involved.
