### ISSUE TITLE
mvc core 2.2 + react 4.0 +webpack4

### ISSUE THREAD

**Issue by funhippo** [reactjs/React.NET#714]
I created mvc core 2.2 project and added React.AspNet 4.0.0 nuget package. Also i installed those npm packages to project:
`   devDependencies": {
    "babel-core": "^6.9.1",
    "babel-loader": "^7.1.5",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0-1",
    "clean-webpack-plugin": "^1.0.1",
    "css-loader": "^2.1.0",
    "json-loader": "^0.5.7",
    "jsx-loader": "^0.13.2",
    "remarkable": "^1.7.1",
    "style-loader": "^0.23.1",
    "ts-loader": "^5.3.3",
    "webpack": "^4.29.0",
    "webpack-cli": "^3.2.1"
  },
  "dependencies": {
    "bootstrap": "^4.2.1",
    "jquery": "^3.3.1",
    "jquery-validation": "^1.19.0",
    "jquery-validation-unobtrusive": "^3.2.9",
    "popper.js": "^1.9.9",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "typescript": "^3.2.4"
  }`
All that dependencies was builded with webpack without errors.
Then I wrote simple react component:
import "../../node_modules/bootstrap/dist/css/bootstrap.css"; 
import "../css/site.css"; 
import "../../node_modules/popper.js/dist/popper.js";
import "../../node_modules/jquery/dist/jquery.js";
import "../../node_modules/jquery-validation/dist/jquery.validate.js";
import "../../node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"
import "../../node_modules/bootstrap/dist/js/bootstrap.js";
import React from "../../node_modules/react/umd/react.development.js";
import ReactDOM  from "../../node_modules/react-dom/umd/react-dom.development.js";
import ReactModal from"../../node_modules/react-modal/dist/react-modal.js";
`global.React = React;
class Hello extends React.Component { render() { return ( <h1>TEST React.JS</h1> );   } } `
In the _Layout.cshtml i added:
`<script src="~/bundle/index.js"></script>
@RenderSection("Scripts", required: false)`
and in the Contacts.cshtml:
`@Html.React("Hello", new { name = "TestModa" })
@Html.ReactInitJavaScript()`
But after project starts "Contacts" page with react component couldn't load "bundle/index.js" and bootstrap/jquery doesn't work - there are no tag <script src=...> on page.  But all other pages works as required: tag script is present on page and bootsrap css styles applyed. When I delete helper @Html.React - page "Contacts" load bundle/index.js and use bootstrap.
P.S. Imports React, ReactDOM are requared for using ReactModal library.

**Comment by dustinsoftware** [comment]
Hi there 👋 

Imports from node modules won’t work without using webpack, please give the webpack sample project a look for supported use cases.

**Comment by funhippo** [comment]
But i'm using webpack with babel... That is part of my webpack.config.js:
    entry: './wwwroot/scripts/index.jsx',
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: [/node_modules/],
                loader: "babel-loader"
            },
            {
                test: /\.jsx$/,
                exclude: [/node_modules/],
                loader: "babel-loader"
            }

 .babelrc:           {  "presets": [  "es2015", "react" ] }      
  
And all stuff (bootstrap, jquery and other imports) were packed without errors.
Can I execute some react components from bundle "index.js" without @Html.React ?
