### ISSUE TITLE
ReactJS.NET has not been initialised correctly. Please ensure you have called services.AddReact() and app.UseReact() in your Startup.cs file.

### ISSUE THREAD

**Issue by apohto** [reactjs/React.NET#715]
I am running into this error when trying to use the React html extension to do server side rendering.

I am using the React.Web.Mvc4 v4.0.0 package for VS2017.

When I remove the extension method and try to render my component client side I am getting:

TinyIoCResolutionException: Unable to resolve type: React.Web.BabelHandler

This may be the underlying issue but I'm unsure how to resolve that either.

I have looked at #546 but I haven't been able to resolve my problem based on that.

Here is my component:

```
class PrimaryCallout extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            header: this.props.header,
            buttonText: this.props.buttonText,
            buttonLink: this.props.buttonLink
        };
    }

    render() {
        return (
            <div className="primary-callout-container">
                <h2 className="primary-callout-header">{this.state.header}</h2>
                <a href={this.state.buttonLink} className="primary-callout-link">
                    <button className="primary-callout-button">{this.state.buttonText}</button>
                </a>
            </div>
        );
    }
}
```

Here is my ReactConfig:

```
public static class ReactConfig
{
    public static void Configure()
    {
        JsEngineSwitcher.Current.DefaultEngineName = V8JsEngine.EngineName;
        JsEngineSwitcher.Current.EngineFactories.AddV8();

        ReactSiteConfiguration.Configuration
        .AddScript("~/Scripts/js/Components/PrimaryCallout.jsx");
    }
}
```

Please let me know if you need anything else from me.

**Comment by dustinsoftware** [comment]
Would you be able to list all the versions of the packages your project is using?

**Comment by apohto** [comment]
Of course I'm using React.Core, React.Web, and React.Web.Mvc4 all v4.0.0. I'm using JavaScriptEngineSwitcher.Core, JavaScriptEngineSwitcher.V8, JavaScriptEngineSwitcher.V8.Native.win-x64, and JavaScriptEngineSwitcher.V8.Native.win-x86 all v3.0.0. I'm also using Microsoft.AspNet.Mvc version 5.2.3.

It's also relevant to mention that I'm trying to do this in an EPiServer project using EPiServer.CMS v11.10.1.

**Comment by dustinsoftware** [comment]
I think we're going to need better logging here. My first suspicion is that the c++ runtime is not present on the machine you're using, so V8 isn't initializing properly. You could try another JS engine but that's just a guess. You could also try cloning this repo and running the samples.

**Comment by apohto** [comment]
Ok I'll try that and update with how it goes.

Thanks!

**Comment by apohto** [comment]
No luck swapping to ChakraCore

**Comment by Taritsyn** [comment]
@apohto Where do you call the `Configure` method of `ReactConfig` class? In `Global.asax` file?

**Comment by apohto** [comment]
@Taritsyn Yes I'm calling Configure in my Global.asax. Here:

```
public class EPiServerApplication : EPiServer.Global
{
    protected void Application_Start()
    {
        AreaRegistration.RegisterAllAreas();
        ReactConfig.Configure();

    }
}
```

**Comment by apohto** [comment]
@Taritsyn @dustinsoftware In a normal Asp.Net Mvc project where does React get initialized? Maybe there's something different about how or where an EPiServer project initializes things that is causing React to not be initialized even though under the wraps it's just an Mvc project?

**Comment by Taritsyn** [comment]
@apohto In ASP.NET 4.X samples a React initialization is performed by using the [WebActivator](https://github.com/davidebbo/WebActivator) library and `[assembly: WebActivatorEx.PreApplicationStartMethod(…)]` attribute ([see example](https://github.com/reactjs/React.NET/blob/b8521d954c5ad7c6c943c65234aa7cf93f13455a/src/React.Sample.Mvc4/App_Start/ReactConfig.cs)).

**Comment by apohto** [comment]
@Taritsyn @dustinsoftware I figured out my issue. It was as I thought a problem with my Babel setup not with React. I think the takeaway from this is that ReactJS.Net needs to be better about not smothering other error messages. Thank you both for your help. I'll close this now.

**Comment by oudoulj** [comment]
> @Taritsyn @dustinsoftware I figured out my issue. It was as I thought a problem with my Babel setup not with React. I think the takeaway from this is that ReactJS.Net needs to be better about not smothering other error messages. Thank you both for your help. I'll close this now.

Could you please elaborate on how you fixed your issue ? Thanks
