### ISSUE TITLE
Rendering array of children from database/partial view?

### ISSUE THREAD

**Issue by jerrywithaz** [reactjs/React.NET#717]
I am having a little trouble wrapping my head around using ReactJS.NET when it comes to partial views.

In our old system we used partial views as demonstrated below. Within the partial view we were able to get the child "widgets" from the database and render them using other partial views.

```
<div id="@Model.ClientID" class="ezzone">
    @foreach (nse.mvc.engine.Widget widget in Model.WidgetItems.OrderBy(s => s.k_Sort))
    {
        <div id="@widget.ClientID" class="ezwidget ezwidget--readonly">
            @Html.Partial(widget.WidgetFile, widget)
        </div>
    }
</div>
```

I want to be able to do the same with ReactJS.NET but I am having trouble understanding how to do that. Our new Placeholder file would look something like this inside of razor: 

```
@Html.React("Placeholder", new {
    readonly: @Model.Readonly,
    clientid: @Model.ClientID,
    available: @Model.Available,
    children: ?
})
```
And then let's say this placeholder wants to render 2 other components as it's children from the server like this:

```
@Html.React("TextEditor", new {...})
@Html.React("Slideshow", new {...})
```

How would I go about dynamically rendering the components?

Is it best do do somthing along these lines as outlined here: [https://reactjs.net/tutorials/aspnet4.html#optimization-server-side-rendering](https://reactjs.net/tutorials/aspnet4.html#optimization-server-side-rendering)

Where I would render the "Placeholder" with a "widgets" prop like such: 

```
[{
        "type": "TextEditor",
        "props": {}
    },
    {
        "type": "Slideshow",
        "props": {}
    }
]
```

**Comment by dustinsoftware** [comment]
You can't nest `Html.React` calls, so the best thing to do is to make your app "components all the way down" from any place you're calling `Html.React`.

For instance, if you call:

```
@Html.React("Placeholder", new {
    readonly = Model.Readonly,
    clientid = Model.ClientID,
    available = Model.Available,
    children = Model.Children // [{ "type": "TextEditor", "props": {} }, { "type": "Slideshow", "props": {} },  ]
})
```

Then your placeholder component could conditionally render other components inside of render:

```js
  render() {
    return this.props.children.map((child, i) =>
      child.type === "TextEditor" ? (
        <TextEditor key={i} {...child.props} />
      ) : child.type === "Slideshow" ? (
        <Slideshow key={i} {...child.props} />
      ) : null
    );
  }
```

Hope that helps, please feel free to comment further if you need more help!

**Comment by jerrywithaz** [comment]
That's pretty much where I ended up going after doing some more research. Thanks for your help!
