### ISSUE TITLE
Invariant Violation: Hooks can only be called inside the body of a function component.

### ISSUE THREAD

**Issue by tehOPEologist** [reactjs/React.NET#718]
converting a component to a function component output: Invariant Violation: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)

webpack entry is a function component, and the component this error is coming from is also a function component...

does ReactJS.NET support the now stable hooks API?

**Comment by Daniel15** [comment]
Should work fine as long as you upgrade to a React version that supports hooks.

Are you seeing this with server side rendering, or is it client side?

**Comment by tehOPEologist** [comment]
this error is coming from an @Html.React declaration, so i assume it's from the SSR.  component classes do this fine.  if you need an example repo i'll throw one together

**Comment by tehOPEologist** [comment]
both react and react-dom are on 16.8.1

**Comment by tehOPEologist** [comment]
here's a reproducable repo to verify the issue i'm having: https://github.com/tehOPEologist/Test

clone repo, go into Test project directory, run npm i, run npm run build, then open the solution file and start the debugger and it will attempt to go to the index page that has the @Html.React calls, and it'll error on the "Bar" entry that uses hooks.

if you comment the "Bar" entry, you can see that the "Foo" entry works without issue.  if you comment the "Foo" entry, Bar will still error, as normally it has no issue hydrating multiple entries on a single page, as long as they're component classes and not component functions with hooks it seems.

please let me know if you need anything else from me to replicate this issue.  i really want to utilize hooks, but this issue is stopping that entirely.  thank you!

**Comment by dustinsoftware** [comment]
It looks like you aren't calling `SetLoadReact(false)`, so your bundled version of React is not getting used on the server. The currently bundled version of react does not support hooks, but I'd like to fix that very soon!

Further, it looks like after loading all the chunks in your example, `global.ReactDOMServer` is not assigned, which is required for server-rendering.

In server.js:
```js
import React from 'react';
import ReactDOM from 'react-dom';
import ReactDOMServer from 'react-dom/server';
import Entries from './entries';

global.React = React;
global.ReactDOM = ReactDOM;
global.ReactDOMServer = ReactDOMServer;
global.Entries = Entries;
```

Also, your repo was a good example of using vendor chunks with webpack, so I'm going to integrate it into this library. Tracking progress in #721. Cheers 🍻

**Comment by tehOPEologist** [comment]
thank you so much for your response and the information!  i'm glad my naivety with the SetLoadReact method and adding ReactDOMServer to global helped the library with you seeing how to chunk out the vendors!  xD
