### ISSUE TITLE
Do I have an order of operations error?

### ISSUE THREAD

**Issue by rcouch00** [reactjs/React.NET#724]
I am using MVC4, 

After getting the documentation samples working, I am looking to do something with existing components.  I am attempting to plug in React-Visibility-Sensor, I expected to import the relevant scripts like so.

<script crossorigin="anonymous" src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
<script crossorigin="anonymous" src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
<script crossorigin="anonymous" src="https://unpkg.com/react-visibility-sensor@4.1.0/dist/visibility-sensor.js"></script>	

@Scripts.Render("~/bundles/main")  .. for my demo.jsx

Nothing more complicated here then the documentation examples..
Demo.jsx

class Demo extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			name: '...'
			, getElement: null
			, visible: true
			, msg: 'Element is initialized'
		};
		this.onVisibilitySensorChange = this.onVisibilitySensorChange.bind(this);
	}

	onVisibilitySensorChange(isVisible) {
		console.log('Element is now %s', isVisible ? 'visible' : 'hidden');
		this.setState({
			visible: isVisible ? true : false
			, msg: 'Element is now ' + (isVisible ? 'visible' : 'hidden')
		});
	}

	render() {
		return (
		<div>
			<VisibilitySensor onChange={this.onVisibilitySensorChange}>
				<div>...content goes here...</div>
			</VisibilitySensor>
		</div>
		);
	}
}

and on some view:
@Html.React("Demo", new {  }, serverOnly: false)

..All I ever end up with is a 500 internal server error from the view because:

Exception Details: Microsoft.ClearScript.ScriptEngineException: ReferenceError: VisibilitySensor is not defined

Demo.jsx is part of my ReactConfig and putting the script packages  in my _navLayout  I would expect the sensor component to resolve but it does not.

Any help pointing me in the right direction is greatly appreciated!

**Comment by dustinsoftware** [comment]
You'll need to host a copy of `visibility-sensor.js` in your project, and then call [AddScript](https://github.com/reactjs/React.NET/blob/1f3e45b8494e62f514d4270c41ea886f9dd21f9f/tutorial-code/Startup.cs#L69) so that it's available during the server render 🙂  Let me know how it goes!
