### ISSUE TITLE
reactjs.net certificate expired 

### ISSUE THREAD

**Issue by kpkozak** [reactjs/React.NET#739]
Hello, I can't see better place to report it, but https://reactjs.net website use expired SSL certificate.

### Steps to reproduce
visit https://reactjs.net

**Comment by dustinsoftware** [comment]
Thanks, we're taking a look 😃

**Comment by dustinsoftware** [comment]
Not sure if there was a temporary problem, but it appears to be valid now. 
![image](https://user-images.githubusercontent.com/942358/52970540-00d43280-3369-11e9-8d5e-64d03077429e.png)

**Comment by Daniel15** [comment]
Please let us know if you see this again... Netlify is supposed to auto renew the certificate, so I'll contact their support if it breaks again.

**Comment by glasody** [comment]
Hi,
This still seems to be a problem for me when trying to access the site on all major browsers.
![image](https://user-images.githubusercontent.com/9078067/53524775-3802ca80-3b45-11e9-89c2-d9fad79ed8ac.png)

> This server could not prove that it is reactjs.net; its security certificate expired 12 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Thursday, February 28, 2019. Does that look right? If not, you should correct your system's clock and then refresh this page.

above from chrome, my timezone is UTC +13

Thank you

**Comment by Daniel15** [comment]
I'm reaching out to Netlify's support team. I used this tool to check it: https://asm.ca.com/en/checkit.php and it looks like it's okay on some servers, but expired on others:

![image](https://user-images.githubusercontent.com/91933/53525131-f36c2600-3a95-11e9-98b1-baec1cf81b36.png)

**Comment by Daniel15** [comment]
@glasody or @kpkozak - Can you please re-test this? Netlify's support have mentioned that it shouldn't be broken any more.

**Comment by weltmeyer** [comment]
Still broken:
![image](https://user-images.githubusercontent.com/1668465/53550904-29fa7d00-3b38-11e9-934f-dc2be0f8adeb.png)

**Comment by Daniel15** [comment]
Thanks! I'm able to verify that an expired cert is being served from that server, using this command:
```
openssl s_client -connect 35.156.37.214:443 -servername reactjs.net
```

```
verify error:num=10:certificate has expired
notAfter=Feb 16 21:02:45 2019 GMT
```

I'll get in touch with Netlify again.

**Comment by Daniel15** [comment]
@weltmeyer This should be fixed now - Could you please check?

**Comment by NikolayPetyukh** [comment]
> @weltmeyer This should be fixed now - Could you please check?

It works:
![image](https://user-images.githubusercontent.com/8134986/53622000-15ce8280-3c01-11e9-9871-8ee8888a1c63.png)

**Comment by weltmeyer** [comment]
Jepp. Working for me too.

**Comment by dustinsoftware** [comment]
Thanks for checking!
