### ISSUE TITLE
bootstrap integration in RJS.NET

### ISSUE THREAD

**Issue by riddokun** [reactjs/React.NET#748]
Looking at the previous issues, I wasn't able to incorporate a simple component from reactstrap. Attached are images on how I am coding NavBar into the Layout Page. What am I doing wrong or what needs to be changed?

-------

(Describe your issue here)
![image](https://user-images.githubusercontent.com/12758776/53438956-00721200-39cf-11e9-9077-ee66bcca008d.png)
![image](https://user-images.githubusercontent.com/12758776/53438995-1253b500-39cf-11e9-81a2-cd72568c7601.png)
![image](https://user-images.githubusercontent.com/12758776/53439032-21d2fe00-39cf-11e9-9f50-cf6ec379117b.png)

**Comment by dustinsoftware** [comment]
This question has come up a few times, so I'm going to update the docs for it. I have the Mvc4 sample here showing how it can be done, please give that a look and comment here on how it worked out for you:

https://github.com/reactjs/React.NET/pull/750

**Comment by dustinsoftware** [comment]
Reactstrap samples added in #750
