### ISSUE TITLE
Issues including external scripts for use as webpack external dependencies

### ISSUE THREAD

**Issue by andycmaj** [reactjs/React.NET#75]
Getting a server-side error message trying to render a react component that depends on React-d3.js.

Error:
<pre>
Error while loading &quot;~/scripts/externs/react-d3.min.js&quot;: ReferenceError: document is not defined
    at Script Document [7]:9:29125 -&gt; 3_array=function(list){return d3_arraySlice.call(list)},d3_document=document,d
    at Script Document [7]:13:26437
    at s (Script Document [7]:6:559)
    at Script Document [7]:6:610
    at ./areachart (Script Document [7]:6:9775)
    at s (Script Document [7]:6:559)
    at e (Script Document [7]:6:726)
    at Script Document [7]:6:743
    at Script Document [7]:6:272
    at Script Document [7]:6:277
Line: 9
Column:29125
</pre>

Scenario:
- Webpack bundle including a react component that requires 'd3-react' library.
```javascript
'use strict';
var React = require('react'),
    BarChart = require('react-d3').BarChart;
var Test = React.createClass({
  render: function() {
    var barData = [
      {label: 'A', value: 5},
      {label: 'B', value: 6},
      {label: 'F', value: 7}
    ];
    return (
      <div>
        pretend im useful: {this.props.data}
        <BarChart data={barData} width={500} height={200} fill={'#3182bd'} title='Bar Chart' />
      </div>
    );
  }
});
module.exports = Test;
```
- Webpack entrypoint including Test.jsx
```javascript
module.exports = {
  Test: require('expose?Test!charts/Test')
};
```
- Webpack config specifying externals including 'React' and 'react-d3'.
```javascript
externals: {
  // Don't bundle these with the server-side bundle. React.NET needs these to be globals
  react: 'React',
  'react-d3': 'react-d3'
},
```
- Server-side ReactConfiguration including 'react-d3' script. Using V8 engine.
```csharp
            React.ReactSiteConfiguration
                .Configuration
                .AddScript("~/scripts/externs/react-d3.min.js")
                .AddScript("~/scripts/c/server/Charts.js");
```

**Comment by Daniel15** [comment]
The `document` global doesn't exist in a server-side JavaScript environment, and you'd encounter the same issue on any other server-side environment (eg. Node.js too). It's part of the browser object model. You'll need to find the code that's accessing `document` and figure out what it's trying to do and if it can be modified to handle server-side execution.

**Comment by andycmaj** [comment]
Looks like it's JSDOM in this case... I think I might just have to include jsdom as a ReactConfiguration script...

**Comment by Daniel15** [comment]
You should be able to get Webpack to bundle react-d3 and all its dependencies (including JSDOM) into the one bundle.

**Comment by Daniel15** [comment]
Going to close this issue because this is an issue with the scripts rather than ReactJS.NET itself. Please feel free to continue using the issue for discussion, even after it is closed. Thanks!

**Comment by PeteDuncanson** [comment]
We've taken to bundling everything (React in our case React-Router) into one bundle and then just including that one bundle in our React.config scripts. We've a fork of React.net which doesn't include React so it just runs our bundle. Seems to work pretty good and removed a lot of the headaches we had with "external".

**Comment by Daniel15** [comment]
> We've taken to bundling everything (React in our case React-Router) into one bundle and then just including that one bundle in our React.config scripts

If using Webpack, you can mark React as an external script in your config:

```
  externals: {
    // Use external version of React (from CDN for client-side, or bundled with ReactJS.NET for server-side)
    react: 'React'
  }
```

This means you can use the bundled React version for server-side rendering, and a version off the Facebook CDN for client-side rendering. Up to you though, bundling React is also a fine approach :)
