### ISSUE TITLE
How to use asp.net core redirect with react? 

### ISSUE THREAD

**Issue by ilya-barkalov** [reactjs/React.NET#751]
Hello! I'm use React.Aspnet for server side rendering. And Reactjs.net do it well! But I have question. 

For example, we have two page (login, main) and one controller (home). 
When application starts we redirect to appname/home/login (or simple login) after this we fill some fields and submit login form. And rich post method auth witch return RedirectToAction("main"), but nothing happens. Login page refresh and I get response with main page, but not redirect to appname/home/main where we should render main page component. How I can resolve this?

**Comment by dustinsoftware** [comment]
It sounds like you'll need to handle the redirect in client-side Javascript. ReactJS.NET won't handle any of the redirects for you unless you are using the react router integration (which it sounds like you aren't)
