### ISSUE TITLE
Creating a global state object

### ISSUE THREAD

**Issue by aventic** [reactjs/React.NET#753]
How can I create a global state object for all my components to reach into? Normally I would just put that object on the window, but on the server there's no window ofcouse.

I have multiple `@Html.React("MyComponent", new {})` so on the top of my head I could pass those global variables into all of these instances as props. But is there a better way to do this, as the data would be the same for each component.

I have been trying to set a variable with this line (seen in another thread):
`ReactEnvironment.Current.Execute("var globalState = { sharedUrl: 'https://....' }");`

But inside my bundle I can't seem to pick up the globalState variable - it's just empty.

As a note, I'm not running this as a SPA

**Comment by Daniel15** [comment]
Yeah I'd store these in variables in C# and then pass them in as props.

**Comment by dustinsoftware** [comment]
If you need to re-use state across the all of your rendered views, you could disable engine re-use via `SetReuseJavaScriptEngines`, although this comes with a performance penalty. As Daniel recommended, you should probably just pass them in via props.

Hope that helps!
