### ISSUE TITLE
Can this library be used for ASP.NET Webforms?

### ISSUE THREAD

**Issue by rkpujari** [reactjs/React.NET#756]
Can you please let me know if ReactJS.NET library be used for ASP.NET Webforms? I couldn't find any tutorial or documentation for ASP.NET Webforms in https://reactjs.net/ website. It shows examples only for ASP.NET Core and MVC, but not for Webforms. If it cannot be used, then are there any other ways to integrate ReactJS into existing ASP.NET Webforms application, please let me know. We have a legacy ASP.NET Webforms application and have a requirement to integrate a React component into it. if you have any information related to this, please share it. Thanks in advance. I couldn't find an option to ask question here, so submitting a new issue.

**Comment by dustinsoftware** [comment]
Hi there 👋 

WebForms is not supported by this library directly, but a few others have attempted making it work. You might find some helpful guidance in this issue: #55

**Comment by rkpujari** [comment]
Thanks for quick response. I am not sure if the proposed solution will
support integrating a complex a React app into an existing ASP.NET Webforms
app, but will look into that.
