### ISSUE TITLE
@Html.React + serverOnly + renderfunctions

### ISSUE THREAD

**Issue by technicaldogsbody** [reactjs/React.NET#765]
- [x] The relevant native JavascriptEngineSwitcher library packages are installed (such as `JavaScriptEngineSwitcher.V8.Native.win-x64`)
- [x] The VC++ 2017 runtime is installed
- [x] The value of `SetUseReact` and `SetUseBabel` is correct in `ReactConfig.cs` or `Startup.cs`
- [x] I've looked at the sample projects in this repo to verify that my app is configured correctly

### I'm using these library versions:
- `ReactJS.NET`: React.Aspnet 4.1.1
- `JavaScriptEngineSwitcher`: ChakraCore 3.0.7
- `react` and `react-dom`: 16.8.2
- `webpack`: 4.29.6
- `node`: 10.13.0

### Runtime environment:
- OS: Windows 10 64bit
- .NET Framework or .NET Core Version: .Net Core 2.1/2.2

### Steps to reproduce

-------

When using @Html.React with serverOnly set to true the styled components render function always returns null, remove serverOnly or set clientOnly and it works, the only workaround I have found to achieve what I want is to use @Html.ReactRouter and everything works as expected.

**Comment by dustinsoftware** [comment]
Sounds like a bug, I’ll take a look

**Comment by dustinsoftware** [comment]
Fixed by #793
