### ISSUE TITLE
Serverside StyledComponents for many @Html.React calls

### ISSUE THREAD

**Issue by simple17** [reactjs/React.NET#766]
Hello,

What is the best way to use StyledComponentsFunctions and ChainedRenderFunctions for multiply components?

Currently i'm trying something like

`    
var component1StyledComponentsFunctions = new StyledComponentsFunctions();
var component2StyledComponentsFunctions = new StyledComponentsFunctions();
`

`@Html.React("Component1", new { initialData1 }, clientOnly: clientOnly, renderFunctions: new ChainedRenderFunctions(component1StyledComponentsFunctions))`

`@Html.React("Component2", new { initialData2 }, clientOnly: clientOnly, renderFunctions: new ChainedRenderFunctions(component2StyledComponentsFunctions))`

`
@Html.Raw(component1StyledComponentsFunctions.RenderedStyles)
@Html.Raw(component2StyledComponentsFunctions.RenderedStyles)
`

But in this case I have two <style> with some duplicatated classes.
I tried to use only one StyledComponentsFunctions but the first component styles are overridden by the second one.

**Comment by dustinsoftware** [comment]
If the generated styles are overwriting each other, you may need to make your style definitions unique. Hard to say without an example. It should “just work”..

**Comment by dustinsoftware** [comment]
Just to add to this, there isn't a good way to deduplicate the styles with multiple component renders. I'd recommend consolidating your components together if possible, or disabling server-rendering and using React portals to render into specific divs if you have a lot of other non-React view code in your app :)
