### ISSUE TITLE
Tutorial.jsx throws 500 internal server error

### ISSUE THREAD

**Issue by jigshGitHub** [reactjs/React.NET#768]
I have followed all instructions for Tutorial (ASP.NET Core) for ReactJS.Net. I have built sample solution in Visual studio 2019. 
I used ASP.Net Core Web Application template and installed following packages through nugget
microsoft.extensions.dependencyinjection.abstractions
microsoft.extensions.dependencyinjection
microsoft.extensions.filesystemglobbing
microsoft.extensions.primitives
microsoft.extensions.fileproviders.abstractions
microsoft.extensions.fileproviders.physical
microsoft.extensions.caching.abstractions
JavaScriptEngineSwitcher.Extensions
JavaScriptEngineSwitcher.ChakraCore
React.Aspnet 4.1.1

Once I successfully set up I created Tutorial.jsx file to run sample code 
But it gives an 500 internal server when I browse through localhost

**Comment by dustinsoftware** [comment]
Were you able to build the sample tutorial code in this repo? Do you have a
specific stack trace for the error?

**Comment by dustinsoftware** [comment]
More information is needed to debug this, please comment when you'd like some more help 👍
