### ISSUE TITLE
SharedAssemblyVersionInfo referenced but not in solution

### ISSUE THREAD

**Issue by c0state** [reactjs/React.NET#77]
There is a SharedAssemblyVersionInfo.cs file referenced in the cspoj files but I don't see it in the root of the solution where it's expected.

**Comment by Daniel15** [comment]
It's generated by build.bat. Once it's generated, you can build from Visual
Studio directly. This is documented in the readme and also on the website
:)

**Comment by c0state** [comment]
Sorry, my bad--should have looked deeper first :)
