### ISSUE TITLE
React.js component testing in ASP.NET Core project in Visual Studio 2017

### ISSUE THREAD

**Issue by kmartin4** [reactjs/React.NET#770]
Sorry if this is the wrong location. Having trouble unit testing React.Js components in ASP.NET Core project in Visual Studio 2017. Is this possible? If so can I get a reference to read, having trouble finding material. Thanks

**Comment by dustinsoftware** [comment]
Take a look at the integration tests in this project, that should give you a good starting point 👍

Cheers

**Comment by dustinsoftware** [comment]
Closing as this question has been answered, please open a new issue or comment if you'd like some more help.
