### ISSUE TITLE
Shared store (Redux?)

### ISSUE THREAD

**Issue by thurfir** [reactjs/React.NET#771]
Hello,

Is there a way in the React.NET library to share some state across multiple @Html.React components?

Redux seems a good starting point to share a store so I checked https://github.com/reactjs/React.NET/issues/513 , but I fails to see how to pass my store across ReactJS.NET components, expecially when using SSR.

My goal is to use multiple small components across my page instead of one big react tree.

**Comment by Daniel15** [comment]
Don't think there's an easy way of doing this at the moment, as I think that different components could use different instances of the JS engine. @dustinsoftware  might have some ideas here.

**Comment by dustinsoftware** [comment]
The preferred strategy here is to use a single React component hierarchy for your Redux store, but if that's not an option..

You could extend `RenderFunctionsBase` to serialize the store to a string - this is sort of how `StyledComponentsFunctions` works, except it just grabs the result of a style render and creates an inline `style` tag. JS engines are returned to the pool after each call to `Html.React`, so if you want to set some kind of global, you'll need to turn of engine pooling.

You could also disable server rendering and leverage client-side React portals to render into different parts of your page.

I've never tried to connect a Redux store to components that live in separate UMD scripts - presumably you'd use a JS global or something like that to keep shared state...

**Comment by thurfir** [comment]
Thank you @dustinsoftware your insights helped a lot. A single hierarchy doesn't fit my needs, mainly because we want to integrate React in an existing website where rewriting everything would be a pain.

I was able to create a RenderFunctions following your instructions:
```csharp

    public class ReduxStoreFunctions : RenderFunctionsBase
    {
        public string InitialStore { get; }

        private bool JSLoaded { get; set; }

        public ReduxStoreFunctions()
        {
            InitialStore = "store = ReduxStore.createStore();";
        }

        public ReduxStoreFunctions(object storeModel)
        {
            var settings = new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() };
            var serialized = JsonConvert.SerializeObject(storeModel, settings);

            InitialStore = $"store = ReduxStore.createStore({serialized});";
        }

        /// <summary>
        /// Implementation of PreRender
        /// </summary>
        /// <param name="executeJs"></param>
        public override void PreRender(Func<string, string> executeJs)
        {
            if (JSLoaded) { return; }

            executeJs(InitialStore);
            JSLoaded = true;
        }
    }

```

Where createStore is a JS function that init my store with its reducers, and I output InitialStore to Razor before ReactInitJavaScript() for the client-side rendering.

Since the IReactEnvironment is persistent per-request, I should be able to keep the engine pooling enabled by writing my own HtmlHelperExtensions without Environment.ReturnEngineToPool() and calling the method manually at the end of my pages, am I correct?

On a side note, the JS engines retain their state even after they are sent back to the pool, hence the ugly (but working) "store = ..." without a const/let/var .

**Comment by dustinsoftware** [comment]
That should work as long as you disable engine pooling, which you can
configure via ReactConfig. It comes with a little delay but should work
fine for your needs..

**Comment by thurfir** [comment]
Hello @dustinsoftware I would like to keep the engine pooling enabled if possible.

From my understanding, every ReactJS.NET component acts like this:

1. The Razor extension get an (PerRequestSingleton) Environment and create a component.
2. At render, the Environment lazily grab (=lock) a JS engine from the pool and evaluate the component.
3. The Razor extension tells the Environment to return (=unlock) the engine to the pool.

Therefore If I'm not mistaken, if I remove the step (3), the JS engine will be persisted accross the render of my page without disabling engine pooling.

What do you think?

**Comment by dustinsoftware** [comment]
I don’t recommend rolling your own engine management solution, because if
an engine isn’t returned to the pool your app will eventually fail to
render due to engine exhaustion. You’re certainly welcome to try it though
and let us know how it goes!

**Comment by dustinsoftware** [comment]
Closing as this question has been answered, please open a new issue or comment if you'd like some more help.

**Comment by thurfir** [comment]
In case someone has the same needs this solution as been working great for us so far.
As stated by dustinsoftware you just have to be sure you return the JS engine at the end of page rendering or you might run out.
Thanks for the help and for this library!

**Comment by schmitch** [comment]
would it be possible to create some kind of example for that?

**Comment by thurfir** [comment]
Hi @schmitch , I wouldn't know how to write a clean, self-contained example of this.

In short:

1 - Start from HtmlHelperExtensions from the project. Write your own and remove the finally-ReturnEngineToPool calls.

2 - Serialize your JS store, run it and set a _myStore_ variable in a <script> before the call to ReactInitJavaScript . 

2' - For SSR, use an RenderFunctionsBase to run this same code before your first component.

3 - Use the myStore as regular redux: <Provider store={mySstore}>...

x - Don't forget to return the engine to the pool at the end of the request !
