### ISSUE TITLE
Semantic UI react webpack integration - 

### ISSUE THREAD

**Issue by slown1** [reactjs/React.NET#777]
- The relevant native JavascriptEngineSwitcher library packages: - - 
- `JavaScriptEngineSwitcher.V8.Native.win-x64 and x86`
- The VC++ 2017 runtime is installed
- SetUseReact is not set, SetUseBabel is not set -> I assume the default it is false.

- I've looked at the sample projects in this repo to verify that my app is configured correctly because I forked the source code and it worked. I just added my semantic UI dependency on top and it breaks.

### I'm using these library versions:
- `ReactJS.NET`:
- `JavaScriptEngineSwitcher`: - V8
- `react` and `react-dom`: (N/A if using bundled react, or version number)
- `webpack`: (N/A if using bundled react)
- `node`: (N/A if using bundled react)

### Runtime environment:
Windows 10 64-bit
- .NET Framework

### Steps to reproduce

I have followed the sample on how to integrate a third party like reactstrap from here:
https://github.com/reactjs/React.NET/pull/750. 

After I render in sample.jsx a semantic ui react component:
<semanticUIReact.Button>Click Here Semantic UI</semanticUIReact.Button> I get the following error:

**ReferenceError: window is not defined**  if I do not reference any semantic UI component - I have made sure that I have included the UMD js file which is : "semantic-ui-react.min.js"
![download](https://user-images.githubusercontent.com/2652146/56083050-b7640900-5e28-11e9-946c-a62a2658a466.png)

You can search by : added semantic ui dependency -  to see where I have added code - 
in home/index.cshtml, in ReactConfig.cs and sample.jsx

Am I right in saying that this is how I should reference the Button from semnatic? semanticUIReact ? I have seen this in the UMD file: exports.semanticUIReact=t(require("React"),require("ReactDOM"))

Can somebody explain what the TransformBabel.proj file does? I can understand that it does the whole magic but maybe I am missing something.

Here is my repo:

https://github.com/dustinsoftware/React.NET/compare/bootstrap-sample...slown1:bootstrap-sample

**Comment by slown1** [comment]
@dustinsoftware  can you help? Thank you very much

**Comment by Taritsyn** [comment]
Hello, Flavius!

JavaScript Engine Switcher's modules can execute only clean ECMAScript code and do not support browser environment. Accordingly, `window` object is not supported.

Typically, to solve this problem, use such a shim:

```js
var global = global || {};
```

But in your case, you may need another implementation.

**Comment by slown1** [comment]
Dear Taritsyn,

Thank you very much. I was looking in the source code by shims.js and I see I have it in the React.Core project.

Can you suggest a place where to put it? Should I put it in the React.Sample.Mvc4? If so, how? 
I am a bit stuck and out of ideas.

Thanks, 
Flavius

**Comment by Taritsyn** [comment]
First of all, you need to see how used a `global` and `window` objects in the `semantic-ui-react.js` file. And whether the `global` object is used there at all?

If not, use the following shim:

```js
var window = window || {};
```

**Comment by slown1** [comment]
I do not know how to put in place a shim? Where do I reference it? Is it just a js file I reference in the Index.cshtml?

**Comment by Taritsyn** [comment]
In the `App_Start/ReactConfig.cs` file:

```csharp
ReactSiteConfiguration.Configuration
	…
	.AddScriptWithoutTransform("~/Content/lib/window-shim.js")
	…
	;
```

**Comment by slown1** [comment]
Thanks,

I get this now...
![screenshot-localhost-63919-2019 04 13-22-47-17](https://user-images.githubusercontent.com/2652146/56084619-2b5cdc00-5e3e-11e9-8ca0-0255a8eb9781.png)

Any suggestions? 

I will push this also on the repo:
https://github.com/slown1/React.NET

**Comment by dustinsoftware** [comment]
There is a bug in your app somewhere. Use clientOnly: true to determine
where the component crash is using the chrome debugger.

**Comment by slown1** [comment]
Hi,

I have put clientOnly and still the same eror.

I have added the shim and js file:
![sample-1](https://user-images.githubusercontent.com/2652146/56090282-0a7da080-5ea9-11e9-8689-b2e4d3e205ed.png)

Rendered the component with clientOnly true and also referenced the semnati-ui-react cdn link
![sample-2](https://user-images.githubusercontent.com/2652146/56090283-0c476400-5ea9-11e9-8caf-4541ca0958d5.png)

I am pretty sure this is the export which tells me how to reference a button => <semanticUIReact.Button>C
![sample-5](https://user-images.githubusercontent.com/2652146/56090328-b7581d80-5ea9-11e9-9f54-736aaa5bbad2.png)

reference a semnatic ui react button
![sample-4](https://user-images.githubusercontent.com/2652146/56090296-3a2ca880-5ea9-11e9-8476-8bcaef26c058.png)

and still have the error at line 1330:3453
![sample-3](https://user-images.githubusercontent.com/2652146/56090284-0e112780-5ea9-11e9-8661-36fac12d1b0c.png)

I have pushed the code here, maybe you can inspect better if you run the code:
https://github.com/slown1/React.NET/tree/bootstrap-sample

**Comment by dustinsoftware** [comment]
Semantic UI react requires that you use a bundler per the docs. https://react.semantic-ui.com/usage

Please use webpack and checkout the webpack sample.

**Comment by slown1** [comment]
Hi @dustinsoftware,

I have spinned a new repo:
https://github.com/slown1/Reactjs.Net-Webpack-sample

I get the 

Can you have a look and maybe point out if I did well the upgrades to babel 7?
@Taritsyn maybe you can help.

I have seen this issues already on the net but I could not manage to solve it yet.

![Screenshot_wepack-1](https://user-images.githubusercontent.com/2652146/56098263-5a8b5000-5f07-11e9-9c2c-13648b39de33.png)

This is my setup:

![sample-3](https://user-images.githubusercontent.com/2652146/56098194-b5707780-5f06-11e9-800c-687e64ce9eea.png)

![Screenshot_wepack-2](https://user-images.githubusercontent.com/2652146/56098250-3fb8db80-5f07-11e9-83c2-6802b3b013a2.png)

![Screenshot_wepack-3](https://user-images.githubusercontent.com/2652146/56098251-40517200-5f07-11e9-91a9-2f388f33ed57.png)

![Screenshot_wepack-4](https://user-images.githubusercontent.com/2652146/56098252-40517200-5f07-11e9-8299-6af3591f058d.png)

![Screenshot_wepack-5](https://user-images.githubusercontent.com/2652146/56098253-40517200-5f07-11e9-89b5-866d8ab53974.png)

Do you think I have setup the sample properly? Semantic UI is used by a lot of developer and I think it would be of general interest to have this an integration.

BR,
Flavius

**Comment by Taritsyn** [comment]
@slown1 You need to install NuGet packages with native V8 assemblies: [JavaScriptEngineSwitcher.V8.Native.win-x86](http://nuget.org/packages/JavaScriptEngineSwitcher.V8.Native.win-x86) and [JavaScriptEngineSwitcher.V8.Native.win-x64](http://nuget.org/packages/JavaScriptEngineSwitcher.V8.Native.win-x64).

**Comment by dustinsoftware** [comment]
Please give the “getting started” sections of the docs a guide a look. If they don’t cover your issue or they aren’t clear let’s continue the discussion from there 👍

**Comment by slown1** [comment]
@dustinsoftware I have seen that somebody just merged with babel 7 support and webpack. Can you guys update the docs for that? - https://reactjs.net/bundling/webpack.html
I am using .Net Framework not .Net Core.

Thanks, I will also look in the next few days at that.

BR,

Flavius

**Comment by dustinsoftware** [comment]
It’s a beta so I don’t want the main docs updated until we officially
release it :)

**Comment by Daniel15** [comment]
@dustinsoftware - If you think it'd be useful, we could set up a separate branch with docs on the latest beta, then I could configure that as a separate subdomain (eg. `beta.reactjs.net`)

**Comment by slown1** [comment]
If you guys can explain some things to me on a skype call, I could contribute as well and we actually need this. 
I have contributions to other open source projects and we have other colleagues that want to help. I just need some intro help from you. 

Would that work?

BR,
Flavius

**Comment by dustinsoftware** [comment]
I want to keep all discussion in this thread so others can benefit from it. Webpack support has been around for some time; have you tried that approach yet? Check out the sample and the docs to see how it’s done.

**Comment by slown1** [comment]
Hi guys,

@dustinsoftware what do you thing about the beta idea that @Daniel15 has?

Thanks.
Flavius

**Comment by dustinsoftware** [comment]
I’m open to it but the existing webpack docs on the website should cover your case already. Babel 7 was about adding typescript support.
