### ISSUE TITLE
ReactServerRenderingException: Error while rendering "component" to "react_jbgwI98lBUKeUkecdbT5DQ": ReferenceError: 'component' is not defined

### ISSUE THREAD

**Issue by LeonidasFettikus** [reactjs/React.NET#789]
Hi guys,

I followed [this](https://medium.com/@mirela95/asp-net-core-2-0-mvc-with-reactjs-net-basic-setup-and-example-template-4811b10b114a) tutorial on building a simple MVC Core solution which uses webpack and react to render server side components with ReactJS.NET. However, after trying to add [Office UI Fabric React](https://developer.microsoft.com/en-us/fabric#/components) and importing a component in my application, I get the above error.

It would be really great to use ReactJS.NET with OUI, so I really want to get this to work. Any ideas?

My repo where I tried adding Office UI be found [here](https://github.com/LeonidasFettikus/ASP.NET-Core-MVC-ReactJS.NETWithOUI/tree/master/ASPNETCoreReactNET-Example)

If I add an import statement in my ExampleComponent file, I get a different error: 

```
import TextField from "office-ui-fabric-react"; //this doesn't work

class ExampleComponent extends React.Component {
    render() {
        return (
            <div className="testDiv">
                <TextField label="With error message" errorMessage="Error message" />
                <h1>{this.props.user.name}</h1>
                <h3>{this.props.user.age}</h3>   
            </div>
        );
    }
}
```

`ReactScriptLoadException: Error while loading "~/dist/bundle.js": Error: Module build failed: Error: Parse Error: Line 1: Illegal import declaration`

EDIT: I noticed that my resulting bundle.js contains all the components from Office UI Fabric, so why can't I import them in my component?

**Comment by dustinsoftware** [comment]
You are using an import declaration, so you need to use webpack if your project isn’t already :)

**Comment by dustinsoftware** [comment]
Hmmm I’m not sure. I think a few others have tried to use that library unsuccessfully, don’t remember offhand why it doesn’t “just work”. Try importing the bundle into a terminal running NodeJS by typing require(“./dist/bundle.js”).

**Comment by dustinsoftware** [comment]
I don't see offhand why it isn't working for you, sorry. Please try adding office UI to the webpack sample in this repo. If you run into the same issue there, then the library may be referencing a symbol (such as window) that isn't available during server-side render....

Since this is an integration question with a third-party library I am going to close the issue, feel free to comment if you find what was causing the crash
