### ISSUE TITLE
How to show transpiler errors?

### ISSUE THREAD

**Issue by Domiii** [reactjs/React.NET#794]
We are using Visual Studio with `React.NET` and `BabelPlugin`, using the default configuration. Every time I make any changes, I see that React.NET picks it up and recompiles it in the `Output` window, like this:

> [JSPool] Watched file 'C:\myCode\React\Home\TrackingContainer.jsx' changed
> [JSPool] Watched file 'C:\myCode\React\Home' changed
> [JSPool] Watched file 'C:\myCode\React\Home\TrackingContainer.jsx~RFf048e3c.TMP' changed
> [JSPool] Watched file 'C:\myCode\React\Home' changed

However, I do not see it reporting any errors if the transpiler failed. It fails silently and in the final page, that file will just not be there.
How can I get it to report errors?

**Comment by dustinsoftware** [comment]
Do you see any rendered output when fetching the file directly? Usually an error message will appear at that phase if transpilation fails. It could be nice to also write that to the Debug window as well.

**Comment by Domiii** [comment]
Can only work on this codebase on Thursdays. Might be able to try this week, and I will let you know what comes out of it.

Thanks for the swift response!

**Comment by dustinsoftware** [comment]
Great. Let me know what you find. Closing this issue in the meantime.
