### ISSUE TITLE
0000000000000000

### ISSUE THREAD

**Issue by dustinsoftware** [reactjs/React.NET#795]
Thanks for filing a bug! To save time, if you're having trouble using the library, please check off the items you have tried. If you are just asking a question, skip right to the bottom.

### Please verify these steps before filing an issue, and check them off as you go
- [ ] The relevant native JavascriptEngineSwitcher library packages are installed (such as `JavaScriptEngineSwitcher.V8.Native.win-x64`)
- [ ] The VC++ 2017 runtime is installed
- [ ] The value of `SetUseReact` and `SetUseBabel` is correct in `ReactConfig.cs` or `Startup.cs`
- [ ] I've looked at the sample projects in this repo to verify that my app is configured correctly

### I'm using these library versions:
- `ReactJS.NET`:
- `JavaScriptEngineSwitcher`:
- `react` and `react-dom`: (N/A if using bundled react, or version number)
- `webpack`: (N/A if using bundled react)
- `node`: (N/A if using bundled react)

### Runtime environment:
- OS: (Mac, Windows, Linux flavor. Include 32-bit/64-bit and version)
- .NET Framework or .NET Core Version:

### Steps to reproduce

-------

(Describe your issue here)

**Comment by Daniel15** [comment]
Nice, @dustinsoftware!

**Comment by dustinsoftware** [comment]
Lol, my son found the keyboard
