### ISSUE TITLE
ASP.NET MVC 4 with Babel 7 + server-side rendering + Fragments ?

### ISSUE THREAD

**Issue by oudoulj** [reactjs/React.NET#798]
I've just added ReactJS.NET 4.1.1 to my ASP.NET MVC 4 project and tried to do some server-side rendering using @Html.React()
**I realized I couldn't use React.Fragment** though because it requires Babel 7.
So I was wondering if you have any idea when ReactJS.NET with Babel 7 would be available ?

If that's not due soon, can someone advise a good tutorial on how to use the webpack integration as suggested on https://reactjs.net/2019/03/4.1.1-release.html ?
And how to generate a Babel 7-ready bundle.server.js file.
Thank you !

**Comment by dustinsoftware** [comment]
The webpack docs are here: https://reactjs.net/bundling/webpack.html

There is a webpack sample here: https://github.com/reactjs/React.NET/tree/master/src/React.Sample.Webpack.CoreMvc

Babel 7 is currently in one of the alpha builds, please enable it via [this setting](https://github.com/reactjs/React.NET/blob/2314096f01727928136dc1b85ab7029eb6d6435a/src/React.Sample.Mvc4/App_Start/ReactConfig.cs#L23).

We'll make Babel 7 the default in 5.0 but for now it is opt in.

**Comment by oudoulj** [comment]
Using the [latest 5.0 alpha 3](https://www.nuget.org/packages/React.AspNet/5.0.0-alpha3) and adding the following line did the work, thanks !
ReactSiteConfiguration.Configuration.SetBabelVersion(BabelVersions.Babel7);
