### ISSUE TITLE
Support source maps

### ISSUE THREAD

**Issue by Daniel15** [reactjs/React.NET#8]
Files transformed to JSX on-the-fly should also output the associated source map
- Does JSX transformation even support source maps at the moment?
- May need to cache on disk in addition to in-memory? See if ASP.NET output caching with file dependency is sufficient.

**Comment by zzz6519003** [comment]
does the react project itself support sourcemap?  that way i can read source code more easily by debugging the program  XD

**Comment by Daniel15** [comment]
Yeah, source maps should be supported. ReactJS.NET supports source maps, as does React itself. Other third party libraries like Webpack, Gulp and Babel support source maps too.
