### ISSUE TITLE
Can't seem to get clearscript to work after deploy

### ISSUE THREAD

**Issue by shadowii** [reactjs/React.NET#80]
The basic reactjs.net packages work fine, so I decided to try out V8. I installed the React.JavaScriptEngine.ClearScriptV8 through the package manager. However, after deploying to our web server, I continually get the following error: 

>Failed to initialise ClearScript V8. This is most likely caused by the native libraries (ClearScriptV8-64.dll and v8-x64.dll) missing from your app's Bin directory. Please ensure your app is referencing the JavaScriptEngineSwitcher.V8 NuGet package.

After copying over those files to both the bin directory and the site's root directory, the error simply changes to a different one: 

>Could not load file or assembly 'ClearScriptV8-64.DLL' or one of its dependencies. The specified module could not be found.

Any ideas? I should note that the clearscript binaries currently seem to deploy to a ClearScript.V8 folder within the bin directory.

**Comment by steroberts89** [comment]
Hey,
Ensure you have this installed on your webserver http://www.microsoft.com/en-us/download/details.aspx?id=30679 (Visual C++ Redistributable for Visual Studio 2012 Update 4)

It's bundled with Visual studio which is why it'll be running locally!

Cheers

**Comment by shadowii** [comment]
Thanks, I'll give that a whirl

**Comment by Daniel15** [comment]
Sorry about that, there should probably be more documentation. Initially V8 was only supported on Linux and Mac OS (via Mono), the Windows support via ClearScript is a fairly recent addition. If you get a chance, feel free to submit a pull request adding more documentation (or just ask me to do it) :)

**Comment by Daniel15** [comment]
Sorry about that, there should probably be more documentation. Initially V8 was only supported on Linux and Mac OS (via Mono), the Windows support via ClearScript is a fairly recent addition. If you get a chance, feel free to submit a pull request adding more documentation (or just ask me to do it) :)

**Comment by jlchmura** [comment]
Note that the latest release of ClearScript no longer supports VS2012, so the VS2013 C++ runtimes must be installed now: http://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by shadowii** [comment]
Just another note, ClearScript 5.4.4 readme says VS2015 or 2013 C++ runtimes will work, but in my experience, it only worked when 2013's was present.

**Comment by joshcobalt** [comment]
This answer solved my problem with Clearscript, (but I'm not using React.NET)
http://stackoverflow.com/questions/23301851/clearscript-files-cannot-be-found-on-host/33391178#33391178
