### ISSUE TITLE
Url.Action in a child component (Html.React)

### ISSUE THREAD

**Issue by oudoulj** [reactjs/React.NET#805]
Hi,
I am converting views and partial views in an ASP.NET MVC 4 project into ReactJS.NET components (SSR with Html.React())

I'm ok with the way to handle Url.Action as a prop in Html.React as long as Html.React is on a parent **cshtml** page like explained [here](https://github.com/reactjs/React.NET/blob/0e8e7c20d1e88692a49dc5d01d013cc9176afd9a/tutorial-code/Views/Home/Index.cshtml) 
But what about a Url.Action in a partial view that has been converted into a **child component** ? (if that request makes any sense)

I found [this syntax](https://stackoverflow.com/questions/49739405/passing-a-url-action-to-a-react-jsx-file) but it's not using ReactJS.NET's Html.React() helper...

**Comment by dustinsoftware** [comment]
You’ll need to pass the Url.Action as props wherever you are calling
Html.React

Something like

Html.React(“componentname”, new { someAction = Url.Action(...) })

And the consume it via the component props.

You could also use a JS template string and hard code a base URL in your
source so it updates properly.
