### ISSUE TITLE
Do you have any plan to support tsx files? 

### ISSUE THREAD

**Issue by B-Esmaili** [reactjs/React.NET#808]
Thank you guys for great effort. is there any plan to support typescript files in near future?

**Comment by dustinsoftware** [comment]
Yes support is already in the 5.0 alpha, you can try it out today by
setting SetBabelVersion in ReactConfig. See the Mvc4 sample.

**Comment by B-Esmaili** [comment]
@dustinsoftware it is good news that you support `TypeScript` but `BabelVersions`  enum only has two options (Babel6 & Babel7), between is the same configuration applied for asp.net core?

**Comment by B-Esmaili** [comment]
I couldn't get typescript working with asp.net core.Could you please update `ASP.NET CORE`  sample to support typescript?

**Comment by dustinsoftware** [comment]
Sorry, it's not officially released yet. You can look at the Mvc4 sample in this repo but that's all until the docs have been updated.

**Comment by B-Esmaili** [comment]
@dustinsoftware thanks for you response.one last question.I couldn't find neither `ts-config`  nor the `ts-loader` in `MVC4` project.how we tell babel transformer we are using typescript?

**Comment by dustinsoftware** [comment]
That is done in [BabelConfig](https://github.com/reactjs/React.NET/blob/master/src/React.Core/BabelConfig.cs#L34). Closing this issue pending future documentation updates. Please give the alpha a try and let me know how it goes.

Here is the [sample code](https://github.com/reactjs/React.NET/blob/master/src/React.Sample.Mvc4/Content/Sample.tsx) I referenced earlier. Still need to investigate making type definitions for React easier to use.
