### ISSUE TITLE
Integration with VS 2015 not working on aspnet 5 project

### ISSUE THREAD

**Issue by roblom** [reactjs/React.NET#81]
This "Install-Package React.Web.Mvc4" installs without errors but there is no transformation happening on the jsx files, and with the absence of web.config there is no httpHandler to uncomment.
(I guess there is no claim that this will work in VS 2015 preview and particularly on an aspnet 5 project.)

If possible with today's release, what is required of manual setup/code in order to get this working?

Thanks!

**Comment by PeteDuncanson** [comment]
Daniel has not had time to looking VS 2015 as yet but there are some details here https://github.com/reactjs/React.NET/issues/47 that might help you. I fear you are on your own at the minute on this path less travelled :)

**Comment by Daniel15** [comment]
I installed the VS2015 preview right before going on vacation so I haven't
had a chance to play around with it. I'll be back on 17th February.
Currently ReactJS.NET only supports released versions of ASP.NET, not the
latest preview version. A lot has changed in the preview.

**Comment by Daniel15** [comment]
Closing in favour of #47
