### ISSUE TITLE
Call bundled js from jsx component (former partial view)

### ISSUE THREAD

**Issue by oudoulj** [reactjs/React.NET#815]
I am converting a partial view (_SearchEngine.cshtml) into a SearchEngine.jsx component  for some server-side rendering.

At the bottom of my current partial view, I have:
`@Scripts.Render(ConfigManager.StaticJsContent, "~/Home/bundle-searchengine.js")`

_(this bundled js is defined in \App_Start\BundleConfig.cs)_

**Can I call this bundled js from within my new jsx component ?**
If so, how ?
Thank you.

NB : ASP.NET MVC 4 project here

**Comment by dustinsoftware** [comment]
Yes. You will need to define the functions contained in your bundled JS globally for this to work. Offhand I am not sure how that works with `BundleConfig` but that is doable with webpack.
