### ISSUE TITLE
Bundling minification not working for ES6

### ISSUE THREAD

**Issue by daniellmb** [reactjs/React.NET#82]
When running in debug mode, everything is fine but when switching to release I get this error and an incomplete JavaScript file. I'm guessing looking at the error that this is because the file hasn't been transpiled first. Am I missing something, is there a way to control the pipeline?

```
/* Minification failed. Returning unminified contents.
(10,9-10): run-time error JS1003: Expected ':': (
(10,12-13): run-time error JS1100: Expected ',': {
(12,7-8): run-time error JS1195: Expected expression: <
(12,7-8): run-time error JS1195: Expected expression: <
(14,21-22): run-time error JS1002: Syntax error: }
(17,28-29): run-time error JS1002: Syntax error: }
(20,22-23): run-time error JS1002: Syntax error: }
(27,9-10): run-time error JS1003: Expected ':': (
(27,12-13): run-time error JS1100: Expected ',': {
(29,4-5): run-time error JS1195: Expected expression: <
(29,4-5): run-time error JS1195: Expected expression: <
(29,18-19): run-time error JS1197: Too many errors. The file might not be a JavaScript file

...

```

**Comment by Daniel15** [comment]
I'm on vacation at the moment but I can take a look once I'm back on 17th
Feb. What minifier are you using? The ASP.NET minification?

**Comment by daniellmb** [comment]
Yes sorry I should have been clear this the default bundling and minification.

```
bundles.Add(new ScriptBundle("~/bundles/comments")
       .Include("~/Scripts/jquery.signalR-{version}.js")
       .IncludeDirectory("~/Scripts/Core", "*.jsx")
       .IncludeDirectory("~/Scripts/Comments", "*.jsx"));
```

**Comment by Daniel15** [comment]
You need to use JsxBundle rather than ScriptBundle. This should be in the
documentation on the website :)

**Comment by daniellmb** [comment]
*facepalm* sure is... http://reactjs.net/guides/weboptimizer.html
Once I installed that it works like a charm!

**Comment by daniellmb** [comment]
Thanks for your help, my demo app is live now :) https://github.com/daniellmb/React-PE

**Comment by Daniel15** [comment]
Nice, glad to hear you could get it working!
