### ISSUE TITLE
React.Exceptions.ReactScriptLoadException (Webpack for 3rd party libs)

### ISSUE THREAD

**Issue by oudoulj** [reactjs/React.NET#827]
I am trying to use **third-party libraries** in my ASP.NET MVC 4 project with ReactJS.NET SSR and **Webpack**.
I went through the docs (SSR, Webpack) and that useful [article](https://dev.to/dance2die/setting-up-a-react-environment-for-aspnet-mvc-44la) in order to use Webpack with ReactJS.NET's server-side rendering.
I also looked at the Github code for inspiration.

I made progress but I'm currently stuck when I launch Visual Studio (MyReactTest.cshtml) with the error :
**React.Exceptions.ReactScriptLoadException: 'Error while loading "~/Scripts/bundle.js": ReferenceError: document is not defined'**

([screenshot](https://ibb.co/R6XYzcb))
I tried with both serverOnly: true and clientOnly: true (and neither of them) but in the end, my Html.React never shows up.

First off, I'm a little confused : do I really need a **client.js** file and if so, what is supposed to be in it ?
Because it's not very clear on the [Webpack doc](https://reactjs.net/bundling/webpack.html).
client.js is mentioned (it has an entry point in webpack.config.js) but we don't see an example of its content. Is it needed even for SSR ?

Right now I have **webpack.config.js** (without a client.js because I don't know what to do with it)
```
"use strict";

var path = require("path");
var WebpackNotifierPlugin = require("webpack-notifier");
var BrowserSyncPlugin = require("browser-sync-webpack-plugin");

module.exports = {
	entry: {
		server: './Scripts/server.js',
		//client: './Content/client.js',
	},
	output: {
		path: path.resolve(__dirname, "./Scripts"),
		filename: "bundle.js"
	},
	module: {
		rules: [
			{
				test: /\.jsx$/,
				exclude: /node_modules/,
				use: {
					loader: "babel-loader"
				}
			}
		]
	},
	devtool: "inline-source-map",
	plugins: [new WebpackNotifierPlugin(), new BrowserSyncPlugin()]
};
```

**.babel.rc**
```
{ 
  "presets": ["@babel/preset-env", "@babel/preset-react"],
	"plugins": [ "@babel/plugin-proposal-class-properties" ] 
}
```

**server.js** (note that I import _react-select_ that I got out of a couple npm install commands into the node_modules folder)
Some lines are probably missing, some others useless...
```
// All JavaScript in here will be loaded server-side
// Expose components globally so ReactJS.NET can use them
import Components from './Components';
import Select from 'react-select';
//import { Header } from './Header.jsx';
import { MenuBlog } from './Components/MenuBlog.jsx';
import { MenuBuy } from './Components/MenuBuy.jsx';
import { MenuRent } from './Components/MenuRent.jsx';
import { Navigation } from './Components/Navigation.jsx';
//import { SearchEngine } from './Components/SearchEngine.jsx';
import { UrlAction } from './Components/UrlAction.jsx';
import { App } from './Components/Test.jsx';

global.Select = Select;
global.Navigation = { Navigation };
global.Test = { App };
global.Components = Components;
```

My **bundle.js** file gets successfully generated thanks to the extension NPM Task Runner suggested by the article above.

I created a very simple React component **Test.jsx**
```
import React from 'react';
import { render } from 'react-dom';

class Test extends React.Component {
	constructor(props) {
		super(props);
		this.state = { data: this.props.initialData };
	}

	render() {
		return (
			<>
				<h1>React in ASP.NET MVC!</h1>
				<div>Hello React World</div>
			</>
		);
	}
}
```

Then I try to call that component in page **MyReactTest.cshtml** like so 
```
@{
	Layout = null;
}
@using React.Web.Mvc
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>MyReactTest</title>
</head>
<body>
	This is a React test below
	<div id="app">
		@Html.React("Test", new { initialComments = "" })
	</div>
	<script src="~/Scripts/bundle.js"></script>
</body>
</html>
```
I don't know if I really need to add line
`<script src="~/Scripts/bundle.js"></script>`

Because in the middle of ReactConfig.cs, I have 
```
ReactSiteConfiguration.Configuration
				.AddScript("~/Scripts/Components/Navigation.jsx")
				.AddScript("~/Scripts/Components/MenuBlog.jsx")
				.AddScript("~/Scripts/Components/UrlAction.jsx")
				.AddScript("~/Scripts/Components/MenuBuy.jsx")
				.AddScript("~/Scripts/Components/MenuRent.jsx")
				.AddScript("~/Scripts/bundle.js");
```
with a similar include (_AddScript("~/Scripts/bundle.js")_) #confused

Anyway this is where I am at and where I get the error mentioned at the beginning.
I'm trying to stitch all these files together and I could use some help, thank you all :)

**Comment by oudoulj** [comment]
OK, I made progress #babysteps 
In ReactConfig.cs , I commented out 
`//.AddScript("~/Scripts/bundle.js")`
and added
`.AddScript("~/Scripts/Components/Test.jsx")`

My page now shows the Test.jsx component ! 👍 
[Simple React component showing in cshtml](https://i.ibb.co/qjZYThX/success.png)

So my next step was to use a third-party library such as _react-select_ in my component.
In **Test.jsx** , I added a _Select_ block and _colourOptions_ array to populate 
```
const colourOptions = [
	{ value: "ocean", label: "Ocean", color: "#00B8D9", isFixed: true },
	{ value: "blue", label: "Blue", color: "#0052CC", isDisabled: true },
	{ value: "purple", label: "Purple", color: "#5243AA" },
	{ value: "red", label: "Red", color: "#FF5630", isFixed: true },
	{ value: "orange", label: "Orange", color: "#FF8B00" },
];

class Test extends React.Component {
	constructor(props) {
		super(props);
		this.state = { data: this.props.initialData };
	}

	render() {
		return (
			<>
				<h1>That line is inside the React test component (Test.jsx)</h1>
				<Select
					defaultValue={colourOptions[0]}
					name="color"
					options={colourOptions}
				/>
			</>
		);
	}
}
```
Error at launch in the Html.React of the cshtml view
`React.Exceptions.ReactServerRenderingException: 'Error while rendering "Test" to "react_0HLNB58UG75RU": ReferenceError: Select is not defined`

Even though there was already (in **server.js**)...
```
import Select from 'react-select';
...
global.Select = Select;
```
... I tried adding (in **Test.jsx**)
`import Select from "react-select";`

At save, NPM Test Runner/Webpack did not like that and I got a toast with message 
```
Error: ./Scripts/server.js
HarmonyLinkingError: "export 'App' was not found in './Components/Test.jsx'
```

So, which _import Select_ do I need ?
The one in server.js or in the jsx ?
How do I use that global variable in server.js ?
Thanks ! 🙏

**Comment by dustinsoftware** [comment]
When using webpack, apps should prefer to use ES module import syntax.

You'll want to use `AddScriptWithoutTransform`. Take a look at the [webpack](https://github.com/reactjs/React.NET/blob/df8585889dfa306f8d5310843d203afdf642fbe9/src/React.Sample.Webpack.CoreMvc/Startup.cs#L50) sample for more information on how to do this.

[Here's an example of styled-components being imported](https://github.com/reactjs/React.NET/blob/master/src/React.Sample.Webpack.CoreMvc/Content/components/styled-components.jsx#L2).

The original error you were getting, `document is not defined` is typically caused by importing third party libraries that do not work with server-side rendering. Sometimes you can work around this by only invoking the third-party code on the client-side, via `useEffect` or `componentDidMount` hooks. You may also be able to use webpack's code splitting so that the third party module is not present in the main bundle, and lazily load the module during the client-side component mount. The [react docs](https://reactjs.org/docs/code-splitting.html#code-splitting) have some more information about how this works.

**Comment by dustinsoftware** [comment]
Indeed, `react-select` does not work with server-side rendering, so I updated the webpack sample to demonstrate how it can be imported. [Source here](https://github.com/reactjs/React.NET/commit/eb011bce395e10cce107706d1a5a34a1347dcdb9)

Cheers 🍻

![image](https://user-images.githubusercontent.com/942358/59163752-19608800-8ad3-11e9-8765-1571b9c6ddae.png)

**Comment by oudoulj** [comment]
@dustinsoftware thank you for investigating and coming with a workaround, I'll try it as soon as tomorrow at work.
_styled-components_ will come in handy pretty soon too 😃 
Excuse my naive question but **how come you hadn't suggested this lazy loading technique earlier to people trying to use third party libraries like myself?** 
I cannot be the first one to try do that, right ? 😕 
For instance @LeonidasFettikus tried something similar with **Office UI Fabric React** on #789  if I'm not mistaken.

**Comment by dustinsoftware** [comment]
The workaround only works with webpack, and it totally bypasses server
rendering for that component. Arguably it is a bug or limitation in the
library being used.. but in many cases library authors aren’t aware that
server rendering does not work in this case. Typically checking ‘typeof
document !== “undefined”’ is good enough to fix this problem in the library
itself around the problematic code.

It would be nice to see if a Node-based server render solution (next,
Gatsby, etc) suffers the same problem with react-select. If it works there,
then we may be able to leverage whatever code or polyfill that is letting
the library work under that environment. Maybe there is a special SSR
bundle used in those cases....

**Comment by oudoulj** [comment]
Ok, here is my update.
I updated my .babel.rc, package.json and webpack.config.json to match yours as much as possible.
=> I am still unable to _import_ anything within my **jsx** test page like you do in [lazy-load.jsx](https://github.com/reactjs/React.NET/blob/eb011bce395e10cce107706d1a5a34a1347dcdb9/src/React.Sample.Webpack.CoreMvc/Content/components/lazy-load.jsx) with

```
import React, { Fragment, useState, useEffect } from 'react';
import { Helmet } from 'react-helmet';
```

As soon as I add the following line to **Test.jsx** :
`import React from 'react';`
then save, I get error :
![Webpack error with import](https://i.ibb.co/bmBT5xR/function-error.png)

The full **Test.jsx** file is like so :
```
import React from 'react';

function Test() {
	return (
		<h1>That line is inside the React test component (Test.jsx)</h1>
	);
}
```
The cshtml view displays that error :
![Error on view](https://i.ibb.co/mz9WdPY/errorviewpage.png)

Whenever I update/save Test.jsx, my /Scripts/dist/**components.js** is rebundled, which is fine :
![Webpack error with import](https://i.ibb.co/j3dwk4w/distcommponentssuccess.png)

It's pretty big and contains my Test.jsx component as expected.
And yes, I have it in my cshtml view :
`<script src="~/Scripts/dist/components.js"></script>`

**So I'm missing something that's preventing me from _import_ anything in my jsx like you do** 😢

**Comment by dustinsoftware** [comment]
When using webpack, components must be exported using `export` syntax. [Here's the lazy-load.jsx component](https://github.com/reactjs/React.NET/blob/5007121b4b3b3239264f2e6e48e23e0fb4f84496/src/React.Sample.Webpack.CoreMvc/Content/components/lazy-load.jsx#L4) as an example.

**Comment by oudoulj** [comment]
Thank you for pointing this out : I've added the _export_ keyword to [my component](https://github.com/oudoulj/ReactJSNETMVC/blob/b72a5480871632f5efd5351bcbda5d8db62eb660/ReactJSNETMVC/ReactJSNETMVC/Components/Test.jsx#L1)

(was not sufficient to make the page display but we're getting there little by little!)

**Comment by oudoulj** [comment]
I was able to show a react-select list eventually!
Some of the key parts are :
+ the dynamic import plugin line in .babelrc (you need to npm install it as well)
```
{ 
  "presets": ["@babel/preset-env", "@babel/preset-react"],
	"plugins": [
		"babel-plugin-styled-components",
		"@babel/plugin-syntax-dynamic-import"
	] 
}
```

+ to have the correct **publicPath** in webpack.config.js to have a certain 0.js output at the right path
```
output: {
		filename: '[name].js',
		globalObject: 'this',
		path: path.resolve(__dirname, 'Scripts/dist'),
		publicPath: 'Scripts/dist/' //allow loading of http://localhost/MyWebApp/Scripts/dist/0.js
	},
```
Click "Show all files" in Visual Studio to see where your 0.js file is located and modify that publicPath accordingly.
