### ISSUE TITLE
Experiment with debugging in V8

### ISSUE THREAD

**Issue by Daniel15** [reactjs/React.NET#83]
JavaScriptEngineSwitcher added support for V8 config in https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/8, including the ability to use the debugger. Experiment with what it would take to use this for debugging server-side rendering.

Reference: https://pandeysk.wordpress.com/2014/05/25/debugging-with-clearscript/

**Comment by Lenne231** [comment]
Is it possible to debug the JS code executed with V8 with VS?

**Comment by Daniel15** [comment]
Not at the moment. I'm not quite sure how to implement that :)

**Comment by dustinsoftware** [comment]
Better debugging support would be great. Since nobody's actively working on it though, I'm closing this old issue and tracking future work in #655
