### ISSUE TITLE
ClearScriptV8 engine - clean stop?

### ISSUE THREAD

**Issue by thurfir** [reactjs/React.NET#841]
Hello,

From time to time, our deployment process fails when using ReactJS.NET with the ClearScriptV8 engine. The issue is the following:

ERROR_FILE_IN_USE - Web Deploy cannot modify the file 'ClearScriptV8-64.dll' on the destination because it is locked by an external process. In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt. 

The application is already stopped using an App_Offline.htm file. This is not a stopping time issue either, I had the issue 30 minutes after stopping the website using App_Offline.htm.

Is there a way to properly release the JS engines at application stop?
Thank you.

**Comment by dustinsoftware** [comment]
Does stopping the application pool via IIS not work? Using App_Offline
won’t shut down the app pool as far as I know.

**Comment by thurfir** [comment]
Hello @dustinsoftware, yes stopping/recycling the application pool works but it's not a clean stop, it basically means we force-kill the process. We should be able to safely release the engines in the global.asax or equivalent.

**Comment by dustinsoftware** [comment]
Yeah, right now we don't handle more graceful shutdown scenarios. The best way to go about deploying an app that uses this library is to stop the app pool first. You might be able to hook into `ReactEnvironment` and dispose all of the pooled engines manually but I haven't tested that. I'm not sure what a more graceful shutdown mechanism would look like - that's probably something that's out of scope for this library...

**Comment by thurfir** [comment]
From what I got from the code, the pooled engines are not reachable from ReactEnvironment: they are managed by the JavaScriptEngineFactory class, which is not publicly accessible.

The JavaScriptEngineFactory class seems to be configured to release its pool (Dispose pattern), but, being a singleton, it probably never does.

**Comment by sampalmerbb** [comment]
Hi @dustinsoftware, I'm just wondering whether this issue is still out-of-scope in this library?

**Comment by dustinsoftware** [comment]
If there is an event we can hook into during app shutdown then we can
probably use that.

I don’t have time to look at this in the near future unfortunately, happy
to accept a PR if someone figures out how.

**Comment by sampalmerbb** [comment]
FYI for anyone else getting this issue, we fixed it by switching `JavaScriptEngineSwitcher` to use Chakra instead of ClearScript or V8.
