### ISSUE TITLE
onChange event not firing with server-side rendering

### ISSUE THREAD

**Issue by oudoulj** [reactjs/React.NET#847]
This is a follow-up to the [closed issue 209](https://github.com/reactjs/React.NET/issues/209) 

I have an ASP.NET MVC 5 project with ReactJS.NET 5 and SSR and Webpack.
In my cshtml page, I call a jsx component 
`@Html.React("ContentHome", new { }, serverOnly: true)`

The jsx contains (it's close to the official example from the React website)
```
export default class ContentHome extends React.Component {
	constructor(props) {
		super(props);
		this.state = { label: 'first value' };

		this.handleChange = this.handleChange.bind(this);
	}

	handleChange(event) {
		this.setState({ label: event.target.value });
		console.log(event.target.value);
	}

	render() {
		return (
			<div>
				<div>{this.state.label}</div>
				<input type="text" value={this.state.label} onChange={this.handleChange} />
			</div>
		);
	}
}
```
Absolutely nothing happens when I type in the input field, no error, no console.log, no nothing, nada... 😢 
I read on issue 209 that this is the expected behavior when doing SSR.
I'm not using Remarkable and I'm ready to provide any other file content that might help.
My question is : **how do I enable this onChange event on the client side ?**
Thank you

**Comment by dustinsoftware** [comment]
Are you calling HTML.ReactInitializeJavascript In your view after the component HTML.React call?

**Comment by oudoulj** [comment]
> Are you calling HTML.ReactInitializeJavascript In your view after the component HTML.React call?

If you meant `@Html.ReactInitJavaScript()`, yes I do, at the very end of my page.
But I was actually missing the calls to the scripts **client-side** :
```
@Scripts.Render("~/Scripts/dist/runtime.js")
@Scripts.Render("~/Scripts/dist/vendor.js")
@Scripts.Render("~/Scripts/dist/components.js")
```

Pretty much the same way I was doing server-side in ReactConfig.cs :
```
.AddScriptWithoutTransform("~/Scripts/dist/runtime.js")
.AddScriptWithoutTransform("~/Scripts/dist/vendor.js")
.AddScriptWithoutTransform("~/Scripts/dist/components.js")
```

I also removed the **serverOnly: true** at the end of my `@Html.React` call.
I had added this parameter there because it was making a ReactDOM error go away from the console at load up but it was doing more harm than good after all.

The main view ends up like so :

```
@using React.Web.Mvc
@using React.RenderFunctions

Index page

@Html.React("ContentHome", new { })

@Scripts.Render("~/Scripts/dist/runtime.js")
@Scripts.Render("~/Scripts/dist/vendor.js")
@Scripts.Render("~/Scripts/dist/components.js")

@Html.ReactInitJavaScript()
```
The onChange event in the ContentHome component now works 😄
