### ISSUE TITLE
Get the console shim to actually do something useful

### ISSUE THREAD

**Issue by PeteDuncanson** [reactjs/React.NET#86]
We've found on a few occasions points where a little console statement would have made debugging so much easier.

Currently for server-side rendering a shim is included for console. I'm pondering two possible solutions that could be handy here. One is to allow the console statement to write to log4net or similar the other is to have the console statement append to an array and then if in debug mod (flagged somehow TBC) it spits the results out in page in a div at the end or as a client-side call to console.log( myinternallogger ); which would allow us to see the output in the browsers dev tools.

Thoughts?

**Comment by jslatts** [comment]
Serious +1 on this! I have a somewhat decent workflow going, but every once in awhile, I run into an issue where the server-side rendering blows up and I am forced to pour over my code to try and figure out what is wrong. I was actually going to post an issue here to ask if I was doing it wrong.

I would be ok with either method, but I think having it spit the log messages out into a div would be easiest for most people to utilize.

**Comment by Daniel15** [comment]
The issue with calling back into .NET code is that there's no cross-engine way of doing it. ClearScript and VroomJs have different ways of doing it, but I don't think the MSIE engine supports it. I wonder if it could be added to JavaScriptEngineSwitcher. Alternatively I could just move to only supporting V8.

I love the idea of converting them to client-side console calls though! That should definitely be doable. The shim could cache all the calls and then just render them out when scripts are rendered. I'll work on this for the next release.

**Comment by Daniel15** [comment]
Implemented a basic version in eff1c2b134ac47771c6991d180cb7908ffffd6d1. This will catch all the console calls made server-side and output them as part of the JS init code (`@Html.ReactInitJavaScript()` in ASP.NET MVC). I can add a separate method that gets just the log calls if there's a valid use case for that :)
