### ISSUE TITLE
5.0.0 release prep

### ISSUE THREAD

**Issue by dustinsoftware** [reactjs/React.NET#860]
Git diff here: https://github.com/reactjs/React.NET/compare/release-4.1.1...7ed661e4fb4def2d35e3510d1be643ac0aa7006c

Notable changes:
- Typescript support via Babel 7
- JSON.NET 12 dependency
- Source link & symbols published to NuGet
- .NET Core 3 support (preview)
- Performance improvements (19d18b134c2e707ce79d8c82316c0ab052ef0c16)
- Output caching support (#858)

**Comment by Daniel15** [comment]
Nice!
