### ISSUE TITLE
.NET core 2.2 with React.Aspnet v4.1.1

### ISSUE THREAD

**Issue by binjan77** [reactjs/React.NET#863]
Hello,

I am using React.Aspnet v3.4.1 for my ASP.NET Core app with .NET core 2.2 version. I am using server-side rendering using @Html.ReactInitJavaScript() in a MVC view.
When I update my reference React.Aspnet v4.1.1, my page does not display any error but it does not show any content.

Can anyone help me?
Thanks in advance.

**Comment by binjan77** [comment]
thanks, I got my answer from the tutorial code of the project.

**Comment by Daniel15** [comment]
Glad that you were able to work it out :)
