### ISSUE TITLE
Cannot access a disposed object

### ISSUE THREAD

**Issue by spicydonuts** [reactjs/React.NET#88]
Hello!  I'm using browserify to build my client and server bundles.  When I change a file it triggers a build.  If I refresh the page instantly I get an error about the js file bein locked, which makes sense and is probably unavoidable (unless it can catch that and keep retrying).  Then there is a period of a few seconds after that where I will get the error below.  If I wait longer or refresh again all is well.  Not sure if this is an issue for anyone using React.NET to transpile their scripts or if it's unique to external file changes (including webpack).  It would be nice if this error could be caught and a new js engine created using the new file.

It's interesting that refreshing sooner shows the file locked error while refreshing later shows the vm disposed error.  Maybe the old pool should only be disposed when the new one is ready.

```
[ObjectDisposedException: Cannot access a disposed object.
Object name: 'JavaScriptEngineSwitcher.V8.V8JsEngine'.]
   JavaScriptEngineSwitcher.Core.JsEngineBase.VerifyNotDisposed() +73
   JavaScriptEngineSwitcher.Core.JsEngineBase.Execute(String code) +20
   React.ReactEnvironment.Execute(String code) +62
   React.ReactEnvironment.EnsureUserScriptsLoaded() +288
   React.ReactEnvironment.CreateComponent(String componentName, T props, String containerId) +42
   React.Web.Mvc.HtmlHelperExtensions.React(HtmlHelper htmlHelper, String componentName, T props, String htmlTag, String containerId) +136
   ASP._Page_Views_Shared__LayoutMobileFirstNoScript_cshtml.Execute() in c:\jane\jane-legacy\VeryJane.Applications.Commerce\Views\Shared\_LayoutMobileFirstNoScript.cshtml:37
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +251
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +154
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +124
   System.Web.WebPages.<>c__DisplayClass3.<RenderPageCore>b__2(TextWriter writer) +314
   System.Web.WebPages.WebPageBase.Write(HelperResult result) +114
   System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body) +89
   System.Web.WebPages.WebPageBase.PopContext() +322
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +375
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +90
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +837
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +81
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +186
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +45
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +75
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +58
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +45
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +44
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +75
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +45
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +180
```

**Comment by Daniel15** [comment]
Sounds like it could be an issue with JSPool not having sufficient locking when it recycles engines (it recycles all the JS engines whenever any of the loaded files change). I'll take a look this weekend.

**Comment by spicydonuts** [comment]
I wandered through the source a bit and found the same thing.  This probably wouldn't be an issue in production environments where the file isn't changing, would it?  Any other reasons it would get disposed?

**Comment by PeteDuncanson** [comment]
I've been getting this one on and off but could not find the cause, would be nice for it to not throw this error on live. Doing a deploy for instance would potentially give this error to live customers which I'd rather avoid (plus of course preventing a client from seeing this for confidence reasons).

**Comment by Daniel15** [comment]
@spicydonuts  - Can you please try upgrading JSPool to 0.2 and see if you encounter the same issue? I fixed an issue there that might be related.

@PeteDuncanson - For a live deployment I'd probably deploy to a separate directory, do smoke testing on it, and only flip over when the push is complete and verified working. This is normally called [blue-green deployment](http://martinfowler.com/bliki/BlueGreenDeployment.html). If you do deployment directly to a live site, you'll occasionally encounter issues either with file locking or with mismatched assemblies while the deployment is taking place (ie if you upgrade some dependencies and they're in the process of being pushed), and it's more difficult to roll back in case of issues.

**Comment by Daniel15** [comment]
JSPool 0.2 should have resolved this, but please reopen if you're still experiencing this issue. Thanks!
