### ISSUE TITLE
Can't Open Tutorial In Any Version of Visual Studio

### ISSUE THREAD

**Issue by MelbourneDeveloper** [reactjs/React.NET#883]
I can't open the ReactDemo.sln solution in Visual Studio 2017, 2019, or 2019 Preview.

Microsoft Visual Studio Professional 2017 
Version 15.9.14
![image](https://user-images.githubusercontent.com/16697547/62409694-877e8280-b61e-11e9-87dc-d0f72cad6ae0.png)

Microsoft Visual Studio Professional 2019
Version 16.1.6
![image](https://user-images.githubusercontent.com/16697547/62409698-a7ae4180-b61e-11e9-9f49-09901b9a0bf7.png)

Microsoft Visual Studio Professional 2019 Preview
Version 16.3.0 Preview 1.0
![image](https://user-images.githubusercontent.com/16697547/62409711-ca405a80-b61e-11e9-9539-793819d7eb82.png)

.NET Core SDKS:
![image](https://user-images.githubusercontent.com/16697547/62409722-f65bdb80-b61e-11e9-94e5-65ad42b65b91.png)

### Runtime environment:
- OS: Windows 10
- .NET Framework or .NET Core Version: 3

### Steps to reproduce

Open the solution

(Describe your issue here)

**Comment by dustinsoftware** [comment]
Thanks for filing an issue. I don't have time to look into this right now, will try and look sometime soon.

**Comment by christopherromero** [comment]
Has there been any update to this? I am experiencing the same issue.

**Comment by dustinsoftware** [comment]
On OSS vacation right now, will look as soon as I am able

**Comment by dustinsoftware** [comment]
Alright, so I think this is caused by the .NET Core 3 preview wanting a very specific version of the preview installed to work. I just bumped the repo to 3.0 rc1, please install that version of the sdk and build, and let me know if it's still problematic..
