### ISSUE TITLE
React.NET just doesn't want to install

### ISSUE THREAD

**Issue by FrostBytesf** [reactjs/React.NET#885]
I feel like this is a problem with just my solution, but, I'm trying to access the React.NET library for the Babel transformations. There is one *teensy, weensy* problem with it when trying to install `React.AspNetCore`.

![NIce.](https://user-images.githubusercontent.com/13282174/62508634-5c3e9380-b7d6-11e9-8d0f-4cd092b51942.png)

React.NET has been tested with .NET Core 2.1, which is what I'm using for comparability reasons. This is just me trying to install on a fresh ASP.NET application. It might have something to do with my Linux distro, but I doubt it.

In the project I originally installed in, I'm using my own middleware instead of static file services provided by ASP.NET so I have more control, so a better question would be if I can use *just* the Babel transformations, as to an extent, that's all I really need. I don't know why I need to configure React.NET to transform my jsx files. Then again, I don't know much about React.NET.

**Comment by FrostBytesf** [comment]
Other people have this problem. [See this issue](https://github.com/reactjs/React.NET/issues/864), [and this pull request](https://github.com/reactjs/React.NET/pull/875).

Maybe I should think before posting an issue. This was late at night, and I was frustrated, so I do apologize.

**Comment by dustinsoftware** [comment]
Thanks for filing an issue. I don't have time to look into this right now, will try and push that PR forward again sometime soon.
