### ISSUE TITLE
Duplicate rerendering when using ReactWithInit

### ISSUE THREAD

**Issue by ntucakovic** [reactjs/React.NET#890]
I think that the `Environment.CreateComponent` does a side effect of adding a component to `_components` list, and is overlooked when using `ReactWithInit`.

https://github.com/reactjs/React.NET/blob/7ed661e4fb4def2d35e3510d1be643ac0aa7006c/src/React.AspNet/HtmlHelperExtensions.cs#L127

At least we should be able to remove the rendered component from list of `_components` once it's successfully added to the markup.

I realized this was going on because I couldn't use get `ReactWithInit` to work without throwing me the `ReactDOM` is undefined error in console. Realized that it's working because it sort of fallbacks to default behavior and just adds the component to the render/hydrate list at the bottom of the page, after all react dependencies are loaded.

I'm using `v4.1.0` on the project but I think this is applicable to `v5.0` as well.

**Comment by dustinsoftware** [comment]
You're right, calling `ReactWithInit` shouldn't add to the list of `_components`. Thanks for the report.
