### ISSUE TITLE
will this work with existing app written in mvc 5?

### ISSUE THREAD

**Issue by aloksharma1** [reactjs/React.NET#893]
Hello,

sorry for the noob question, but i think i will ask it here rather then going to SO, so we have a big app built with backend and frontend working ok in MVC5 now we want to offload some parts of it to react and slowly shift as we go with the experience.
my question is if i use react will my server side routing stop or will we be able to use this side by side? as both angular and react uses client side routing and its not possible to us for offload everything to client neither it is needed, especially the admin part will always stay server side.

hope you are clear on my question.

thanks

**Comment by dustinsoftware** [comment]
Yeah, you can still keep your routes with ASP.NET's server side routing. Should work fine. 😄

**Comment by aloksharma1** [comment]
thanks, i will try and let you know results
