### ISSUE TITLE
DisableServerSideRendering() in config still tries to render scripts server side

### ISSUE THREAD

**Issue by owlyowl** [reactjs/React.NET#900]
### Please verify these steps before filing an issue, and check them off as you go
- [x] The relevant native JavascriptEngineSwitcher library packages are installed (such as `JavaScriptEngineSwitcher.V8.Native.win-x64`)
- [x] The VC++ 2017 runtime is installed
- [x] The value of `SetUseReact` and `SetUseBabel` is correct in `ReactConfig.cs` or `Startup.cs`
- [x] I've looked at the sample projects in this repo to verify that my app is configured correctly

### I'm using these library versions:
- `ReactJS.NET`: 5
- `JavaScriptEngineSwitcher`: v8
- `react` and `react-dom`: (N/A if using bundled react, or version number)
- `webpack`: (N/A if using bundled react)
- `node`: (N/A if using bundled react)

### Runtime environment:
- OS: (Mac, Windows, Linux flavor. Include 32-bit/64-bit and version)
- .NET Framework or .NET Core Version:

### Steps to reproduce
In my ReactConfig I have code like so:
`public static class ReactConfig
	{
		public static void Configure()
		{
			JsEngineSwitcher.Current.DefaultEngineName = V8JsEngine.EngineName;
			JsEngineSwitcher.Current.EngineFactories.AddV8();
			ReactSiteConfiguration.Configuration
				.SetLoadReact(false)
                .DisableServerSideRendering()
				.AddScriptWithoutTransform("~/dist/vendors~spa.js")
				.AddScriptWithoutTransform("~/dist/spa.js");
		}
	}`

I find that it is still throwing the exception below trying to render /dist/spa.js server side after app clean, rebuild and restart.

Is it a matter for adding those scripts in to the body manually?
``
-------

[ScriptEngineException: ReferenceError: window is not defined]
   V8Exception.ThrowScriptEngineException(V8Exception* ) +236
   Microsoft.ClearScript.V8.V8ContextProxyImpl.Execute(UniqueDocumentInfo documentInfo, String gcCode, Boolean evaluate) +887
   Microsoft.ClearScript.V8.V8ScriptEngine.ExecuteInternal(UniqueDocumentInfo documentInfo, String code, Boolean evaluate) +299
   Microsoft.ClearScript.V8.<>c__DisplayClass100_0.<Execute>b__0() +373
   Microsoft.ClearScript.ScriptEngine.ScriptInvokeInternal(Func`1 func) +82
   Microsoft.ClearScript.V8.<>c__DisplayClass106_1`1.<ScriptInvoke>b__0() +77
   Microsoft.ClearScript.V8.V8ContextProxyImpl.InvokeWithLock(Action gcAction) +163
   Microsoft.ClearScript.V8.V8ScriptEngine.ScriptInvoke(Func`1 func) +249
   JavaScriptEngineSwitcher.V8.V8JsEngine.InnerExecute(String code, String documentName) +207

[JsRuntimeException: ReferenceError: window is not defined]
   JavaScriptEngineSwitcher.V8.V8JsEngine.InnerExecute(String code, String documentName) +258
   React.JavaScriptEngineFactory.LoadUserScripts(IJsEngine engine) in d:\a\1\s\src\React.Core\JavaScriptEngineFactory.cs:185

**Comment by dustinsoftware** [comment]
Unfortunately, you will probably need to pull in any scripts that have a hard coded reference to the `window` variable separately instead of bundling them in your script bundle. This is a known limitation of this library.

A few other suggestions if that doesn't work: you might be able to use lazy-loading with webpack's dynamic import or possibly shim the `window` global via webpack...

**Comment by owlyowl** [comment]
Thanks Dustin,
Yes I've managed to work around it but thanks for clarifying as well :)

**Comment by StefH** [comment]
@owlyowl 
Can you provide your solution here?
