### ISSUE TITLE
Reactjs.net application is not running in asp.net core 3.0.100-preview8-013656 

### ISSUE THREAD

**Issue by MohamedSahir** [reactjs/React.NET#901]
I have downloaded a guided project from the Reactjs.net and followed the recommended steps and install the dependencies and while build the application , get a below error.

project Url :
https://github.com/reactjs/React.NET/tree/master/tutorial-code

Dotnet Sdk Version :

<img width="260" alt="dotnet sdk" src="https://user-images.githubusercontent.com/20682302/63931796-9583bf80-ca73-11e9-98d3-e76de7f09cfb.PNG">

Compiler Error on build
<img width="921" alt="compiler error" src="https://user-images.githubusercontent.com/20682302/63931813-9caacd80-ca73-11e9-8b07-94418f1a3bdd.PNG">

Is .net core 3 support reactjs.net , if it support kindly guide me.

if i install .net core sdk 2 jsx file html not render in webpage

**Comment by hez2010** [comment]
I've tested and found reactjs.net do can run in .NET Core 3.0.
However, there's a depencendy System.IO.FileSystem.Primitives in Reactjs.NET need to be updated to 4.3.0, otherwise it prevents your app from publishing to specific architecture and system.

**Comment by MohamedSahir** [comment]
The mentioned documentation project works successfully on 3.0.100-preview6-012264 . [But](url) it throws a compiler error on  3.0.100-preview8-013656  this version and 
<img width="952" alt="snipping tool" src="https://user-images.githubusercontent.com/20682302/64525765-32b9e000-d31f-11e9-8f02-f601c757344b.PNG">
 kindly run it in this version .
