### ISSUE TITLE
Compile using babel in a C#/.NET project

### ISSUE THREAD

**Issue by HCorte** [reactjs/React.NET#917]
Thanks for filing a bug! To save time, if you're having trouble using the library, please check off the items you have tried. If you are just asking a question, skip right to the bottom.

### Please verify these steps before filing an issue, and check them off as you go
- [x] The relevant native JavascriptEngineSwitcher library packages are installed (such as `JavaScriptEngineSwitcher.V8.Native.win-x64`)
- [ ] The VC++ 2017 runtime is installed
- [ ] The value of `SetUseReact` and `SetUseBabel` is correct in `ReactConfig.cs` or `Startup.cs`
- [ ] I've looked at the sample projects in this repo to verify that my app is configured correctly

### I'm using these library versions:
- `ReactJS.NET`:
- `JavaScriptEngineSwitcher`:
- `react` and `react-dom`: (N/A if using bundled react, or version number)
- `webpack`: (N/A if using bundled react)
- `node`: (N/A if using bundled react)

### Runtime environment:
- OS: Windows Include 32-bit
- .NET Framework or .NET Core Version: 5.1.0

### Steps to reproduce

-------

(Describe your issue here)

As in the post that made in [StackOverflow](https://stackoverflow.com/questions/58065991/compile-using-babel-in-a-c-net-project) trying to use babel to compile some code as in the example provided, installed the package React.Core v5.1.0 but keep getting the error of Unhandled Exception: React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.IReactEnvironment.

Is there some extra step that I am missing?

**Comment by dustinsoftware** [comment]
It’s hard to say without seeing your app.. you could look at the .NET Core sample in this repo to see how it is initialized.
