### ISSUE TITLE
Could you upgrade ReactJs to v0.13?

### ISSUE THREAD

**Issue by glikoz** [reactjs/React.NET#93]
http://www.productiverage.com/typescript-es6-classes-for-react-components-without-the-hacks

I want to use this approach, with or without TypeScript is big difference for me?

**Comment by Daniel15** [comment]
Sorry, not going to include an RC version of React. I'll update React once
the final release of 0.13 is out, which should be pretty soon. :)

**Comment by glikoz** [comment]
0.13 is out :)

**Comment by Daniel15** [comment]
:+1: I'll upgrade React in the next release.
