### ISSUE TITLE
SSR React Router StaticRouter receives url without query parameters from props.location

### ISSUE THREAD

**Issue by mattywong** [reactjs/React.NET#933]
Thanks for filing a bug! To save time, if you're having trouble using the library, please check off the items you have tried. If you are just asking a question, skip right to the bottom.

### Please verify these steps before filing an issue, and check them off as you go
- [x] The relevant native JavascriptEngineSwitcher library packages are installed (such as `JavaScriptEngineSwitcher.V8.Native.win-x64`)
- [x] The VC++ 2017 runtime is installed
- [x] The value of `SetUseReact` and `SetUseBabel` is correct in `ReactConfig.cs` or `Startup.cs`
- [x] I've looked at the sample projects in this repo to verify that my app is configured correctly

### I'm using these library versions:
- `ReactJS.NET`:
- `JavaScriptEngineSwitcher`:
- `react` and `react-dom`: (N/A if using bundled react, or version number)
- `webpack`: (N/A if using bundled react)
- `node`: (N/A if using bundled react)

### Runtime environment:
- OS: (Mac, Windows, Linux flavor. Include 32-bit/64-bit and version)
- .NET Framework or .NET Core Version:

### Steps to reproduce

-------

Not sure exactly the expected behavior, however currently props.location does not get the query parameters from the current HttpContext. This means that if a react component further down in the tree is referencing something from location.search, it only gets rendered on the client and a React mismatch error gets logged to the console.

Currently the workaround we're using is to manually pass through the query string as a prop, and check for it before passing it to the StaticRouter... e.g

cshtml
```
var Props = new
  {
    queryString = Context.Request.QueryString.HasValue ? Context.Request.QueryString.Value : ""
  };

@Html.ReactRouter("Component", Props)
```

js
```
var { queryString, location } = props;
<StaticRouter location={queryString ? location + queryString : location}>
    <Component {...props} />
</StaticRouter>
```

So i guess I was just wondering whether or not the current behavior is the intended behavior? Or  is the query string being passed as well and something is wrong with our routes setup?

Additional context, looking through the node docs and ReactRouter docs, nodes req.url has the query string (https://nodejs.org/api/http.html#http_message_url) and in ReactRouter's StaticRouter api docs it seems to take nodes req.url straight (https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/StaticRouter.md).

**Comment by mattywong** [comment]
Looking through source code and doing some tests on our end, seems to be from this line here:

https://github.com/reactjs/React.NET/blob/master/src/React.Router/HtmlHelperExtensions.cs#L104

So looks like we can set the path argument instead of passing the query string as a prop:
```
 var Path = Context.Request.QueryString.HasValue ? $"{Context.Request.Path.ToString()}{Context.Request.QueryString.Value.ToString()}" : Context.Request.Path.ToString();

@Html.ReactRouter("Component", props, path: Path)
```

Is there any reason why by default it doesn't attach the query string to the path?

**Comment by dustinsoftware** [comment]
Probably an oversight; feel free to PR if I don’t pick this up in the next week or so

**Comment by mattywong** [comment]
Sure, will try to create one this week when I get a chance. Thanks for confirming.
