### ISSUE TITLE
Multiple Apps? - Documentation

### ISSUE THREAD

**Issue by owlyowl** [reactjs/React.NET#943]
Hi I was wondering if it is possible to have multiple apps? I've set up the following in ReactConfig;

![image](https://user-images.githubusercontent.com/1916426/66538324-9aa65500-eb6f-11e9-94f7-212d5f795059.png)

It doesn't seem to want to initialise react correctly on my second app I have:
![image](https://user-images.githubusercontent.com/1916426/66538398-efe26680-eb6f-11e9-8c9a-cb270f65059e.png)

And am getting:
Please expose your version of React as global variables named 'React', 'ReactDOM', and 'ReactDOMServer', or enable the 'LoadReact'configuration option to use the built-in version of React.

**Comment by dustinsoftware** [comment]
Use webpack to create a shared vendor bundle, and then add your individual
app bundles after that. I think the webpack sample demonstrates creating a
vendor bundle already.

**Comment by dustinsoftware** [comment]
Closing since this question has been answered, feel free to comment if you’re still stuck. Cheers 🍻
