### ISSUE TITLE
Stop bundling MSIE JS engine by default

### ISSUE THREAD

**Issue by Daniel15** [reactjs/React.NET#96]
- Pull MSIE support out into separate package
 - Require user to select the engine they'd like to use (still allow MSIE as an option)

**Comment by Daniel15** [comment]
Done in fe639046c94aa94a967e5b856bd688a6cf746d57. I've still kept MSIE but have also bundled V8 by default.

**Comment by Surreal9** [comment]
How do you make that selection, and choose V8?
