### ISSUE TITLE
ASP.NET Web Forms (VB.NET) config

### ISSUE THREAD

**Issue by pmonty** [reactjs/React.NET#963]
Wondering if it is a possibility to get this done. We have an existing ASP.NET Web forms app we would love to convert to ReactJS and really want to use this package.

Just a test I installed the nuget React.Web.MVC4 package and it added a reactconfig.cs to `App_Start`. Is there a way to generate vb files or do i need to convert them manually? Fine to do the entire thing manually. But thought I would ask here if this is even possible before I went and started adding stuff for no reason maybe?

**Comment by dustinsoftware** [comment]
It should be possible, yeah. You may need to write your own HTML helpers to
pull off server rendering though, since the ones included won’t work with
web forms.

**Comment by Daniel15** [comment]
It's not tightly-coupled to MVC so it should work with WebForms too. You might find this issue useful: #55

I don't have any VB examples, but anything doable in C# should be doable in VB too 😄

**Comment by pmonty** [comment]
Thanks for the quick reply guys!

After some messing about I have a `ReactConfig.vb`
```vb
Imports React

Namespace ReactTest
    Module ReactConfig
        Sub Configure()
            ReactSiteConfiguration.Configuration.AddScript("~/Content/index.jsx")
        End Sub
    End Module
End Namespace
```
`test.aspx`
```html
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div>
        hello this is div test
    </div>
  <asp:Literal ID="PageContent" runat="server"></asp:Literal>
</asp:Content>
```

`test.aspx.vb`
```
            Dim env = AssemblyRegistration.Container.Resolve(Of IReactEnvironment)()
            Dim objectModel = New With {Key .user = "React User"}
            Dim reactComponent = env.CreateComponent("PageContent", objectModel)
            PageContent.Text = reactComponent.RenderHtml()
```
It is rendering the div but not my react component

**Comment by pmonty** [comment]
Have just setup a repo so it is easier :) [ReactJS.WebForms repo](https://github.com/pmonty/ReactJS.WebForms)

**Comment by pmonty** [comment]
Ok so got it working. Main issue was I think forgetting `env.GetInitJavascript()` and calling `ReactConfig.Configure()` in global.asax.vb

Seems it wasn't necessary to call that explicitly.

Will close for now as it seems it is all working. Going to attempt webpack bundling and typescript support. If that all works can actually attempt copying some react stuff into our project and working inside which will significantly help!

Amazing effort by all collaborators and contributors! Great project

**Comment by sushmitasen11** [comment]
> Thanks for the quick reply guys!
> 
> After some messing about I have the following:
> `App_Start/ReactConfig.vb`
> 
> ```vbnet
> Imports React
> <Assembly: WebActivatorEx.PreApplicationStartMethod(GetType(ReactConfig), "Configure")>
>     Public Module ReactConfig
>         Sub Configure()
>             ReactSiteConfiguration.Configuration.AddScript("~/Scripts/React/index.jsx")
>         End Sub
>     End Module
> ```
> 
> `test.aspx`
> 
> ```
> <asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
>     <div>
>         hello this is div test
>     </div>
>   <asp:Literal ID="PageContent" runat="server"></asp:Literal>
> </asp:Content>
> ```
> 
> `test.aspx.vb`
> 
> ```
>             Dim env = AssemblyRegistration.Container.Resolve(Of IReactEnvironment)()
>             Dim objectModel = New With {Key .user = "React User"}
>             Dim reactComponent = env.CreateComponent("PageContent", objectModel)
>             PageContent.Text = reactComponent.RenderHtml()
> ```
> 
> It is rendering the div but not my react component
> 
> **UPDATE:**
> Realised I missed the `ReactConfig.Configure()` line in my `global.asax` file. Added it but still get the same error. My page loads the master page and for some reason it shows a 500 error. Really strange. If i comment out the `test.aspx.vb` code then it renders the div again but no the react component.
> 
> **UPDATE 2:**
> Now messing around in a test webforms project I setup. I get the following on line
> `Dim env = AssemblyRegistration.Container.Resolve(Of IReactEnvironment)()`
> ![image](https://user-images.githubusercontent.com/7111292/68001217-4ba79780-fcb7-11e9-9c66-e48893c4f679.png)
> 
> Have also tried ReactEnvironment.Current per your tip in [#55](https://github.com/reactjs/React.NET/issues/55#issuecomment-306954341)

**Comment by sushmitasen11** [comment]
@pmonty how did you resolve this issue mentioned in #Update2, however i am working in asp.net  and getting the same error for the line : 
_env = AssemblyRegistration.Container.Resolve<IReactEnvironment>();  which is written in  500.aspx page.

**Comment by omartheman** [comment]
@pmonty Did you ever happen to make a video or something showing the whole process? I've tried to do this multiple times using other resources, but have never succeeded. Maybe one day I can get around to trying your above steps.
