### ISSUE TITLE
Document WebForms integration

### ISSUE THREAD

**Issue by pmonty** [reactjs/React.NET#967]
So wondering if this is possible. Since I have finally managed to get React.NET working with my ASP.NET Web Forms project (VB.NET). I was wondering if it is possible to have some kind of way to flag when to use it.

Idea I have in my head is to somehow based on the `Solution Configuration` setting I can do the following.

If it is set to `Release` then it will build with Webpack. If set to `Debug` then it will use the setup I have working in #963 to run.

I am thinking of something this where IsDebug is a directive check on `DEBUG`
```vb
Sub Configure()
    If IsDebug() Then
        ' Debug
        ' I have multiple entry points so I guess exposing them all via an index.tsx file will fix this
        ReactSiteConfiguration.Configuration
            .SetReuseJavaScriptEngines(True)
            .SetAllowJavaScriptPrecompilation(True)
            .SetBabelVersion(BabelVersions.Babel7)
            .AddScript("~/React/index.tsx")
    Else
       ' Release
       ' Here I am confused but I guess including each entrypoint bundle?
       ReactSiteConfiguration.Configuration
           .AddScriptWithoutTransform("bundle1")
           .AddScriptWithoutTransform("bundle2")
    End If
End Sub
```

My questions from that setup though are:
1. Is it possible to get HMR working in Debug mode especially?
2. Will I need to call `IsDebug()` in each `aspx.vb` page code now so it doesn't error?
```vb
Protected Sub Page_Load(ByVal sender As Object, ByVal e As EventArgs) Handles Me.Load
    If IsDebug() Then
        Dim env = React.ReactEnvironment.Current
        env.GetInitJavaScript()
        Dim objectModel = New With {Key .user = "React ssUser"}
        Dim reactComponent = env.CreateComponent("TestPage", objectModel)
        PageContent.Text = reactComponent.RenderHtml()
    End If
End Sub
```
3. Having a `<script src="../bundles/bundle1.js" />` in the respective pages will work for Release I guess and 404 in Debug? which I am fine with if its only debug mode.
4. Is it possible to have the package.json and webpack files inside the React app folder so I can still use vscode and run the app separately to the ASP.NET project which some devs will do from time to time.

**Comment by pmonty** [comment]
After reading the documentation on webpack section a bit further. Looks like I can just use webpack itself and that will mean I can definitely run the project by itself (question 4 answered) and then also run the bundles inside my ASP.NET application. 

But in that case I could just add the React stuff into the Project and just have a task that on startup builds the webpack build and runs the app? Almost eliminating the need for React.NET entirely.

**Comment by dustinsoftware** [comment]
Correct, webpack is a suitable alternative. Some people don’t want to go
through the trouble of that for small projects.

You can still leverage server side rendering if using webpack, check out
the samples if you want to see how that’s done.

Cheers

**Comment by pmonty** [comment]
Yeh will give the webpack path a go. Only concern is... can I have the webpack config, package.json and tsconfig files in the `~/ClientApp/` so I can run it directly and only open that folder in vscode as I'll have a script for injecting it into a template.

**Comment by pmonty** [comment]
Ok so after some following along with the sample I have the following VB.NET setup.
ReactConfig.vb:
```vb
        ReactSiteConfiguration.
                Configuration.
                SetReuseJavaScriptEngines(True).
                AddScriptWithoutTransform("~/Clientapp/dist/routes.bundle.js")

        JsEngineSwitcher.Current.DefaultEngineName = V8JsEngine.EngineName
        JsEngineSwitcher.Current.EngineFactories.AddV8()
```
test.aspx
```
   <asp:Literal ID="route1" runat="server"></asp:Literal>
    <script src="~/Clientapp/dist/routes.bundle.js"></script>
```
test.aspx.vb
```
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As EventArgs) Handles Me.Load
        Dim env = ReactEnvironment.Current
        env.GetInitJavaScript()
        Dim objectModel = New With {Key .route = "route1"}
        Dim reactComponent = env.CreateComponent("Routes.Route1", objectModel)
        route1.Text = reactComponent.RenderHtml()
    End Sub
```
index.js
```
import { Route1 } from './Route1'
import { Route2 } from './Route2'

global.Routes = { Route1, Route2 }
```
Route1/index.tsx
```
import * as React from 'react'
export class Route2 extends React.Component<any> {
    render = () => {
        return (
            <div>Hello world from {this.props.route}</div>
        );
    }
}
```

But when I run it I get 
```
Error while rendering "Routes.Route1" to "react_0HLR35UQ05PM1": Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=t
```

**Comment by dustinsoftware** [comment]
Interesting!  I think for the sake of keeping the docs focused on using a single language, we should stick with C#. However adding a brief section on calling from WebForms would be very useful!

**Comment by pmonty** [comment]
So got back on to this project after a hiatus and one situation which is strange is occurring when I create a simple component and import it into the parent.

Component.tsx
`
export class ComponentTest extends React.Component {
    render: any = () => {
       return ( <p>test component</p>)
    }
}`

**Comment by dustinsoftware** [comment]
Hey @pmonty I think at this point this github issue will do a good enough job getting folks started with using WebForms :) given that MS is actively pushing people away from it (no new updates, no .NET 5 support) I hope folks will reach for an incremental MVC port before they reach for this library.
