### ISSUE TITLE
See if we can use Jering.Javascript.NodeJS

### ISSUE THREAD

**Issue by Daniel15** [reactjs/React.NET#971]
Repo: https://github.com/JeringTech/Javascript.NodeJS
Mentioned here: https://github.com/aspnet/AspNetCore/issues/12890#issuecomment-554624959

This library allows the usage of Node.js from .NET via some form of IPC (haven't looked too far into it). Might be an interesting approach to consider, rather than embedding a JS engine in-process like we do today. Would be interesting as it'd give us support for several things we don't support today, like CommonJS modules.

I wonder if it could be added as an engine to JavaScriptEngineSwitcher? It's technically not the same as the other engines (which are all in-process) but perhaps we could have a facade that conforms to the same API.

cc @JeremyTCD

**Comment by dustinsoftware** [comment]
Similar to NodeServices?

https://github.com/aspnet/AspNetCore/tree/master/src/Middleware/NodeServices

I wonder what additional serialization overheads there are for crossing a
process boundary..

**Comment by JeremyTCD** [comment]
## Latency
Latency is acceptable (`Jering.Javascript.NodeJS.INodeJSService` vs `Microsoft.AspNetCore.NodeServices.INodeServices` default implementations):

|                         Method |     Mean |   Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------------- |---------:|--------:|--------:|-------:|------:|------:|----------:|
|  INodeJSService_InvokeFromFile | 108.0 us | 0.82 us | 0.76 us | 2.4414 |     - |     - |   9.87 KB |
| INodeJSService_InvokeFromCache | 104.5 us | 0.58 us | 0.54 us | 2.1973 |     - |     - |   9.71 KB |
|                  INodeServices | 112.4 us | 0.78 us | 0.73 us | 1.7090 |     - |     - |   7.72 KB |

```
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18362
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.0.100
  [Host]     : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), X64 RyuJIT
  DefaultJob : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), X64 RyuJIT
```

For reference, the in process Node.js library, edge.js, is ~4x faster:

|                  Method |     Mean |    Error |   StdDev |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|------------------------ |---------:|---------:|---------:|-------:|-------:|------:|----------:|
| EdgeJS_InvokeFromString | 25.10 us | 0.331 us | 0.310 us | 0.0916 | 0.0305 |     - |     507 B |

```
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18362
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4018.0), X86 LegacyJIT
  DefaultJob : .NET Framework 4.8 (4.8.4018.0), X86 LegacyJIT
```

Unfortunately it isn't compatible with .Net Core.  

For our own use, `Jering.Javascript.NodeJS`'s latency is negligible relative to JS logic execution time. `JeringTech.Javascript.NodeJS` just uses `HttpClient` for IPC. The fact that it's usable is testament the .Net team's work.

## Relationship with NodeServices

Functionally the difference between the libraries is that `JeringTech.Javascript.NodeJS` allows for invoking of in-memory JS - strings, streams etc. We squeezed out a bit more performance and we don't invoke scripts from the temp directory, so `JeringTech.Javascript.NodeJS` is more secure.  

Apart from all that we made some quality of life improvements like supporting async JS functions, AspNetCore-idiomatic configuration and better test coverage.

If you guys decide to use `JeringTech.Javascript.NodeJS` feel free to let me know, am happy to help.

**Comment by joshmccall221** [comment]
> Similar to NodeServices? https://github.com/aspnet/AspNetCore/tree/master/src/Middleware/NodeServices I wonder what additional serialization overheads there are for crossing a process boundary..
> […](#)

FYI: Node services are slated to be deprecated and will no be a part of 5.0. 

The same thread was looking for people to make it a community project.

**Comment by Taritsyn** [comment]
> I wonder if it could be added as an engine to JavaScriptEngineSwitcher? It's technically not the same as the other engines (which are all in-process) but perhaps we could have a facade that conforms to the same API.

@Daniel15 Jering.Javascript.NodeJS is focused only on working with modules, i.e. we don’t have the ability to execute and evaluate regular JS code (always need to specify exports). As far as I understood that the service unlike the engine does not store any state except the cache of modules, i.e. each call occurs independently of the others. In general, this is a fundamentally different architecture.

**Comment by JeremyTCD** [comment]
@Taritsyn You can execute regular JS code, it just needs to be wrapped in a function assigned to `module.exports`.

```csharp
string regularJavascript = @"
";
string javascriptModule = @"
module.exports = (callback, x, y) => {  // Module must export a function that takes a callback as its first parameter
    var result = x + y; // Your javascript logic
    callback(null /* If an error occurred, provide an error object or message */, result); // Call the callback when you're done.
}";

// Invoke javascript
int result = await StaticNodeJSService.InvokeFromStringAsync<int>(javascriptModule, args: new object[] { 3, 5 });
```

**Comment by JeremyTCD** [comment]
@Taritsyn You can execute regular JS:

```csharp
const string javascriptModule = @"
module.exports = (callback, x, y) => {

    var result = x + y; // Regular JS here

    callback(null, result);
}";

// result == 8
int result = await StaticNodeJSService.InvokeFromStringAsync<int>(javascriptModule, args: new object[] { 3, 5 });
```

And you can cache results:

```csharp
const string javascriptModule = @"
var lastResult;

module.exports = (callback, x) => {

    var result = x + (lastResult ? lastResult : 0); // Use cached value here
    lastResult = result; // Cache

    callback(null, result);
}";

// result == 3
int result = await StaticNodeJSService.InvokeFromStringAsync<int>(javascriptModule, "customIdentifier", args: new object[] { 3 });

// result == 8
result = await StaticNodeJSService.InvokeFromStringAsync<int>(javascriptModule, "customIdentifier", args: new object[] { 5 });
```

The CommonJS syntax does take some getting used to, but (at least in our case) it's worth it because we get access to Node.js's modules. E.g you can use the [worker threads](https://nodejs.org/api/worker_threads.html) module to parallelize CPU bound work like SSR.

**Comment by Taritsyn** [comment]
@JeremyTCD Modification of JS code for a specific engine does not quite correspond to main concept of the [JavaScript Engine Switcher](https://github.com/Taritsyn/JavaScriptEngineSwitcher):

> JavaScript Engine Switcher determines unified interface for access to the basic features of popular JavaScript engines (ChakraCore, Jint, Jurassic, MSIE JavaScript Engine for .NET, NiL.JS, Microsoft ClearScript.V8 and VroomJs). This library allows you to quickly and easily switch to using of another JavaScript engine.

**Comment by JeremyTCD** [comment]
@Taritsyn Took a look at [IJsEngine](https://github.com/Taritsyn/JavaScriptEngineSwitcher/blob/master/src/JavaScriptEngineSwitcher.Core/IJsEngine.cs) and I think it can be implemented. Stuff like executing plain JS, pre-compiling and setting variables etc could be done with a JS interop layer, e.g interop.js:

```js
var variables = {};

module.exports = {
    execute: (callback, javascript) => {
        
        // Evaluate and execute

        callback(null, result);
    },
    setVariableValue: (callback, value) => {
        
        // Set variable

        callback(null);
    }
}
```

That said you're right, Node.js technically isn't an engine, so it does not fit with the concept/theme of your project. For strict semantic correctness, another layer on top of both libraries would be necessary.

**Comment by Taritsyn** [comment]
> Stuff like executing plain JS, pre-compiling and setting variables etc could be done with a JS interop layer, e.g interop.js:

Interesting idea.

**Comment by Taritsyn** [comment]
@JeremyTCD Two months ago I [experimented with ES modules in the ChakraCore](https://github.com/Taritsyn/TestChakraCoreEsModules), but unfortunately I could not convince the authors of this library that the `JsModuleEvaluation` method should return a result.

**Comment by JeremyTCD** [comment]
@Taritsyn Node.js wraps any code you try to run on it with the following strings:

https://github.com/nodejs/node/blob/917fedd21ae07c6fac10681c9393a2c7652a5f1e/lib/internal/modules/cjs/loader.js#L174-L177

```js
(function (exports, require, module, __filename, __dirname) { 
    // User's javascript that exports stuff
    module.exports = ...
});
```

Not very familiar with your library so I don't know if it'll help. Does this affect whether you can incorporate `Jering.Javascript.NodeJS`?

**Comment by JeremyTCD** [comment]
@Taritsyn Node.js wraps any code you try to run on it with the following strings, from [loader.js](https://github.com/nodejs/node/blob/917fedd21ae07c6fac10681c9393a2c7652a5f1e/lib/internal/modules/cjs/loader.js#L174-L177):

```
const wrapper = [
  '(function (exports, require, module, __filename, __dirname) { ',
  '\n});'
];
```

You could get the exports by doing the same thing:

```js
(function (exports, require, module, __filename, __dirname) { 
    // User's javascript that exports stuff
    module.exports = ...
});
```

Not very familiar with your library so I don't know if it'll help. Does this affect whether you can incorporate `Jering.Javascript.NodeJS`?

**Comment by Taritsyn** [comment]
> Does this affect whether you can incorporate `Jering.Javascript.NodeJS`?

I have long been [asked to implement such functionality](https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/39). As soon as I have free time I will try to make a module based on the `Jering.Javascript.NodeJS` library.

**Comment by JeremyTCD** [comment]
@Taritsyn Oh I see. Let me know if you need any help with `Jering.Javascript.NodeJS`. Feel free to tag me if you open a pull request on your repo to add it.

**Comment by DaniilSokolyuk** [comment]
We made a library today, it is almost compatible with React.NET API, https://github.com/DaniilSokolyuk/NodeReact.NET, we use worker threads for rendering

**Comment by JeremyTCD** [comment]
@DaniilSokolyuk Looks interesting. How does performance compare with React.NET?

**Comment by dustinsoftware** [comment]
There is a benchmark suite in this project you can use if you’d  like to
compare render times.

A fork of this project is a great place to start, and later we can figure
out how to work it in after experimenting.

Later on... we could add an optional INodeService that lives in React.Core,
and create a new project React.NodeServices that provides an implementation
of it. I’d be a bit worried about having React.Core depending on any more
packages than it has to :)

I agree that it seems a bit out of scope for JsEngineSwitcher but would not
be opposed to deferring to an implementation in that project if there’s a
clean way to pull that off.

**Comment by DaniilSokolyuk** [comment]
I make [benchmarks ](https://github.com/DaniilSokolyuk/NodeReact.NET/tree/master/NodeReact.Benchmarks) but result is not good because [this](https://github.com/DaniilSokolyuk/NodeReact.NET/blob/master/NodeReact.Benchmarks/SampleNode.js) component does nothing. In our production application we see performance boost 10-20%  compared [ZeroReact](https://github.com/DaniilSokolyuk/ZeroReact.NET)

**Comment by DaniilSokolyuk** [comment]
@JeremyTCD @dustinsoftware 
I am updated my banchmarks, now i use real production bundle and real production data
results is very good excluding allocations 😄 
``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.17763.475 (1809/October2018Update/Redstone5)
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.0.100
  [Host] : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), X64 RyuJIT

Job=InProcess  Toolchain=InProcessEmitToolchain  

```
|                 Method |      Mean |     Error |    StdDev |    Median | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------- |----------:|----------:|----------:|----------:|------:|------:|------:|----------:|
| NodeReact_RenderSingle |  8.380 ms | 0.4387 ms | 1.2867 ms |  7.831 ms |     - |     - |     - | 638.34 KB |
| ZeroReact_RenderSingle | 14.106 ms | 1.3290 ms | 3.8345 ms | 13.604 ms |     - |     - |     - |   4.73 KB |
|   ReactJs_RenderSingle | 12.027 ms | 0.3590 ms | 0.9705 ms | 12.018 ms |     - |     - |     - | 898.66 KB |

**Comment by DaniilSokolyuk** [comment]
And bigger component
``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.17763.475 (1809/October2018Update/Redstone5)
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.0.100
  [Host] : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), X64 RyuJIT

Job=InProcess  Toolchain=InProcessEmitToolchain  

```
|                 Method |     Mean |    Error |   StdDev |   Median | Gen 0 | Gen 1 | Gen 2 |  Allocated |
|----------------------- |---------:|---------:|---------:|---------:|------:|------:|------:|-----------:|
| NodeReact_RenderSingle | 27.32 ms | 1.047 ms | 3.038 ms | 26.93 ms |     - |     - |     - | 1262.37 KB |
| ZeroReact_RenderSingle | 48.73 ms | 2.198 ms | 6.165 ms | 48.48 ms |     - |     - |     - |    4.73 KB |
|   ReactJs_RenderSingle | 55.89 ms | 2.289 ms | 6.714 ms | 54.03 ms |     - |     - |     - | 1305.15 KB |

**Comment by JeremyTCD** [comment]
@dustinsoftware

> Later on... we could add an optional INodeService that lives in React.Core,
and create a new project React.NodeServices that provides an implementation
of it. I’d be a bit worried about having React.Core depending on any more
packages than it has to :)

A separate project makes sense and @DaniilSokolyuk's project seems to do the job. I'll work on optimizing for his project instead.  

I guess this thread has reached a conclusion?

**Comment by Taritsyn** [comment]
@JeremyTCD I have the following conclusion: in coming days I will begin work on the JavaScriptEngineSwitcher.Node module. I will try to make a standard engine based on the Jering.Javascript.NodeJS.

**Comment by JeremyTCD** [comment]
@Taritsyn okay tag me in the pull request, am happy to help.

**Comment by Daniel15** [comment]
#1021

**Comment by dustinsoftware** [comment]
Continuing investigation in the linked pull request.
