### ISSUE TITLE
SyntaxError: Unexpected token '<' & ReferenceError: {className} is not defined

### ISSUE THREAD

**Issue by dariusz-wozniak** [reactjs/React.NET#976]
### Please verify these steps before filing an issue, and check them off as you go
- [x] The relevant native JavascriptEngineSwitcher library packages are installed (such as `JavaScriptEngineSwitcher.V8.Native.win-x64`)
- [x] The VC++ 2017 runtime is installed
- [x] The value of `SetUseReact` and `SetUseBabel` is correct in `ReactConfig.cs` or `Startup.cs`
- [x] I've looked at the sample projects in this repo to verify that my app is configured correctly

### I'm using these library versions:
- `ReactJS.NET`: 5.1.2
- `JavaScriptEngineSwitcher`: ChakraCore 3.2.3
- `react` and `react-dom`: N/A
- `webpack`: N/A
- `node`: N/A

### Runtime environment:
- OS: Windows 10 x64
- .NET Framework or .NET Core Version: .NET Core 3.0

### Steps to reproduce

The code is as following:

`hello.jsx`:

```
class HelloWorld extends React.Component {
    render() {
        return (
            <div><h1>Hello world</h1></div>
        );
    }
}
```

`Index.cshtml`:

```
@Html.React("HelloWorld", new { })

<script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react/16.8.0/umd/react.development.js"></script>
<script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.8.0/umd/react-dom.development.js"></script>
<script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/prop-types/15.6.0/prop-types.js"></script>

<script src="@Url.Content("~/js/hello.jsx")"></script>

@Html.ReactInitJavaScript()
```

`Startup.cs`:

`ConfigureServices` method:

```
services.AddJsEngineSwitcher(switcher => switcher.DefaultEngineName = ChakraCoreJsEngine.EngineName).AddChakraCore();
services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
services.AddReact();
services.AddMvc();
```

`Configure` method:

```
app.UseReact(configuration =>
{
    configuration
        .AddScript("~/js/hello.jsx")
        .SetJsonSerializerSettings(new JsonSerializerSettings
        {
            StringEscapeHandling = StringEscapeHandling.EscapeHtml,
            ContractResolver = new CamelCasePropertyNamesContractResolver()
        });
});
```

References:

```
<PackageReference Include="JavaScriptEngineSwitcher.ChakraCore" Version="3.2.3" />
<PackageReference Include="JavaScriptEngineSwitcher.ChakraCore.Native.win-x64" Version="3.2.3" />
<PackageReference Include="JavaScriptEngineSwitcher.ChakraCore.Native.win-x86" Version="3.2.3" />
<PackageReference Include="JavaScriptEngineSwitcher.Extensions.MsDependencyInjection" Version="3.1.0" />
<PackageReference Include="React.AspNet" Version="5.1.2" />
```

-------

I've tried to follow the steps in the tutorial and code in the `ReactDemo`. When compiling and running`ReactDemo`, it does not yields errors as below.

The "Hello world" is rendered on the page, but there are errors in console window:

```
hello.jsx:4 Uncaught SyntaxError: Unexpected token '<'
(index):15 Uncaught ReferenceError: HelloWorld is not defined
    at (index):15
```

Output part in the HTML is as following:

```
<div id="react_0HLRJ2KOHPQCO"><div data-reactroot=""><h1>Hello world</h1></div></div>
<script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react/16.8.0/umd/react.development.js"></script>
<script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.8.0/umd/react-dom.development.js"></script>
<script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/prop-types/15.6.0/prop-types.js"></script>

<script src="/js/hello.jsx"></script>

<script>ReactDOM.hydrate(React.createElement(HelloWorld, {}), document.getElementById("react_0HLRJ2KOHPQCO"));
</script>
```

**Comment by andrisole92** [comment]
Have the same issue

**Comment by dustinsoftware** [comment]
Hi there; does your project match the [tutorial source code](https://github.com/reactjs/React.NET/tree/master/tutorial-code)? It should have a working example of JSX on the fly compilation working. You can also check the Network tab to see why `hello.jsx` is failing to load.

(This issue is pretty old so closing for now)
