### ISSUE TITLE
JSX does not transform with MSBuild

### ISSUE THREAD

**Issue by jkmuka** [reactjs/React.NET#99]
I added the nuget package to my project and verified the targets below were in the TransformJsx.proj but no jsx has transformed prior to the browser and there are no errors or build messages

	<UsingTask AssemblyFile="$(OutputPath)\React.MSBuild.dll" TaskName="TransformJsx" />
	<Target Name="TransformJsx">
		<TransformJsx SourceDir="$(MSBuildProjectDirectory)" />
	</Target>

**Comment by jkmuka** [comment]
After restarting VS I see that it does the transforms now

**Comment by Daniel15** [comment]
Visual Studio probably had to reload the MSBuild file :)
